jetify-com/devbox

README.md

Fix go version in readme

---

.github/pull_request_template.md
.github/workflows/release.yml
.github/workflows/tests.yaml
.golangci.yml
README.md
boxcli/root.go
cuecfg/cuecfg.go
cuecfg/json.go
generate.go

* Moves tests over to own workflow. Release jobs depend on it.
* Adds golangci linter and runs it in test workflows.
* Adds new pull request template.
GHA

[linting] Add golangci-lint and GHA that runs it

---

README.md

Add Twitter link

---

.github/workflows/release.yml

[CICD] Fix release job

---

README.md

Add links to devbox site & docs in readme

---

boxcli/midcobra/telemetry.go
go.mod

Fix spurious segment error

---

README.md

[PHP] update readme

---

.gitignore
planner/languages/java/java_planner.go
planner/plansdk/plansdk.go
testdata/java/openjdk-11/plan.json
testdata/java/openjdk-11/pom.xml
testdata/java/openjdk-17/plan.json
testdata/java/openjdk-17/pom.xml
testdata/java/openjdk-8/plan.json
testdata/java/openjdk-8/pom.xml
testdata/java/openjdk-default/plan.json
testdata/java/openjdk-default/pom.xml

Added installcommand and start command to planner for Java + Maven
Note: The docker image size is VERY big (1.7GB) I'll make a followup PR to optimize the size.
```shell 
./devbox plan
./devbox build
docker run devbox
```

[Java Planner] part2: Added install + build steps to planner

---

planner/languages/dotnet/dotnet_planner.go

I added this printf and comment for myself during development.
I had meant to delete this prior to landing but forgot.
it compiles

remove erroneous printf

---

.github/workflows/release.yml

Change pre-releases to happen weekly on Thursdays
Didn't test.

Change pre-releases to happen weekly on Thursdays

---

boxcli/plan.go
devbox.go
devbox_test.go
planner/planner.go
planner/plansdk/plansdk.go

Right now in the plans merging logic we pick a buildable plan.
In this case, if all plans have error messages, we should return a plan with error messages instead of returning an empty plan.
Is this the desired behavior?
go test ./...

[Bug fix] Pick one plan if no plans are buildable

---

go.mod
planner/languages/ruby/ruby_planner.go
testdata/ruby/ruby-3.1/Gemfile
testdata/ruby/ruby-3.1/Gemfile.lock
testdata/ruby/ruby-3.1/app.rb
testdata/ruby/ruby-3.1/devbox.json

Simple first pass at a Ruby planner. Runs `app.rb` inside the container.
`devbox shell` and `devbox build`

Ruby planner (without Rails)

---

docs/app/docs/language_support/java.md

Title says it
No need for testing only markdown files were changed

Added gradle support to docs

---

boxcli/midcobra/telemetry.go

Silence any segment errors
`go test -v ./...`

Silence any segment errors

---

docs/app/docs/language_support/python.md

docs: fix typo in Python language detection docs

---

devbox.go

The current command for nix-env starts as a string and then gets split by spaces to form the args slice. This doesn't handle paths with spaces, so change it to just create a slice directly instead.
Also improve the error message when `nix-env` fails to give more info instead of just the exit code.
Finally, unexport `ApplyDevNixDerivation` because isn't used anywhere else.
Ran `devbox shell` from a directory with spaces in the name.

devbox: handle paths with spaces

---

devbox.go

Until we can land #227, I want to revert the changes in #222 so that shell plans can continue working, and we can release some other (unrelated) fixes.
In this PR, I revert (manually) the `devbox.go` changes in #222, while leaving the test changes to minimize merge conflicts with #227.
cc @loreto @LucilleH 
sanity check
```
> cd testdata/nodejs/nodejs-18
> devbox shell
> which node
> exit
```
Example 1: nginx
```
> devbox shell
Installing nix packages. This may take a while...done.
You may need to add
"include ./.devbox/gen/shell-helper-nginx.conf;"
to your shell-nginx.conf file to ensure the server can start in the nix shell.
Use "shell-nginx" to start the server
```
Example 2: python/pip-example
```
devbox/testdata/python/pip-example 
> devbox shell
Installing …
```

[shell] minimal revert of #222 to bring back shell plans temporarily

---

nix/shell.go

User `mtunski` in discord helpfully pointed out that their shell setup using
zsh4humans (https://github.com/romkatv/zsh4humans) wasn't working with devbox shell.
Specifically, they get an error saying:
> Installing nix packages. This may take a while...done.
/tmp/devbox3134336657/.zshrc:62: command not found: z4h
We currently just copy over the `.zshrc` file into the new `ZDOTDIR` of devbox shell. The fix is:
1. to link more zsh startup files (specifically, .zshenv, .zprofile, .zlogin)
2. manually link other zsh-plugin specific files in the .zshrc. This is not great, but a workaround until we introduce a more formal architecture for custom shells to be hooked up (i.e. with a provider or plugin model).
1. installed zsh4humans on my laptop
2. 
The advanced config …

[devbox shell] ensure all zsh startup files are linked to ZDOTDIR

---

docs/app/docs/cli_reference/devbox_run.md
docs/app/docs/configuration.md
docs/app/docs/guides/pinning_packages.md
docs/app/docs/guides/scripts.md
docs/app/docs/language_support/nginx.md
docs/app/docs/language_support/zig.md
docs/app/sidebars.js

Docs for Devbox Run and Setting the Commit Sha
localhost

 Docs for Devbox Run and Setting the Commit Sha

---

boxcli/run.go

Unhide devbox run

---

.github/workflows/deployment.yaml
.github/workflows/previews.yaml
docs/launchpad.yaml

Deploy docs with launchpad on CICD.
preview

Deploy docs with launchpad on CICD

---

vscode-extension/CHANGELOG.md

Added changelog for V0.0.2

---

.github/workflows/release-extension.yaml
vscode-extension/package.json
vscode-extension/src/extension.ts

Added github action for vscode extension release
Not tested

Added github action for vscode extension release

---

pkgcfg/package-configuration/nginx.json
pkgcfg/package-configuration/nginx/fastcgi.conf
pkgcfg/package-configuration/nginx/nginx
pkgcfg/package-configuration/nginx/nginx.conf
pkgcfg/pkgcfg.go

Adds basic nginx config. Creates a simple config file and a shim that uses it. Can be customized with environment variable.
Note that the readme is currently not implemented but I'm adding so it will be available once it is.
```
devbox add nginx
devbox shell
nginx
```

[pkgcfg] Add nginx config

---

pkgcfg/package-configuration/apache/httpd.conf
pkgcfg/package-configuration/apacheHttpd.json

[pkgcfg] Add Apache httpd config

---

pkgcfg/package-configuration/python*.json

Just a readme
```
devbox info python
```

[pkgcfg] python config (readme)

---

docs/app/docs/contributor-quickstart.md
docs/app/docs/quickstart.mdx

Add Markdown snippet for adding Badges to Readmes
Visual Confirmation

Jl/qs quality'

---

README.md

Signed-off-by: John Lago <750845+Lagoja@users.noreply.github.com>
Adds the badge to our Readme
Visual Verification

Add Devbox Badge to Readme

---

vscode-extension/CHANGELOG.md
vscode-extension/package.json

Bumping the version for vscode extension so that the latest fix can be included.
N/A

Bumping vscode extension version

---

README.md

To point to the correct workflow after I renamed them.
N/A
Signed-off-by: Daniel Loreto <279789+loreto@users.noreply.github.com>

Update test badge in README

---

boxcli/build.go
boxcli/plan.go
devbox.go
devbox_test.go
generate.go

Title says it.
- compile
- try ./devbox build
- try ./devbox plan

deprecate devbox build + hide devbox plan

---

internal/boxcli/featureflag/feature.go
internal/boxcli/featureflag/nixinstaller.go
internal/boxcli/featureflag/pkgconfig.go

[features] Enable plugins and nix install

---

.github/ISSUE_TEMPLATE/plugin-request.md

Make it easy for users to request a new plugin

Add a Plugin Request Template

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json

[extension] Updated readme and changelog + bumped version

---

internal/boxcli/setup.go
internal/nix/install.go

If nix is already installed show warning and quit.
`devbox setup nix`

[nix] Don't install nix if its already installed DEV-1261

---

internal/cloud/cloud.go

In this PR, we `scp` the `devbox.json` config file into the VM. We do this prior
to beginning mutagen-sync for the rest of the devbox-project.
The motivation is to enable us to start the `devbox shell` in the VM sooner. 
Lucille observed that starting the cloud-shell would sometimes time out waiting
for the devbox.json file to be synced (often when there were some large files
in the devbox-project directory).
A future PR will explore providing an indicator in the cloud-shell about the mutagen
sync status.
1. deployed a new fly VM
2. started cloud shell with golang and rust projects

[cloud] scp devbox.json to VM, prior to syncing

---

.github/ISSUE_TEMPLATE/bugs.md

Adds an issue template for reporting new bugs.
N/A

Add issue template for bug reports

---

internal/boxcli/midcobra/telemetry.go

- Refactor sentry logic into it's own function
- Ensure we do not call sentry when the `runErr` is `nil`.
I didn't ...
I'm thinking it's a small refactor, but let me know if you think I should test it more before landing.

Refactor sentry logic and fix bug

---

docs/app/docs/cli_reference/devbox.md
docs/app/docs/cli_reference/devbox_add.md
docs/app/docs/cli_reference/devbox_generate.md
docs/app/docs/cli_reference/devbox_generate_devcontainer.md
docs/app/docs/cli_reference/devbox_generate_direnv.md
docs/app/docs/cli_reference/devbox_generate_dockerfile.md
docs/app/docs/cli_reference/devbox_info.md
docs/app/docs/cli_reference/devbox_init.md
docs/app/docs/cli_reference/devbox_plan.md
docs/app/docs/cli_reference/devbox_rm.md
docs/app/docs/cli_reference/devbox_run.md
docs/app/docs/cli_reference/devbox_services.md
docs/app/docs/cli_reference/devbox_services_ls.md
docs/app/docs/cli_reference/devbox_services_restart.md
docs/app/docs/cli_reference/devbox_services_start.md
docs/app/docs/cli_reference/devbox_services_stop.md
docs/app/docs/cli_reference/devbox_shell.md
docs/app/docs/cli_reference/devbox_version.md
docs/app/docs/devbox_examples/databases/postgres.md
docs/app/docs/devbox_examples/databases/redis.md
docs/app/docs/devbox_examples/servers/caddy.md
docs/app/docs/ide_configuration/direnv.md
docs/app/sidebars.js

Add Docs for 0.2.1 Release
- Envrc Changes
- New Plugins
Localhost and https://devbox-web-john-lago-jetpack-io.cloud.jetpack.dev/devbox

Docs for 0.2.1

---

.github/workflows/cli-post-release.yml
.github/workflows/cli-publish.yml
.github/workflows/cli-release.yml
.github/workflows/cli-tests.yaml
internal/boxcli/setup.go

1. Add devbox install nix action as a test in cicd
2. Only update latest version in S3 on publishing a release
CICD

[CICD] add devbox install nix action in cicd, change release workflow

---

internal/nix/shell.go

Remove redundant debug output

---

internal/cloud/cloud.go

We should bubble these errors up the stack so that the midcobra telemetry can 
capture them.
did a sanity test of `devbox cloud shell`

[cloud] remove log.Fatal in favor of returning the error

---

README.md

[readme] Fix link

---

examples/testdata/commands/init/init_test.go
examples/testdata/commands/run/run_test.go
examples/testdata/testframework/impl/framework.go
examples/testdata/testframework/interface.go

Title says it.
Ran the tests locally and it succeeded

[test] additional tests for devbox init and run

---

internal/impl/devbox.go

[minor polish] add space before y/n in question

---

internal/impl/devbox_test.go
internal/impl/tmpl/development.nix.tmpl
internal/impl/tmpl/shell.nix.tmpl
internal/planner/plansdk/plansdk.go
internal/planner/plansdk/plansdk_test.go

This has not been used for many months now...

[cleanup] remove overlays code from generated nix files

---

internal/nix/shell.go

Remove unused profile bin dir in shellrc template

---

internal/impl/generate.go

This PR looks if the devbox project is in a git repository before adding the
flake.nix to a "fake git repository". With this PR, `devbox` with flakes will no longer require `git` as a hard dependency.
When I tested with a simple flakes playground project, I observed:
1. if not in a git repository, then flakes.nix can be used by `nix develop`.
2. if in a git repository, then `nix develop` fails if flakes.nix is not tracked.
3. Surprisingly, if in a mercurial repository, then `nix develop` still works if flakes.nix is not tracked by mercurial. Surprising because docs online hint that flakes supports both git and mercurial, but I guess not enforced for this requirement.
Ran `DEVBOX_FEATURE_FLAKES=1 devbox shell` in devbox projects:
1. in a git repo 
2. outside a git repo

[flakes] add flakes.nix to git only if we are in a git repo

---

internal/impl/devbox.go
internal/impl/writer.go

Re-add message when ensuring packages are installed.
`devbox shell`

[easy][nix] Add ensure message

---

internal/nix/nix.go

Use legacy search for now to make `info` and `add` much faster. (first add is about 20 seconds faster)
```
devbox info php
devbox add curl
```

[perf] Make PkgInfo faster by using non-flakes lookup

---

internal/cloud/openssh/sshshim/mutagen.go

Its possible the check for activeVM failed due to some ephemeral reason. So, we 
try 3 times with a sleep of 10 seconds in between.
1. verified that sync still works.
2. 
- killed the VM
- tailed the logs at `~/.config/devbox/ssh/shims/logs.txt`
```
[DEBUG] 2023/01/27 17:09:59 /Users/savil/code/jetpack/devbox/internal/cloud/openssh/sshshim/logger.go:27: Debug mode enabled.
[DEBUG] 2023/01/27 17:09:59 /Users/savil/code/jetpack/devbox/internal/cloud/openssh/sshshim/logger.go:28: started sshshim
[DEBUG] 2023/01/27 17:09:59 /Users/savil/code/jetpack/devbox/internal/cloud/openssh/sshshim/command.go:30: os.Args: [/Users/savil/.config/devbox/ssh/shims/ssh -oConnectTimeout=5 -oServerAliveInterval=10 -oServerAliveCountMax=1 savil@e784935c246683.vm.devbox-vms.internal …
```

[sshshim] re-try 3 times for finding activeVM

---

testscripts/README.md

small grammar fix in testscript README

---

internal/nix/run.go
testscripts/basic/install_hello.test.txt
testscripts/testscripts_test.go

Add testscripts that tests installing 'hello'
`go test -v`

Add testscripts that tests installing 'hello'

---

internal/cloud/cloud.go

Instead of assuming that the VM username is the same as the one given to the CLI, use the one returned by the gateway. This makes things a bit more flexible by allowing the gateway to decide which username goes with the VM's key.
Launching a new VM and authenticating with an existing one.

cloud: let the gateway set VM usernames

---

.github/workflows/cli-tests.yaml

[CICD] Fix cli tests

---

internal/boxcli/add_test.go
internal/boxcli/rm_test.go

Experimenting to see if this speeds up tests, especially on macos
CICD

[CICD] Install smaller package in tests

---

CONTRIBUTING.md
devbox.json

Update the Contributing Guide to describe the Devbox workflow
Localhost + Lint

Add Devbox Instructions to CONTRIBUTING.md

---

testscripts/run/env.test.txt
testscripts/run/script.test.txt

TSIA
```
go test ./testscripts/testscripts_test.go
```

Add some basic devbox run testscript tests

---

testscripts/run/path.test.txt

TSIA
```
> go test ./testscripts/testscripts_test.go
```

Add tests for PATH setting in run

---

go.mod
go.sum
internal/cloud/cloud.go

Rewrite `getGithubUsername` to make it clearer by adjusting `if`s and adding logs.

[refactor]: make getGithubUsername clearer

---

testscripts/run/env.test.txt

TSIA
```
go test ./testscripts/testscripts_test.go
```

Add testscript tests for config env vars

---

testscripts/run/env.test.txt

Also tests the `PWD` special logic
```
go test ./testscripts/testscripts_test.go
```

Add tests for env var application order

---

testscripts/run/args.test.txt

TSIA, pretty straight-forward.
```
> go test -run TestScripts/run/args.test ./testscripts/testscripts_test.go
```

Add tests for passing args to run scripts

---

internal/impl/devbox_test.go

[easy][global] Fix tests when global pkgs exist DEV-1280

---

docs/app/docs/devbox_examples/languages/python.md
docs/app/docs/guides/plugins.md

Adds documentation for using the new `pip` plugin for Python
Localhost

Add Pip Docs

---

docs/app/docs/devbox_examples/index.md
docs/app/docs/devbox_examples/stacks/django.md
docs/app/sidebars.js

Add a Django Example to the Docs
Localhost

Add Django Example Docs

---

docs/app/docs/devbox_global.md
docs/app/sidebars.js

Devbox Global Docs aren't appearing on the sidebar, this fixes things
Localhost

Fix Devbox Global Visibility

---

docs/app/docs/ide_configuration/direnv.md

Add a note to the direnv docs that users may have to regenerate their envrc in 0.4.0
Localhost

Direnv document note

---

internal/boxcli/setup.go
internal/nix/source.go

Tries $XDG_STATE_HOME in addition to previous paths. Shows better error message.

[nix] Check other locations for nix startup and better error

---

internal/boxcli/setup.go

Instead of showing a nix error, switch to multi-user install when user tries to install as root (this is common in docker and CICD)
fresh docker ubuntu

[nix] Always do multi-user install if root

---

internal/boxcli/setup.go
internal/nix/install.go
internal/telemetry/telemetry.go

This shows an error is user tries to install nix on WSL as root. cc: @Lagoja 
Untested

[WSL] Don't allow root nix instalation on WSL

---

.github/workflows/cli-tests.yaml

Testing this fix out (I can't remember if exported variables are available across steps in GHA)
Testing in CICD

[cicd] add NIX_PATH to tests

---

.github/workflows/cli-tests.yaml
typos.toml

follow up to https://github.com/jetpack-io/devbox/pull/658
will observe github actions run

[spell check cicd] do not run on main branch, and ignore .svg files

---

internal/boxcli/featureflag/flakes.go

Woo!
All buildkite tests should pass

[flakes] enable featureflag

---

vscode-extension/src/extension.ts

Fixed a bug where devbox extension would run `devbox shell` when opening a new terminal in vscode even if there was no devbox.json present in the workspace.
The change would make sure there is a devbox.json file present before running devbox shell in the newly opened terminal.
- Open vscode from devbox/vscode-extension
- from run and debug on the left bar click run extension 
- in the newly opened window create a devbox.json file and open a new terminal in vscode
- confirm `devbox shell` is run when devbox.json file is present and vice versa

[vscode extension] Fixed autorun shell on new terminal open bug

---

internal/boxcli/featureflag/env_config.go

Enables the Env Config in advance of our upcoming release

Enable the Env in Config Feature

---

internal/nix/nix.go

Remove dead code

---

plugins/README.md

Draft Contributing Guide for Plugins -- covers a lot of ground, but wanted to get everything in a document to iterate on
Markdown Only

Plugin Contributing Guide

---

internal/impl/shell.go
internal/impl/shellrc.tmpl
internal/impl/shellrc_fish.tmpl

Remove more dead code

---

plugins/plugins.go

TSIA
Ran testscripts tests successfully

Include plugin subdirs

---

internal/impl/packages.go
internal/nix/profile.go
internal/nix/writer.go

We want to re-try nix profile install with package conflicts by setting
a higher priority (lower priority number) for later packages.
using the github.com/jetpack-io/devbox-examples repo
before:
```
devbox-examples/development/ruby on  main [!?] on ☁️  (us-east-2) on ☁️  savil.srivastava@jetpack.io 💫 initial project sync
❯ devbox shell
Installing 2 packages: bundler, ruby_3_1.
[1/2] bundler
[1/2] bundler: Success
[2/2] ruby_3_1
error: files '/nix/store/spgr12gk13af8flz7akbs18fj4whqss2-bundler-2.4.5/bin/bundle' and '/nix/store/l4wmx8lfn6hlcfmbyhmksm024f8hixm1-ruby-3.1.2/bin/bundle' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' or type 'nix profile install --help' if using 'nix profile' to find out howto change the …
```

[flakes] Assign higher priority to later packages to resolve conflicting packages error

---

docs/app/docs/configuration.md

Add Details on the `env` portion of the devbox.json to the documentation
Localhost

add env to configuration

---

internal/impl/packages.go

This was failing in macOS tests because the Nix profile didn't exist. Change it to only fail if the error is not an `os.ErrNotExist` error.
```
$ DEVBOX_FEATURE_FLAKES=0 devbox add hello
$ DEVBOX_FEATURE_FLAKES=1 devbox add hello
$ rm .devbox/nix/profile/default
$ DEVBOX_FEATURE_FLAKES=0 devbox add hello
```

impl: don't error in resetProfileDir if profile doesn't exist

---

docs/app/docs/guides/plugins.md

Link `services.md`

---

docs/app/docs/guides/plugins.md

Remove unnecessary verbs

---

docs/app/docs/devbox_global.md

The global data path is out of date. Update it.

Update global data path

---

docs/app/docs/guides/pinning_packages.md

Lowercase for commit

---

docs/app/docs/index.md

Wrap filename with quotes

---

docs/app/yarn.lock

Upgrade minor deps
Fixes https://github.com/jetpack-io/devbox/security/dependabot/27
No

[docs] Update dependencies

---

plugins/pip/venvShellHook.sh

Fix typo in pip plugin

---

examples/development/python/pip/main.py

typo: s/Poetry/Pip in Pip example

---

examples/development/python/pipenv/main.py

typo: s/Poetry/Pipenv in Pipenv example

---

vscode-extension/package.json
vscode-extension/src/openinvscode.ts

Title says it.
This is the follow up from https://github.com/jetpack-io/axiom/pull/3098
See #804

[vscode extension] Added getting working directory from `getvminfo()`

---

docs/app/docs/cli_reference/devbox_cloud_forward.md
docs/app/docs/cli_reference/devbox_cloud_forward_list.md
docs/app/docs/cli_reference/devbox_cloud_forward_stop.md
docs/app/docs/cli_reference/devbox_completion.md
docs/app/docs/cli_reference/devbox_completion_bash.md
docs/app/docs/cli_reference/devbox_completion_fish.md
docs/app/docs/cli_reference/devbox_completion_zsh.md
docs/app/docs/cli_reference/devbox_install.md
docs/app/docs/cli_reference/devbox_run.md
docs/app/docs/cli_reference/devbox_shellenv.md

Update Docs for 0.4.5 CLI based on #839 from @hezhizhen 
Localhost, using `yarn start`

Update Docs with 0.4.5 CLI

---

.golangci.yml
internal/boxcli/gen-docs.go
internal/boxcli/generate.go
internal/boxcli/init.go
internal/boxcli/log.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/run.go
internal/cloud/cloud.go
internal/cloud/mutagen/type_test.go
internal/cloud/openssh/sshshim/mutagen.go
internal/cloud/openssh/username.go
internal/cloud/user_test.go
internal/impl/config_test.go
internal/impl/devbox.go
internal/impl/devbox_test.go
internal/impl/generate.go
internal/impl/shell.go
internal/initrec/recommenders/java/java.go
internal/initrec/recommenders/python/python_pip.go
internal/initrec/recommenders/rust/rust.go
internal/initrec/recommenders/zig/zig.go
internal/nix/profile.go
internal/nix/profile_test.go
internal/nix/writer.go
internal/plugin/plugin.go
internal/services/services.go
internal/telemetry/segment.go
internal/wrapnix/wrapper.go
testscripts/testrunner/examplesrunner.go

1. Enable more rules for revive.
2. Address existing issues.
devbox run lint

[linting] enable more rules for revive and address issues

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json

Updated readme and changelog for new release of extension
N/A

[vscode extension] Updated readme and changelog for v0.0.5

---

internal/boxcli/args.go
internal/boxcli/generate/devcontainer_util.go
internal/boxcli/install.go
internal/boxcli/run.go
internal/boxcli/usererr/exiterr.go
internal/impl/devbox.go
internal/nix/profile.go
internal/nix/run.go

Improve some misc. error messages so that they can be useful in Sentry. Also threw in some TODOs for a couple of bug related to error handling.

boxcli,nix: some better error messages

---

README.md

[Readme] Moved install to above benefits

---

internal/boxcli/global.go
internal/impl/devbox.go
internal/impl/global.go

Wrap common part in global commands in a function and use that function to simplify global commands.

chore: simplify global commands

---

vscode-extension/README.md

Update README.md in vscode-extension.

[vscode extension] update README

---

vscode-extension/src/openinvscode.ts

Added better error messages and debugs for vscode extension.
run and debug when open vscode-extension directory in vscode

[vscode-extension] Added better error messages and debugs for openinvscode

---

.github/workflows/cli-release.yml

TSIA, we're currently using secrets for these variables when we should be using vars
n/a

Use vars context for Sentry project + org

---

devbox.go
internal/impl/devbox.go
internal/impl/packages.go
internal/lockfile/local.go
internal/nix/input.go
internal/nix/nix.go
internal/plugin/info.go

1. update comments of `Add` based on its implementation
2. tweak functions used in the implementation

Update add method of devbox interface

---

internal/impl/config.go
internal/impl/devbox.go
internal/impl/devbox_test.go
internal/initrec/recommenders/dotnet/dotnet.go
internal/initrec/recommenders/golang/golang.go
internal/initrec/recommenders/haskell/haskell.go
internal/initrec/recommenders/java/java.go
internal/initrec/recommenders/javascript/nodejs.go
internal/initrec/recommenders/nginx/nginx.go
internal/initrec/recommenders/python/python_pip.go
internal/initrec/recommenders/python/python_poetry.go
internal/initrec/recommenders/ruby/ruby.go
internal/initrec/recommenders/rust/rust.go
internal/initrec/recommenders/zig/zig.go
internal/planner/plansdk/analyzer.go
internal/planner/plansdk/plansdk.go

[cleanup] replace checks for file existing with fileutil.Exists

---

internal/services/client.go

[cleanup] replace literal http methods with constants

---

internal/planner/planner.go
internal/planner/plansdk/analyzer.go
internal/services/services.go
internal/wrapnix/wrapper.go

[cleanup] remove unused functions

---

CONTRIBUTING.md

- Add a small section for code style.
- Simplify some of the steps for building and getting started.
- Misc. formatting fixes.

Update CONTRIBUTING.md with fixes and style guide

---

internal/cloud/openssh/sshshim/invoke.go
internal/env/env.go
internal/env/util.go
internal/impl/config.go
internal/impl/shellcmd/command.go
internal/telemetry/sentry.go
internal/telemetry/telemetry.go

1. Unexport some constants in `env`
2. Rename some functions in `env`

chore: update env constants and functions

---

internal/vercheck/vercheck.go

For trigger update to work, we need to invoke the "launcher" and not the "devbox CLI binary".
To do so, we can use the `LAUNCHER_PATH` env-var. And fallback to "devbox" if in PATH,
or finally as a fail-safe to the prior `os.Executable`.
:eyes:
carefully pair-programmed with @mikeland86. We'll test after building the pre-release
in `0.4.9-dev`.

[version update] use LAUNCHER_PATH in triggerUpdate function

---

internal/boxcli/root.go
internal/cmdutil/cmdutil.go
internal/impl/devbox.go
internal/impl/global.go
internal/nix/doc.go
internal/nix/install.go
internal/nix/run.go
internal/services/manager.go
internal/vercheck/vercheck.go
internal/wrapnix/wrapper.go

1. add cmdutil package
2. move command related functions to this package
3. tweak some error handling

feat: add cmdutil package to provide utils for commands

---

internal/envir/util.go
internal/impl/devbox.go
internal/initrec/recommenders/javascript/nodejs.go
internal/initrec/recommenders/python/python_poetry.go
internal/initrec/recommenders/ruby/ruby.go
internal/planner/plansdk/version.go
internal/searcher/client.go
internal/searcher/searcher.go

1. Add `GetValueOrDefault` in package `envir`
2. Use the function in `searcher` and `impl`
3. simplify some functions in `initrec` and `plansdk`

chore: add GetValueOrDefault for environment variables

---

internal/boxcli/featureflag/lockfile.go
internal/impl/devbox.go

[lockfile] Enable feature flag

---

examples/stacks/drupal/composer.lock
examples/stacks/drupal/web/.htaccess
examples/stacks/drupal/web/sites/default/default.settings.php

[easy][examples] Fix vulnerability

---

internal/impl/devbox.go
internal/impl/global.go
internal/nix/profile.go
internal/nix/search.go
testscripts/info/info.test.txt

`devbox info php@8` now works correctly
```bash
devbox info php
devbox info php@8
devbox info php@latest
```

[info] Ensure devbox info works with versioned packages

---

examples/README.md
examples/development/haskell/my-project/README.md
examples/development/ruby/README.md
examples/flakes/README.md
examples/flakes/go-mod/.gitignore
examples/flakes/go-mod/README.md
examples/flakes/go-mod/devbox.json
examples/flakes/go-mod/devbox.lock
examples/flakes/go-mod/ory-cli/flake.lock
examples/flakes/go-mod/ory-cli/flake.nix
examples/flakes/overlay/README.md
examples/stacks/django/README.md
examples/stacks/jekyll/README.md
examples/stacks/lapp-stack/README.md
examples/stacks/lepp-stack/README.md
examples/stacks/rails/README.md

* Add a Go Mod Flake Example
* Add links back to our docs for some key examples
Markdown Only

Go Mod Example + Doc Links

---

internal/boxcli/search.go

[search] unhide command

---

internal/vercheck/vercheck.go

:facepalm:
I'm so sorry. I added these hardcodes last minute to do a sanity test and forgot to undo the change.
Will test

[update] remove test hardcode

---

examples/data_science/llama/README.md
examples/data_science/llama/devbox.json

Title says it.
Follow README.md in the examples/data_science/llama/README.md

[examples] Added llama example

---

internal/boxcli/featureflag/autolatest.go
testscripts/rm/add-rm.text.txt
testscripts/rm/rm.test.txt

TSIA
To be merged once https://github.com/jetpack-io/devbox/pull/1000 and https://github.com/jetpack-io/devbox/pull/1009 are merged.

[versions] Enable auto-latest

---

plugins/pip.json

[easy][pip] Fix pip plugin

---

.envrc
internal/impl/devbox.go
internal/impl/packages.go
internal/nix/input.go
internal/nix/input_test.go
internal/nix/profile.go
internal/nix/search.go

Ensure that nixkgs has been downloaded in a few places we were expecting it and causing poor UX.
* Installed a few packages
* unit tests

[UX] Improve ux when nixpkgs has not been downloaded

---

internal/impl/config.go

[easy][bug] Fix legacy resolving when nixpkgs hash is not set

---

docs/app/docs/devbox_examples/languages/ruby.md

[docs] Mention bundler flags/configs for ruby projects

---

docs/app/docs/devbox_examples/languages/ruby.md

[docs][easy] Fix missing code block type in ruby.md

---

README.md

[readme][easy] Update readme example

---

.github/workflows/cli-release.yml

[cicd] Fix pre-release

---

docs/app/docs/guides/pinning_packages.md

Minor copy change to use the correct file name.
Manually read the content.

Use `devbox.lock` instead of `Devbox.lock`

---

examples/servers/nginx/README.md
examples/servers/nginx/devbox.d/nginx/nginx.conf
examples/servers/nginx/devbox.lock

It turns out that our nginx plugin works as expected, but the example is not up-to-date according to the plugin. Tested with devbox.sh
devbox.sh
devbox services up

Fix nginx example

---

plugins/php.json

The PID file was set to the log file path.

fix: pid file was set to log file path

---

internal/impl/devbox.go

TSIA
- compile
- `./devbox shell --pure`
- `echo $USER`
- `echo $DISPLAY`

[CLI] Removed DISPLAY & USER to leak to pure shell

---

.github/ISSUE_TEMPLATE/feature-request.md

Currently we have issue templates for Bug Reports and for Plugin Requests, but not for general Feature Requests. This PR adds a template for the Feature Request case.

Add an issue template for Feature Requests

---

docs/app/docs/devbox_examples/servers/apache.md

[plugins] Update file names and other punctuation in apache docs

---

go.mod
go.sum
internal/boxcli/global.go
internal/boxcli/setup.go
internal/nix/install.go
internal/ux/messages.go
internal/vercheck/vercheck.go

1. add `FNotice` and reuse it
1. Install an old version of devbox
2. Run `devbox` to trigger version checking
3. See the notice message

[ux] Add FNotice

---

docs/README.md
docs/app/docs/devbox_examples/index.md
docs/app/docs/devbox_examples/stacks/laravel.md
internal/templates/templates.go

Add Docs for the Laravel Example. Also adds Laravel to Templates
Local host

Initial Laravel Docs

---

docs/app/docs/guides/using_flakes.md

Feel free to complete the thought instead, if you remember what it was!

Remove incomplete sentence in docs

---

examples/stacks/django/devbox.json
examples/stacks/django/devbox.lock

1. Updates python + pip package versions to align with stdenv (maybe?)
2. Install pip packages using [pep517](https://peps.python.org/pep-0517/)
Tested in Devbox Cloud 
https://github.com/jetpack-io/devbox/?branch=jl/django-fix&folder=examples/stacks/django
(Wow what a handy feature)

Fix the Django Example

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json

[vscode-extension] Version bump and README/CHANGELOG update

---

docs/app/docs/ide_configuration/vscode.md

Title says it
Partially addresses #1029
CICD

[Docs] Updated docs for vscode integration

---

docs/app/docs/ide_configuration/vscode.md

[docs] Fixed broken link in vscode doc page

---

docs/app/docs/cli_reference/devbox_add.md

add docs for `--allow-insecure`

---

.github/ISSUE_TEMPLATE/package-issue.md

Add a new issue template for packages
N/A

Add a new issue template for packages

---

docs/app/docs/devbox_examples/index.md
docs/app/docs/devbox_examples/stacks/spring.md
examples/stacks/spring/README.md

Add Spring Boot Documentation to our Docs + Readme
`yarn start` on localhost

Add Spring Boot Documentation

---

examples/plugins/github/test.sh

[easy][plugins] Fix test

---

examples/development/nodejs/nodejs-npm/devbox.json
examples/development/nodejs/nodejs-npm/devbox.lock

Update node npm package version
devbox install

Update node npm package version

---

examples/flakes/remote/devbox.json
examples/flakes/remote/devbox.lock

Recent Process compose changes broke their flake (or at least how we install it)

[easy][examples] Fix remote flake example

---

testscripts/run/env.test.txt
testscripts/run/pure.test.txt
testscripts/run/script.test.txt
testscripts/shellenv/node/devbox.json

Updating these to use versioned packages. I decided against adding complexity to the tests by keeping unversioned packages as well, but let me know if you disagree.
the Github Action for testscripts should pass

[testscripts] update to use versioned packages

---

README.md

Link Nixhub in the Readme
TSIA
Markdown only change

[Easy] Update README.md to link to Nixhub

---

internal/impl/devbox_test.go
internal/impl/update.go
internal/impl/update_test.go

I'm sorry if this steps a bit on your toes :( . I just figured I wanted some unit test before I made the changes to the merging logic, and noticed that if I just refactored a function a little bit, then we could add some unit tests easily at the function level.
I just added 1 unit test here to demonstrate, and will add more later as I implement the bugfix.
Unit tests

[update] Add simple unit test for lockfile merge logic

---

.github/workflows/vscode-ext-release.yaml
vscode-extension/README.md
vscode-extension/package.json

Added github action step to publish to openvsx
Addresses #1340 
locally tested the `ovsx publish` command

[extension] Added github action step to publish to openvsx

---

docs/app/docs/cli_reference/devbox_global_push.md

[docs] Added devbox global push docs page

---

examples/development/csharp/hello-world/README.md
examples/development/fsharp/hello-world/README.md
examples/development/go/hello-world/README.md
examples/development/haskell/README.md
examples/development/java/gradle/hello-world/README.md
examples/development/java/maven/hello-world/README.md
examples/development/nodejs/nodejs-npm/README.md
examples/development/nodejs/nodejs-pnpm/README.md
examples/development/nodejs/nodejs-yarn/README.md
examples/development/php/php8.1/README.md
examples/development/python/pip/README.md
examples/development/python/pipenv/README.md
examples/development/ruby/README.md
examples/servers/apache/README.md
examples/servers/caddy/README.md
examples/servers/nginx/README.md

TSIA -- realized the YAML metadata headers didn't render well on the templates page
Localhost

Change YAML titles to H1 for better rendering

---

devbox.json
devbox.lock

woo! new version is now in our index.
testscripts should pass :fingers-crossed:

[go] update to 1.21 version

---

.github/workflows/cli-tests.yaml

[Github Action] Only run max space action on ubuntu

---

examples/development/haskell/devbox.lock
examples/development/php/php8.1/devbox.lock
examples/stacks/drupal/devbox.lock
examples/stacks/lapp-stack/devbox.lock
examples/stacks/lepp-stack/devbox.lock
examples/stacks/rails/devbox.lock
internal/boxcli/featureflag/remove_nixpkgs.go

We can now update all the examples, and run the tests!
Assuming this passes, I think we can enable the feature. Still feel it should not go in this week's release, but in the next one so we can dog food it internally.
ran `devbox run update-examples`.
testscripts should pass

[rm nixpkgs] enable feature flag (assuming tests pass)

---

devbox.lock

```
ran `devbox update`
```
tests should pass

[easy] run devbox update to add system-info and store-paths to devbox.lock

---

examples/development/go/hello-world/README.md

fix: spelling

---

.github/workflows/cli-tests.yaml

[cicd] Test nix 2.18

---

internal/boxcli/featureflag/remove_nixpkgs.go

[remove nixpkgs] enable feature for next release

---

go.mod
go.sum
internal/boxcli/auth.go
internal/boxcli/pull.go
internal/boxcli/push.go

[auth] Update to newest auth pkg

---

docs/app/package.json
docs/app/yarn.lock

[docs] upgrade docusarus

---

.github/workflows/docker-image-release.yml

title says it 
not tested, 
CICD will break if issues arise.

added arm64 support for multi user nix in docker

---

examples/stacks/rails/process-compose.yml

Corrected it to reflect rails and not django
Changed `django` to `rails`
No test needed, comment update

Update process-compose.yml in rails stack

---

internal/devpkg/flakeref.go
internal/devpkg/flakeref_test.go

Improve `FlakeInstallable.String` so that it reassembles the installable string using the current field values instead of returning the original parsed string that it came from. This mirrors the other commit that updates `FlakeRef.String`. Similar to `FlakeRef.String`, `FlakeInstallable.String` normalizes the resulting string so that if two installables are equal, then their strings will always be equal.

devpkg: use struct field values in FlakeInstallable.String

---

docs/app/docs/devbox_examples/servers/nginx.md
plugins/nginx/nginx.conf
plugins/nginx/nginx.template

* Docs now describe how the nginx.template and nginx.conf files interact
* Added comments to nginx.conf + nginx.template so users know they have to modify nginx.template
* Updated example
Build devbox locally, then made sure the nginx example works

[Docs] Clarify how NGINX Plugin works in docs

---

internal/impl/generate/tmpl/devcontainerDockerfile.tmpl

Potential fix of mentioned security issue: https://github.com/jetpack-io/devbox/issues/1638
devbox generate dockerfile
docker build -t devbox-test .
docker run -it devbox-test

 [docker] security fix of sudo/chown/user issue #1638 

---

internal/nix/install.go

[nix] Bump auto-installer to 18.1

---

.schema/devbox-plugin.schema.json

Adds a JSON schema for creating plugins. Hopefully, this should make authoring plugins a bit easier
Tested against the `devbox plugins` repo

Create a json schema for plugins

---

docs/app/docs/guides/pinning_packages.md
docs/app/docs/guides/scripts.md
docs/app/docs/guides/using_flakes.md

So I read about devbox in a reddit thread and found it interesting. So I looked into the guides and found a typo,  so while fixing that I decided to go through some more of your guides and fixed the overall wording and grammer for the docs
Not tested

guides: Improve overall wording

---

internal/boxcli/auth.go

[easy][auth] whoami should not require project

---

testscripts/languages/php.test.txt

A version of PHP is having trouble building, possibly related to https://github.com/php/php-src/issues/12965
This updates the php test to use a newer version.
CICD

[tests] Update php test

---

internal/devbox/devbox.go

[secrets] Show better error if secrets not initialized

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json

[vscode-exntension] extension version 0.1.4 changes

---

internal/boxcli/secrets.go
internal/fileutil/fileutil.go

[secrets] Fix working dir for secrets upload/download

---

internal/boxcli/featureflag/resolvev2.go

@gcurtis confirmed this is ready to enable now that the API has updated
compiles?

[search api] enable /v2/resolve api

---

internal/shellgen/generate.go

In b3903520 the call to nix print-dev-env was updated to explicitly use a path flake reference. This means that Nix no longer tries to build the flake as part of a git repo, and therefore we no longer need to add it to git.

internal/shellgen: stop adding flake to git

---

examples/insecure/devbox.json

Is flaky. Need to investigate.

[easy][cicd] Disable insecure pacakge example test

---

internal/devbox/update.go

See comment in code. Not worth returning an error for this.

[update] Ignore update flake error

---

.github/workflows/cli-tests.yaml

[CICD] Unbreak

---

internal/devbox/packages.go

This function used to check for packages in profile, but that's redundant with
checking in the store and also inaccurate. A package may have been installed
in the nix store, but not yet in the nix profile: for example, `devbox add`
but not yet `devbox shell`.
`devbox add ripgrep` was already in my store and worked as expected.
`devbox add ripgrep@14.0.2` was not in store and showed output as expected.

[cleanup] remove unnecessary code when installing packages in store

---

internal/devconfig/file.go
internal/templates/template.go

Attach schema and templates to a specific version of devbox.
`devbox create --template`
`devbox init`

[versioning] Add tag version to json schema and templates

---

plugins/nodejs.json

[corepack] Make opt-in

---

examples/development/nodejs/nodejs-pnpm/README.md

Update nodejs README.md to include corepack

---

internal/devbox/secrets.go

[secrets]Unbreak

---

internal/build/build.go

[auth] Change success redirect url

---

go.mod
go.sum
internal/devbox/cache.go
internal/devbox/providers/identity/identity.go
internal/nix/cache.go

If user specifies a `DEVBOX_ACCESS_TOKEN` we use it to fetch a short lived JWT access token.
generated a pat and used it `DEVBOX_ACCESS_TOKEN=xxx devbox add hello`

[pat]Exchange pat for access token

---

internal/boxcli/cache.go

The `devbox cache credentials` subcommand prints out short-lived AWS STS credentials that grant access to the user's Nix cache.
The output follows the format described in `aws help config-vars` under `Sourcing Credentials From External Processes`. This allows the AWS CLI/SDKs to obtain credentials from Devbox. For example:
[default]
credential_process = /usr/local/bin/devbox cache credentials
Because Nix uses the AWS SDK's default credential chain, this allows it to automatically authenticate with private Devbox caches.
Note: this can be improved by using the newer credentials-only API endpoint, which is faster.

internal/boxcli: add `devbox cache credentials`

---

internal/vercheck/vercheck.go

[launcher] Bump version

---

.schema/devbox.schema.json
examples/cloud_development/temporal/.envrc
examples/data_science/jupyter/.envrc
examples/data_science/pytorch/basic-example/pyproject.toml
examples/development/bun/devbox.json
examples/development/go/hello-world/.envrc
examples/development/php/latest/.envrc
examples/development/python/pip/.envrc
examples/development/ruby/.envrc
examples/plugins/github-with-revision/devbox.json
examples/plugins/github/devbox.json
examples/plugins/v2-github/devbox.json
examples/plugins/v2-local/devbox.json
examples/servers/nginx/.envrc
examples/stacks/jekyll/.envrc
plugins/nodejs.json

Updates to new domain in envrcs and plugins

update envrcs and plugins

---

internal/nix/nix.go
internal/nix/nix_test.go

Parse the Nix version, system, and nix.conf path from `nix --version --debug`. The output from this command was tested on Nix versions 2.12 to 2.21.

internal/nix: get nix.conf path from nix --version

---

README.md
docs/app/docusaurus.config.js
docs/translation/README-zh-CN.md

[easy] change discord links

---

docs/app/docs/cli_reference/devbox_generate_direnv.md
docs/app/docs/cli_reference/devbox_generate_readme.md

Fix documentation for these commands:
- devbox generate direnv -h
- devbox generate readme -h
Markdown preview in VSCode

[docs] Minor fixes

---

docs/app/docs/devbox_cloud/index.mdx
internal/cloud/cloud.go

[Github App] devbox cloud app rename to jetify

---

docs/app/vercel.json

TSIA. Mitigating Google crawling issues
On vercel preview

Add trailing slash redirection to docs

---

.github/workflows/cache-upload.yml

[easy] Cleanup cache action

---

internal/pullbox/s3/push.go

fix: close archivePath

---

docs/app/docs/devbox_examples/databases/mongodb.md
docs/app/docs/devbox_examples/databases/rabbitmq.md

Add documentation for RabbitMQ + MongoD
Localhost + `npm run build` to test broken links

Add mongodb + rabbitmq docs

---

docs/app/docs/devbox_examples/databases/rabbitmq.md
docs/app/docs/devbox_examples/index.md

TSIA
localhost + npm run build

Fix errors on rabbitMQ + Index Page

---

.github/workflows/cache-upload.yml
.github/workflows/cli-tests.yaml
docs/app/docs/continuous_integration/github_action.md

[cicd] Update actions

---

internal/devbox/providers/nixcache/nixcache.go

[credentials] Add version to cache key

---

internal/build/build.go
internal/devbox/cache.go
internal/devbox/providers/identity/identity.go

Show link to configure cache if user is logged in but has no write cache.

[cache] Show better error for no write cache

---

docs/app/docs/cli_reference/devbox_shell.md

- added --config flag;
- added --environment flag;
- removed dirs path param;
Checked against the command `devbox shell -h` with the latest version.

Updated devbox shell documentation

---

README.md
docs/translation/README-ko-KR.md

Hello :) I found that the README file does not have Korean version yet, I would like to add one.
Native Korean speaker translated the original README written in English.

docs: add translation of README - Korean version

---

docs/app/docs/configuration.md

json format fix of configuration.md
just docs update

[docs] json format fix of configuration.md

---

docs/translation/README-ko-KR.md

fix the relative path of some files

[i18n/kr]: Update README-ko-KR.md

---

docs/translation/README-zh-CN.md

+ sync with upstream
+ proofed and then fix typos

[i18n/zh-cn]: Update README-zh-CN.md

---

docs/app/docs/devbox_examples/databases/postgres.md

I was struggling to configure postgresql with Phoenix Framework because of the lack of instructions, so I figured it out and am adding the information that solved my problem.
I've tested on terminal and using the Phoenix Framework to create the database.

(Examples - Databases - PostgreSQL) Add more info about configuring the database

---

internal/devconfig/configfile/env.go

TSIA
Will hold off on updating the docs until the `flakepath` discussion is resolved.
devbox run test

Used go-envparse to parse .env files

---

docs/app/docs/devbox_examples/servers/apache.md
examples/development/php/latest/README.md
examples/servers/apache/.gitignore
examples/servers/apache/README.md
examples/servers/apache/devbox.json
examples/servers/apache/devbox.lock

Update apache example with proper start command for jetify cloud.
locally

Update apache example with proper start command for jetify cloud

---

examples/servers/apache/.gitignore
examples/servers/nginx/devbox.json
examples/servers/nginx/devbox.lock

Add build and start command to nginx server example.
locally

Add build and start command to nginx server example

---

examples/stacks/django/README.md
examples/stacks/django/devbox.json
examples/stacks/django/devbox.lock

Fix Django permissions by granting the default user permissions to the public schema
Fix potential psycopg2 build issues by adding the dev output of openssl
Localhost and Devbox.sh

fix permissions and build issues

---

internal/devbox/util.go

[pc-version] Bump process compose to 1.24.2

---

flake.nix

Increase flake version
Build locally, plus CI/CD

Flake version to 0.13.3

---

vscode-extension/CHANGELOG.md

[vscode extension] updated changelog

---

docs/app/devbox.json
docs/app/devbox.lock
docs/app/package.json
docs/app/pnpm-lock.yaml

I wanted to update dependencies to see if we can get rid of some Dependabot warnings. Also wanted to modernize our devbox.json a bit to make the onboarding process easier. Not totally working though.
I'm able to do `devbox run serve` but I only get 404s.
If I do build/start I get:
`Error: Cannot mix different versions of joi schemas` 
Not sure if I introduced this issue.

[docs] Update deps

---

.github/workflows/debug.yaml

[cicd] Remove macos-12

---

docs/app/docusaurus.config.js

Disable algolia temporarily until I resolve the domain issues
Localhost

[Temp] Disable Search

---

internal/telemetry/segment.go

Add event properties for the Devspace ID, repo, ref, and subdir.

telemetry: add devspace analytics

---

internal/devbox/devopt/devboxopts.go

Missed updating this comment in last round of revisions for #2391

[easy] comment fix OnStaleState

---

flake.nix

Fixes #2401 
nix build . + CI/CD

Fix flake version string issue

---

internal/devpkg/package.go
internal/nix/storepath.go

chore: fix some comments

---

.schema/devbox.schema.json

[easy][devboxjson] Add nixpkgs to schema

---

.github/workflows/cli-release.yml

This action is flaky, this is one of the reasons it fails.

[cicd] fix release action

---

docs/app/docs/faq.md

fix: faq.md

---

flake.lock
flake.nix

Bump version to 0.14.1
`nix build .`
the

Bump Version

---

docs/app/package.json
docs/app/pnpm-lock.yaml

Update doc dependencies, including algolia, to fix an issue with algolia search
Tested algolia before and after upgrading locally, confirmed bug + fix
the

Update Docs dependencies

---

.github/workflows/cache-upload.yml
.github/workflows/cli-tests.yaml
docs/app/docs/continuous_integration/github_action.md

bump version of devbox-install-action

---

.envrc
docs/app/.envrc
examples/cloud_development/temporal/.envrc
examples/data_science/jupyter/.envrc
examples/development/go/hello-world/.envrc
examples/development/php/latest/.envrc
examples/development/python/pip/.envrc
examples/development/ruby/.envrc
examples/servers/nginx/.envrc
examples/stacks/jekyll/.envrc
internal/devbox/generate/tmpl/envrc.tmpl

Update envrc template and generated files.
I think this may require us to re-allow direnv
the

[direnv] Update tmpl and links

---

.github/workflows/cli-tests.yaml

[gha] clear space to avoid 'No space left on device' error
