internal/impl/devbox.go
internal/impl/packages.go
internal/impl/update.go
internal/nix/input.go
internal/nix/input_test.go
internal/nix/profile.go
internal/nix/search.go
internal/nix/upgrade.go
internal/plugin/files.go
internal/plugin/hooks.go
internal/plugin/includes.go
internal/plugin/info.go
internal/plugin/manager.go
internal/plugin/plugin.go
internal/plugin/services.go
internal/shellgen/scripts.go

I split this up to reduce conflicts. This is part 1 of 3. 
`devbox run build`

[nix.Input][Part I] Refactor nix.Input -> nix.Package

---

internal/boxcli/featureflag/remove_nixpkgs.go
internal/impl/devbox.go
internal/lock/lockfile.go
internal/searcher/client.go
internal/searcher/model.go

**Motivation For "Remove Nixpkgs"**
Today, when adding a versioned package, Devbox will look up the versioned package’s metadata by mapping the user-specified version to a nixpkgs commit hash and an attribute path. This `nixpkgs/<commit hash>#attributePath` is used in the generated flake.nix. 
We want to remove the dependency on the nixpkgs commit hash, so that the user need not download that nixpkgs artifact, and spend time resolving it.
**Essence of the approach**
Today, when adding a versioned package, Devbox will look up the versioned package’s metadata by mapping the user-specified version to a nixpkgs commit hash and an attribute path. This `nixpkgs/<commit hash>#attributePath` is used in the generated flake.nix. 
```
builtins.fetchClosure {
fromStore = "https://cache.nixos.org"; …
```

[remove nixpkgs] part 1: write info for nix store paths in lockfile

---

vscode-extension/src/devbox.ts

Fixes the issue where terminal's $PATH env variable wouldn't get updated in integrated terminal.
buckle up, the steps are long:
- `cd vscode-extension`
- `vsce package` (install vsce via `npm i -g vsce`)
- `code --install-extension devbox-0.0.7.vsix`
- setup a devbox.json in a sample directory with a couple of packages (e.g., `hello`, `go@1.18`)
- open the sample directory in vscode
- cmd+shift+p and run `Devbox: Reopen in Devbox shell environment`
- after vscode reopens, echo $PATH in terminal

[vscode-extension] fix vscode terminal PATH 

---

internal/impl/devbox.go
internal/impl/pure_shell.go
internal/impl/shell.go
internal/wrapnix/wrapper.go

This is a follow up to [this conversation](https://github.com/jetpack-io/devbox/pull/1143#discussion_r1228862678) and [this conversation](https://github.com/jetpack-io/devbox/pull/1170#pullrequestreview-1484088841).
1. Renamed `ConvertEnvToMap` function to a more precise name. 
2. Added pure_shell.go file under `impl` package and moved related functions to pure shell there.
3. Moved call to function that creates devbox symlink outside of CreateWrappers.
- compile
- devbox shell --pure
- inside pure shell run devbox commands (e.g., `devbox version`) to confirm devbox is available inside pure shell.

[cleanup] Added pure_shell.go and renamed convertEnvToMap

---

examples/flakes/README.md
examples/flakes/remote/devbox.json

We should avoid torturing our users who may happen to run this example. The 
fenix flake downloads a ton of nix packages and takes a very long time to be
ready.
did `devbox shell`

[examples] simplify remote flakes example by dropping `fenix` flake

---

internal/vercheck/vercheck.go

I don't think it is necessary to warn users about a fresh new version if they are updating devbox
`go run main.go update`

(cli) Don't check version when updating devbox

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json
vscode-extension/src/extension.ts

- Fixed small issue in readme from last release
- added missing commands from CLI to vscode extension's command palette (install, update, search)
Q: should I add more devbox commands? e.g., global, info, version, auth, etc.
- vsce package
- code --install <generated-devbox>.vsix
- open a project with devbox.json
- cmd+shift+p and type devbox
- confirm install, update and search exists in the list of available commands and try them.

[vscode-extension] Adding missing commands to devbox vscode extension - v0.1.1

---

examples/databases/mysql/devbox.json
examples/databases/mysql/devbox.lock
plugins/mysql.json
plugins/mysql/flake.nix
plugins/mysql/process-compose.yaml
plugins/mysql/setup_db.sh

Adds a plugin for MySQL DB. Implementation is very similar to MariaDB plugin, except: 
1. init_hook is changed to use `mysqld --initialize-insecure`
2. removed unnecessary symlink wrappers from flake.nix
3. renamed services
`devbox shell` using the example in this PR, then: 
* `devbox services up` -- should show mysql + mysql_logs 
* `devbox run mysql` -- should give you a mysql console

Mysql Plugin v1

---

internal/impl/generate/tmpl/envrcContent.tmpl

I ran it and it didn't explode with 
```
$ devbox generate direnv --print-envrc
Error: template: envrcContent.tmpl:5: unexpected {{else}}
```

Fix broken envrc template

---

internal/boxcli/log.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/root.go
internal/cloud/cloud.go
internal/cloud/openssh/sshshim/command.go
internal/envir/env.go
internal/envir/util.go
internal/impl/devbox.go
internal/impl/shell.go
internal/telemetry/segment.go
internal/telemetry/sentry.go
internal/telemetry/telemetry.go

Instead of blocking the process from exiting, buffer Segment events to disk and start another process to upload them. With this change all telemetry should be non-blocking.
Most of the Segment event logic now lives in the telemetry package instead of the cobra middleware. A bunch of the unused logic around tracking CLI SSH sessions has also been removed. The telemetry package API now looks something like:
```go
type EventName int
const (
EventCommandSuccess EventName = iota
EventShellInteractive
EventShellReady
)
func Error(err error, meta Metadata)
func Event(e EventName, meta Metadata)
func Start()
func Stop()
func Upload()
```
Fixes #1003.

telemetry: report segment events asynchronously

---

internal/impl/devbox.go

Added `$TERM` to the list of env vars that leak to pure shell. Reason being, Pure shell doesn't allow colorful text in prompt because TERM variable is unset. 
Adding the TERM allows pure shell to know if terminal supports color and enable it.
Addresses #1200
- compile
- `./devbox shell --pure`
- `ls -a`
- `ls -a --color`
- confirm directories and executables show in different colors when `--color` is passed.

[CLI] Added TERM as leaking env vars in pure shell

---

internal/impl/shell.go

In `shellPath()` function where we decide which type of shell to use when dropping user in devbox shell, if we can't figure out the shell, we drop the user in the default `bash` that nix installs in store. But this bash doesn't handle arrow keys and keyboard combinations very well, so it creates a frustrating experience for users (including pure shell users).  `bashInteractive` package has all these capabilities and makes the experience better for a 'default' shell. 
So this PR changes this:
- `nix eval <bash>` to get store path and use to create default shell
to this:
- `nix eval <bashInteractive>` to get store path
- nix build <generated store path>
- use store path to create default shell
Addresses #1193
- compile
- ./devbox shell --pure
OR 
- unset $SHELL
- ./devbox shell

[CLI] Changed default nix bash to bashInteractive

---

CONTRIBUTING.md

When I was following the contribution guide, all the steps worked except:
`Tip: you can also start VSCode from inside your Devbox shell with devbox run code.`
I was getting an error stating the command `code` was not found. I checked the file `devbox run code` was running, which is `.devbox/gen/scripts/code.sh`. In the file (line 3), it tries to run `code .` -> which only works if you have installed the Visual Studio shell command.
Steps I took:
1. I could not run the command successfully without installing the Visual Studio shell command.
2. I installed the shell command.
3. The command ran successfully.
This is useful for developers who do not use Visual Studio Code as their primary IDE, therefore increasing the chances encountering an error on the beginning setup steps

Update Contribution Guide To Help Solve Potential Setup Error

---

internal/impl/devbox.go

While investigating ensuring computeNixEnv idempotency, I realized that
JoinPathLists goes a long way towards ensuring idempotency by dropping duplicates.
This is especially useful if computeNixEnv is always appending or prepending
to a path-list.
compiles
tests should pass

[minor improvement] computeNixEnv: use JoinPathLists for idempotency of LIBRARY_PATHs

---

internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

The `Env` doesn't seem to be set in the template data.
Was removed in https://github.com/jetpack-io/devbox/pull/1150/files#diff-cedf8befe2d1cf00c67c8c48fcb5dd556a871376ae57de3406f91b4d0c2c0de1
Have not tested. Relying on testscripts examples.

[cleanup] remove unused Env code from bin-wrapper template

---

internal/boxcli/run.go
internal/cloud/mutagen/install.go

Add `list` flag to `devbox run` to list all scripts.
`devbox run --list`
`devbox run -l`

[run] Add list flag to list all scripts

---

internal/impl/devbox.go
internal/lock/lockfile.go

Removes the workaround hack I had made
compiles

call nix.System directly from lock.lockfile

---

internal/lock/lockfile.go

I'm not yet entirely sure why, but #1245 led to some testscript error.
For now, I'm hiding the nix.System call inside the feature flag's if-condition
to get the testscripts status to green again on `main`.
testscripts should pass

move nix.System call inside featureflag.RemoveNixpkgs if-condition

---

internal/cuecfg/cuecfg.go

Added '\n' to end of `WriteFile()` in `cuecfg` package. This resolves an issue of devbox.json unnecessarily showing up in PR diffs because the newline at the end of the file is removed by CLI and was added by IDE formatters.
However, this function is used to write the config to a file as well as a couple of other cases such as in `auth` package. 
I'm guessing the `\n` for cases other than writing config won't cause an issue. But I haven't tested those cases.
Addresses #1248 
- compile
- `./devbox init` has a newline at the end of devbox.json and devbox.lock
- `./devbox add hello` keeps the newline at the end of devbox.json and devbox.lock

[CLI] Added a "\n" to end of writefile

---

internal/shellgen/scripts.go

Getting the following error when running any script
```
[DEBUG] 2023/07/05 21:06:23 go.jetpack.io/devbox/internal/shellgen/scripts.go:73: failed to clean up script file build.sh, error = remove ~/devbox/.devbox/gen/scripts/build.sh.sh: no such file or directory
```
It looks like `.sh` is wrongly appended to the existing files under the scripts directory. This PR fixes that.

Fix script gen clean up failure

---

internal/boxcli/featureflag/remove_nixpkgs.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl

Many testscript unit-tests were failing because they use unversioned legacy packages like `"hello"`, as opposed to `hello@latest`, or `hello@<version>`.
These legacy packages do not use the Binary Cache Store.
I considered whether we should treat them automatically as upgraded to `@latest`, but decided against:
1. We'll need this logic in the flake template regardless. There will be some packages that are not in binary store.
2.  This also keeps the `Package.IsInBinaryStore` easier to reason about.
We should instead encourage users to `devbox update` their packages: which our messaging already does. 
The remaining three testscript unit-tests are failing due to "unable to find nix executable" errors. Will fix in followup.
enabled feature-flag and ran testscripts: …

[remove nixpkgs] enable fallback for packages not in binary store

---

internal/devpkg/package.go
internal/impl/packages.go
internal/nix/nixprofile/profile.go
internal/nix/profiles.go

builds on top of #1236
Goal: 
We should be able to install the package without downloading nixpkgs.
Changes made to:
- `nixprofile.ProfileInstall`: use `/nix/store/<hash>` as `installable`
- `nixprofile.ProfileListIndex`: return index when `item.nixStorePath == pkg.PathInStore`
- `devpkgs.Package.ValidateExists`: `true` if `IsInBinaryStore`
- `devpkgs.Package.EnsureNixpkgsPrefetched`: skip if `IsInBinaryStore`.
`devbox add go@1.20.3` and `devbox rm go@1.20.3`

[remove nixpkgs] Enable installing and removing packages

---

devbox.json
devbox.lock
internal/devpkg/package.go
internal/impl/update.go
internal/lock/lockfile.go
internal/lock/resolve.go
internal/nix/nix.go
internal/nix/store.go
internal/nix/store_test.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl

This PR rolls in a few fixes:
1. Add `toPath` to `builtins.fetchClosure`
- lets us remove `--impure` flag in `nix print-dev-env`
2. Add `ca_store_path` to `devbox.lock`
- Because this is system-dependent, _and_ is calculated locally, a `devbox update` will only update the user's system's `ca_store_path`. 
- This is good for team-mates on the same system, and to avoid the slow `nix store make-content-addressed <path>` call on each `devbox shell/run/shellenv`.
3. Only update `devbox.lock` during `devbox update`. 
- Previously, it would update system info on `devbox shell/run/shellenv`.
4. Simplify `devbox.lock` schema's `SystemInfo` to have `StorePath` and `CAStorePath`. These are used as `fromPath` and `toPath` in `builtins.fetchClosure`.
Miscellaneous changes:
1. I remove `actionlint` …

[remove nixpkgs] add toPath, and edit devbox.lock only on update command

---

internal/devpkg/package.go
internal/impl/packages.go
internal/lock/lockfile.go
internal/nix/nixprofile/profile.go
internal/shellgen/flake_input.go
internal/shellgen/flake_plan.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl

This PR is a follow up to this request from @gcurtis:
https://github.com/jetpack-io/devbox/pull/1256#pullrequestreview-1517592912
BUT having `NixStorePath` and `ContentAddressedPath` seemed odd since content-addressed paths
are also nix store paths. So, in this PR, I'm explicit about `NixStorePath` being
`InputAddressedPath`.
Also - changed `BinaryStore` to `BinaryCache`.
**RFC**:
I didn't change the `lock.SystemInfo` struct, I've left it as:
```
type SystemInfo struct {
// StorePath is the input-addressed path for the nix package in /nix/store
// It is the cache key in the Binary Cache Store (cache.nixos.org)
// It is of the form <hash>-<name>-<version>
// <name> may be different from the canonicalName so we store the full store path.
StorePath string `json:"store_path,omitempty"`
// …
```

[remove nixpkgs] Naming: update Package methods to InputAddressedPath and ContentAddressedPath, and s/BinaryStore/BinaryCache

---

internal/devpkg/package.go
internal/nix/nixprofile/profile.go

I didn't feel strongly about where this lived. Moving to Package.Installable 
upon @mikeland73's suggestion in https://github.com/jetpack-io/devbox/pull/1255#discussion_r1256401600
compiles

[remove nixpkgs] move installableForPackage to a Package.Installable method

---

internal/devpkg/package.go
internal/impl/update.go

@mikeland73 points out that this line was erroneously updating all SystemInfos:
https://github.com/jetpack-io/devbox/pull/1256/files#r1256408509
Instead, we should only update the missing SystemInfo of the user's current system.

[remove nixpkgs] bug fix: update only the user's sysInfo, rather than for all systems

---

internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

This fixes an issue where if you install `coreutils` devbox shell in some cases gets stuck in infinite loop due this sequence of events:
1. devbox shell creates wrappers
2. wrappers try to omit wrappers from PATH and call devbox shellenv but it's unsuccessful 
3. devbox call in wrappers uses a couple of util tools (like `tr`) that now have their own wrappers because of coreutils.
4. the process is never able to skip the wrappers hence showing `fork: Resource Temporarily Unavailable`
I think it addresses #881 or at least a portion of it.
The fix:
in step 3 instead of calling devbox (launcher script in /usr/local/bin) we get the absolute path to the devbox binary and reference that directly in wrappers script.
This way the launcher script is not called more than once and avoids getting …

[bug] Added abs path ref. to devbox binary in wrappers

---

internal/devpkg/package.go
internal/devpkg/package_test.go
internal/impl/packages.go
internal/impl/update.go
internal/lock/interfaces.go
internal/lock/lockfile.go
internal/lock/resolve.go

`devbox add` fallthrough and fallback for packages not handled by search.
This PR does not do the following:
1. Print a warning that a package is in a fallthrough case (I'm unclear if a warning is needed?)
2. Accept an alternative nixpkg commit hash for that specific package (I'm unclear if we are deprecating `nixpkg` commit field in `devbox.json` immediately?)
I'd like to address those two things above if needed in a separate PR as a follow up.
Example lockfile:
```
{
"lockfile_version": "1",
"packages": {
"python310": {
"plugin_version": "0.0.1",
"resolved": "github:NixOS/nixpkgs/f80ac848e3d6f0c12c52758c0f25c10c97ca3b62#python310",
"source": "nixpkg"
},
"python310Packages.pip@latest": {
"last_modified": "2023-05-06T16:57:53Z",
"plugin_version": "0.0.1",
"resolved": …
```

devbox add fallthrough and fallback for packages not handled by search

---

internal/devpkg/package.go
internal/devpkg/package_test.go
internal/lock/interfaces.go
internal/lock/lockfile.go
internal/lock/package.go

Update lockfile api for package source as suggested in https://github.com/jetpack-io/devbox/pull/1264#discussion_r1259057306
devbox update

Update lockfile api for package source

---

plugins/ruby.json

Fixes an issue where global gems (like rails) were not included in PATH
Using the Rails example: 
```
devbox shell
which rails
(should show the rails in `virtenv`)
```

Add Global Gems to Path

---

examples/plugins/github-with-revision/devbox.json
examples/plugins/github/devbox.json
examples/plugins/github/test.sh
internal/plugin/files.go
internal/plugin/github.go

This makes 2 changes:
* Allow multiple plugins per repo using fragment syntax (similar to nixpkgs)
* Rename default from `devbox.json` to `default.json`
example tests

[plugins] Allow multiple plugins per repo

---

vscode-extension/CHANGELOG.md
vscode-extension/package.json

changelog and packagejson updates for v0.1.2

---

.github/workflows/cli-tests.yaml
examples/plugins/github-with-revision/devbox.json
examples/plugins/github/devbox.json
internal/plugin/github.go

This follows the following plan:
- No manifest
- Use flake notation `github:org/repo/<revision>?dir=<dir>`
- Use `plugin.json` as config file name
TODO (in follow up):
- Special case `plugin:<name>` to our own plugin repo.
`devbox run run_test`

[plugins] New github repo structure

---

internal/devpkg/package.go
internal/impl/update.go
internal/lock/package.go

After calling `devbox update`, we were not writing back to `devbox.lock`. `ensurePkgsAreInstalled` would then return early because the local lock file hadn't changed (since it re-reads `devbox.lock` from disk, rather than using the updated in-memory lockfile), so it would skip writing the lockfile as well.
This also makes the lockfile a bit more self-healing, since it will overwrite the current user's sysInfo entirely, rather than just adding the CAStorePath. This ensures that the StorePath and CAStorePath are written together.
Manually, but plan to add testscripts in separate PR. I tested a few different scenarios, notably:
1. `devbox update` adds system info for current user without changing system info for other systems.
2. If current system info is missing something (either …

[bugfix] Write back lockfile after devbox update

---

internal/lock/resolve.go

* ~Skips packages with missing store versions, since they're needed for the store path.~
* Adds debug line and context to error msg to aid in debugging.
A related question: My understanding is that nix store paths are of the form `/nix/store/<hash>-<pkg>`, and _not_ of the form `/nix/store/<hash>-<pkg>-<version>`. Meaning that some (most) package names just add the version suffix as convention. So I'm a bit worried about trying to parse the version from the name and then essentially reconstructing that here. Would prefer to just pass the untouched pkg name and use that. @gcurtis why do we parse out the version separately (if that's what we're doing)?
Another thing is I noticed that as long as the hash we pass to `nix store make-content-addressed` is correct, then the rest doesn't matter. …

[rm nixpkgs] Add more info on errors for debuggability

---

internal/devpkg/package.go
internal/nix/nixprofile/profile.go

I don't really expect there to be a difference here, but for consistency, we should be installing exactly the same packages in profile and in flake.nix, even if we expect the contents to be the same.
Before:
```
> DEVBOX_FEATURE_REMOVE_NIXPKGS=1 devbox rm hello
> DEVBOX_FEATURE_REMOVE_NIXPKGS=1 devbox add hello@2.12.1
> cat devbox.lock
...
"hello@2.12.1": {
"last_modified": "1970-01-01T00:00:00Z",
"resolved": "github:NixOS/nixpkgs/eb751d65225ec53de9cf3d88acbf08d275882389#hello",
"source": "devbox-search",
"systems": {
"aarch64-darwin": {
"store_path": "/nix/store/qh8s6yb93b1wl0jxg5i0pfq2rf7qm44j-hello-2.12.1"
},
"x86_64-darwin": {
"store_path": "/nix/store/ycbqd7822qcnasaqy0mmiv2j9n9m62yl-hello-2.12.1",
"ca_store_path": "/nix/store/1jaa5hqp6pv43z7p3xc7gkck0q3rkg4n-hello-2.12.1"
}, …
```

[rm nixpkgs] Install same package in profile as in flake.nix

---

examples/flakes/overlay/devbox.json
examples/flakes/overlay/devbox.lock
examples/flakes/overlay/yarn-overlay/flake.lock
examples/flakes/overlay/yarn-overlay/flake.nix

- Fixes the yarn overlay example so that the nodejs16 version matches the one installed by devbox
- Updates the lockfile
`devbox shell`
`yarn versions`

Update the Yarn overlay example and make sure it works

---

internal/nix/nixprofile/profile.go

*Motivation*
Seeing this output:
```
error parsing "nix profile list" output: %!w(string=Index:              0): %!s(MISSING)
go.jetpack.io/devbox/internal/nix/nixprofile.parseNixProfileListItem
/home/runner/work/devbox/devbox/internal/nix/nixprofile/profile.go:138
```
in failing CICD: https://github.com/jetpack-io/devbox/actions/runs/5658605381/job/15330281379
This fixes the error message, not the underlying cause
*Fix*
%w format string in golang is for errors. Docs: https://pkg.go.dev/fmt#Errorf

[easy][minor fix] add error object to error message's format string inputs

---

.github/workflows/cli-tests.yaml

Since we saw CLI format change (See https://github.com/jetpack-io/devbox/pull/1308) we should test against many nix versions.
Possible followup: In `main` should we run all nix versions?
CICD

[tests] Add test for old nix versions

---

internal/boxcli/featureflag/feature.go
internal/impl/update.go
internal/impl/update_test.go

This should fix the two remaining bugs in the lockfile merging logic:
1. If we have new system infos for a system that is not our own, add them anyway.
2. If we have a system info whose StorePath does not match the existing info's StorePath, then replace the info. This is to ensure correctness--all infos should come from the same resolved package version.
Added unit tests!

[bugs]: add other sysinfos, but respect existing ca paths

---

.github/workflows/cli-tests.yaml
internal/nix/store_test.go

Changes extracted from #1311 so they can be merged sooner.
- Upgrade the Nix installer action to v4 and configure the experimental features Devbox needs.
- Print out the Nix version, `/etc/nix/nix.conf`, and the resolved Nix config to make debugging easier.
- Do the same for `test-nix-versions` and add the last 3 Nix releases to the matrix. Nix 2.15.1 is the current stable version and 2.17.0 is the latest.
- Update `TestContentAddressedPath` to accept hashes from Nix <2.17 and 2.17+.

ci: upgrade nix install action, use it in nix-test-versions

---

devbox.lock
internal/impl/devbox.go
internal/impl/packages.go
internal/impl/update.go
internal/lock/local.go
internal/lock/lockfile.go
internal/lock/resolve.go

Follow up to https://github.com/jetpack-io/devbox/pull/1291.
This simplified the lockfile interface and mostly removes "local" lock from public view.
It addresses this comment: https://github.com/jetpack-io/devbox/pull/1291#discussion_r1270102373
`devbox update` on a package that needs system info downloaded.

[lock] Refactor local lock

---

internal/boxcli/services.go
internal/devpkg/package.go

On new devbox/nix installations, nix is not in PATH. For most commands, we add nix to path (add, shell, run, etc), but not for services.
Longer term, we probably don't want this if we want to support non-nix package services.
In fresh docker ubuntu, ran:
```bash
devbox init
devbox services ls
devbox add apache
devbox services up
```

[services] Fix process-compose not being installed

---

internal/boxcli/version.go
internal/cloud/openssh/config.go
internal/fileutil/fileutil.go
internal/impl/packages.go
internal/vercheck/vercheck.go
internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

**Motivation**
In #1260, the bin-wrappers were changed to invoke the devbox-binary, instead of the devbox-launcher. However, when devbox has been updated, these bin-wrappers have the older devbox-binary's path hardcoded. So, they call the older devbox-binary leading to two issues:
1. runs older functionality of the older devbox binary
2. re-prints the notice about "New devbox available. Run .... to update", despite the user already having updated their devbox.
**Implementation**
1. Create a symlink that always points to the "current" devbox binary. 
- I use "current" instead of "latest" to be consistent with the Launcher's usage of these terms.
2. In the bin-wrappers, we prepend the directory containing this devbox-symlink to PATH. The bin-wrappers revert back to directly invoking devbox, …

[Bug fix] Ensure bin-wrappers use latest devbox binary to prevent false update notifications

---

internal/impl/generate/devcontainer_util.go
internal/impl/generate/tmpl/devcontainerDockerfile.tmpl

Multi user nix installation with creating a devbox user in dockerfile causes an issue in devcontainer with Nix due to permission issues with subdirectories nix creates in `/tmp/`. Changing to a single user installation and handling everything under root user in docker seems to fix the issue.
- `devbox init && devbox add hello`
- `devbox generate devcontainer`
- open vscode: `code .`
- in vscode command palette (cmd + shift + p) run `Dev Containers: Rebuild Without Cache and Reopen in Container`
- confirm that devcontainer gets created successfully and vscode switches to remote devcontainer environment.

[devcontainer] Changed to single user nix in devcontainer

---

internal/boxcli/version.go
internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

This PR tries to address some concerns with #1324.
1. We drop `export` from `PATH` in the bin-wrappers. This would have modified
PATH for all child programs, which we need not do. 
2. When creating the symlink, we ensure the target value is passed through `EvalSymlink`.
Previously, it was set as the result of `os.Executable`, which may still have been
a symlink.
did a basic sanity test of opening a devbox shell in a golang project

[bin wrappers] Fixes: don't export PATH, and eval the symlink of the binary

---

internal/impl/devbox.go

The Devbox launcher invokes the Devbox binary with `DEVBOX_LATEST_VERSION` env-var
being set. The Devbox binary uses this env-var to determine if a new version is 
available, and if it needs to alert the user to update.
This env-var was never intended to be "exported" to the rest of the environment.
However, `devbox shellenv` was doing so.
This becomes problematic if a user does `eval $(devbox global shellenv)` in 
their shellrc file, and has done `devbox global add coreutils`. Then, doing `ls`
or `cat <file>`, or using any of the coreutils programs seems to trigger 
an avalanche of "new Devbox available" notices. 
Fix:
this PR filters out `DEVBOX_LATEST_VERSION` from the environment that shellenv
exports.
```
> export DEVBOX_LATEST_VERSION=0.5.12
> devbox shellenv | grep "DEVBOX_LATEST" …
```

[shellenv] filter out DEVBOX_LATEST_VERSION env var

---

examples/development/rust/rust-stable-hello-world/src/main.rs

Got this error:
```
cargo run . 
Compiling rust-stable-hello-world v0.1.0 (/home/savil/repo/rust)
warning: unused import: `super::*`
--> src/main.rs:10:7
|
10 |   use super::*;
|       ^^^^^^^^
|
help: consider adding a `#[cfg(test)]` to the containing module
--> src/main.rs:9:1
|
9  | mod tests {
| ^^^^^^^^^
= note: `#[warn(unused_imports)]` on by default
```
Afterwards:
```
❯ cargo test 
Compiling rust-stable-hello-world v0.1.0 (/home/savil/repo/rust)
Finished test [unoptimized + debuginfo] target(s) in 0.25s
Running unittests src/main.rs (target/debug/deps/rust_stable_hello_world-5499c8f65b21de0b)
running 1 test
test tests::test_hello_world ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
~/repo/rust is 📦 v0.1.0 via 🦀 v1.71.0 via ❄️ …
```

[rust template] Add cfg(test) attribute to mod test

---

internal/impl/generate/tmpl/devcontainerDockerfile.tmpl

Mohsen has a PR that will eventually copy all the code of the project into
the dockerfile, but I can see why that may be complicated.
For now, sending a quick fix to just copy the `devbox.lock` file 
so that our users get the exact packages they expect. This line can be removed
when the aforementioned PR is ready.
ran `devbox generate dockerfile` and saw the `COPY devbox.lock devbox.lock` 
line was present

[easy] copy devbox.lock in generated Dockerfile

---

docs/app/sidebars.js

"guides/plugins" was duplicated
Not tested

[docs] sidebars.js, "guides/plugins" section is duplicated

---

internal/boxcli/create.go
internal/templates/template.go
internal/templates/templates_test.go

Added arbitrary git repo url handling to `devbox create` by adding `--repo` and `--subdir` flags. The behavior is as follows:
Either `--template` or `--repo` are required flags.
When `--template` is provided, we clone from devbox and use the mapping (no change)
When `--repo` is provided we clone that repo and if `--subdir` is provided, we copy over only the contents of the `subdir` otherwise, the whole repo is copied over.
Update: marked the 2 new flags (`--repo` and `--subdir`) hidden.
See unit tests

[CLI] Added http url handling to create template

---

internal/cuecfg/cuecfg.go
internal/devconfig/config.go

`cuego.Complete` leads to non-trivial complexity when dealing with custom json
marshalling. In particular, it does a round-trip JSON marshal/unmarshal and fields
that are not handled by golang's json-framework can be lost. This interferes
with custom marshalling/unmarshalling.
`cuego.Complete` is only needed if we rely on the `cue:` annotations to autocomplete some fields (I mean, assign default values respecting cue constraints). We don't rely on this, so, right now it is superfluous.
I also remove the `cue:` annotations in a couple of structs since we do not
rely on them.
testscript unit tests must pass

remove cuego.Complete from cuecfg.Marshal

---

devbox.go
internal/boxcli/services.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/services/config.go
internal/services/manager.go

Fix the issue where passing a custom process compose file with `--process-compose-file` failed to load custom services
1. Add a process-compose.yaml with a service in a custom path
2. Load the file with `devbox services up --process-compose-file path/to/file
3. Verify that the service starts

fix --process-compose-file issue

---

go.mod
go.sum
internal/boxcli/midcobra/telemetry.go
internal/cuecfg/json.go
internal/devconfig/config.go
internal/devconfig/packages.go
internal/devconfig/packages_test.go
internal/impl/devbox.go
internal/impl/global.go
internal/impl/packages.go
internal/searcher/parse.go
internal/searcher/parse_test.go
testscripts/testrunner/assert.go

**Motivation**
User feedback is leading us to add more parameters besides version to the packages config.
For instance, some packages may only need to be added on certain platforms.
Previously, packages were specified as `[]string`. For example:
```
{
"packages": [
"python@3.9",
"hello",
"cowsay@latest"
],
...
}
```
In the new format, they can also be specified as:
```
{
"packages": {
"python": "3.9",
"hello": "",
"cowsay": {
"version": "latest",
}
}
}
```
NOTE: `python` is an inline-version, while `cowsay` has a struct value which can
accomodate other fields like `platforms`.
**Approach**
For now, we enable both packages as List and Map to work. The default continues to be List.
We do this by adding a `Packages` struct and `Package` struct with custom JSON marshalling and unmarshalling. …

[Config Packages] Enable optional map spec

---

.goreleaser.yaml

This should release devbox for an armv7l machine.
I've added the default values in case there was no value found here: https://goreleaser.com/customization/builds/#builds
Closes #1299
Manually created a release: `TELEMETRY_KEY=whatever SENTRY_DSN=whatever EDGE_TAG=0.0.0-dev goreleaser release --clean --skip-publish --skip-announce --snapshot` unpacked the armv7l binary and ran it on my Raspberry PI.

fix: release for armv7l

---

docs/app/docs/continuous_integration/github_action.md

Docs updated for the GitHub Action.
```diff
- run: devbox shell -- echo "done!"
+ run: devbox run -- echo "done!"
```
I ran the command locally.

Use `devbox run -- ...` instead of `devbox shell -- ...`

---

devbox.go
internal/boxcli/env.go
internal/boxcli/generate.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/impl/generate/devcontainer_util.go
internal/impl/generate/tmpl/envrc.tmpl
internal/impl/generate/tmpl/envrcContent.tmpl
internal/wrapnix/wrapper.go

This allows users to generate .envrc files that use custom env variables like so:
```bash
devbox generate direnv -e foo=bar -e foo1=bar2
devbox generate direnv --env-file .env
```
Users can also manually modify `.envrc` files to add additional flags:
`devbox generate direnv --print-envrc -e foo=bar`
Generated .envrc file with custom env flags. Then used direnv and verified environment was setup as expected.
Newly generated `.envrc` files that contain `--env` or `--env-file` flags will not be compatible with previous versions of devbox.

[env] Add env flags to direnv commands

---

examples/development/nodejs/nodejs-pnpm/devbox.json
examples/development/nodejs/nodejs-pnpm/devbox.lock
examples/development/nodejs/nodejs-typescript/devbox.json
examples/development/nodejs/nodejs-typescript/devbox.lock
examples/development/nodejs/nodejs-yarn/devbox.json

Unfortunately I can't tell if the version for `nodePackages.pnpm` is prebuilt or not. Once we have that information in https://nixhub.io I will update the examples again.
devbox install

Update node example to use the prebuilt binary

---

.github/workflows/vscode-ext-release.yaml
vscode-extension/README.md

Open-VSX does not recognize `ms-vscode-remote.remote-ssh` extension which we depend on for `Open in Desktop` feature. This stops our github actions to publish to open-vsx without removing this dependency from package.json.
I first implemented dynamic removal of this using `jq` but installing jq throws permission error, so this PR achieves the same with `sed`.
Fixed github actions so that it can automatically publish to vscode and open-vsx extension marketplaces.
N/A

[vscode extension] Fixed github action workflow error

---

devbox.go
internal/boxcli/generate.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/impl/generate/devcontainer_util.go
internal/impl/generate/tmpl/devcontainerDockerfile.tmpl

follow up for #1325 
This also potentially fixes an issue reported for users having permission issues with `.devbox/` directory inside devcontainer because of `root` user inside the container.
Added a `--root-user` flag to allow both single user installation and multi user installation for nix as well as setup for Dockerfile and devcontainer.json.
This allows users to choose either `devbox` as a user in the container environment (default) or `root` as a user in the container environment (passing `--root-user` flag).
`devbox generate dockerfile -f -r`
compare content of Dockerfile with 
`devbox generate dockerfile -f`

Added --root-user flag to devbox generate

---

internal/devconfig/packages.go
internal/devpkg/package.go
internal/impl/devbox.go
internal/impl/flakes.go
internal/impl/global.go
internal/impl/packages.go
internal/impl/update.go
internal/lock/interfaces.go
internal/lock/lockfile.go
internal/nix/install.go
internal/nix/nix.go
internal/plugin/manager.go
internal/plugin/plugin.go
internal/shellgen/flake_plan.go
internal/shellgen/scripts.go

This PR lays some groundwork for introducing platform-specific packages in a later PR (#1358)
This PR makes the following changes to `devbox` struct:
1. Replace `devbox.Packages` with `ConfigPackageNames()` and `InstallablePackageNames()`. 
2. Replace `devbox.PackagesAsInputs` with `ConfigPackages()` and `InstallablePackages()`. 
Updates callers to call the appropriate one.
**devpkg.Package changes**
I also introduce a new method `devpkg.PackagesFromConfig`, which enables us to add an `isInstallable bool` field on the `devpkg.Package`. I needed this because it affects the implementation of certain methods (such as `IsLegacy` changed in #1358).
One can still construct via `PackagesFromStrings` which default to `isInstallable = true` (as before). I audited the callers.
Did adhoc testing. …

[Packages] Introduce the concept of Installable packages

---

internal/impl/devbox.go
internal/impl/packages.go
internal/impl/update.go

This PR refactors `devbox.findPackagesByName` to be constructed from `devconfig.Package`.
**Motivation**
`devbox.Update` calls `findPackageByName` and needs to call `devbox.Add` again with the Platform and ExcludedPlatforms. (see #1370)
compiles

devbox.findPackagesByName should be constructed from Config packages

---

devbox.go
internal/boxcli/add.go
internal/devconfig/packages.go
internal/devconfig/packages_test.go
internal/devpkg/package.go
internal/impl/packages.go
internal/impl/update.go
internal/nix/nix.go
testscripts/add/add_platforms.test.txt

**Motivation**
Some users have a need to install platform-specific packages. For example, `glibcLocales` cannot be installed on macOS but may be needed on Linux.
**Approach**
We enable two flags in `devbox add`:
```
> devbox add glibcLocales --exclude-platform x86_64-darwin
> devbox add darwin.apple_sdk.frameworks.Security --platform x86_64-darwin 
> devbox add darwin.apple_sdk.frameworks.Security --platform aarch64-darwin 
```
Follow up PRs:
Added testscript unit test
Adhoc testing:
```
savil@Savil-Srivastavas-MacBook-Pro ~/c/j/d/e/d/g/hello-world (savil/config-packages-2)> rm -rf .devbox
savil@Savil-Srivastavas-MacBook-Pro ~/c/j/d/e/d/g/hello-world (savil/config-packages-2)> devbox shell
Installing package: go@1.19.8.
[1/1] go@1.19.8
[1/1] go@1.19.8: …
```

[per-OS Packages] Add platforms and excluded_platforms functionality

---

devbox.go
internal/boxcli/add.go
internal/devconfig/packages.go
internal/impl/packages.go
internal/impl/update.go
internal/nix/nix.go
testscripts/add/add_platforms.test.txt

This PR enables calling `--platform` with multiple values with `devbox add`.
It gives the user an option to user either or both (1) comma-separated flag values (2) multiple flag invocations. Like:
`--platform <platform>,<platform>...,<platform> --platform <platform> --platform <platform>`
Ditto for `--exclude-platform`
Augmented testscript unit test

[per-OS Packages] in devbox add, allow multiple --platform/--exclude-platform flag values

---

internal/nix/nix.go
internal/nix/nixprofile/profile.go

Changes the error message to suggest using `--platform/--exclude-platform` with `devbox add`.
I wish we had a way to recommend the platforms that are supported for the exact package being installed, but we don't.
The heavy lifting for this was done in #1279. Thanks @mikeland73!
```
> devbox add glibcLocales
Installing package: glibcLocales.
Error: package glibcLocales cannot be installed on your platform x86_64-darwin. Consider using `--platform` or `--exclude-platform` with `devbox add` to install on a supported platform. Other available platforms are: aarch64-darwin, aarch64-linux, i686-linux, x86_64-linux, armv7l-linux.
```

[per-OS Packages] Suggest --platform/--exclude-platform upon error with installing package that is uninstallable on user's platform

---

internal/devconfig/packages.go
internal/devpkg/package.go
internal/impl/packages.go
internal/impl/update.go

This PR fixes a slightly edge-casey workflow:
1. User on macOS tries to `devbox shell` with `glibcLocales` in devbox.json. Note: unversioned package.
2. Is asked to run: `devbox add glibcLocales --exclude-platforms x86_64-darwin`
3. Running that, prints a notice to run `devbox update`.
4. Runs `devbox update`.
This should work, but was previously broken for two reasons:
1. In `update.go`, we were calling `devbox.Add` with `nil` for platforms and excluded_platforms. 
2. In `devbox.Add`, we check `versionedPkg.ValidateExists()` prior to converting the raw package name to the versioned-name.
Both are now fixed.
Ran the workflow described above. It's hard to write a testscript unit-test, since
some packages build may or may not build on whichever system is running the unit-test. And mocking …

[per-OS Packages] fix devbox update for unversioned packages with platform/excluded-platform

---

internal/devconfig/packages.go
testscripts/add/add_platforms.test.txt

Background:
for a package, `platforms` and `excluded_platforms` should be defined mutually-exclusively.
Previously, we were being "clever" by dropping "excluded_platforms" when a user
does `devbox add <package> --platform <platform>`. But I think we should:
1. Ensure the user explicitly makes the change to their devbox config.
2. Be consistent with how the inverse is handled: using `--exclude-platform` when `platform` is defined.
added testscript unit-tests

[per-OS Packages] Error if adding --platform, when `excluded_platforms` is defined

---

.github/workflows/cli-tests.yaml
internal/devconfig/packages.go
internal/devpkg/package.go
internal/impl/devbox.go
internal/impl/update.go
internal/impl/update_test.go
internal/lock/resolve.go
internal/nix/install.go
internal/nix/nix.go
internal/nix/nixprofile/profile.go
internal/plugin/plugin.go
internal/shellgen/flake_plan.go

`nix.System` is widely used. So, in #1357 we wanted to change its API to just
return `string` instead of `string, error`.
To do so, we cache the result in a `nix` package variable. And populate it
during `EnsureNixInstalled`.
However, `EnsureNixInstalled` was only called from Cobra command functions. But
`devbox` as a library also now needs to call it. IMO, it should always have called
it since we do rely on `nix` being installed. This PR adds this.
It also fixes up the API to:
`System: string` and `ComputeSystem: (string, error)`.
NOTE: inside `System`, I still do a best-effort to avoid panic by calling
`ComputeSystem`. This can happen in edge-cases like some tests `generate_test/TestWriteFromTemplate`
that exercise internal functions reliant on `nix.System` without calling …

[nix.System] call EnsureNixInstalled from devbox.Open, and cleanup function API

---

internal/impl/devbox.go
internal/nix/search.go
internal/searcher/client.go
internal/searcher/model.go
testscripts/info/info.test.txt

The `devbox info` command is quite old and outdated. 
1. It returns results inconsistent with the `devbox search` results. It also doesn't print much useful information except a poorly formatted package-name and version.
2. Some users have asked in the past for understanding what a particular package in the search results is for.
This PR leverages the search service's API to get the package information, and also prints a summary of the package. 
BEFORE:
```
> devbox info go
go-1.20.2
> devbox info go@1.19.2
Ensuring nixpkgs registry is downloaded.
Downloaded 'github:NixOS/nixpkgs/1c6eb4876f71e8903ae9f73e6adf45fdbebc0292' to '/nix/store/y3kz7n62fwvp331na0k17xdw4dyaa66d-source' (hash 'sha256-hI7+s1UVDsJNqNn9UGV6xTBGqMC4dqOyVpeDf+su7JU=').
Ensuring nixpkgs registry is downloaded: Success …
```

[info] Modernize via search api

---

.github/workflows/cli-tests.yaml

We could have more intentional test coverage with different nix versions:
1. Earliest supported nix version
2. Nix version 2.17 since that is the minimum for Remove Nixpkgs code paths and I want it tested
3. Latest nix version
testscripts should run

[Remove Nixpkgs] Ensure we run cli-tests for oldest supported nix version, and 2.17

---

docs/app/docs/ide_configuration/direnv.md

Based on conversation in [discord](https://discord.com/channels/903306922852245526/1140685982673416273/1140710781390954606), we want to highlight the restrictions on direnv integration in docs as requested.
`yarn build`
`yarn start`

[docs] update docs to highlight restrictions for direnv integration

---

examples/development/nodejs/nodejs-yarn/devbox.lock

Doing `devbox shell` would have `yarn` install try to build nodejs from scratch. Took way too long.
Ran `curl 'https://search.devbox.sh/v1/search?q=yarn' | jq | less`
Picked the top-most commit-hash
Ran `rm -rf .devbox && devbox shell` and it installed quickly

[cli-test] speed up yarn example

---

examples/stacks/rails/blog/Gemfile.lock
examples/stacks/rails/devbox.json
examples/stacks/rails/devbox.lock

We pin yarn to a version that has pre-built binaries.
We also update the nodejs version so it is pinned to a nixpkgs hash commit that has pre-built binaries.
From my tests (see PRs stacked from #1388), I think this should fix the cli-tests that were timing out for nix 2.17
tested locally via running `devbox shell`.

[cli-tests] fix by pinning dependencies in rails examples

---

docs/app/docs/cli_reference/devbox_global_shellenv.md
docs/app/docs/cli_reference/devbox_shell.md
docs/app/docs/cli_reference/devbox_shellenv.md

Updated docs to add `--pure` to it. It slipped my mind to update it when we added the feature. I was reminded by [this comment](https://github.com/jetpack-io/devbox/issues/1029#issuecomment-1684344164)
N/A

[docs] Added pure flag docs

---

internal/nix/nixprofile/profile.go

Instead of gating the entire per-OS packages feature due to __some__ packages
not being installable on the user's platform for that particular version, I propose
this PR.
Here, we modify the error message to be less prescriptive. We explain the two
scenarios and let the user pick.
This is obviously not the ideal UX. But a good enough measure until we can
provide firmer guidance on which version of the package may work for this 
platform?
in axiom on mac, did `devbox update` and saw:
```
Installing package: gotty@latest.
Error: package gotty@latest cannot be installed on your platform x86_64-darwin.
If you know this package is incompatible with x86_64-darwin, then you could run `devbox add gotty@latest --exclude-platform x86_64-darwin` and re-try.
If you …
```

[per-OS Packages] Improve error message if package is uninstallable

---

internal/devpkg/narinfo_cache.go
internal/devpkg/package.go

No logic change. Just grouping this code into its own file, ordered by public functions/methods on top.
Also fixed this placeholder error message: https://github.com/jetpack-io/devbox/pull/1318#discussion_r1298550115
compiles

[Remove Nixpkgs] move concurrency code to own file

---

plugins/mysql/process-compose.yaml

Fix typo in `plugins/mysql/process-compose.yaml` .

fix: typo in mysql process-compose.yml

---

internal/pullbox/s3/config.go

title says it.
Additional context, if you have a region other than `us-east-2` in your `~/.aws/config` specified, global push will fail due to region mismatch in s3 bucket and the s3 request we send to push the profile.
- change default region specified in ~/.aws/config to anything other than `us-east-2` 
- run `devbox auth login`
- run `devbox global push`

[global] Added hardcoded region to push pull bucket

---

.github/workflows/cli-tests.yaml

Actions have been failing with `no space left on device` for a few days now.
This change adds the https://github.com/marketplace/actions/maximize-build-disk-space action to leave more space available for the actual job, per @savil 's suggestion.
To choose the parameters to use, I looked at [Savil's PR's](https://github.com/jetpack-io/devbox/pull/1425) runs, for example:
https://github.com/jetpack-io/devbox/actions/runs/6005813206/job/16289263569
And noticed that before any changes:
```
Available storage:
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   62G   22G  74% /          <-------- we start out with 22G and we run out
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock …
```

Give Github Actions instance more disk

---

internal/impl/shell.go

Zim is a framework for zsh. It relies on a `.zimrc` file for its settings.
If this .zimrc file is not present in `ZDOTDIR/.zimrc`, then users
get some ugly error messages (and zim itself doesn't work).
Devbox generates a temp-dir for the new `devbox shell`'s configuration files
like .zshrc, or .bashrc, or fish.config. 
For zsh:
1. the ZDOTDIR is set to this temp dir.
2. we already symlink some other files like .zprofile. 
3. In this PR, we also symlink the .zimrc.
Fixes #1426
Note: the task title asserts that the problem is starship. However, the cause
is that zim is not supported. For good measure, in my testing below I have 
enabled starship and it works fine after the fix.
setup:
1. set zsh as the login shell
2. install zim using the curl install command.
BEFORE:
`devbox shell` output …

[shell] Support zim (a zsh framework)

---

.github/workflows/cli-tests.yaml
internal/devpkg/package.go
internal/impl/devbox.go
internal/impl/packages.go
internal/nix/nixprofile/item.go
internal/nix/nixprofile/profile.go
internal/nix/nixprofile/upgrade.go

When a package is added by store path, then when we query `nix profile list`, it'll look like this:
```
> nix profile list --profile .devbox/nix/profile/default
Index:              0
Store paths:        /nix/store/yjkac3v6c1v129fph0gvy9c7ndnx738b-cowsay-3.04
```
instead of this:
```
> nix profile list --profile .devbox/nix/profile/default
Index:              0
Flake attribute:    legacyPackages.x86_64-darwin.hello
Original flake URL: github:NixOS/nixpkgs/3007746b3f5bfcb49e102b517bca891822a41b31
Locked flake URL:   github:NixOS/nixpkgs/3007746b3f5bfcb49e102b517bca891822a41b31
Store paths:        /nix/store/gyh1bri77vlcs1pwxyg4x3z06aql2c6p-hello-2.12.1
```
Thus, when we read the profile items and try to build a map out of the item's unlockedRef, we were always ending up with a map of size …

[rm-nixpkgs] Fix profile list bug for packages added by store path

---

internal/vercheck/vercheck.go

In the generated shellrc file, we invoke `devbox log` to track shell start times.
```
> git grep "devbox log"
internal/impl/shellrc.tmpl:devbox log shell-ready {{ .ShellStartTime }}
internal/impl/shellrc.tmpl:devbox log shell-interactive {{ .ShellStartTime }}
internal/impl/shellrc_fish.tmpl:devbox log shell-ready {{ .ShellStartTime }}
internal/impl/shellrc_fish.tmpl:devbox log shell-interactive {{ .ShellStartTime }}
```
We should skip checking if devbox version is up-to-date for this case.
Also, made a change to check if the commandPath matches the prefix of the commandSkipList items. This will #1420 
Did not test. It compiles.

[bug fix] do not check version for devbox log, and for commands whose prefix is in the skip-list

---

docs/app/docs/devbox_global.md

The correct name of flag - `rm` 
```sh
$ devbox global remove nodejs
Manage global devbox packages
Usage:
devbox global [command]
Available Commands:
add         Add a new package to your devbox
install     Install all packages mentioned in devbox.json
list        List global packages
path        Show path to [global] devbox config
pull        Pull a config from a file or URL
push        Push a [global] config. Leave empty to use jetpack cloud. Can be a git repo for self storage.
rm          Remove a package from your devbox
run         Run a script or command in a shell with access to your packages
services    Interact with devbox services
shellenv    Print shell commands that add Devbox packages to your PATH
update      Update packages in your devbox
Flags:
-h, --help   help for global …
```

docs: devbox remove command not exist, only rm

---

internal/impl/generate/tmpl/devcontainerDockerfile.tmpl

Publishing a docker image for devbox, makes it easier to use an image with devbox installed and configured. So we can use it in our generated dockerfiles for `generate dockerfile` and `generate devcontainer` commands. 
`devbox generate dockerfile`
or `devbox generate dockerfile --root-user`
`devbox generate devcontainer`
or `devbox generate devcontainer --root-user`

[generate] Updated dockerfile template to use devbox image

---

devbox.json
examples/development/csharp/hello-world/devbox.lock
examples/development/elixir/elixir_hello/devbox.lock
examples/development/fsharp/hello-world/devbox.lock
examples/development/go/hello-world/devbox.lock
examples/development/haskell/devbox.lock
examples/development/java/gradle/hello-world/devbox.lock
examples/development/java/maven/hello-world/devbox.lock
examples/development/nodejs/nodejs-npm/devbox.lock
examples/development/nodejs/nodejs-pnpm/devbox.lock
examples/development/nodejs/nodejs-typescript/devbox.lock
examples/development/nodejs/nodejs-yarn/devbox.lock
examples/development/php/php8.1/devbox.lock
examples/development/python/pip/devbox.json
examples/development/python/pip/devbox.lock
examples/development/python/pipenv/devbox.lock
examples/development/python/poetry/poetry-demo/devbox.lock
examples/development/ruby/devbox.lock
examples/development/rust/rust-stable-hello-world/devbox.lock
examples/development/zig/zig-hello-world/devbox.lock
examples/flakes/php/devbox.lock
examples/flakes/remote/devbox.lock
examples/insecure/devbox.lock
examples/plugins/local/devbox.d/my-plugin/some-file.txt
examples/stacks/drupal/devbox.lock
examples/stacks/jekyll/devbox.lock
examples/stacks/lapp-stack/devbox.lock
internal/impl/update.go
testscripts/testrunner/updater/main.go

This PR adds `testscripts/testrunner/updater/main.go` that walks the `examples/`
directory and updates projects that have a `run_test` script defined. 
In the future, perhaps we want this to run on other (non run_test) projects as 
well, but that is left as an exercise for future contributors.
Also includes a fix for `devbox update` for insecure packages.
```
export DEVBOX_FEATURE_REMOVE_NIXPKGS=1
devbox run update-examples
```
Note: this adds info to devbox.lock for the Remove Nixpkgs feature that 
is not turned on. However, things should continue to work.

 introduce testscript-examples updater, and update the examples

---

.github/workflows/cli-tests.yaml

seeing odd errors in another PR, so seeing if we can bump the lint action
cicd cli-test should pass

[golangci-lint] bump action to latest release

---

examples/servers/nginx/devbox.d/nginx/nginx.template
examples/servers/nginx/devbox.json
examples/servers/nginx/devbox.lock
examples/stacks/lepp-stack/devbox.d/nginx/nginx.template
examples/stacks/lepp-stack/devbox.json
examples/stacks/lepp-stack/devbox.lock
plugins/nginx.json
plugins/nginx/nginx.template
plugins/nginx/process-compose.yaml

NGINX does not support using environment variables in it's configuration file, which makes it difficult for our plugin to configure NGINX to run in a local devbox shell.
This update to the NGINX plugin installs envsubst, and then uses it to generate a valid `nginx.conf` from an `nginx.template` file. Developers can further customize their nginx.conf by adding environment variables to the `nginx.template` file. 
Envsubst will generate the nginx.conf whenever `devbox services up` or `devbox service start` is run. 
Using the nginx example:
1. Change the NGINX_WEB_PORT variable
2. Run `devbox services up`
3. NGINX should generate a valid nginx.conf in the `devbox.d/nginx` folder, and run on the NGINX_WEB_PORT

Use `envsubst` in our NGINX plugin

---

internal/devconfig/packages.go
testscripts/add/add_platforms_flakeref.test.txt

Discussing with @lagoja, we felt that we can omit the version string if its empty
`devbox add github:F1bonacc1/process-compose --exclude-platform x86_64-darwin`:
BEFORE:
```
{
"packages": {
"github:F1bonacc1/process-compose/v0.40.2": {
"version": "",
"excluded_platforms": [
"x86_64-darwin"
]
}
},
...
}
```
AFTER:
```
{
"packages": {
"github:F1bonacc1/process-compose/v0.40.2": {
"excluded_platforms": [
"x86_64-darwin"
]
}
},
...
}
```

[per-OS Packages] omitempty for version in expanded Package json representation

---

internal/lock/resolve.go
internal/nix/command.go
internal/nix/store.go

**Motivation**
With Remove Nixpkgs feature on, installing `curl@8.0` was failing with:
```
[3/7] curl@8.0
don't know how to build these paths:
/nix/store/0xyi7w3cm3g7gzwfpwqzx0n7xks2sdc6-curl-8.0.1
asked 'https://cache.nixos.org/' for '/nix/store/0xyi7w3cm3g7gzwfpwqzx0n7xks2sdc6-curl-8.0.1' but got '/nix/store/0xyi7w3cm3g7gzwfpwqzx0n7xks2sdc6-curl-8.0.1-bin'
error: path '/nix/store/0xyi7w3cm3g7gzwfpwqzx0n7xks2sdc6-curl-8.0.1' is required, but there is no substituter that can build it
```
**Explanation**
Thanks to @gcurtis.
curl’s first (and therefore default) output is `bin`, not `out`, so Nix is appending `-bin` to the path.
From `man nix-build`:
> If a derivation has multiple outputs, nix-build will build the default (first) output. You can also build all outputs:
$ nix-build …

[rm nixpkgs] use path-from-hash-part command when updating lock file

---

docs/app/devbox.json
docs/app/devbox.lock
docs/app/docs/cli_reference/devbox_add.md
docs/app/docs/cli_reference/devbox_global_add.md
docs/app/docs/configuration.md
docs/app/docs/guides/pinning_packages.md
docs/app/docs/guides/platform_specific_packages.md
docs/app/sidebars.js

Add docs for the new schema and commands that support platform specific packages
Localhost, also check Vercel Docs for more details

Docs for platform-specific packages

---

.github/workflows/cli-release.yml
.github/workflows/cli-tests.yaml
testscripts/testscripts_test.go

**Motivation**
The name summary for `cli-tests` in the Github PR page is:
```
test (false, ubuntu-latest, true, 2.12.0)
```
This isn't very helpful.
This PR:
- removes the `booleans` and changes their true/false states to explicit names
- renames `devbox-json-tests` to `project-tests` for brevity.
will observe the testscripts pass...
Now, it looks like:
```
cli-tests / test (not-main, ubuntu-latest, project-tests, 2.12.0)
```
which is much more understandable.

[Github Action] cli-test: improve naming summary

---

docs/app/docs/continuous_integration/github_action.md

Update the version listed, and link to the GitHub Marketplace page in order to avoid needing to duplicate its configuration table.
As a bonus, fix capitalization of GitHub.

docs: Update action version in github_action.md

---

internal/impl/devbox.go

Problem:
Commands like `devbox version` are installing nix.
Cause:
By inserting a `debug.PrintStack()` one can [see](https://gist.github.com/savil/0fff37124abae3d1c0088404c05a73cc) that `devbox.Open` is invoked
for `devbox version` from a few places. In the latest 0.5.12 release, we added
a call to `ensureNixInstalled` in `devbox.Open`. Hence even though we don't set `PreRunE: ensureNixInstalled`
in the command, the nix install is triggered.
The original motivation for adding this call in `devbox.Open` was that `nix` is pretty widely used in the `Devbox`
library, and we should add `ensureNixInstalled` as a check.
compiles
will rely on tests to pass

[devbox.Open] drop ensureNixInstalled function call

---

docs/app/docs/configuration.md
docs/app/docs/guides/pinning_packages.md
docs/app/docs/quickstart.mdx

I just discovered DevBox
I read the whole documentation
I found some errors
I did a big PR with anrelated content, if you disagree with some of the commits, i can split in several PR
It's just markdown content, i haven't tested it

improve documentation

---

internal/impl/packages.go

When trying to remove a package, or update a package, we'd print a message
like below if the package was not found in the profile.
```
Error: Package uxn@latest not found in profile. Skipping.
```
This is confusing for a few reasons:
1. Devbox users are not usually aware of a concept called "profile". This is a nix-ism that is seeping through our messaging.
2. Even if they understand "nix profile", there's nothing actionable about this message. Their package is still removed from devbox.json and the shell environment (which is what they care about).
Instead, we can make this a debug.Log, and not bother users with it.
didn't explicitly test. Compiles.

[profile remove] if package was not found, change message from error to info

---

internal/lock/resolve.go

We'd show this warning about missing store path to users.
```
❯ time devbox add nodePackages_latest.yalc@latest
Warning: Failed to resolve store path for x86_64-darwin with storeHash h1fpdwwq2x528xwq3si97z6vny0vkjhf. Installing will be a bit slower.
Warning: Failed to resolve store path for x86_64-linux with storeHash is1ds4h8qa95s31crvgf19mlmx1990s3. Installing will be a bit slower.
Warning: Warning: Failed to resolve store path for aarch64-linux with storeHash cqjb45zk4cs4i4qzkknh5116zk7z471g. Installing will be a bit slower.
Failed to resolve store path for aarch64-darwin with storeHash 5wfxcx235xpwr5lcv29ijlpw85kb0vj0. Installing will be a bit slower.
Installing package: nodePackages_latest.yalc@latest.
[1/1] nodePackages_latest.yalc@latest
[1/1] nodePackages_latest.yalc@latest: …
```

[rm-nixpkgs] drop warning about missing store path when updating lockfile

---

internal/boxcli/featureflag/remove_nixpkgs.go
internal/devpkg/narinfo_cache.go

Restores functionality implemented by https://github.com/jetpack-io/devbox/pull/1264 and refactored in https://github.com/jetpack-io/devbox/pull/1279
which was accidentally broken by https://github.com/jetpack-io/devbox/pull/1437
tldr: the `FillNarInfoCache` function breaks if packages are not in search, but we support non-search packages via fallback (.e.g. stdenv.cc.cc.lib)
I'm keeping surface area as small as possible, but as a follow up I think we can remove the `devpkg.FillNarInfoCache` calls from `impl.Add` if we simply ignore the`IsInBinaryCache` errors in [ValidateExists](https://github.com/jetpack-io/devbox/blob/main/internal/devpkg/validation.go#L10-L26)  or remove `IsInBinaryCache` from that function completely (I'm not convinced it is needed, @savil @ipince correct me if I'm …

[remove-nixpkgs] Disable remove-nixpkgs to fix non-search fallback

---

internal/boxcli/midcobra/debug.go
internal/boxcli/root.go
internal/debug/debug.go
internal/debug/time.go
internal/envir/env.go
internal/envir/util.go
testscripts/testrunner/setupenv.go

Enable this by setting `DEVBOX_PRINT_EXEC_TIME=1`
```
export DEVBOX_PRINT_EXEC_TIME=1
devbox run echo 1
```

[debug] Print exec time

---

examples/servers/nginx/devbox.lock
examples/stacks/drupal/devbox.d/nginx/nginx.template
examples/stacks/drupal/devbox.json
examples/stacks/drupal/devbox.lock
examples/stacks/lepp-stack/devbox.d/nginx/nginx.conf
examples/stacks/lepp-stack/devbox.d/nginx/nginx.template
examples/stacks/lepp-stack/devbox.json
examples/stacks/lepp-stack/devbox.lock
plugins/nginx.json
plugins/nginx/process-compose.yaml

Ugh.
Fixes a few envsubst related issues in the Nginx plugin: 
1. The `envsubst` package seemed to have a different version of envsubst than what I expected. I replaced this package with `gettext` to get the GNU version
2. `envsubst` was replacing all the nginx variables with blanks if they weren't included in the environment, which caused Drupal and PHP related examples to stop working. This update uses `gawk` to get a list of all the current environment variables and pass them as arguments to envsubst, which will make envsubst skip any unset variables. 
3. Fixed Drupal and LEPP examples to use the plugin correctly
Ran `runtest` for the examples, verified that the generated nginx.conf matched previous versions.

Fix envsubst issues

---

internal/boxcli/midcobra/telemetry.go
internal/build/build.go
internal/telemetry/segment.go
internal/telemetry/telemetry.go

Upon request by @Lagoja, this PR adds nix-version information to the sentry and segment telemetry logging.
Added a sentryDSN and telemetryKey locally, and built the binary.
Added a print-statement to verify the nix-version in the commandEvent to segment is correctly set for me.

[telemetry] add nix.version to sentry and segment

---

internal/boxcli/featureflag/remove_nixpkgs.go
internal/devpkg/narinfo_cache.go
internal/devpkg/package.go
internal/impl/packages.go
internal/impl/update.go
internal/nix/nixprofile/profile.go
internal/shellgen/flake_input.go
internal/shellgen/flake_plan.go
testscripts/add/add.test.txt

In this PR, we loosen the conditions under which `devpkg.Package.IsInBinaryCache` can be called. Internally, it checks an in-memory map for the status of the package in the binary cache. Previously, it was _required_ that callers pre-compute this status by invoking `FillNarInfoInCache`. The motivation then was to ensure that we avoid a synchronous http request if `IsInBinaryCache` is called within a loop.
However, this condition and the fact that golang lacks async-await support resulted in a loosely coupled load-and-check-later design whereby calls to `FillNarInfoInCache` would be sprinkled in various parts of the codebase and then `IsInBinaryCache` checked in other parts. This loose-coupling made it hard to reason about _why_ any particular FillNarInfoInCache was present.
The straw that …

[nar info cache] Only fillNarInfoCache in perf-sensitive code path

---

internal/nix/nixprofile/profile.go

ProfileListIndex was broken for raw flakes. This would break `devbox update`
I could have left the `return -1, errors.Wrap(nix.ErrPackageNotFound, args.Package.String())` inside the if statement, but it seems safer to just to attempt the slow matching instead of returning an error and only returning an error after all matching fails.
Blame PR: https://github.com/jetpack-io/devbox/pull/1422
```bash
devbox add github:F1bonacc1/process-compose/v0.43.1
devbox update
```

[nix] Fix profile list index for raw flakes

---

.github/workflows/docker-image-release.yml

Add arm64 builds to the non-root image build(currently the root image cannot be built because of #1444) 
I have tested this locally and confirmed the non-root image is built successfully with this change

Update docker-image-release.yml to support ARM builds for newer Macbooks

---

docs/app/docs/continuous_integration/github_action.md
internal/boxcli/featureflag/feature.go
internal/boxcli/featureflag/script_exit_on_error.go

Fixes #1457
This feature enables `set -e` in the generated shell files for the "scripts" and "init hooks" of Devbox.
This feature has been running internally for a long time to power our CICD tests for the projects in `examples/`,
and has been very useful in ensuring correctness.
This may expose bugs in user code. While this results in `devbox version update` possibly leading to 
code that used to seemingly work previously now needing some fixes, we feel this is acceptable because:
1. We no longer auto-update Devbox. Users are intentionally updating when they are ready.
2. For CICD, they can pin the devbox-version for additional Stability. This PR updates the CICD docs
to call this out.
testscripts should pass

[Script Exit on Error] enable feature flag, and add stability advice to CICD docs

---

internal/boxcli/featureflag/envsec.go
internal/devconfig/config.go
internal/devconfig/env.go
internal/impl/devbox.go
internal/integrations/envsec/envsec.go

This pre-mvp integration is mostly just to get something working. It's missing a lot of stuff. Specifically:
* envsec auto-install
* error handling (this requires new envsec `--json` output so we don't have to do clever parsing). 
* Performance. Currently `envsec.Env` gets called a few times and not cached.
One open question is how generic we want to make the integration. This implementation is pretty coupled. 
```bash
envsec set FOO=BAR
devbox run echo \$FOO
```

[envsec] Initial envsec integration

---

internal/devconfig/config.go
internal/devconfig/env.go
internal/integrations/envsec/envsec.go

* Fixes field name
* Handles json errors returned by envsec
`devbox run build`

[envsec] Fix devbox.json field and handle envsec errors

---

internal/boxcli/global.go
internal/boxcli/root.go
internal/boxcli/services.go

cobra doesn't chain `PersistentPreRunE`. So if a parent declares one and a child declares it as well, the parent function is ignored. `global` uses `PersistentPreRunE` to set the global project directory. The `services` command was running it to ensure nix is installed. The child replaced the parent, so we were never setting th
The fix here is a bit ugly but it solves them problem.
There's a UX issue I rediscovered while testing this. When adding global packages the environment is not automatically refreshed. This means services wont work until a new shell is opened or if the user does `eval "$(devbox global shellenv)"` manually.
```
devbox global add nginx
eval "$(devbox global shellenv)"
devbox global services up
```

[global] Fix global services

---

internal/impl/devbox.go
internal/impl/shell.go
internal/shellgen/scripts.go
testscripts/run/script_exit_on_error.test.txt

`set -e` can fail in fish-shells (sometimes), so we disable script-on-error for them.
I also add a testscript unit-test for script-exit-on-error, in general.
I run fish-shell, and did a sanity test that the `go/hello-world` example passes `run_test`.
BEFORE:
with this devbox.json
```
> cat devbox.json
{
"packages": [
"go@1.19.8"
],
"shell": {
"init_hook": [
"export \"GOROOT=$(go env GOROOT)\"",
"echo \"foo\""
],
"scripts": {
"run_test": "go run main.go"
}
}
}
```
doing `devbox shell` would give:
```
> devbox shell
Installing package: go@1.19.8.
[1/1] go@1.19.8
[1/1] go@1.19.8: Success
set: -e: option requires an argument
~/code/jetpack/devbox/examples/development/go/hello-world/.devbox/gen/scripts/.hooks.sh (line 1):
set -e
^ …
```

[script-on-error] disable for fish shell, and add testscript unit-test

---

internal/boxcli/root.go
internal/debug/time.go
internal/impl/devbox.go
internal/impl/packages.go
internal/shellgen/scripts.go
internal/wrapnix/wrapper.go

Profile a few functions. This shows any function that takes more than 1 ms. 
Q: does trace have this functionality? It looks like it does time events but we have to explicitly enable it using the `trace` flag? 
```bash
export DEVBOX_PRINT_EXEC_TIME=1
devbox add curl
...
Exec times over 1ms:
"syncPackagesToProfile" took 343.118292ms
"nixEnv" took 128.018333ms
"nixEnv" took 128.219083ms
"CreateWrappers" took 257.527167ms
"ensurePackagesAreInstalled" took 768.378084ms
"CreateWrappers" took 2.56ms
"devbox add curl" took 1.21434s
```

[perf] Profile possibly slow functions

---

internal/impl/devbox.go
internal/impl/shell.go
internal/shellgen/scripts.go

@Lagoja identified an issue with scripts-exit-on-error. We source init-hooks into the host shell. So, `set -e` will get set in the host shell. Any subsequent error will cause the shell to exit (error may be from the init-hook, or later in the shell). 
For now, this PR disables this feature entirely for init hooks. We'll revisit this later: https://github.com/jetpack-io/devbox/issues/1494
Also, this PR undoes the previous change to restrict this feature to fish-shells, since that only applied to init-hooks. Regular Devbox scripts always run in `sh`.
testscript unit-tests
did a sanity check that regular init_hooks work.

[script-exit-on-error] disable for init-hooks

---

examples/plugins/local/my-plugin/my-plugin.json
examples/plugins/local/test.sh
internal/plugin/hooks.go
internal/shellgen/scripts.go

Ensure custom plugin init hooks run. Previously they were only running for builtins.
`devbox run run_test`

[plugins] Fix init hooks for custom plugins

---

docs/app/docs/guides/creating_plugins.md
docs/app/docs/guides/plugins.md

Update Plugin documentation in response to #1499.
* Adds more details about how to include/add a plugin
* Updated schema to match upcoming init_hook improvements
* Adds suggestions on how to structure the plugin directory, along with an example from mongodb
Localhost, also check the preview URL from Vercel below

Update plugin documentation

---

internal/boxcli/featureflag/envsec.go
internal/devconfig/env.go
internal/impl/devbox.go
internal/impl/util.go
internal/integrations/envsec/envsec.go

This PR adds envsec to devbox env $PATH if it is used in config. This allows user to use envsec without explicitly installing it and without adding any envsec specific commands to devbox. e.g.
`devbox run envsec ls`
and `devbox shell` followed by `envsec ls` 
will both work.
Other improvements:
* Don't modify current process path when adding envsec (it's best to avoid `os.Setenv` if we can so that environment is more consistent trough run and now longer depends on when `envsec.EnsureInstalled` is called.)
* Remove feature flag (this feature is gated anyway by requiring explicit opt-in in the config) 
``` 
devbox run envsec ls
```

[envsec] Add envsec to path if used in config

---

devbox.go
internal/boxcli/add.go
internal/boxcli/cloud.go
internal/boxcli/generate.go
internal/boxcli/global.go
internal/boxcli/info.go
internal/boxcli/install.go
internal/boxcli/integrate.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/pull.go
internal/boxcli/push.go
internal/boxcli/rm.go
internal/boxcli/root.go
internal/boxcli/run.go
internal/boxcli/services.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/boxcli/update.go
internal/impl/devbox.go
internal/impl/devbox_test.go
internal/impl/devopt/devboxopts.go
internal/impl/global.go
internal/impl/packages.go
internal/impl/update.go
internal/impl/util.go
internal/plugin/info.go
testscripts/info/info.test.txt

This renames the devbox `Writer` field to the more accurate `Stderr`. It changes a few functions that used to print stuff and now they return strings instead.
Also renamed a few functions that where called `PrintX` to something more accurate because they don't actually print anything.
How to review:
* grep for `devopt.Opts` this will show all the places where we used to pass in stdout sometimes. Specifically @mohsenari please look at integrate.go. @ipince please look at telemetry.go. I think both of these were wrong.
* Please take a look at functions that used to print stuff and now return strings (i.e. Info and PrintGlobalList). I tried to keep formatting identical so nothing should change.
compiles

[code-cleanup] Rename devbox.Writer to Stderr

---

internal/boxcli/featureflag/remove_nixpkgs.go
internal/boxcli/featureflag/script_exit_on_error.go

Turning these off to reduce scope of the next release. 
did not test. Will rely on CICD being green.

[features] Turn off Remove Nixpkgs and Script Exit on Error

---

internal/boxcli/midcobra/midcobra.go
internal/boxcli/midcobra/telemetry.go
plugins/poetry.json

* When a user script errors out, show the error code (e.g. `Error: exit status 1`) This helps in cases when stderr is empty (which the previous `--quiet` was causing)
* Improve poetry plugin by removing `--quiet` flag and adding more required into in readme.
Possible future improements:
* Better error when python is not installed
* Better error when pyproject is missing
* Allow custom pyproject locations
New implementation

[errors] Show better errors when user script errors out and fix poetry plugin

---

internal/boxcli/integrate.go
internal/impl/devbox.go
internal/impl/envvars.go
internal/impl/shell.go
internal/impl/shell_test.go

We were assuming that most shells set `SHELL` upon startup, but this is only true for bash. Usually `SHELL` is only set by `login`, so we need to set it ourselves when launching the user's shell.
Also remove the `keyEqualsValue` which was only being used by the VSCode integration. This function escapes environment variable values for a shell, but we were setting the `code` process's environment with them directly. This was mangling the values by adding quotes and backslashes.
Fixes #1454.

impl: set SHELL environment variable

---

internal/boxcli/shellenv.go

I started receiving errors about `hash: command not found` in my fish shell.
I'm not quite sure why this didn't error earlier.
No longer receive these errors doing `devbox global shellenv | source` in my fishrc file

[fish] do not print hash -r in shellenv

---

internal/boxcli/multi/multi.go
internal/boxcli/multi/sync.go
internal/boxcli/update.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/impl/update.go

RFC for flag that updates all projects under a given directory (recursively) 
Also adds ability to sync specific packages via `--sync-lock` and moved sync code into `multi` package.
`devbox update --all-projects` in a few of our repos.

[RFC][update] Add --all-projects flag

---

devbox.json

I don't see any of these env-vars in my devbox shell, so didn't try unsetting
them in fish ;-)  the fish command is `set -e <name>` to "erase" the env-var.
could start devbox shell. 
before: it would break since `unset` is unrecognized.

[fish] unbreak init-hook

---

internal/impl/devbox.go
internal/impl/packages.go
internal/impl/update.go
internal/wrapnix/wrapper.go

This removes all `CreateWrappers` calls except one.  It also removes the interface used to prevent a circular dependency and passed in all arguments at the callsite. It no longer needs to recompute nix env.
It helps address performance issues where CreateWrappers was causing extra calls to ComputeNixEnv.
It builds and runs. This will need extensive testing.

[bin-wrappers] Reduce/improve when we create bin wrappers

---

internal/devconfig/packages.go
internal/impl/packages.go

@Lagoja pointed out that `devbox add <existing package>` would exit with a no-op.
In this PR, I print messages during the execution of `devbox add` about changes made to each package.
If no changes were made for a package, then I explicitly print that at the end.
```
> devbox add vim
Adding package "vim@latest" to devbox.json
Installing package: vim@latest.
[1/1] vim@latest
[1/1] vim@latest: Success
Recomputing the devbox environment.
> devbox add vim --platform x86_64-darwin
Package "vim@latest" already in devbox.json
Added platform x86_64-darwin to package vim@latest
> devbox add vim go@1.19.8
Package "vim@latest" already in devbox.json
Package "go@1.19.8" already in devbox.json
Packages vim@latest, go@1.19.8 were already in devbox.json and were not modified
> devbox add vim go@1.19.8 …
```

[add] Print messages about actions taken, or not taken.

---

internal/impl/packages.go

@Lagoja has a healthy number of `devbox global` packages. This exposed that `devbox add <package>` had a perf regression for him:
```
❯ devbox global add procs
Exec times over 1ms:
"ensurePackagesAreInstalled" took 1.44075ms
"nixEnv" took 2.446083ms
"devbox shellenv --preserve-path-stack -c /Users/johnlago/.local/share/devbox/global/default" took 49.446834ms
Exec times over 1ms:
"devbox shellenv only-path-without-wrappers" took 45.889ms
Installing package: procs@latest.
[1/1] procs@latest
[1/1] procs@latest: Success
Exec times over 1ms:
"syncPackagesToProfile" took 31.80875375s
Recomputing the devbox environment.
"CreateWrappers" took 17.186833ms
"ensurePackagesAreInstalled" took 36.056620833s
"devbox global add procs" took 36.410408875s
```
See the `syncPackagesToProfile` taking 31 …

[perf] FillNarInfoCache during nix profile's pendingPackagesForInstallation

---

devbox.lock
internal/impl/update.go

When we update the store-paths in the lockfile, we should also update the other fields, including "resolved" for the nixpkgs commit hash, and the modified-time.
This way the exact same derivation is used whether installing the binary directly via store-path, or via relying on the derivation in the package's "resolved" field. This ensures parity for the following scenarios:
1. A team has a devbox project. Some team members are using nix >= 2.17, while others are using older nix.
2. The store-path binary is no longer in the nix binary cache, and the package is installed via the older way. This should alleviate @lagoja's concern that there may be a discrepancy between the store-path and the derivation source in "resolved" field of the package.
Did `devbox update` and saw that `go@latest` had …

[lockfile] When updating store-paths, we should update all fields

---

internal/boxcli/featureflag/script_exit_on_error.go
internal/shellgen/scripts.go

[script set -e] enable feature flag

---

internal/impl/packages.go
internal/impl/update.go
internal/impl/update_test.go

This PR refactors code to reduce duplication of logic around nix profile updates.
Specifically:
- the implementation under `syncPackagesToProfile` is refactored so that we first prepare profileDir, and installablePackages, and _then_ remove extra packages from profile, and add missing packages to profile. Preparing these variables upfront reduces much code duplication.
- in `devbox.Remove`, we now rely on `ensurePackagesAreInstalled` calling `syncPackagesToProfile` to remove the package from the profile. We can eliminate the extra `removePackagesFromProfile` function.
- in `ensurePackagesAreInstalled`, we now _always_ execute it if `mode` is `install` or `uninstall`. We only check the lockfile status for `ensure` mode.
Did some basic adding and removing of packages

[RFC] [refactor] Consolidate profile update code under syncPackagesToProfile

---

internal/boxcli/shellenv.go
internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

This replaces our existing `only-path-without-wrappers` wrapper implementation to use `sed`. 
Context:
We use `only-path-without-wrappers` to remove bin wrappers in the environment of our binaries. This is particularly useful when a binary calls another binary. See https://github.com/jetpack-io/devbox/pull/1160 for more context. Unfortunately this adds a perf hit to every single binary call. In my informal experiments this cost was ~40ms. For example:
Previously, `time go version` was taking ~60ms even if environment is fully up to date.
Now, `time go version` takes ~20ms.
@Lagoja I'm getting an error in the elixer example (since that was the motivation for the original fix) but it looks like nix elixer on Sonoma is broken: https://elixirforum.com/t/bus-error-after-upgrading-to-sonoma-beta …

[perf] Replace only-path-without-wrappers with sed

---

.github/workflows/cli-tests.yaml
devbox.json
devbox.lock
internal/devpkg/package.go
internal/devpkg/package_test.go
internal/devpkg/pkgtype/runx.go
internal/devpkg/validation.go
internal/impl/devbox.go
internal/impl/packages.go
internal/lock/lockfile.go
internal/nix/search.go
internal/shellgen/flake_input.go

Inspired by golangci-lint being broken in nixpkgs, I wanted to see if I could get a quick and dirty implementation so we can replace golangci-lint from nixpkgs with runx. The current PR implements this using `runx:<path>` syntax. Since we already use `github:<path>` for nix flakes, I can't use that without breaking backwards compatibility. We could overload it.
What this PR implements:
* Add and rm of runx, with and without versions.
* runx installed packages are added to PATH for run, shell, etc
Things that are not implemented by this PR:
* Search and validation. Currently trying to install a non-existing package will fail with a semi-cryptic error.
* lockfile support.

[runx] Proof of concept for runx integration

---

examples/development/php/php8.1/devbox.json
examples/development/php/php8.1/devbox.lock
internal/impl/devbox.go
internal/plugin/manager.go
internal/plugin/plugin.go
plugins/haskell.json
plugins/mariadb.json
plugins/mysql.json
plugins/php.json

Previously, we were expecting `$buildInputs` to match the order of $PATH, specifically, packages installed first appeared first (in both $PATH and $buildInputs). This would allow us to prioritize the first binary that shows up. In a few plugins we add a flake that installs a wrapped or alternate version of the binary. We were relying on the order of `$buildInputs` to point to the correct wrapped binary.
It looks like `$buildInputs` is not deterministic, or something in the mariadb/mysql case caused the order to change.
The solution in this PR is to add a new `__remove_trigger_package` field that when set to true tells devbox to remove the package that causes the plugin to be installed. This does not affect plugins installed `include` field.
This has the additional benefit of not …

[plugins] Remove trigger package

---

internal/impl/devbox.go
internal/nix/nix.go

This has been bugging me for many months. Previously, with DEVBOX_DEBUG=1 and doing
some command that evaluated `nix print-dev-env`, we'd see output like:
```
path '/Users/savil/code/jetpack/devbox-projects/lagoja-global/.devbox/gen/flake/flake.nix' does not contain a 'flake.nix', searching up
```
This is because `nix print-dev-env` expects the path to the flake directory but not including the flake.nix itself.
changed devbox.json to trigger a re-evaluation of `nix print-dev-env`, and then
`DEVBOX_DEBUG=1 devbox install` and didn't see such output

[minor cleanup] use flake dir instead of flake-file-path in nix print-dev-env

---

internal/boxcli/run.go

Printing the name to make it easier to identify the source of the error.
Added this script
```
"hello": [
"echo \"hello\"",
"exit 1"
],
```
ran `devbox run hello` and got:
```
Error: error running script "hello" in Devbox: exit status 1
```

[error ux] print script name upon error

---

internal/impl/devbox.go
internal/impl/envvars.go
internal/impl/packages.go
internal/impl/shell_test.go
internal/impl/update.go

In this PR, we skip forcing `computeNixEnv` if a user is adding/removing/updating packages, AND if we are not in a shellenv-enabled environment from that devbox project.
Also:
- ~rename `ensurePackagesAreInstalled` to `ensureDevboxEnvIsUpToDate`~
- some minor comment cleanups
did `devbox add vim` when:
1. in devbox project's directory, but direnv disabled => did not print "Recomputing Devbox environment."
2. in devbox project's directory with direnv enabled => did print "Recomputing Devbox environment".
3. in devbox shell => did print again
Repeated the same exercise with `devbox global`:
1. with `devbox global shellenv | source` run in shellrc => did print "Recomputing Devbox environment".
2. after commenting out that line in shellrc => did not print
NOTE: there's no special …

[perf] skip forcing printDevEnv when add/rm/update outside shellenv

---

internal/impl/devbox.go

Adds a few helpful Env Vars to the shell/run/services environment. These should help in situations where a developer needs to refer to files within their project directory, but doesn't want to hardcode the path into their configuration
Since this just adds a few variables to the shell environment, it should be a fairly low risk change
Locally

add helpful env vars during shell + run

---

.github/workflows/cli-tests.yaml
devbox.json

* unified gofumpt and lint
* Added go caching to tests
* Added pre-building devbox binary to be shared between tests
CICD

[cicd] Unify lint, add caching

---

examples/development/python/poetry/poetry-demo/devbox.lock
internal/impl/devbox.go
plugins/poetry.json
plugins/poetry/initHook.sh

A user is saying that the poetry plugin's init-hook was failing for them with Fish 
shell. While the init-hook's command does work with modern fish shells, it fails
for older versions of fish. 
In this case, the user is on Ubuntu whose package manager seems to use an older
version of fish.
Regardless, we can ensure the plugin's init-hooks work for consistently if we
ensure that they are written as posix scripts executed via /bin/sh. This PR
seeks to do that.
Fixes #1550
```
cd examples/development/poetry/poetry_demo
devbox run run_test
```

[poetry plugin] ensure initHook runs with /bin/sh

---

go.mod
go.sum

Addresses:
https://github.com/jetpack-io/pkg/issues/1
did:
```
go get -u go.jetpack.io/pkg
go mod tidy
```
CICD should be green

[dependencies] update go.jetpack.io/pkg and go mod tidy

---

internal/boxcli/services.go

As per user request
`devbox services down` did run the same as `devbox services stop`

[services] make down an alias of stop

---

internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

TSIA
Using this config: https://discord.com/channels/903306922852245526/1009933892385517619/1163763578399105064
Pre-change, could not shell in, got bash nesting error.
Post-change, could shell in.

[sed] Fix bin wrappers when sed is installed with devbox

---

internal/boxcli/root.go
internal/wrapnix/wrapper.go

This feels like the safest solution to https://github.com/jetpack-io/devbox/pull/1566#discussion_r1364318788
It also avoids creating bin wrappers for `bash` and `sed` which reduces risk and improves performance.
Used setup from https://github.com/jetpack-io/devbox/pull/1566
```
devbox shell
devbox add bash
hash -r
which bash # ensure I get profile bash instead of wrapped bash
```

[wrappers] Always use system bash and sed in bin wrappers

---

devbox.go
examples/stacks/lapp-stack/devbox.json
examples/stacks/lepp-stack/devbox.json
examples/stacks/lepp-stack/devbox.lock
internal/boxcli/run.go
internal/boxcli/services.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/impl/envpath/pathlists.go
internal/wrapnix/wrapper.go

Fixes https://github.com/jetpack-io/devbox/issues/1565
The bugs:
* env vars specified via `--env-file` (and possibly via other methods) are ignored in nginx config.
* When inside a devbox shell or a direnv context, starting services would ignore env vars.
Intermediate causes:
* `envsubst` binary was a bin wrapped binary. This was resetting the env vars. Fix: Never use bin wrappers when inside a `devbox run` (This was previously only scoped to using the CLI command explicitly, but now we do it any time we use RunScript function)
* Previously we would only run services in new shell if we were not already in a shell or direnv. But this causes us to ignore environment variables that are set after the environment is created due to bin wrappers. Fix: always run services in new shell.
Root …

[services] Fix issue where env var is ignored

---

internal/impl/devbox.go
internal/impl/shell.go
internal/impl/shell_test.go

I noticed this wasn't being used anywhere.

impl: remove profileDir from shell

---

internal/devconfig/config.go
internal/devconfig/config_test.go

The default hujson formatting uses tabs, which causes a bunch of whitespace changes for existing configs. Most JSON formatters/LSP servers also tend to default to 2 spaces. Add a simple replace all to change all tabs to "  ", which should be safe since raw tab characters are not allowed in valid JSON values.

devconfig: use two spaces instead of tab

---

internal/impl/shell.go

Seeks to address two concerns that have arisen:
1. Zsh startup files are linked, not copied. We should copy. This was affecting a user who was mounting the filesystem which disallows linking in that scenario. 
Fixes #1536
2. ZDOTDIR was not respected for finding the ZSH startup files. We should support it as the zsh manual specifies that its the location of its startup files: https://zsh.sourceforge.io/Intro/intro_3.html
(Originally for #1582 , but it seems that issue is unrelated to ZDOTDIR)
EDIT: Fixes #1582, as per user who reported the issue 
Tested by setting `ZDOTDIR=~/zsh-dot-dir` and moving my `.zshenv` and `.zshrc` files there. Starting a `devbox shell` showed that these startup files were run.
Moved them back to my homedir, and unset `ZDOTDIR` and starting a `devbox shell` still …

[shell] respect ZDOTDIR for zsh startup files, and copy startup files instead of linking

---

go.mod
go.sum
internal/devpkg/package.go
internal/nix/nix.go
internal/nix/search.go
internal/nix/search_test.go

From observing times for adding and removing packages, I notice that a lot of time is spent in `syncPackagesToProfile` and most of that is from `nix.Search`, which is a fairly slow operation. However, from observing the results, it seems that these should be constant. 
For example, here are some search results keyed by the queries:
https://gist.github.com/savil/584c4d9bd6c468aaa8c289265287a23a
Correct me if wrong: all these seem to be constants that won't change, because the queries we run have the nixpkgs-commit-hash in them.
The general [`nix search` command](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-search.html) seems to be slower since the query it accepts is an `installable regex`, which can match a large number of concrete queries. Furthermore, it needs to accept …

[perf] cache nix.searchSystem

---

internal/devpkg/flakeref.go
internal/devpkg/flakeref_test.go

In anticipation of adding support for non-default package outputs, I wanted to clean up some of the flakeref parsing in `devpkg`. This will make it easier to handle Nix's `flakeref#attrpath^outputs` installable syntax. This PR is broken up into two commits: one that handles flakeref parsing and one that handles installable parsing.
The `ParseFlakeRef` function is able to parse the more common flakerefs that devbox currently supports ("path", "flake", "indirect", etc.). It doesn't support mercurial, gitlab, and sourcehuthut for now. The `ParseFlakeInstallable` function parses Nix flake installables, which are a superset of the flake reference syntax. It allows an attribute path and/or outputs to be specified using the `flake#attrpath^outputs` syntax. The tests were validated using the nix …

devpkg: better flake references and installable parsing

---

docs/app/docs/guides/plugins.md

Fix minor spelling mistake in plugins.md doc.

Fix minor spelling mistake in plugins.md doc.

---

.golangci.yml
internal/devpkg/flakeref.go
internal/devpkg/flakeref_test.go

Improve FlakeRef.String so that it reassembles the flakeref using the current field values instead of returning the original parsed string that it came from. This makes it easier to modify parsed flakerefs or to create new ones from scratch.
The strings are normalized so that when two flakerefs are equal, their strings will also be equal. The docs for FlakeRef.String go into more detail on what the normalized form looks like.
Being able to parse/modify/encode flake references is part of the work to support multiple package outputs. Having a single (well-tested type) for handling flakes should help manage the complexity as another syntax for outputs is added.

devpkg: use struct field values in FlakeRef.String

---

.golangci.yml
internal/devpkg/flakeref.go
internal/devpkg/flakeref_test.go

Split flakeref paths before unescaping to properly handle encoded slashes (%2F). Use `URL.String()` to ensure that unescaped characters get re-escaped for `FlakeRef.URL`.

devpkg: better handling of escapes in flakeref paths

---

internal/devpkg/flakeref.go
internal/devpkg/flakeref_test.go

Change `ParseInstallable.Outputs` from a `[]string` to a `string` and move the splitting logic to a `SplitOutputs` method. This makes installables directly comparable with `==` and usable as map keys, which is something we currently do a bunch using unparsed installable strings.

devpkg: make FlakeInstallable.Outputs a string

---

internal/boxcli/pull.go
internal/boxcli/push.go

Login should not be required for push/pull to github.
Fixes https://github.com/jetpack-io/devbox/issues/1580
```
devbox global push git@github.com:mikeland73/global.git
devbox global pull git@github.com:mikeland73/global.git
```

[easy][global] global push/pull should not require login for github

---

internal/impl/devbox.go

Prepend all glibc-patched packages to the PATH instead of just the last one.

impl: PATH fix for multiple glibc-patched packages

---

internal/vercheck/vercheck.go

This flag was removed after bin wrappers were removed in v0.8.0.

vercheck: remove `--update-devbox-symlink` flag

---

go.mod
go.sum
internal/boxcli/auth.go

Use newest version of auth which fetches access token.
```
devbox auth login
devbox auth whoami
```

[easy][auth] Update auth package

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json

tasks:
addresses #1576
- follow steps to generate custom vsix file and install it on vscode
- or after the extension is published, update the extension to 0.1.3

Added schema validation to devbox vscode extension

---

.schema/devbox.schema.json

Adds missing fields to the json schema
Restricts additional properties -- this ensures that developers can't put `init_hook` in the wrong location
Manually using the root `devbox.json`

add fields, restrict additional props

---

internal/impl/packages.go

This bug was introduced in https://github.com/jetpack-io/devbox/pull/1584 and has at least 2 effects:
* Perf regression (because we recompute environment all the time)
* Plugins that create flakes may break if they create additional files in the same directory. (Another PR will address this issue in more depth)
```bash
devbox add mysql80
devbox services up -b
devbox services stop
```

[ensure] Don't recompute environment if up to date

---

plugins/haskell.json
plugins/mariadb.json
plugins/mysql.json
plugins/php.json

**What this fixes:**
When plugins create flake in a directory shared with other files, `nix search` can break. (We use `nix search` to determine output path). For example in the mysql plugin the flake would live side-by-side with the `run` directory which has a sock file. `nix search` would recurse in that directory and try to search for nix expressions and break because the file had an unexpected format. 
**How it was surfaced:**
This issue was previously hidden because we don't call `nix search` if a package has already been installed. The bug fixed in https://github.com/jetpack-io/devbox/pull/1625 was causing us to needlessly call `nix search` on stuff that was already 
**Solution:**
The partial solution in this PR is to always create the flake in its own dir. This is a bit fragile, …

[plugins] flakes should be in own dir

---

internal/devpkg/flakeref.go
internal/devpkg/flakeref_test.go

This got to the point where the string literals were being repeated in a bunch of places. The enum values also make it easier for tooling to find where we're handling specific flake types throughout devbox.

devpkg: add const for flake types

---

.schema/devbox.schema.json

Updates the schema to better reflect the packages object -- packages can be either: 
* A list of Strings
* An object, where each key contains either a version string or an object
Used the following package list: 
```json
"packages": {
"go":                          "latest",
"runx:golangci/golangci-lint": "latest",
"runx:mvdan/gofumpt":          "latest",
"glibcLocales": {
"version":            "latest",
"excluded_platforms": ["aarch64-darwin"]
}
},
```

Update `packages` object

---

internal/boxcli/shellenv.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/impl/generate/tmpl/envrcContent.tmpl

Adding alias to `direnv` environment is causing problems in fish and doesn't work anyway (because direnv doesn't support aliases)
* For both zsh and fish
* Started shell
* activated direnv hook
* cd to devbox directory
* confirmed environment was actice
* installed package and tested it

[direnv] Fix direnv fish support

---

internal/devpkg/flakeref.go
internal/devpkg/flakeref_test.go

Fix a bug where `ParseFlakeRef` returns an empty FlakeRef and no error when it doesn't recognize the URL scheme (e.g., "blah:/..."). Update the tests to explicitly check for an error with invalid flakerefs.

devpkg: return error for invalid flakeref scheme

---

internal/devpkg/package.go
internal/devpkg/package_test.go
internal/devpkg/validation.go
internal/impl/packages.go
internal/nix/nixprofile/profile.go
internal/shellgen/generate_test.go

Depends on #1627 and #1629.
Update `devpkg.Package` to use `FlakeInstallable` instead of a URL so that it can correctly handle the flake outputs syntax. For example, `flake:nixpkgs#prometheus^out,cli`.
Untangling parts of `devpkg` has been tricky, so this commit focuses on changing only the pieces necessary to replace `Package.URL` with `Package.installable`. There's still a lot more cleanup that can be done.
Tested by adding/removing various flakes with and without outputs specified:
```
$ devbox add prometheus
$ devbox run -- promtool --version
promtool: command not found
Error: error running script "promtool" in Devbox: exit status 127
$ devbox add flake:nixpkgs#prometheus
$ devbox run -- promtool --version
promtool: command not found
Error: error running script "promtool" in Devbox: …
```

devpkg: allow multiple/non-default package outputs

---

internal/devconfig/env.go

I've encountered a few scenarios when testing envsec + Jetpack secrets where an issue with authentication of the envsec server prevented me from starting my shell. Since envsec errors also require an internet connection, an unstable connection can prevent me from starting my local dev environment
This PR changes a line in env.go so that Envsec errors will be logged, instead of causing Devbox to fail
Tested on a local new project, with the following scenarios:
- User not logged in
- Project missing a github repo
- Project has a repo but no remote

Envsec errors do not block devbox

---

docs/app/docs/devbox_examples/languages/python.md
examples/development/python/pip/devbox.json
examples/development/python/pip/devbox.lock
plugins/pip/venvShellHook.sh
plugins/python.json

The Nix Python packages come bundled with `pip`, so we can go ahead and create a virtual environment whenever a user installs a `python` package, even if they do not also install `pip`. 
This plugin reuses the `venvShellHook` and `VENV_DIR` environment variable from the `pip` plugin to create a virtual environment when the user starts their shell (assuming one has not been created). The user can activate the virtual environment by running `source $VENV_DIR/bin/activate`
A few notes
* This should not cause issues with virtual environments that have been created with `pythonPackages.pip`, meaning behavior should remain the same for existing python projects
* Devbox will use `VENV_DIR` variable and virtual environment for the package the appears last in the `packages` list.
* Going forward, …

[Plugin] Create a virtual environment with the `python` plugin

---

examples/development/python/pip/devbox.json
examples/development/python/pip/devbox.lock

Quick revert of the pip example. This is needed until we release a new devbox binary with the updated Python plugin
Tested against the python-pip example

[Plugins] Revert pip example changes

---

docs/app/docs/cli_reference/devbox_global.md

- `exec ...` should be `eval ...`
- `devbox add ripgrep` was missing `global`

Fix a couple devbox global command examples

---

examples/development/python/poetry/poetry-demo/devbox.lock
plugins/pip.json
plugins/pip/venvShellHook.sh
plugins/poetry.json
plugins/poetry/initHook.sh
plugins/python.json

The python, pip, and poetry plugins send output to stdout in the init hooks. This breaks any script that relies on a clean std out. In general no devbox builtin plugin should ever send output to std out in init hooks or commands that where the user does not expect output. The solution in this PR is to redirect to stderr.
A separate question I'm punting on is whether `--quiet` flag should also suppress init hook output. Since init hooks are usually user code, I think the answer is no. On the other hand, built in plugins should probably respect it. This could be a follow up.
Partially addresses https://github.com/jetpack-io/devbox/issues/1632
I created a test project with poetry and confirmed there was nothing being sent to stdout when running a script.

[plugins] Make python, pip, and poetry plugins output to stderr

---

internal/boxcli/add.go
internal/devconfig/packages.go
internal/devpkg/narinfo_cache.go
internal/devpkg/package.go
internal/impl/devopt/devboxopts.go
internal/impl/packages.go
internal/nix/nix.go

* Adds new `--patch-glibc` flag 
* Fixes glibc feature (I think) when package is in binary cache. We were previouwly always installing the cached version instead of the patched version.
* Flag was tested using `devbox add python --patch-glibc`
* I'm not 100% sure how to test the patch itself, but I did verify we are creating the patch flake

[glibc] Add patch-glibc patch and fix when package in binary cache

---

.github/workflows/cli-tests.yaml
internal/impl/devbox.go

Very basic fix. Doesn't handle all cases, but fixes run/shell.
Fixes https://github.com/jetpack-io/devbox/issues/1657
Turned off my wifi, modified `.local.lock` file to bust cache. Was able to run/shell.

[offline] Allow devbox to work offline if packages are already fetched

---

internal/vercheck/vercheck.go

Depends on https://github.com/jetpack-io/axiom/pull/3577
(that needs to be deployed before this change can be released)

[launcher] Bump launcher version

---

devbox.json

I sometimes need to build devbox for specific os-arch, which used to be possible
but was no longer. Bringing that facility back.
```
> rm -rf dist/
> devbox run build-all
> ls -al dist/
```

[scripts] split build-all command into os-arch specific commands

---

devbox.json
internal/boxcli/envsec.go
internal/boxcli/root.go
internal/devconfig/env.go
internal/devconfig/field.go
internal/integrations/envsec/envsec.go

[envsec] Add (hidden) envsec init command

---

devbox.json
devbox.lock
internal/impl/update.go
internal/lock/lockfile.go
internal/lock/resolve.go

This task is one of the follow ups from https://jetpack-io.slack.com/archives/C05KDNNN0Q6/p1702320680314359
If the package we get from nixhub is old, we should not try to update.
Other fixes:
* runx update was broken (or never implemented?)
`devbox update`
Simulated old package issue by changing lock file to a future date.

[update] Don't update if old last_modified, fix runx update

---

internal/boxcli/add.go
internal/boxcli/cloud.go
internal/boxcli/config.go
internal/boxcli/generate.go
internal/boxcli/info.go
internal/boxcli/install.go
internal/boxcli/pull.go
internal/boxcli/push.go
internal/boxcli/rm.go
internal/boxcli/run.go
internal/boxcli/services.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/boxcli/update.go
internal/devconfig/env.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/integrations/envsec/envsec.go

Adds new `--environment` flag that gets passed in to envsec. 
A few notes:
* This flag is present in any command that allows a custom config path. The idea is that in the future users can add per environment configuration to their `devbox.json`
* This PR validates in devbox.Open instead of CLI. This can probably be moved up to CLI code but this would have bloated this PR.
* Related, the way we pass options to devbox.Open is very brittle. It involves a lot of copy paste that is easy to mess up. We should look to refactor that, maybe in a follow up. 
```
devbox run --environment prod echo $SECRET
```

[envsec] Add environment flag

---

examples/development/php/php8.1/devbox.lock
internal/devpkg/package.go
internal/impl/packages.go
internal/plugin/manager.go

Run `nix profile upgrade` on any virtenv (plugin) flakes after any package is installed. This is a bit blunt, but works. (ideally we determine which plugin is being touched and we only upgrade that flake, but that's a bit tricky)
Fixes https://github.com/jetpack-io/devbox/issues/1680
```bash
devbox add php
devbox add php82Extensions.xdebug
devbox run php -m | grep xdebug
```

[plugins] Ensure plugin flakes get upgraded on every install

---

internal/plugin/info.go
internal/plugin/plugin.go
internal/services/config.go

We were relying on the package already being installed and in virtenv. This change ensures it works when not installed as well.
`devbox info php`

[plugins] fix info for packages with process-compose services

---

docs/app/docs/devbox_examples/languages/python.md
docs/app/docs/devbox_examples/stacks/django.md
examples/cloud_development/temporal/devbox.json
examples/data_science/pytorch/gradio/devbox.json
examples/data_science/tensorflow/devbox.json
examples/development/python/pip/README.md
examples/stacks/django/README.md
plugins/pip.json
plugins/python.json

Think its a bit nice to be posix compatible where we can.
The downside is that `source` is more recognizable, perhaps, compared to `dot`.
cicd tests

[python] use posix-compatible dot instead of bashism source

---

internal/boxcli/setup.go

Ensures that the nix used is >= 2.12 which is the minimum version we support.
Our CICD tests run this version, and I believe so does @mohsenari.
I considered renaming the function to `ensureSupportedNixInstalled` but
decided against it. The current name is good enough, given the function's scope
and location in the package.
ran `devbox shell` which results in this function being called.
Toggled the condition to trigger the error to verify it prints as we want.

[nix] ensure nix version is >= 2.12

---

internal/devbox/devbox.go
internal/devbox/util.go
internal/integrations/envsec/envsec.go

This is combined with https://github.com/jetpack-io/opensource/pull/251 to ensure devbox and envsec environments are always the same.
Otherwise, when using dev devbox, it will install a prod envsec and environments won't match which causes issues because dev environment uses a different authentication issuer so keys are not compatible.

[envsec] Ensure build environment is the same

---

internal/devbox/devbox.go
internal/devbox/devbox_test.go
internal/devbox/envvars.go
internal/devbox/refresh.go
internal/shellgen/scripts.go
internal/shellgen/tmpl/init-hook.tmpl

Fixes https://github.com/jetpack-io/devbox/issues/1651
Added a `devbox run echo foobar` into our init hook. Tested with
```
devbox run echo 123
SHELL=fish devbox run echo 123
```

[init-hooks] Prevent init hook recursion

---

internal/devbox/shell.go
internal/shellgen/scripts.go
internal/shellgen/tmpl/init-hook.tmpl

Fixes an issue with https://github.com/jetpack-io/devbox/pull/1709
Also, adds a `FISH_VERSION` check which seems more reliable? (See https://github.com/fish-shell/fish-shell/issues/374) 
I think longer term it may be better to generate different init hooks (e.g. `.hooks.fish`) instead.
```
SHELL=fish devbox shell
refresh
```

[fish] Fix fish init hook

---

internal/boxcli/secrets.go
internal/devbox/devbox.go
internal/devconfig/env.go

* Renamed config from `envsec` to `jetpack-cloud`
* Handle edge case where directory is initialized but devbox.json is not.
`devbox secrets init`

[secrets] Renamed config value and small fixes

---

internal/boxcli/auth.go
internal/boxcli/run.go
internal/boxcli/services.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/boxcli/update.go

In short, command help is capitalized, flag help is not.
CICD

[polish] Ensure all helptext is consistent

---

docs/app/devbox.json
docs/app/docs/faq.md
docs/app/docs/guides/using_flakes.md
docs/app/sidebars.js

Adds an FAQ, and details about non-default packages via Flake Refrences
Build + preview locally

add FAQ, non-default packages

---

.gitignore
internal/boxcli/add.go
internal/devbox/devopt/devboxopts.go
internal/devbox/packages.go
internal/devconfig/ast.go
internal/devconfig/config_test.go
internal/devconfig/packages.go
internal/devconfig/packages_test.go

Enables `devbox add <package-name> --outputs <output-name>` to add an `outputs` field to the config for that package.
The next PR will hook up reading this `outputs` field from the config, and changing how we generate the flake.nix to match this outputs field.
augmented unit tests
```
> devbox add prometheus --outputs out,cli
Info: Adding package "prometheus@latest" to devbox.json
Info: Added outputs out, cli to package prometheus@latest
> git diff devbox.json
diff --git a/devbox.json b/devbox.json
index 224072bc..f1a0c59c 100644
--- a/devbox.json
+++ b/devbox.json
@@ -3,6 +3,10 @@
"go":                          "latest",
"runx:golangci/golangci-lint": "latest",
"runx:mvdan/gofumpt":          "latest",
+    "prometheus": {
+      "version": "latest",
+      "outputs": ["out", "cli"],
+ …
```

[package outputs] add --outputs flag to devbox add, and save in config

---

internal/devpkg/narinfo_cache.go
internal/devpkg/package_test.go
internal/nix/storepath.go
internal/nix/storepath_test.go

This should be in the `nix` package
Seeking to reduce the code in #1692.
compiles, and tests should pass

[StorePathParts] move to nix package

---

go.mod
go.sum
internal/boxcli/secrets.go
internal/devbox/devbox.go
internal/devbox/secrets.go

Adds
```
devbox secrets download
devbox secrets upload
```
Also, updated envsec dependency that has a simpler API.
```
devbox secrets download foo.json
devbox secrets upload foo.json
```

[secrets] Add secrets download and upload

---

internal/devbox/packages.go
internal/lock/lockfile.go
internal/plugin/plugin.go

Refactor the implementation of `ensureStateIsUpToDate` as per the suggestion in this comment: https://github.com/jetpack-io/devbox/pull/1692#discussion_r1449453688
1. Split `lockfile.Save` into `lockfile.Save` and `lockfile.UpdateAndSaveStateHash`
2. For now, regardless of `recomputeState` (boolean variable), we always call `recomputeState` (the function). In the next PR, this will change.
NOTE:
In `pluginManager.create`, I only do  `lockfile.Save` and not `lockfile.UpdateAndSaveLocal` (as before), because:
When I do `devbox add php81Extensions.ds` then the `lockfile.Save` in `pluginManager.Create` here is resulting in the `local.lock` being up-to-date so that the next `devbox run` is thinking everything is up to date and early returning in `ensureStateIsUpToDate`.
```
devbox shell
devbox …
```

[Refactor ensureStateIsUpToDate] split into two modes for when to recompute state

---

.github/workflows/cli-tests.yaml
internal/devbox/nixprofile.go
internal/devbox/packages.go
internal/devbox/util.go
internal/nix/build.go
internal/nix/nixprofile/item.go
internal/nix/nixprofile/profile.go
internal/nix/profiles.go
testscripts/add/add_platforms_flakeref.test.txt
testscripts/add/global_add.test.txt
testscripts/languages/php.test.txt
testscripts/packages/unfree.test.txt

This PR is a re-write of #1692. See motivation and discussion there.
**Motivation**
This PR seeks to unify our nix print-dev-env and nix profile steps. Other benefits:
- It will enable us to remove some hacks (example, this one [introduced for glibc-patch](https://github.com/jetpack-io/devbox/blob/d66f6ea5388adb3b90008c64a1b9b9abdc4550cd/internal/devbox/devbox.go#L938-L944))
- Re-enable some testscripts that were disabled (example, this [one for php extension removal](https://github.com/jetpack-io/devbox/blob/main/testscripts/languages/php.test.txt#L4-L15))
Previously, these would be two separate processes: we'd manually do nix profile install.
Now, we get the `buildInputPaths` from `nix print-dev-env` and install those, so the nix profile is derived from the flake.
**Implementation …

Derive nix profile from flake: attempt 2

---

internal/devpkg/narinfo_cache.go
internal/devpkg/package.go
internal/shellgen/flake_input.go
internal/shellgen/generate.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl
testscripts/add/add_outputs.test.txt

This PR reads the `outputs` field from the Config for a package.
For packages with non-default outputs in the config, we specify:
1. They are not to be taken from the binary cache
2. They are exempt from the `flakeInput.buildInputs()` that are specified in the generated flake's devshell.buildInputs
Instead, we generate a [`symlinkJoin` derivation](https://nixos.org/manual/nixpkgs/stable/#trivial-builder-symlinkJoin) of the form:
```
(pkgs.symlinkJoin {
name = "prometheus-combined";
paths = [
nixpkgs-fd04be-pkgs.prometheus.cli
nixpkgs-fd04be-pkgs.prometheus.out
];
})
```
This `prometheus-combined` derivation is useful so that when we derive the nix-profile from the flake's buildInputs as in #1692, it is treated as a single package. Without this, we could inline each output as a distinct …

[package outputs] generate buildInputs for package-outputs in flake

---

examples/databases/mariadb/devbox.lock
examples/databases/mysql/devbox.lock
plugins/mariadb.json
plugins/mariadb/process-compose.yaml
plugins/mysql.json
plugins/mysql/process-compose.yaml

This PR fixes a permissions issue that can arise when running the MySQL plugin in CI. 
Previous versions of the mysql plugin were creating error logs in the virtenv directory by routing stderr to a file. While this kept the error logs local, mysql would still create a log file in `/var/logs`. This worked fine on user machines, but could hit permission errors in CI. 
This update now creates the error log using the --log-error flag. This should override any log creation in `/var`, which will avoid the permissions error. 
Tested locally, verified the service was still working and error logs were being captured

[mysql plugin] use --log-error instead of 2>

---

internal/devbox/devbox.go
internal/devbox/shell.go
internal/devbox/shell_test.go
internal/devbox/testdata/shellrc/basic/shellrc.golden
internal/devbox/testdata/shellrc/noshellrc/shellrc.golden
internal/shellgen/scripts.go
internal/shellgen/tmpl/init-hook-fish.tmpl

Fixes issue introduced in https://github.com/jetpack-io/devbox/pull/1709
`devbox run` uses `sh` instead of native shell. So init hooks must always be `sh` compatible for `run`. On the other hand, `devbox shell` uses native shell so init hooks must be `fish` if the native shell is fish.
This is ugly, but it's how it has always worked. 
https://github.com/jetpack-io/devbox/pull/1709 introduced recursion protection that would be `fish` or `sh` depending on native shell. This worked fine for `devbox shell` but would break `devbox run`. 
This change fixes that by creating 2 hooks files, one fish and one sh and sourcing the correct one in shellrc, while still always using the `sh` for run.
cc: @Lagoja 
```
devbox run echo 5
devbox shell
SHELL=fish devbox run echo 5
SHELL=fish devbox shell
```

[fish] Fix init hooks for fish

---

internal/devbox/shellrc.tmpl
internal/devbox/shellrc_fish.tmpl
internal/devbox/testdata/shellrc/basic/shellrc.golden
internal/devbox/testdata/shellrc/noshellrc/shellrc.golden

Devbox prefixes the user's prompt (PS1) with `(devbox)` when inside the `devbox shell`. Unfortunately, this doesn't look great with prompts which have been customized (with starship for example). 
Disable prompt modification by setting either `DEVBOX_NO_PROMPT` or `devbox_no_prompt` (fish) in your shell. Now the user can detect devbox and display it on their PS1 using the method if their choosing.
Fixes #845.
I ran the command in these shells with `export DEVBOX_NO_PROMPT=true` and without the variable (`unset DEVBOX_NO_PROMPT`) and observed the results. 
```
if [ -z "$DEVBOX_NO_PROMPT" ]; then
export PS1="(devbox) $PS1"
fi
```
Disclaimer, I'm not a fish user. I installed fish and read the documentation.
I added `set devbox_no_prompt true` to my `.config/fish/config.fish`, then removed it …

Option to disable modification of the user's prompt.

---

devbox.md
internal/devbox/docgen/readme.tmpl

Improve automatically generated readme. Highlights:
* Adds "getting started" section.
* documents how to install devbox, start shell, run script
* Adds more context around scripts, init hook.
* Adds link to devbox repo.
* Adds more spacing between script details
What it looks like: https://github.com/jetpack-io/devbox/blob/56e7427a8f3da266d2f3d2b4a5028a7c7a017fc3/devbox.md
`devbox gen readme devbox.md`

[gen-readme] Improve gen readme

---

.github/workflows/cli-tests.yaml
internal/devbox/nixprofile.go
internal/devbox/packages.go
internal/devbox/util.go
internal/devpkg/narinfo_cache.go
internal/devpkg/package.go
internal/lock/lockfile.go
internal/nix/build.go
internal/nix/nixprofile/item.go
internal/nix/nixprofile/profile.go
internal/nix/profiles.go
internal/shellgen/flake_input.go
internal/shellgen/generate.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl
testscripts/add/add_outputs.test.txt
testscripts/add/add_platforms_flakeref.test.txt
testscripts/add/global_add.test.txt
testscripts/languages/php.test.txt
testscripts/packages/unfree.test.txt

This reverts #1742
cicd should pass

Bring back: derive nix profile changes  (#1742)

---

docs/app/docs/ide_configuration/direnv.md

[docs] Updated wording on direnv integration

---

internal/devbox/packages.go

[easy] remove extraneous debugging Printf from devbox.installNixPackagesToStore

---

internal/shellgen/tmpl/init-hook-fish.tmpl

Problem:
```
❯ SHELL=$(which fish) devbox shell
~/code/jetpack/devbox/.devbox/gen/scripts/.hooks.fish.sh (line 2): 'return' outside of function definition
return
^
from sourcing file ~/code/jetpack/devbox/.devbox/gen/scripts/.hooks.fish.sh
called on line 164 of file /var/folders/zv/r3sx92_94gq86_rq3yn1ky2h0000gn/T/devbox340516573/config.fish
from sourcing file /var/folders/zv/r3sx92_94gq86_rq3yn1ky2h0000gn/T/devbox340516573/config.fish
source: Error while reading file “/Users/savil/code/jetpack/devbox/.devbox/gen/scripts/.hooks.fish.sh”
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
(devbox) savil@Savil-Srivastavas-MacBook-Pro ~/c/j/devbox (main)> exit
```
Fix: use `exit` instead of `return`
Made the following …

[fish] use exit instead of return in init-hook recursion guard

---

internal/boxcli/add.go
internal/devbox/devopt/devboxopts.go
internal/devbox/packages.go
internal/devconfig/ast.go
internal/devconfig/config_test.go
internal/devconfig/packages.go
internal/devconfig/packages_test.go
internal/devpkg/package.go
internal/nix/build.go
internal/nix/nix.go
internal/nix/nix_test.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl
testscripts/testrunner/examplesrunner.go

Changes
1. Modify `devbox add`'s `--allow-insecure` flag to take a `[]string` instead of `bool`.
2. Save `allow_insecure` field in the package in the `devbox.json` config
3. Set `NIXPKGS_ALLOW_INSECURE=1` in the `nix build` during `devbox add`
4. Set the packages specified in `allow_insecure` in the generated flake's `permittedInsecurePackages`.
TODO:
**Downside:**
If a user erroneously specifies the wrong package name or names in `--allow-insecure=<packages>`, then a `devbox add  <pkg> --allow-insecure=<packages>` outside the `devbox shell` environment will quietly work. However, the user will experience an error when running `devbox shell` (or similar) next time, and need to fix the erroneous `--allow-insecure` value.
- Fix: we could fix this by doing "recomputeState" when …

[devbox add] --allow-insecure should handle multiple, user-specified packages

---

internal/devbox/devbox.go
internal/devbox/packages.go
testscripts/testrunner/examplesrunner.go

This PR migrates the `allow_insecure` setting in `devbox.lock` of existing projects to `devbox.json`.
Set up project with an insecure package `devbox add python@2.7.18 --allow-insecure` using the prod Devbox binary:
```
❯ git diff
diff --git a/devbox.json b/devbox.json
index cf698ebc..45aac7cc 100644
--- a/devbox.json
+++ b/devbox.json
@@ -5,6 +5,7 @@
"go":                          "latest",
"runx:golangci/golangci-lint": "latest",
"runx:mvdan/gofumpt":          "latest",
+    "python":                      "2.7.18",
},
"env": {
"GOENV": "off",
diff --git a/devbox.lock b/devbox.lock
index 7d4cb7e2..b54fd69b 100644
--- a/devbox.lock
+++ b/devbox.lock
@@ -21,6 +21,14 @@
}
}
},
+    "python@2.7.18": {
+      "allow_insecure": true,
+      "last_modified": "2024-01-14T03:55:27Z",
+ …
```

[add] migrate allow_insecure from lockfile to config

---

internal/devbox/devbox.go

I was getting shell script parsing errors when doing
`devbox global shellenv --init-hook | source`
in fish
Turns out, we were sourcing the init-hook file for non-fish. This PR fixes that
Ran the above command succesfully in a fish shell

[fish] use fish hooks file for devbox.EnvExports (used in shellenv)

---

docs/app/docs/devbox_examples/databases/postgres.md
examples/databases/postgres/devbox.json
examples/databases/postgres/devbox.lock

Current PostgreSQL example doesn't work on MacOS because it attempts to install glibcLocales. This updates the example and documentation to only install glibcLocales on Linux
CI/CD, run example locally

Update PostgreSQL example for cross-platform

---

internal/boxcli/auth.go

Exposing the tokens for easier debugging, when needed
`devbox auth whoami --show-tokens`

[auth] add --show-tokens to devbox auth whoami

---

internal/lock/statehash.go
internal/shellgen/scripts.go
internal/shellgen/tmpl/init-hook-fish.tmpl
internal/shellgen/tmpl/init-hook.tmpl

I accidentally merged https://github.com/jetpack-io/devbox/pull/1765 without committing the fixes requested in the PR. This PR contains them.

[state-hash] Change requests from previous PR

---

.github/workflows/cli-tests.yaml
internal/nix/nixprofile/item.go
internal/nix/nixprofile/profile.go
internal/nix/nixprofile/profile_test.go
internal/nix/nixprofile/upgrade.go
internal/nix/profiles.go
internal/nix/search.go
internal/nix/upgrade.go

The latest nix version (2.20) changed how the nix profile output is represented:
From the [release notes](https://nixos.org/manual/nix/stable/release-notes/rl-2.20):
> nix profile now allows referring to elements by human-readable names https://github.com/NixOS/nix/pull/8678
> [nix profile](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile) now uses names to refer to installed packages when running [list](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-list), [remove](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-remove) or [upgrade](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-upgrade) as opposed to indices. Profile element names are generated when a package is installed and remain the same until the …

[nix profile] Changes to support format changes from nix 2.20

---

internal/devbox/devbox.go
internal/lock/statehash.go

This is a bit hacky, but was smallest, safest I could come up with. This fixes the following case:
* User uses fish as shell
* User adds `devbox run` in their init hook
*  User gets warning that environment is stale. This happens because shell doesn't match, but we don't really care that shell doesn't match for `run`. We only care for `shell` because we use different shellrc for fish vs POSIX.
Added `devbox run echo foo` to init hook. Then ran
```
SHELL=fish devbox run echo bar
```

[state] Ignore shell mismatch for run

---

internal/devbox/update.go

When I modified the `examples/flakes/php` to omit `ds` extension and did `devbox update`, then the output alarmed me at first. 
The Error made me think something drastic went wrong. But in this case, since its an "attempt", I think we should
make it a Warning or even an Info.
```
❯ devbox update
Info: Attempting to upgrade path:my-php-flake#php using `nix profile upgrade`
Error: Failed to upgrade path:my-php-flake#php using `nix profile upgrade`: php: package not found
Info: Attempting to upgrade path:my-php-flake#hello using `nix profile upgrade`
Error: Failed to upgrade path:my-php-flake#hello using `nix profile upgrade`: hello: package not found
Info: Already up-to-date ripgrep@latest 14.1.0
[1/2] php
[1/2] php: Success
[2/2] hello
[2/2] hello: Success
✓ Computed the Devbox …
```

[update] change Error: to Warning: for failed attempt to upgrade flake

---

internal/nix/nix.go

On MacOS, in nix 2.20, I am seeing the following error with the `global_add` testscript. This also repros in CICD:
```
Error: Command: /nix/var/nix/profiles/default/bin/nix print-dev-env /var/folders/zv/r3sx92_94gq86_rq3yn1ky2h0000gn/T/TestScripts3021118989/001/.local/share/devbox/global/default/.devbox/gen/flake --extra-experimental-features ca-derivations --option experimental-features nix-command flakes fetch-closure --json: exit status 1
2024/02/02 16:44:15 Command stderr: error (ignored): error: end of string reached
error:
… while fetching the input 'path:/var/folders/zv/r3sx92_94gq86_rq3yn1ky2h0000gn/T/TestScripts3021118989/001/.local/share/devbox/global/default/.devbox/gen/flake'
error: path '«unknown»/var' is a symlink
```
I'm not sure why this is now failing. Possibly (but low …

[eval symlinks] eval symlinks in print-dev-env

---

.github/workflows/cli-tests.yaml

Github action ubuntu image has been reduced. This fixes the error with Maximize build disk space step.
github actions

[github actions] changed root-reserve size

---

internal/nix/nix.go

Don't pass a slice of already-redacted arguments to `redact.Errorf` so that they're preserved in the regular error message.
Tested by forcing an error and seeing the full message:
```
$ go run ./cmd/devbox shell
✓ Computed the Devbox environment.
Error: nix print-dev-env --json "path:/Users/gcurtis/src/devbox/.devbox/gen/flake": exit status 1
Error: There was an internal error. Run with DEVBOX_DEBUG=1 for a detailed error message, and consider reporting it at https://github.com/jetpack-io/devbox/issues
```
Gets redacted in Sentry as:
```
nix print-dev-env --json "path:<redacted string>": <redacted *exec.ExitError>
```

internal/nix: fix unredacted error message

---

internal/boxcli/featureflag/resolvev2.go
internal/lock/resolve.go
internal/searcher/client.go
internal/searcher/model.go
nix/flake/flakeref.go

Add a `DEVBOX_FEATURE_RESOLVE_V2` feature flag that enables the new `/v2/resolve` endpoint when resolving packages. The new endpoint unlocks a couple of improvements:
- We no longer need to call `nix store path-from-hash-part` (which incurs a network request) for every `fetchClosure` package. The full store path is returned directly by the API.
- The resolved package response includes store paths for all known outputs, allowing us to support `fetchClosure` for non-default outputs as well.
- The new endpoint returns a flake installable rather than a nixpkgs commit hash and attribute path. This gives more flexibility, allowing the API to potentially return packages from sources other than nixpkgs.

internal/searcher,lock: use /v2/resolve endpoint

---

examples/development/zig/zig-hello-world/build.zig
examples/development/zig/zig-hello-world/devbox.json
examples/development/zig/zig-hello-world/devbox.lock

The zig example is out-of-date and isn't working on macOS. Updating to the latest version of Zig seems to fix it. I don't think we run these tests on macOS, so this bug was never caught.
The bug was caused by https://github.com/ziglang/zig/issues/12069 which has been fixed in 0.11.0.

examples/development/zig: update to 0.11.0 and fix for macOS

---

examples/development/elixir/elixir_hello/devbox.json
examples/development/elixir/elixir_hello/devbox.lock

Version 1.14.5 of erlang seems to segfault on macOS Sonoma. Upgrading to the latest fixes it.

examples/development/elixir: update elixir to fix for macOS Sonoma

---

.github/workflows/cli-tests.yaml

We were accidentally excluding the example tests on macOS. Also add some descriptions to the workflow inputs to make the schema validate with the YAML language server.

ci: run example tests on macOS for releases

---

plugins/redis/redis.conf

The redis plugin configures redis to log to a file in `.devbox/virtenv/redis/redis.log`. This causes logs to not show up in process-compose (with `devbox services up redis`), which relies on capturing logs from stdout/stderr.
Logging to a file probably predates the process-compose integration back when there was no other way to view the logs. Today it makes more sense to default to having logs go to stdout and show up in process-compose.
The trade-off is that logs will go to /dev/null if redis is launched as a regular daemon (and therefore doesn't have a stdout). In this case, the user can always uncomment the config line to send logs to a file again.
Fixes #1727.

plugins/redis: log to stdout by default

---

internal/devbox/devbox.go

As discussed, these cause way more problems than they solve. Now that we support multiple and non-default package outputs, other programs should be able to find libraries as long as they use the wrapped clang/gcc from the stdenv.
Fixes #1752.
Fixes #1798.

internal/devbox: stop setting LD_LIBRARY_PATH and LIBRARY_PATH

---

docs/app/docs/faq.md

Documentation for `DEVBOX_NO_PROMPT` from PR #1743.

Add documentation for DEVBOX_NO_PROMPT to the FAQ.

---

examples/insecure/devbox.json
examples/insecure/devbox.lock

Whenever the example tests run, Devbox updates the devbox.json to use the newer `allow_insecure` syntax. Commit those changes so they stop showing up as diffs.

examples/insecure: modernize devbox.json

---

.github/workflows/cli-tests.yaml

This is to temporarily unblock CI for a release. The example tests were recently re-enabled for macOS and are taking a long time to run.

ci: increase mac test timeout to 1 hour

---

devbox.md
internal/boxcli/generate.go
internal/devbox/docgen/docgen.go
internal/devbox/docgen/readme.tmpl

This adds:
Flag that saves default template
```
devbox generate readme [path] --save-template
```
Flag that uses custom template
```
devbox generate readme [path] --template <custom-template>
```
It also:
* defaults readme [path] to `README.md`
* defaults template [path] to `readme.tmpl`
* If there is `readme.tmpl` in root, then `devbox generate readme` will use it automatically.
* Fixed missing env vars from default template
```
devbox generate readme --save-template # generate template
vi readme.tmpl # modified template
devbox generate readme devbox.md # tested creating new readme
```

[gen-readme] Allow custom templates

---

.github/workflows/docker-image-release.yml
internal/devbox/generate/tmpl/DevboxImageDockerfileRootUser

This fix is due to customer message in discord mentioning the launcher having old version.
Nix installation in `docker-image-build-publish` workflow was failing for root-user mode.
This PR fixes it.
The fix was based on recommendation from https://github.com/LnL7/nix-docker/issues/41#issuecomment-1890873956
https://github.com/jetpack-io/devbox/actions/runs/7893709911

[docker] fix for devbox docker image root-user build

---

nix/flake/flakeref.go
nix/flake/flakeref_test.go

I ran into an issue causing the generated `.devbox/gen/flake` to contain an invalid flake reference when adding some installables to `devbox.json`, specifically those which pointed to a remote resource. Local files were fine.
After a quick hike around the repo, the fix seemed trivial enough to open up a PR rather than open up an issue. Interestingly, I didn't seem to find any issues around this even though this bug would've been around for some months.
As it turns out, `Installable`s returned from `ParseInstallable` included the attribute path when provided a value with any scheme aside from `<empty string>`, `flake`, `path`, or `github`. This was because the `parseURLRef` method was not separating the fragment out of the refURL. More generically, the affected branches were any of those …

nix/flake: installables exclude attribute path from URL

---

internal/shellgen/tmpl/glibc-patch.bash
internal/shellgen/tmpl/glibc-patch.nix.tmpl

This addresses an issue where scripts (and other text files) could still refer to the unpatched version of a program after enabling `patch_glibc`. This is one of the reasons why Ruby would still segfault in issue #1772. For example, if you look at `bundler` (installed by default with `ruby`) it's a wrapper script with the shebang:
#!/nix/store/vs52hm8jbwgx19plicg02dzz2vmvbyy5-ruby-2.7.8/bin/ruby
This means that commands like `bundler exec rails` would still run using the unpatched version of ruby. I suspect this was also happening with Python or other packages that rely on wrapper scripts.
The fix updates glibc-patch.bash to grep for the old store path and replace it using sed. It relies on ripgrep's ability to ignore binary files so that we only modify text files.

shellgen: update store paths when patching glibc

---

internal/devbox/packages.go
internal/nix/build.go

I mostly copied over what we have from `nix.ProfileInstall`. I thinks this is OK? It will pipe all output and errors to stderr so user can see progress and if anything breaks it will show up there as well.
Tried installing something slow:

[UX] Show add (nix build) stdout

---

internal/devbox/nixprofile.go
internal/devbox/packages.go
internal/nix/store.go
internal/nix/store_test.go
typos.toml

We have two separate steps for "installing packages".
1. We use nix build to add to the nix store.
2. We later ensure the nix profile is updated to have items pointing to the nix store packages.
For the first step, we should only run `nix build` if the package's outputs are not in the nix store. For this, we check `nix store ls <path>`. We get `<path>` from `nix path-info <installable>`. 
Previously, we were checking if the packages were in the `nix profile`, rather than directly querying the nix store. This would lead to re-running `nix build` for when we've done `devbox add` outside a devbox-environment, and then started a devbox-environment (example: doing `devbox add` followed by `devbox shell`).
For the second step, we can remove the `[1/3] <package>` being removed print outs. This …

[UX] Better dedup packages we nix build, and improve UX printouts

---

internal/services/manager.go
internal/services/ports.go

This helps fix the lapp and lepp stack test issues. It also provides a more reliable way to provide an unused port that does not have race condition issues or the limit of 10 ports.
devbox services start

[process-compose] Improve port selection

---

.github/workflows/cli-release.yml
.github/workflows/cli-tests.yaml

* Don't run mac tests on release
* Don't run mac tests on main
* Only run mac tests on request or nightly
CICD

[cicd] Run mac tests on cron only

---

internal/devbox/update_test.go
internal/devpkg/narinfo_cache.go
internal/devpkg/outputs.go
internal/devpkg/package.go
internal/lock/package.go
internal/shellgen/flake_input.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl

Goal:
This PR ensures we add store-paths for package outputs in the generated flake. This means users can skip the nixpkgs download saving 30-60 seconds, for packages with non-default outputs.
Along the way, it also improves how we handle multiple default outputs of packages. Well, the follow up PR #1842 achieves that.
Implementation:
- Needed to add an `outputs` struct in `devpkg`. It was needed to abstract the handling of user-selected outputs versus default outputs.
- The logic in `devpkg/narinfo_cache.go` to determine if the store-path is cached needed updating to be output-specific. 
- Needed to add output-specific versions of `package.Installable()` and `package.InputAddressedPath`
For ease of reviewing, I suggest toggling "Hide Whitespace":
`devbox add prometheus --outputs cli,out` …

[Outputs] Update generated flake to handle store paths for each output

---

internal/devbox/packages.go
internal/devbox/util.go
internal/devpkg/package.go
internal/nix/nixprofile/item.go
internal/shellgen/flake_plan.go

This is a follow up to #1837.
It enables packages with multiple default outputs to work properly. 
`devbox add curl && devbox install`. Then inspect `.devbox/gen/flake/flake.nix` to see both `-bin` and `-man` outputs are included:
```
1 {
2    description = "A devbox shell";
3
4    inputs = {
5      nixpkgs.url = "github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c";
6    };
7
8    outputs = {
9      self,
10      nixpkgs,
11    }:
12       let
13         pkgs = nixpkgs.legacyPackages.x86_64-darwin;
14       in
15       {
16         devShells.x86_64-darwin.default = pkgs.mkShell {
17           buildInputs = [
18             (builtins.fetchClosure {
19               fromStore = "https://cache.nixos.org";
20               fromPath = …
```

[Outputs] make pkg.Installable and pkg.InputAddressedPaths return array

---

nix/flake/flakeref.go
nix/flake/flakeref_test.go

Parse github flake references with refs that have slashes by limiting the number of splits to 3. For example,
"github:jetpack-io/devbox/gcurtis/flakeref" should parse as having the ref "gcurtis/flakeref".
Also handle the `?dir=` query parameter in github flake refs.

nix/flake: handle github refs with / and subdirs

---

internal/devpkg/outputs.go
internal/devpkg/package.go

Fixes https://github.com/jetpack-io/devbox/issues/1852
Ensure we initialize outputs using flake if package is a flake.
Made outputs non-pointer so we don't have to worry about initialization. 
Installed `github:nixos/nixpkgs#curl^out,dev` and verified that flake and profile contain both outputs.

[nix-outputs] Fix flake installable with custom outouts

---

internal/devbox/packages.go
internal/nix/build.go
internal/nix/nix.go
internal/nix/store.go

Amidst the recent changes to improving installing packages, we lost the nicer error messages for two scenarios:
1. Packages that are incompatible for the current system, but installable on other systems (`glibcLocales` is incompatible on darwin, but installable on linux)
2. Insecure packages
Also, improved both kinds of error messages:
1.  added support for incompatible-packages for a different kind of error message I saw with `sublime4` package.
2. Added the package name (when available) to the suggested command in `devbox add <pkg> --allow-insecure=<package>` so users can copy paste it directly.
Incompatible packages:
```
devbox add glibcLocales
```
Added support for a new kind of error message:
```
devbox add sublime4
```
Insecure packages:
```
devbox add python@2.7
```

[error message UX] Bring back nicer error messages for insecure and platform-incompatible packages

---

internal/devpkg/outputs.go
internal/devpkg/package.go

Ensure flake packages always parse outputs. (re-do of https://github.com/jetpack-io/devbox/pull/1864)
This approach is more general. It also supports (with some small changes) the use of devbox output flags with flakes (e.g. `devbox add github:nixos/nixpkgs#curl --outputs out,dev`)

[flakes] Ensure flake outputs are always used

---

internal/devbox/pure_shell.go

Symlink in pure shell seemed to be broken in some systems. This fixes the issue.
Addressed #1849 
devbox init
devbox shell --pure
devbox

Fixes a bug where devbox symlink isn't recognized in some systems

---

plugins/builtins.go
plugins/nodejs.json

Builtin version of the plugin built by @jasononeil to fix #1577. This plugin configures Corepack to work with Devbox, so developers can install pnpm + nodejs via corepack.
This will require updates to documentation and examples for Nodejs as well. 
* Create an empty Devbox project, and add `nodejs@latest`. 
* You should see the readme from the plugin, describing how to use Corepack
* Create a `package.json`, and add ` "packageManager": "pnpm@8.15.3"` or "packageManager": "yarn@1.22.21"`
* Run `pnpm -v` or `yarn -v` and confirm the version matches what's in your package.json

Add builtin plugin for nodejs + Corepack support

---

internal/lock/lockfile.go
internal/lock/package.go
internal/lock/resolve.go

This PR enables a `devbox.lock` updated by a user with the latest Devbox that has written Outputs to continue working for their teammate using a legacy Devbox.
Note two differences:
1. The legacyDevbox teammate will not benefit from output store-paths
2. If the legacyDevbox teammate modifies the lockfile in any way, then the Outputs will be lost. Presumably, this is not a huge problem since I anticipate most users rely on source control to track their `devbox.lock` in their devbox projects (except for maybe the Devbox global, but then those are less likely to be shared).
1. Added `devbox add curl` and `devbox add prometheus --outputs cli,out` using compiled devbox. This updated `devbox.lock` file.
2. `rm -rf .devbox`
3. `/usr/local/bin/devbox shell` using released Devbox. Observe that (1) …

[outputs lockfile] make backwards compatible

---

internal/devconfig/configfile/packages.go
internal/devconfig/configfile/packages_test.go

It was only used in tests. Replace it with Go struct literals.

internal/devconfig/configfile: remove NewPackage func

---

internal/devbox/generate/tmpl/devcontainerDockerfile.tmpl

When set to non `RootUser` for generating Dockerfile. We need to make sure `/code` owned by the devbox user for allowing the script to create new files / dirs in `/code` dir.
Locally, Manually

set the ownership of /code to devbox user

---

internal/devbox/devbox.go
internal/devbox/pure_shell.go

Fix #1783: Support non-root install in pure mode
Ran `devbox shell` and `devbox shell --pure` and they both work now with my non-root install of nix on MacOS.

Fix #1783: Support non-root install in pure mode

---

internal/devbox/packages.go

Did `devbox shell` after a minor change and saw it print with `Info:`

[easy][UX] use ux.Finfo for printing ensuring packages are installed

---

devbox.lock

```
❯ devbox update
Info: Updating go@latest 1.22.0 -> 1.22.1
Info: Updating runx:golangci/golangci-lint@latest v1.56.1 -> v1.56.2
Info: Already up-to-date runx:mvdan/gofumpt@latest v0.6.0
...
```
cicd should pass

[Devbox] update dependencies

---

internal/boxcli/cache.go
internal/boxcli/config.go
internal/boxcli/pull.go
internal/boxcli/root.go
internal/devbox/cache.go
internal/nix/cache.go

Note: this may not be the final UX for this command. I'm just getting it in hidden so we can build the cache feature end-to-end and will refine details later.
Adds `devbox cache copy <url>` command. It copies the current devbox nix profile to the url. `<url>` can be anything supported by https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-copy
There are two future plans for this command:
* `url` will be optional when logged in. It will be determined by API in those cases. We may want to move url to be a flag in that case (possibly the `--to` flag to mimic `nix copy`). 
* This command will support specifying the package you wish to copy. Packages can be nix installable, but also devbox packages (i.e. package@version). We could even support runx in the future.
I used `copy` to …

[nix-cache] Add cache copy command

---

internal/boxcli/pull.go
internal/boxcli/push.go

This stopped working a while back. The previous ID provider ID and Sub where the same. This is no longer the case.
DEVBOX_PROD=1 devbox global push

[global pull] Fix logged in global push/pull

---

.golangci.yml
internal/devbox/bincache/bincache.go
internal/devbox/packages.go
internal/nix/build.go

Sets up boilerplate to use nix cache and allows use via environment variable.
TODOs: (in follow ups)
`DEVBOX_NIX_BINCACHE_URI="s3://mike-test-nix-cache?region=us-west-2" devbox add hello`

[nix-cache] Add ability to use nix cache with env var

---

.schema/devbox-plugin.schema.json

Update JSON schema for Devbox Plugins

Update JSON schema for plugin v2

---

internal/devbox/devbox.go
internal/devbox/util.go
internal/nix/profiles.go

Fixes https://github.com/jetpack-io/devbox/issues/1901
Alternative: https://github.com/jetpack-io/devbox/pull/1902
nix 2.20 removed index support. Use store paths instead.

[process-compose] Remove old process compose using store path

---

internal/devbox/packages.go
internal/plugin/plugin.go

Fixes #1909
Makes two changes:
1. The users control `devbox.d` directory files once the plugin has generated it for them. Devbox should never be overwriting them. Added code to check for this.
2. For the code that checks if filepath contains `.devbox` or `devbox.d`, I now try to make that stricter by checking if filepath contains `/.devbox/` or `/devbox.d/`. As pointed out in the issue, the jetpack-mongodb plugin is generating user-configs at `devbox.d/jetpack-io.devbox-plugins.mongodb` which also contains `.devbox` string. This will pass checks for `strings.Contains(filepath, ".devbox")` even though that is not the intention of that particular check.
cc @mikeland73 
Repro'd the scenario of the issue.
Added the files via `git init && git commit -a`
Ran `rm -rf .devbox` and `devbox …

[Plugins] Do not overwrite existing user-config files of plugins

---

internal/devbox/shellrc.tmpl
internal/devbox/shellrc_fish.tmpl
internal/devbox/testdata/shellrc/basic/shellrc.golden
internal/devbox/testdata/shellrc/noshellrc/shellrc.golden
internal/nix/nix.go
internal/shellgen/tmpl/init-hook-wrapper.tmpl
internal/shellgen/tmpl/script-wrapper.tmpl

In aid of #1914
Added some basic support for spaces. I think this requires more extensive testing around:
1. plugins
2. flake packages
I should try to have the examples tests run in cicd with a space in their path.
```
mkdir -p `/Users/<omitted>/code/jetpack/devbox-projects/path with space`
devbox init
devbox shell
devbox add hello
devbox add cowsay
```
could run:
```
cowsay hello
```
set `export FISH=$(which fish)` and repeat the above steps

Support Project Directory having spaces

---

internal/plugin/plugin.go

remove extraneous print

---

examples/plugins/local/my-plugin/plugin.json
internal/plugin/github.go
internal/plugin/local.go
internal/plugin/plugin.go
plugins/python.json

Fixes #1911
This PR cleans the json-file-content of comments before processing it as "json content" i.e. we discard the comments prior to invoking existing logic for ingesting the `plugin.json` file.
This PR relies on Devbox not programmatically modifying the `plugin.json`. For now, users hand edit the `plugin.json` files. This is different from `devbox.json` which we do programmatically modify due to `devbox add`, `devbox rm` and similar commands, and so need to keep track of the json-with-comments' AST.
To test, I added comments to the following:
1. local plugin example
2. a builtin plugin (python)
I did NOT test remote Github plugin. But I tried to modify its code path. Did i get it right?

[plugins] support reading (and discarding) comments plugin.json files

---

internal/devbox/devbox.go
internal/nix/run.go

Related to #1914
Ran into this scenario during further testing
move the plugins examples:
`mv devbox/examples "devbox/examples with plugins"`
`cd examples/plugins with spaces/v2-github`
`devbox run run_test` -> this would previously fail

[path with spaces] run scripts for projects with paths in spaces

---

internal/plugin/plugin.go

@mikeland73 pointed out that these lines are extraneous, and testing confirmed it.
The real fix was the "/"+devboxHiddenDir+"/".
Also changed to use `filepath.Separator`
same test plan as #1917

[plugins] remove extraneous code change from #1917

---

internal/devbox/devbox.go
internal/devbox/shellrc.tmpl
internal/devbox/shellrc_fish.tmpl
internal/devbox/testdata/shellrc/basic/shellrc.golden
internal/devbox/testdata/shellrc/noshellrc/shellrc.golden
internal/nix/nix.go
internal/nix/run.go
internal/shellgen/tmpl/init-hook-wrapper.tmpl
internal/shellgen/tmpl/script-wrapper.tmpl

Will rework these and do better testing.
Revert "[path with spaces] run scripts for projects with paths in spaces (#1924)"
This reverts commit 8171595a5ec8d2000f349e82c77a97534af6567e.
Revert "Support Project Directory having spaces (#1920)"
This reverts commit 41294c291098634b040e12012d84446f90385796.

Revert "[path with spaces] run scripts for projects with paths in spaces (#1924)"

---

docs/app/docs/faq.md

Fixes #1938
This is more nix beginner friendly
will run the command locally (but takes time, so over lunch break)
`devbox run -- nix store gc --extra-experimental-features nix-command`

[docs] FAQ: add --experimental to nix store gc

---

internal/devbox/devbox.go
internal/devbox/docgen/docgen.go
internal/devbox/packages.go
internal/devbox/update.go
testscripts/rm/add-rm.test.txt

Fixes issue where user could not remove package that is replaced by a flake in plugin (uses `__remove_trigger_package`)
Fixes https://github.com/jetpack-io/devbox/issues/1936
We need two different functions for packages:
* `AllPackages` which is used for instalation and lock file. Includes packages added/removed by plugins.
* `TopLevelPackages` is only what is in root devbox.json
* Tested manually
* Added php to rm unit test

[plugins] Fix rm for packages with __remove_trigger_package

---

plugins/pip/venvShellHook.sh

This was requested on discord.
The `source` is non-posix. Using the period (`.`) is posix.
did not test

[plugins] change pip venv shell hook recommendation to be posix-compatible

---

internal/boxcli/cache.go
internal/devbox/cache.go

Renames `devbox cache copy` to `devbox cache upload`. Also changes the interface to use `--to` flag for cache URI. This allows easier use if cache is provided by jetpack API.
e.g.
```
devbox cache upload
devbox cache upload <installable>
```
If user wishes to specify cache URI, they can do:
```
devbox cache upload --to 's3://mike-test-nix-cache?region=us-west-2'
devbox cache upload --to 's3://mike-test-nix-cache?region=us-west-2' nixpkgs#php
```
```
devbox cache upload --to 's3://mike-test-nix-cache?region=us-west-2'
devbox cache upload --to 's3://mike-test-nix-cache?region=us-west-2' nixpkgs#php
```
Inspected cache on aws.

[cache] Rename cache copy, add single package functionality

---

internal/devbox/docgen/docgen.go
internal/devconfig/configfile/scripts.go

Plugins v2 allow scripts that may have `Virtenv` or `DevboxDir` in them.  This causes the commands to show up as absolute paths in the readme. This fixes that issue.
An alternative is to read the raw scripts from the plugin (including the un-templatized string). This may be a better solution long term, but is more work and would require specially plugin parsing only for the readme generation so I punted on that approach for now.
Tested with new go monorepo plugin https://github.com/jetpack-io/devbox-plugins/pull/7

[gen-readme] For generated readme scripts, replace absolute paths

---

internal/devbox/generate/tmpl/devcontainerDockerfile.tmpl

Resolves:
- https://github.com/jetpack-io/devbox/issues/1953
- https://github.com/jetpack-io/devbox/issues/1930
* Note: I don't recommend applying the patch below used to test this PR. Building an actual Dockerfile is way more of an integration test and I feel it is out of scope.
```diff
diff --git a/testscripts/generate/dockerfile.test.txt b/testscripts/generate/dockerfile.test.txt
index d63680b3..ec561564 100644
--- a/testscripts/generate/dockerfile.test.txt
+++ b/testscripts/generate/dockerfile.test.txt
@@ -1,3 +1,5 @@
exec devbox init
exec devbox generate dockerfile
exists Dockerfile
+exec devbox add docker
+exec devbox run -- docker build .
```
Followed by:
```shell
$ go test ./testscripts -run TestScripts/dockerfile
```
which results in a successfully built dockerfile.

[gen-dockerfile] Make /code directory creation idempotent

---

internal/nix/store.go

`nix.DaemonVersion` attempts to connect to the Nix daemon and returns its version string. Devbox will use the error from this function when configuring cache authentication:
- If the nix daemon is running, we need to update ~root/.aws/config so that it can authenticate with the private devbox cache. This requires a sudo prompt.
- If it's not running, then it's probably a single-user install without a daemon. We won't need sudo.

internal/nix: add DaemonVersion function

---

internal/nix/store.go
internal/vercheck/vercheck.go

chore: fix function names in comment

---

internal/devbox/devbox.go
internal/devbox/errors.go

Fixes https://github.com/jetify-com/devbox/issues/1977
(with another hack).
Unfortunately the way we structure our flake makes it really difficult to remove our network requests (when state is stale). Ideally, the flake can be built off of local only nix store references, but that's a much bigger project.
In the meantime, this is a quick hack that fixes issue above.
Added synthetic error that returns `connection refused` in the message. Ensures I was still able to run/shell with a stale state.

[offline] Allow devbox to work offline if DNS fails

---

vscode-extension/CHANGELOG.md
vscode-extension/package.json
vscode-extension/src/devbox.ts
vscode-extension/src/openinvscode.ts

changes all mentions and links of jetpack to jetify.
Publisher field in package.json is not changed since we decided to keep the publisher Id.
N/A

[vscode-extension] Rebranding changes for extension

---

.github/workflows/vscode-ext-release.yaml
docs/app/docs/ide_configuration/vscode.md
vscode-extension/CHANGELOG.md
vscode-extension/README.md

github action node version 16 makes publishing the extension to ovsx fail. Discord link is also broken

[vscode extension] updated discord link and github action for publishing the extension

---

docs/app/docusaurus.config.js

Two of our footer links were using http instead of https
yarn build

Change footer links to https

---

docs/app/docs/contributor-quickstart.md
docs/app/docs/devbox_global.md
docs/app/docs/guides/creating_plugins.md
docs/app/docs/installing_devbox.mdx
docs/app/docs/quickstart.mdx
examples/cloud_development/temporal/README.md
examples/development/elixir/elixir_hello/README.md

[easy] fix docs and links

---

go.mod
go.sum
internal/boxcli/cache.go
internal/devbox/packages.go
internal/devbox/providers/nixcache/nixcache.go

* Adds new info command
* key cache and credentials local cache to current member.

[cache] Add cache info command

---

internal/boxcli/global.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/root.go
internal/devbox/devbox.go
internal/devbox/flakes.go
internal/devbox/packages.go
internal/devconfig/config.go
internal/lock/interfaces.go
internal/lock/lockfile.go
internal/plugin/manager.go
internal/plugin/plugin.go
testscripts/testrunner/assert.go

The source of this bug is that when calling `lockfile.Tidy()` we were passing in only top level packages and not including plugin packages as well.
This bug was also affecting dev container construction and some edge case plugin template logic. This bug only affects users that are using custom plugins with packages.
I renamed `PackageNames` to `AllPackageNames` for clarity. Also removed a redundant function in config package that was no longer needed.
In other project added golang monorepo plugin and logged to ensure Tidy was not recreating lockfile. Also tested adding go to that project.

[bug-fix] Fix lockfile rewrite

---

internal/devbox/generate/tmpl/DevboxImageDockerfile
internal/devbox/generate/tmpl/DevboxImageDockerfileRootUser

Updated devbox install link for docker image.
After merging this we will release a new docker image, and that should upgrade the launcher version to 0.2.2. Currently, docker images have 0.2.1 or 0.2.0 for launchers due to devbox image being built and pushed to dockerhub before launcher changes.
N/A

[docker] Updated devbox install links for docker images

---

internal/boxcli/generate.go

Add a command that allows creating aliases to devbox scripts. This lets users source aliases from any project they want. It's opt-in, works in POSIX and fish. Aliases make it easy to call the scripts for other projects or directories.
How it works:
```bash
eval "$(devbox gen alias)"
devbox-build
```
It builds the alias name using the project name in devbox.json.
Alternatively the user can specify a prefix
```bash
eval "$(devbox gen alias --prefix dx)"
dx-build
```
```bash
eval "$(devbox gen alias --prefix dx)"
dx-build
cd $HOME && dx-build
```

[gen] Add gen alias command

---

internal/boxcli/generate.go

Adds `--no-prefix` flag to generate aliases for scripts without a prefix.
```bash
devbox gen alias --no-prefix
build
```

[alias] Add no-prefix flag

---

docs/app/docs/guides/scripts.md

Fixed typos in scripts.md

---

internal/nix/nix.go

Increase the `nix --version` command timeout from 3 seconds to 10 seconds. It was timing out in CI.

internal/nix: increase nix --version timeout

---

internal/boxcli/global.go
internal/boxcli/root.go
internal/boxcli/shellenv.go

Credit to @dax and #1963 for pointing out the need for this, and pioneering this solution.
This PR merely nudges the code to be a bit neater.
```
% git diff
diff --git a/internal/boxcli/shellenv.go b/internal/boxcli/shellenv.go
index 991c2bec..8076e125 100644
--- a/internal/boxcli/shellenv.go
+++ b/internal/boxcli/shellenv.go
@@ -78,6 +78,9 @@ func shellEnvFunc(
cmd *cobra.Command,
flags shellEnvCmdFlags,
) (string, error) {
+       fmt.Printf("shellenv --recompute flag is %v\n", flags.recompute)
+       return "", nil
+
env, err := flags.Env(flags.config.path)
if err != nil {
return "", err
```
compiled via `devbox run build`, and then:
```
% devbox shellenv
shellenv --recompute flag is true
hash -r
% devbox global shellenv
shellenv --recompute flag is false
hash -r
```

[shellenv] add --recompute flag with default=true, while keep global shellenv's recompute flag with default=false

---

internal/devbox/devbox.go

`devbox shell` and `devbox shell --pure` have differences in inheriting the host shell's env variables. But there is no devbox-defined env variable for users and devbox itself to know if it is in a pure shell or regular shell. 
This PR sets a `DEVBOX_PURE_SHELL=1` env variable to help fix that issue. 
This will allow users to differentiate and customize their setup based on if they're in a pure shell or not. For example, not sourcing `.bashrc` if in a pure shell.
- `devbox run build`
- `devbox shell` then `env | grep "DEVBOX_PURE_SHELL"`
- exit
- `devbox shell --pure` then `env | grep "DEVBOX_PURE_SHELL"`
- confirm the env variable is set for pure shell and not for regular shell.

[easy] added env variable to distinguish pure shell

---

internal/devbox/providers/nixcache/setup.go
internal/devpkg/narinfo_cache.go
internal/nix/install.go
internal/nix/nix.go
internal/nix/nix_test.go
internal/nix/store.go
internal/nix/upgrade.go
internal/telemetry/segment.go
internal/telemetry/telemetry.go

To check if nix daemon is running, Devbox runs:
nix store info --json --store daemon
This fails on older versions of Nix for a couple reasons:
- Before Nix 2.19.0, `nix store info` was `nix store ping`.
- Before Nix 2.14.0, the `--json` flag wasn't supported.
Check for both of these versions when constructing the `nix store` command so it works for Nix versions 2.12 - 2.21+.
Also add a `nix.VersionInfo.AtLeast` method and constants to make checking for supported major Nix versions easier.
Tested by running the `nix store` commands on all supported Nix versions.

internal/nix: support older nix versions in DaemonVersion

---

internal/devbox/packages.go

This changes how `installNixPackagesToStore` calls `nix.Build` so that it installs all installables in same nix command.
It does this by grouping all installables into two groups, one for allow-insecure and other for default and runs `build` on both groups (if not empty)
I was able to remove `packageInstallErrorHandler`  because it is already called in `packagesToInstallInStore` so we will never actually try to build something that can't build on the system, or if it requires `--allow-insecure` we will notice it then.
This does change our segment logging to group packages together for install times, so we will need to do some more work on the metrics side to determine slow packages. 
* Installed multiple packages not present in my nix store at once, including a combination of secure and …

[nix] Build all packages in same nix command

---

internal/devpkg/narinfo_cache.go

If store path exists locally, we know we can use that store path in `fetchClosure`. This helps speed up almost any operation where state is not up to date and we need to check if some store path is in cache.
* added print statement
`devbox run echo 5`

[perf] Skip cache check if store path exists locally

---

internal/boxcli/search.go

Current `devbox search` UI only shows the 10 newest versions for a package, unless the developer runs the command with `--show-all`. With the current presentation, this may confuse developers by making it seem like only 10 versions are available at all.
This pr Adds a `...` at the end to indicate that more versions are available. For example: 
```
Found 8+ results for "python":
* python  (3.13.0a6, 3.13.0a5, 3.13.0a3, 3.13.0a2, 3.13.0a1, 3.12.3, 3.12.2, 3.12.1, 3.12.0, 3.12.0rc3 ...)
* python-cosmopolitan  (3.6.14)
* python-launcher  (1.0.0)
* python-qt  (3.5.2, 3.5.1, 3.4.2, 3.3.0, 3.2)
* python-swiftclient  (4.2.0, 4.1.0, 4.0.0, 3.13.1, 3.13.0, 3.12.0)
* python-language-server  (2022-02-18, 2021-09-08, 2021-05-20, 2020-10-08, 2020-06-19, 2020-04-24)
* python-matter-server  (5.10.0, …
```

Indicate of a package version list in `devbox search` is truncated

---

internal/devbox/packages.go
internal/devbox/providers/nixcache/nixcache.go
internal/devbox/providers/nixcache/setup.go
internal/setup/setup.go
internal/setup/setup_test.go

Move the code that calls `sudo devbox` into the `setup` package and clean it up a bit. Fix some issues that were preventing the cache from being configured in non-interactive environments (such as CI).
- Don't re-prompt the user for confirmation in the sudo process.
- Don't call NeedsRun a second time in the sudo process.
- Don't prompt the user when stdin isn't a tty. This fixes cache configuration on macOS in CI.
- Preserve Devbox environment variables such as DEVBOX_DEBUG, DEVBOX_API_TOKEN, DEVBOX_PROD, and DEVBOX_USE_VERSION. This addresses cases where the sudo devbox process would use the wrong auth or API endpoint.
- Combine the nixcache aws and nix setup tasks into one task. There was a lot of overlap and this simplifies the setup code.
Reran the `cache-upload` workflow against …

internal/setup: move sudo into SudoDevbox function + fix macOS CI

---

internal/devpkg/narinfo_cache.go

Reverts jetify-com/devbox#2042
jetify-com/devbox#2042 introduced a bug where adding non-cached packages would fail to add them to the flake on the first attempt. (it would succeed on subsequent attempts after the package is already in the store).
The root cause is that `fetchNarInfoStatus` gets called twice per package (even though we cache it and we're not supposed to call it twice). The first call returns `false` because the package is not cached. The second call returns `true` because the package is already in store. This discrepancy essentially causes the package not to appear on the flake at all. When updating state again, the package is already in the nix store so both `fetchNarInfoStatus` calls return true.
I think reverting this is best immediate course of action. In follow up we …

Revert "[perf] Skip cache check if store path exists locally"

---

internal/devpkg/narinfo_cache.go

Fixes bug described here https://github.com/jetify-com/devbox/pull/2054
A better (but a bit more involved) solution is to parallelize by output. Currently we parallelize by meta-output (which includes `__default_output__`). This has two downsides:
* `__default_output__` can be multiple outputs, in which case we don't parallelize them at all.
* We still do redundant work when `__default_output__` is multiple outputs. (once as `__default_output__` and once for each individual outout that forms part of defaults).

[nix-cache] Prevent checking cache twice per package

---

internal/boxcli/cache.go
internal/devbox/packages.go
internal/devpkg/narinfo_cache.go
internal/nix/build.go
internal/nix/store.go

Credentials command is hidden, this flag can help debugging.

[debug] Add cache credentials flag and more perf profiling

---

internal/boxcli/push.go
internal/boxcli/secrets.go
internal/devbox/devbox.go
internal/pullbox/s3/pull.go

```
% git grep "jetpack cloud"
internal/boxcli/push.go:                Short: "Push a [global] config. Leave empty to use jetpack cloud. Can " +
internal/boxcli/secrets.go:             Short:             "Interact with devbox secrets in jetpack cloud.",
internal/boxcli/secrets.go:             Short: "Initialize secrets management with jetpack cloud",
internal/devbox/devbox.go:                              "Ignoring env_from directive. jetpack cloud secrets is not "+
internal/devbox/devbox.go:                                      "Error reading secrets from jetpack cloud: %s\n\n",
internal/pullbox/s3/pull.go:            "Logged in as %s, pulling from jetpack cloud (profile: %s)\n",
```
cleared these up

[easy] rename jetpack-cloud to jetify-cloud

---

internal/devpkg/narinfo_cache.go
internal/devpkg/package.go
internal/shellgen/flake_input.go
internal/shellgen/tmpl/flake_remove_nixpkgs.nix.tmpl

This is mostly a revert of a few changes made in https://github.com/jetify-com/devbox/commit/32465875d2d5c4650647395c8b2c739394f212b1 that introduced a perf regression. 
* builds
* ran `devbox install` on a project that had 2 packages cached in nix cache and 1 package cached in jetify cache

[perf] Fix regression

---

internal/nix/cache.go

Add the `NIXPKGS_ALLOW_UNFREE` and `NIXPKGS_ALLOW_INSECURE` environment variables to `nix copy` commands so that those packages can be uploaded by default. This also requires the `--impure` flag so that Nix respects the environment variables.

nix: allow unfree and insecure in cache upload

---

internal/devbox/packages.go
internal/devpkg/narinfo_cache.go
internal/devpkg/package.go
internal/nix/build.go
internal/nix/store.go
internal/nix/store_test.go

This improves install and ensure perf by making the following changes:
* Batch all store path existence checks. (previously we did one by one, each `nix ls` call is about 50ms)
* If lockfile has store paths we use them (instead of trying to get them from nix)
* Fix regression in `FillNarInfoCache`
Installed large devbox.json (30+ packages) and used `DEVBOX_PRINT_EXEC_TIME` and observed almost all "prep" time disappear. prep time is the work devbox does before actually building the packages.

[perf] Improve install and ensure perf

---

internal/devbox/packages.go
internal/devpkg/package.go

Fixes issue introduced in https://github.com/jetify-com/devbox/blame/main/internal/devbox/packages.go#L558-L558
Removed store paths from lock file, ensured package was still installed.

[easy][bug] Fix install if package has no storepaths in lockfile

---

internal/devbox/packages.go
internal/devbox/providers/nixcache/nixcache.go
internal/devpkg/narinfo_cache.go
internal/telemetry/telemetry.go

* If we fail to build with caches, try again without them.
* Added logging when build fails and user has substituters.
Ran install on devbox project that installs cached terraform. Commented out `--extra-substituters` flag to force it to fail. Observed output indicating substituter error, and fallback to building from source.

[cache] Fallback for failed build with cache

---

.github/workflows/docker-image-release.yml

Added metadata to tag each container image with the same version as devbox as well as `latest`
Will have to be tested with CICD

[container] Added metadata to tag docker image with devbox version

---

internal/devbox/cache.go
internal/devbox/packages.go
internal/devpkg/narinfo_cache.go
internal/devpkg/package.go

This changes `devbox cache upload` so that it now longer has to build packages if they are already in cache.
For each package, it first checks if it is in target cache. If it is, it skips. Otherwise it builds/copies.

[cache] Optimize cache upload

---

internal/devbox/packages.go
internal/devbox/providers/nixcache/setup.go

Don't add extra substituters when the user answers "no" to the confirmation prompt for configuring Nix caches. This stops Nix from printing warnings such as:
warning: ignoring untrusted substituter 's3://mycache', you are not a trusted user.
Run man nix.conf for more information on the substituters configuration option.
Also print a message saying that `devbox cache configure` can be used to configure the cache after answering no.

internal/devbox: fix warning when user refuses cache setup

---

internal/devbox/packages.go
internal/devbox/providers/nixcache/setup.go
internal/devpkg/narinfo_cache.go
internal/setup/setup.go

Don't check the Jetify Nix caches for store paths if Nix isn't configured to use them. This can happen if the user says "no" to the confirmation prompt for cache setup. Otherwise, `nix build` prints an error about the path missing:
$ devbox add mongodb@6.0.15
Info: Adding package "mongodb@6.0.15" to devbox.json
? You're logged into a Devbox account that now has access to a Nix cache. Allow Devbox to configure Nix to use the new cache (requires sudo)? No
Info: Skipping cache setup. Run `devbox cache configure` to enable the cache at a later time.
Info: Installing the following packages to the nix store: mongodb@6.0.15
error: path '/nix/store/n7fkj8vif9yc1g063r0z88j5dh3i7p8a-mongodb-6.0.15' is required, but there is no substituter that can build it

nixcache: don't check Jetify caches if they're not configured

---

internal/nix/store.go
internal/nix/store_test.go
testscripts/lockfile/nopaths.txt

Fix regression introduced in https://github.com/jetify-com/devbox/pull/2076
I misunderstood the API. A null value (in modern API) or a valid: false (in legacy API) occur when store path doesn't exist. Whether the store path itself is a valid store path doesn't matter, obviously if it is not a valid path, it won't be present in the store, but if it's valid and not installed, it will return null value or valid: false. The users of this function do not want to ignore these paths.
Edit: This bug is a bit less bad than initially thought. Because we install non-cached packages in flake, so anything missing would be installed then.
Unit test. 
This is tricky to test. I added a test script that can hopefully catch this.
Edit: This test doesn't actually catch this because the package ends up …

[bug] Fix parseStorePathFromInstallableOutput

---

internal/devbox/providers/nixcache/nixcache.go
internal/devpkg/narinfo_cache.go
internal/goutil/sync.go
internal/setup/setup.go

TSIA
This still means an extra ~50-100ms because we check the status but this is probably fine.
The `defer debug.FunctionTimer().End()` call in Status only prints once.

[perf] memoize cache setup status

---

plugins/postgresql/process-compose.yaml

This PR adds the following `readiness_probe` to the `postgresql` plugin:
```yaml
readiness_probe:
exec:
command: "pg_isready"
```
With that change, Devbox users have the ability to create their own processes that depend on a healthy postgresql service. For example, to seed a database, one can add the following to a `process-compose.yml`:
```yaml
version: "0.5"
processes:
seed_db:
command: |
npm run db:seed # for example
depends_on:
postgresql:
condition: process_healthy
```
In a project with the above `process-compose.yml` file and the changes in this PR applied to `.devbox/virtenv/postgresql/process-compose.yml`

Add a readiness_probe for postgresql

---

internal/boxcli/global.go
internal/boxcli/list.go

Refactor the list command into its own file. Also update the description to be more accurate.
1. Verified the `list` command is updated with the new message in the `--help` command output
2. Verified the `list` command outputs the same list of packages before and after this change (compared my local `devbox` install output to the output in my `devbox shell` with these changes).

Refactor the list command

---

internal/nix/store.go
internal/nix/store_test.go

Addresses issue introduced in 
https://github.com/jetify-com/devbox/pull/2076
and
https://github.com/jetify-com/devbox/pull/2098
Basically we have 2 different uses cases when looking up store paths. Sometimes we want all store paths (whether installed or not) and in other cases we only want paths that are in local store. This change fixes that and adds some testing.
unit tests, manual integration test by installing a package that was not in local store.

[nix] Fix StorePathsAreInStore

---

internal/nix/nix.go
internal/nix/nix_test.go

Increases leniency for `nix --version` output to support Nix forks, such as [Lix](https://lix.systems):
`nix (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab`
On Lix:
```bash
$ nix --version
nix (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab
$ go run ./cmd/devbox run nix --version
nix (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab
$ go run ./cmd/devbox shell
```
On Nix:
```bash
$ nix shell nixpkgs#nix
$ nix --version
nix (Nix) 2.18.2
$ go run ./cmd/devbox run nix --version
nix (Nix) 2.18.2
$ go run ./cmd/devbox shell
```
```bash
$ go run ./cmd/devbox shell
Error: nix: ensure install: get version: parse nix version: nix (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab
exit status 1
```

fix(nix): add support for Nix forks

---

plugins/pip/venvShellHook.sh

Only prompt the user about activating their Python Virtual Env on setup, and not on every shell activation
Build + test on python

Only notify users about Venv Activation on setup

---

internal/boxcli/services.go
internal/devbox/devbox.go
internal/devbox/devopt/devboxopts.go
internal/services/manager.go

Add new `--pcflags` option which provides flags directly to process-compose
https://github.com/jetify-com/devbox/issues/2105
The `--pcflags` flag must be provided in front of each flag as shown below:
```
devbox services up ${service} \
--pcflags ${flag1} \
--pcflags ${flag2} \
...
```
1. Added debugging print statement in `manager.go`, right before providing the flags to process-compose, to ensure that the flags are being passed down as expected to process-compose.
2. Verified that `devbox services up nginx` shows the process-compose UI but `devbox serviecs up nginx --pcflags -t=false` does not show the UI.

Add new --pcflags option to devbox services up

---

docs/app/docs/quickstart.mdx

Make sure that we do not duplicate the installation guide, because:
1) It's redundant; and
2) `curl -fsSL https://get.jetify.com/devbox | bash` does not work for [NixOS-WSL](https://github.com/nix-community/NixOS-WSL), but using NixOS guide is fine. If other NixOS users come across this page directly and directly install using the installation script, then I'm afraid they cannot install `devbox` as well.
N/A

[docs] update the quickstart guide

---

internal/boxcli/install.go
internal/boxcli/pull.go
internal/devbox/devbox.go
internal/devbox/nixprofile.go
internal/devbox/packages.go
internal/devbox/update.go
internal/devpkg/package.go
internal/lock/lockfile.go
internal/nix/nixprofile/profile.go
internal/nix/profiles.go
internal/nix/storepath.go
internal/nix/storepath_test.go
internal/ux/messages.go

Adds new `--tidy-lockfile` flag that can be used with install. It fills in any missing store paths in lockfile, improving future performance. 
I'm not 100% convinced this works in all cases. My two biggest concerns would be:
* I'm setting all outputs to default.
* re derivation name parsing: Not 100% sure we can rely on versions never having dashes.
* unit test
* Manually removed store paths form lockfile and tried to install. Got warning, ran with flag.

[perf] Add flag to fix missing store paths

---

internal/nix/build.go
internal/nix/cache.go
internal/nix/command.go
internal/nix/config.go
internal/nix/eval.go
internal/nix/nix.go
internal/nix/nixpkgs.go
internal/nix/profiles.go
internal/nix/search.go
internal/nix/store.go
internal/nix/upgrade.go

Add a new `cmd` type that wraps `exec.Cmd` and provides better error handling when a Nix command fails.
Calls to `commandContext`, `exec.Command` and `exec.CommandContext` are consolidated into the `command` function, which now returns a `*cmd` instead of an `*exec.Cmd`. The `cmd.Run` and related methods return an error that provides more detail about the command in the following format:
nix: command ("error"|"canceled"|"timed out"): <shell command>: <stderr>: <exec error>
The shell command in the error is a properly-escaped shell string that can be copy/pasted to re-run the command.
If Nix prints a line with the prefix "error: " to stderr, then the error will include that line in its message. If there are multiple lines with that prefix, it only includes the last one. Otherwise, it will …

internal/nix: improve command error handling

---

internal/nix/nix.go
internal/nix/nix_test.go

Nix prerelease version strings aren't valid semvers. An example is `2.23.0pre20240526_7de033d6`. This breaks the Nix minimum version check that Devbox performs at startup.
Special-case prerelease versions by coercing them to valid semvers when performing a comparison. For example, `2.23.0pre20240526_7de033d6` becomes `2.23.0-pre.20240526+7de033d6`.
Fixes #2128.

internal/nix: fix version comparison for prerelease versions

---

internal/devbox/nixprofile.go
internal/nix/eval.go
internal/nix/profiles.go
testscripts/add/add_insecure.tst.txt

This change installs all packages into profile with same command. If we fail due to priority conflict, we fallback to the previous one by one installation.
This significantly improves performance on projects with many packages when all packages are already in store. This aims to solve a common CICD case where nothing has changed, all packages are in store, but we need to create the .devbox directory and nix profile from scratch.
cc: @Lagoja this helps address some reported issues.
Happy path:
On project with 30+ packages, delete `.devbox` directory and ran `devbox install`. This change reduced total time from 10s to 2s.
Sad path:
On new project added `curl`, `ruby`, `bundler`, `go`. `ruby` and `bundler` conflict. I ran `devbox install` and it correctly fell back to one by one. I inspected …

[perf] Install all packages to profile in a single nix command

---

.schema/devbox.schema.json

The current JSON schema does not include the **name** and **description** fields. This update adds these fields as optional properties to the Devbox JSON schema.
* Used an online JSON schema validator to ensure that the updated schema is valid.
* Ensured that the schema allows optional name and description fields.

Add name/description to devbox json schema.

---

internal/nix/build.go
internal/nix/command.go
internal/nix/profiles.go
internal/nix/search.go
internal/nix/store.go

Write logs whenever a Nix command is about to start and after it exits. Make `cmd` a `slog.LogValuer` so that it writes structured log attributes grouped under a `cmd` prefix.
Example logs and attributes (line breaks added for readability):
msg="nix command starting"
cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem"
cmd.path=/nix/var/nix/profiles/default/bin/nix
msg="nix command exited"
cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem"
cmd.path=/nix/var/nix/profiles/default/bin/nix
cmd.pid=68672
cmd.code=0
cmd.dur=34.296041ms
Command exits …

internal/nix: log all command starts and exits

---

.github/workflows/cli-release.yml

`--rm-dist` flag is deprecated in newer versions of Goreleaser in favor of `clean`: https://goreleaser.com/deprecations/#-rm-dist 
Release action was failing due to the deprecated flag. This PR replaces it with the new clean flag

[CI] Update go-releaser action

---

.github/workflows/docker-image-release.yml
internal/devbox/generate/tmpl/DevboxImageDockerfile
internal/devbox/generate/tmpl/DevboxImageDockerfileRootUser

This PR addresses the issue of our previous approach to only publish the latest version of devbox with `:latest` tag in dockerhub. It achieves 2 things:
1. fixes the previously broken github action to release a docker image after every tag creation.
2. updates the dockerfile so that devbox binary doesn't automatically upgrade to latest version upon first use. This allows docker pulls have fixed versions.
Already tested on releasing 0.10.7 version to dockerhub as test.
- `docker pull jetpackio/devbox:0.10.7`
- `docker run jetpackio/devbox:0.10.7`
- confirm output shows devbox version 0.10.7 and doesn't upgrade to latest version.
- same for devbox-root-user

[docker] fix docker release image

---

internal/devbox/devbox.go
testscripts/run/env.test.txt

This was introduced in #635 (cc @ipince). I don't think its needed anymore. 
It seems to be used in the `/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh` script, at the very top to prevent re-execution:
```
1 # Only execute this file once per shell.
2 if [ -n "${__ETC_PROFILE_NIX_SOURCED:-}" ]; then return; fi
3 __ETC_PROFILE_NIX_SOURCED=1
4
```
Perhaps it has other use-cases as well? RFC.
From my casual usage of a Devbox binary built with this change, it all seems to still work fine.

[RFC][Devbox] computeEnv: remove __ETC_PROFILE_NIX_SOURCED=1

---

.github/workflows/docker-image-release.yml

TSIA
tested via github action
https://github.com/jetify-com/devbox/actions/runs/9507160567/job/26205993393

[docker] Added steps for latest tag for devbox & devbox-root

---

internal/devbox/devbox.go
internal/devbox/envvars.go
internal/shellgen/scripts.go
internal/shellgen/tmpl/init-hook-wrapper.tmpl
internal/shellgen/tmpl/script-wrapper.tmpl

This PR implements a change to the semantics of `devbox run`.
BEFORE:
`devbox run` would always ensure that the Devbox State and Environment is up-to-date.
AFTER:
`devbox run` will only do so when _outside_ a Devbox Environment (i.e. `devbox shell` or equivalent like direnv-enabled shell).
The motivation is two fold:
1. Speed. Users often want to just run a quick script, this slows them down.
2. Users often have init-hooks which are more appropriate for one-time setup, rather than when running a utility script inside a `devbox shell` that has already been set up appropriately.
This was shared in the Discord channel for feedback: https://discord.com/channels/903306922852245526/1009933892385517619/1248724103750483978
Notably, the focus there was on skipping the init-hooks, but in this PR, …

[devbox] run: skip re-computing Devbox State if in devbox shell

---

internal/devbox/packages.go
internal/devpkg/package.go

[easy][lock-tidy] Don't tidy flakes

---

internal/boxcli/global.go
internal/boxcli/root.go
internal/boxcli/run.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/devbox/devbox.go
internal/devbox/devopt/devboxopts.go
internal/devbox/nixprofile.go

…vars
In this PR, we change `devbox global` shell environment to omit the env-vars from `nix print-dev-env`. Instead, we rely on the `nix profile` that Devbox manages to introduce the global packages into `PATH`. As before, `nix profile` continues to be generated from the `buildInputs` from `nix print-dev-env <devbox-generated-flake>`.
The motivation is:
1. `devbox global` adds a bunch of nix stdenv packages to the top of your `$PATH` variable, which can cause conflicts when trying to compile or build projects on your machine. 
2. `devbox global` also sets a global `PYTHONPATH` variable that interferes with other packages, as well as python scripts that are installed/running on the host. This global `PYTHONPATH` is unnecessary because any python binaries installed by the user are already …

[devbox global] add `--omit-nix-env` flag for shellenv/shell/run commands

---

internal/boxcli/run.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/devbox/devbox.go
internal/devbox/devbox_test.go
internal/devbox/devopt/devboxopts.go
internal/devbox/shell.go

From the EnvOptions docblock:
```
// EnvOptions configure the Devbox Environment in the `computeEnv` function.
// - These options are commonly set by flags in some Devbox commands
// like `shellenv`, `shell` and `run`.
// - The struct is designed for the "common case" to be zero-initialized as `EnvOptions{}`.
```
This gets rid of the pseudo-global state in the `Devbox` struct where we were setting `pure`, `preservePathStack` and `omitNixEnv` values.
TODO:

[Devbox] introduce devopt.EnvOptions

---

internal/boxcli/auth.go
internal/boxcli/cache.go
internal/devbox/providers/identity/identity.go

Don't merge until the new cloud.jetify.com/team/cache URL is live.
---
Add a `devbox cache enable` subcommand that:
1. Opens a browser and performs the login flow is the user isn't logged in.
2. Configures Nix to use the Jetify cache if it isn't already.
The login flow redirects to the new cloud.jetify.com/team/cache URL to let the user know the cache is enabled.

boxcli: devbox cache enable

---

internal/boxcli/featureflag/tidywarning.go
internal/devpkg/package.go

`--tidy-lockfile` is not reliable, so put this warning behind a feature flag until it is fixed.
Ran `devbox install` with missing outputs in lockfile, did not see error.

[lock-tidy] Put warning behind feature flag

---

internal/boxcli/shellenv.go
internal/devbox/devbox.go
internal/devbox/packages.go
internal/devbox/refresh.go

A few improvements:
* Use same refresh command. Previously we were using two different ways of refreshing the environment.
* Display `refresh-global` even if alias is not set (since it will likely be set by the end of the command).
* Don't show the refresh message will calling refresh.
* Tested refresh-global on zsh.
* TODO: test refresh-global on fish.
* Calling refresh-global does not show refresh message.

[ux] Improve refresh messaging

---

internal/devbox/devbox.go
internal/devconfig/configfile/env.go
testscripts/run/envfrom.test.txt

NOTE: Docs update PR will follow.
As per request from users, I added support for `env_from` field being able to take a  path to `*.env` file and have those env variables available in devbox shell and run.
If a duplicate env variable is specified in both `.env` and in the `"env"` section of devbox.json, the env section from devbox.json takes priority and overwrites. This I believe is the correct behavior but I'm open to discussion.
see test file at `testscripts/run/envfrom.test.txt`

[devbox.json] support env_from dotenv files

---

examples/data_science/R/.gitignore
examples/data_science/R/README.md
examples/data_science/R/devbox.json
examples/data_science/R/devbox.lock
examples/data_science/R/src/examplePlot.R

This adds README and example R script (along with devbox.lock and devbox.json)
I tested the example repo on both `aarch64-darwin` and `x86_64-linux` by `cd`'ing into `examples/data_science/R` directory; running `devbox shell` then `Rscript src/examplePlot.R`. I considered the test to have passed if an Rplots.pdf file was produced with a scatterplot image.
This *should* do for most R users. However there is a case that I haven't handled: Sometimes users will want to install packages that are not on CRAN and therefore not on nixpkgs/nixhub.io (e.g. installing packages from github using the `R` package `devtools`). I'm not sure of an easy way to address this yet.
Addresses https://github.com/jetify-com/devbox/issues/2182

[example] add R example

---

internal/searcher/client.go

The format is `Devbox/$VERSION ($GOOS; $GOARCH)`.

searcher: set custom user agent in search client

---

examples/servers/caddy/devbox.d/caddy/Caddyfile
examples/servers/caddy/devbox.json

TSIA. The caddy example did not work before, as the port `8800` is served, but only port `8082` is defined.
devbox run start

Change the caddy example port to 8080

---

docs/app/docs/devbox_examples/databases/valkey.md
docs/app/docs/guides/plugins.md
docs/app/docs/guides/services.md
examples/databases/valkey/README.md
examples/databases/valkey/devbox.d/valkey/valkey.conf
examples/databases/valkey/devbox.json
examples/databases/valkey/devbox.lock
plugins/builtins.go
plugins/valkey.json
plugins/valkey/process-compose.yaml
plugins/valkey/valkey.conf

Added a plugin for Valkey, including environment variables, default conf file, and a service
Added Docs And Example Files
Addresses #2153 
- compile
- `valkey-server $VALKEY_CONF --port $VALKEY_PORT`

Add Valkey Plugin

---

internal/devbox/devbox.go

Adds new `DEVBOX_WD` env var that can be used in scripts and shell. It has the original directory where the devbox command was called. It's useful when the script is directory specific.
Added the following script:
`"print-wd": "echo PWD=$PWD DEVBOX_WD=$DEVBOX_WD",`

[envars] Add DEVBOX_WD env var

---

.schema/devbox-plugin.schema.json

The list had `readme` instead of `description`

fix: devbox-plugin.schema.json required properties

---

go.mod
go.sum

Uses newest version of runx (https://github.com/jetify-com/opensource/pull/368)
cc: @mikael-lindstrom
```
rm -rf ~/Library/Caches/runx/pkgs/mvdan
devbox run fmt  # which requires mvdan/gofumpt
```

[pkg] Update pkg deps

---

devbox.json
testscripts/Dockerfile
testscripts/languages/python_missing_so.test.txt
testscripts/languages/python_old_glibc.test.txt
testscripts/testrunner/setupenv.go
testscripts/testrunner/testrunner.go

Add tests that install Python with Devbox and then run scripts that import numpy
and psycopg2. They currently fail on Linux due to linker errors related to missing shared libraries.
To run the tests on Linux with Docker, run:
devbox run -e DEVBOX_RUN_FAILING_TESTS=1 docker-testscripts -test.run '^TestScripts$/python'
The new docker-testscripts script in devbox.json runs testscripts in a Docker
container to make it easier to test various Linux distros and architectures.

testscripts: python tests for numpy and psycopg2

---

internal/devbox/generate/tmpl/envrcContent.tmpl

fix: make direnv watch devbox.lock

---

internal/boxcli/patch.go
internal/boxcli/root.go
internal/patchpkg/builder.go
internal/patchpkg/glibc-patch.bash
internal/shellgen/flake_plan.go
internal/shellgen/generate.go
internal/shellgen/tmpl/glibc-patch.nix.tmpl

Start porting the glibc patching script (which has expanded to patching other libraries too) over to Go.
To make this change more incremental, this commit only ports copying the original package's files to the patched package (basically the `cp` command). Devbox still runs the embedded bash script until the rest of it is ported.
The general patching steps are:
- When generating the `glibc-patch.nix` flake, Devbox gets the absolute path to itself and adds it as a flake input. This makes devbox available in the flake's build.
- Instead of running `glibc-patch.bash` as the flake's builder, run `devbox patch <pkg>`.

patchpkg: start moving glibc-patch.bash to Go

---

internal/patchpkg/builder.go

When running inside a Nix derivation the PATH is completely empty, so functions like `exec.Command("bash")` don't work. To make dealing with this easier, add a helper function that looks for an environment variable named after the command and returns `$cmd/bin/cmd` (e.g., `bash` becomes `$bash/bin/bash`). This will automatically find build-time dependencies that are added as attributes to the derivation.

patchpkg: `lookPath` helper to find nix binaries

---

internal/patchpkg/builder.go

Add a `packageFS` type that extends `fs.FS` to translate to/from operating system paths. This makes it a little easier to get real file paths when writing or passing files to external commands (like `patchelf`).

patchpkg: add packageFS to handle store paths

---

docs/app/docs/nixhub/index.mdx

Add links to typeform and calendly on Nixhub Docs page
Localhost

Nixhub Links

---

docs/app/docs/cli_reference/devbox_add.md
docs/app/docs/configuration.md
docs/app/docs/devbox_examples/databases/mariadb.md
docs/app/docs/devbox_examples/databases/mysql.md
docs/app/docs/devbox_examples/databases/postgres.md
docs/app/docs/devbox_examples/databases/redis.md
docs/app/docs/devbox_examples/databases/valkey.md
docs/app/docs/devbox_examples/languages/php.md
docs/app/docs/devbox_examples/languages/python.md
docs/app/docs/devbox_examples/languages/ruby.md
docs/app/docs/devbox_examples/servers/apache.md
docs/app/docs/devbox_examples/servers/caddy.md
docs/app/docs/devbox_examples/servers/nginx.md

Add details on disabling plugins
Localhost

add information on disabling plugins

---

internal/boxcli/patch.go
internal/patchpkg/builder.go
internal/patchpkg/glibc-patch.bash
internal/patchpkg/patch.go
internal/shellgen/tmpl/glibc-patch.nix.tmpl

Move the patching functionality from glibc-patch.bash to Go while also updating it to set RPATH instead of RUNPATH.

patchpkg: port ELF patching to Go and use RPATH

---

internal/boxcli/patch.go
internal/patchpkg/builder.go
internal/patchpkg/patch.go
internal/patchpkg/search.go
internal/shellgen/tmpl/glibc-patch.nix.tmpl

Add a `devbox patch --restore-refs` flag that attempts to restore removed store path references. It works by finding store paths that have had their hashes replaced with e's (`/nix/store/eeee...-foo`) and then searching the package's build environment for store paths with matching names.
For example, for the removed reference `/nix/store/eee...-foo-1.2.3` search all environment variables for a path ending in `foo-1.2.3`, then overwrite the removed reference with the one we found.

patchpkg: restore removed refs to build deps

---

docs/app/docs/guides/creating_plugins.md

Add the ProjectDir placeholder in the plugin docs

Fix plugin placeholder docs

---

.golangci.yml
internal/boxcli/add.go
internal/devbox/devopt/devboxopts.go
internal/devbox/packages.go
internal/devconfig/configfile/ast.go
internal/devconfig/configfile/packages.go
internal/devpkg/package.go

Add a `devbox add --patch <mode>` flag that replaces `--patch-glibc` and a corresponding `patch` JSON field that replaces `patch_glibc`. The new name reflects the new patching behavior, which affects more than just glibc.
The new patch flag/field is a string instead of a bool. Valid values are `auto`, `always` and `never`. The default is `auto`.
devbox add --patch <auto/always/never>
- `auto` - let Devbox decide if a package should be patched. Currently only enables patching for Python or if `patch_glibc` is true in the config.
- `always` - always attempt to patch a package. Corresponds to the `--patch-glibc=true` behavior.
- `never` - never patch a package, even if `auto` would.
If a config has an existing package with the `"patch_glibc": true` field, it's interpreted as `"patch": …

devpkg: auto-patch python

---

testscripts/languages/python_missing_so.test.txt
testscripts/languages/python_old_glibc.test.txt

The Python linker tests that fail on Linux (which is expected) also fail on darwin. The darwin tests only run in the pre-release job, so it went unnoticed in the original PR.

testscripts: skip (known) failing tests on darwin

---

internal/devpkg/package.go
internal/patchpkg/builder.go
internal/shellgen/tmpl/glibc-patch.nix.tmpl

This enables the part of Python patching that restores some build dependencies on macOS. This fixes some `pip install` build errors for packages without needing to manually add dev dependencies on packages like openssl.

patchpkg: patch missing Python refs on darwin

---

plugins/pip/venvShellHook.sh
plugins/python.json

Moves `.venv` to the Devbox Project Root, and adds some checks to ensure we warn the user if we are going to squash a user created venv. Moving `.venv` to the project root makes it more likely that Python Extensions and IDEs will pick up the devbox managed python, instead of a system python
Fixes DEV-105

[Python] Change `.venv` script to be more compatible with IDEs

---

plugins/pip.json
plugins/pip/venvShellHook.sh

A few small tweaks after testing in Sandboxes
1. Move the `STATE_CHECK` to after we verify that a VENV exists and that it's properly formatted. This ensures that we can fix scenarios where the venv was deleted or broken, without excessively prompting the user
2. Add a `UV_PYTHON` environment variable to ensure that users who install `uv` don't accidentally overwrite the Python version in their `devbox.json`
1. Open the `python-flask` Jetify Example in Sandboxes
2. Test `.venv` is setup correctly with `devbox shell`
3. Delete the `.venv` dir, verify that re-running `devbox shell` creates it
4. Install `uv` (`devbox add uv`)
5. Verify that `uv sync` and other commands don't override Devbox Python

[Python] Venv tweaks based on testing in Sandboxes

---

internal/boxcli/services.go
internal/devbox/services.go
internal/services/manager.go

This fixes two previously reported issues: 
1. If process-compose is not terminated gracefully (e.g., it's parent shell crashes, or is closed on accident), then process-compose may terminate without also terminating it's services. 
2. If process-compose is started in the background, a user can now run the `attach` command to re-attach the TUI to the backgrounded process compose
A few current limitations: 
1. This only applies to `devbox services up -b`, but could be extended to `devbox services up` as well by starting process-compose in the background, and then attaching the TUI
2. You will now need to explicitly run `devbox services stop` to stop process-compose for your project
Todos: 
1. Should we apply the backgrounding to `devbox services up` as well?
2. Should we allow users to …

[Services] Keep Process Compose alive in background, add `attach` command

---

internal/boxcli/patch.go
internal/patchpkg/builder.go
internal/patchpkg/patch.go
internal/shellgen/tmpl/glibc-patch.nix.tmpl

This fixes an issue with TensorFlow not being able to find libstdc++.so at runtime.

patchpkg: patch libstdc++

---

internal/devpkg/narinfo_cache.go
internal/devpkg/package.go
internal/shellgen/flake_input.go
internal/shellgen/flake_plan.go

Fix a case where an empty patch mode wouldn't default to "auto". This was causing Devbox to skip patching when it should not have.
Got rid of the sync.OnceValue function for determining if a package needs to be patched. This was originally done to avoid a call to nix.System(), but that call doesn't happen anymore.

devpkg: fix empty patch mode

---

internal/boxcli/featureflag/feature.go
internal/boxcli/featureflag/feature_test.go
internal/envir/env.go

[easy][refactor] Move env var to owner package

---

internal/boxcli/featureflag/impure_print_dev_env.go
internal/nix/nix.go

Add `--impure` to the `print-dev-env` command, allowing flakes to access environment variables also in this step. Without this change, a flake that needs an env var to work will correctly build but then a shell could not be created.
This also solves #2196, signifying that other people encountered a similar problem.
Both by
```
devbox run test
```
and manually, building the tool and locally checking that a flake would pick up variables (with `builtins.getEnv`) when activating a shell.

Aadd `--impure` flag when calling print-dev-env

---

internal/nix/search.go
internal/nix/search_test.go

nix search would return `{}` which and we would not return an error. Now we return error.
`devbox add rust`

[search] Fix bad error when installing "rust"

---

internal/patchpkg/builder.go
testscripts/languages/python_patch_missing_ref.test.txt
testscripts/languages/python_patch_missing_so.test.txt
testscripts/languages/python_patch_old_glibc.test.txt

Don't exit non-zero when `devbox patch` is unable to restore some of the missing references to Python build dependencies.
Fixes #2289.

patchpkg: don't error on missing store refs

---

internal/devbox/devbox.go
internal/devbox/shellrc.tmpl
internal/devbox/shellrc_fish.tmpl
internal/devbox/testdata/shellrc/basic/shellrc.golden
internal/devbox/testdata/shellrc/noshellrc/shellrc.golden
internal/nix/nix.go
internal/shellgen/tmpl/script-wrapper.tmpl
testscripts/basic/path_whitespace.test.txt

Make sure the flake ref is URL-encoded and quote the rcfile in the shellrc template.
Fixes #2290.

internal/devbox: handle whitespace in paths

---

.github/workflows/cli-tests.yaml
internal/nix/install.go

Bumping to 2.24.7 which seems latest tag on https://github.com/NixOS/nix/tags 
Our current hardcoded one is fairly old (we should more periodically update this),
and is leading to issues with MacOS Sequoia (see https://github.com/NixOS/nix/issues/11543)
Also add this to the test-nix-versions. I am keeping the older nix versions
around because some of them exercise older nix profile (and other similar issues
that i am failing to recall atm) formats that some users may still be reliant on.
At some point, we should consider bumping up our minimum nix version as well
so we can deprecate legacy nix support (and keep the code base neater).
@lagoja is testing this manually
will ensure cicd pass as a sanity test

bump installed nix version to latest, and update test-nix-versions

---

internal/devbox/generate/tmpl/envrc.tmpl

https://www.shellcheck.net/wiki/SC2148 (tips depend on target shell)
https://direnv.net/#how-it-works (.envrc is loaded into a bash sub-shell)

refactor: add bash shebang for shellcheck

---

internal/boxcli/services.go
internal/devbox/devopt/devboxopts.go
internal/devbox/services.go
internal/services/manager.go
internal/services/ports.go

Users can set the port that process-compose runs on when they use `devbox services`. If they do not specify a port, we default to randomly picking an open port with low risk of conflict
Users can specify their process-compose port by:
1. Passing the `--pcport, -p` flag when running `devbox services up`. 
2. Setting the `PC_PORT_NUM` environment variable. This variable can be set in the projects `devbox.json` if you want to always use the same port for process-compose. This is overridden by the `--pcport` flag.
In the MySQL example: 
1. When I run `devbox services up -b -p 8080`, or
2. When I run `PC_PORT_NUM devbox services up -b`,
I can verify that process-compose is running on my 8080 with `curl localhost:8080/processes` and seeing the list of expected processes.

[services] Let users set the port for process-compose

---

.github/workflows/cli-tests.yaml
internal/boxcli/featureflag/detsys.go
internal/boxcli/featureflag/feature.go
internal/boxcli/setup.go
internal/nix/install.go

* Adds detsys installer.
* Puts it behind disabled flag. Add CICD matrix to test.
* Special casing: Handles missing systemd by just skipping it.
* Tested `devbox setup nix` in linux docker container.
* Will test in CICD
* Much more testing needed before removing feature flag

[nix] Add DetSys installer behind feature flag

---

internal/devpkg/package.go
internal/patchpkg/builder.go
internal/patchpkg/search.go
internal/shellgen/flake_plan.go
internal/shellgen/tmpl/glibc-patch.nix.tmpl
testscripts/languages/python_patch_cuda.test.txt

Automatically patch python to use any `cudaPackages.*` packages that are in devbox.json. This will only work if the CUDA drivers are already installed on the host system.
The patching process is:
1.  When generating the patch flake, look for the system’s `libcuda.so` library (installed by the driver) and copy it into the flake’s directory.
2.  Nix copies the flake’s source directory (and therefore libcuda.so) into the nix store when building it.
3.  The flake calls `devbox patch` which adds a `DT_NEEDED` entry to the python binary for `libcuda.so`. It also adds the lib directories of any other `cudaPackages.*` packages that it finds in the environment.

patchpkg: patch python to use devbox CUDA libs

---

internal/boxcli/midcobra/telemetry.go

We're running out of Sentry events and it looks like the culprit is devbox overlogging, including a lot of user errors that should not be logged.
This PR https://github.com/jetify-com/devbox/pull/844 removed code that avoided logging user errors. I think this was a bug? If programmer wants a user error to be logged, they should use `WithLoggedUserMessage` instead.
Untested

[telemetry] Don't log user errors

---

.github/workflows/cli-tests.yaml
.gitignore
devbox.json
flake.lock
flake.nix
go.sum
vendor-hash

This adds a flake.nix to our repo for building and distributing Devbox. This will make it easier for developers who install Devbox with Nix to use pre-releases, and keep Devbox up-to-date on their system. 
This changes our workflow in a few small ways:
1. Whenever `go.mod` changes, we'll need to run `devbox run update-hash` to update the vendorHash for the flake. You can also run this script when you run `go mod tidy`
2. Releasing a new version will also require us to update the version number in the flake.nix. This should be done with a commit ("Bump version to x.y") that also gets tagged with the release number.
3. For debugging purposes, the flake will add the shortened commit hash to the version string. This also helps identify if a user built the binary from a flake.
4. I've added a …

Build and Install Devbox via Flake

---

flake.nix

Nix flake fails to build with:
```nix
error: attribute 'dirtyShortRev' missing
at /nix/store/m5mqwkz0ss2cav2c9663mx8vwsmvcas3-source/flake.nix:21:28:
20|               then "${x}-${self.shortRev}"
21|               else "${x}-${self.dirtyShortRev}")
|                            ^
22|         ];
```
This fixes the issue
```
nix build github:jetify-com/devbox/jl/fix-flake-rev
```

Fix flake rev issue

---

internal/patchpkg/elf.go
internal/patchpkg/search.go
internal/shellgen/flake_plan.go
testscripts/languages/python_patch_cuda.test.txt

Consolidate the shared library search logic into patchpkg. Search in more directories (notably `/var/lib/*/lib`) and do a better job of detecting the various [library names]. This allows Devbox to find `libcuda` inside Devspace containers.
[library names]: https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
The new patchpkg types and functions are:
```go
type SharedLibrary struct {
*os.File
LinkerName string
Soname     string
RealName   string
}
func OpenSharedLibrary(name string) (SharedLibrary, error)
func FindSharedLibrary(name string, searchPath ...string) iter.Seq[SharedLibrary]
func (lib SharedLibrary) CopyAndLink(dir string) error
```

patchpkg: improve CUDA shared library search

---

.github/workflows/docker-image-release.yml

Previously we ran docker image build and publish to dockerhub when a new tag was created, but this introduced a bug when a tag was created as a draft it would trigger this run but the assets from the tag weren't publicly available yet.
This change makes sure that the tag is marked as a release and is published to run so that the assets it needs (mainly compiled devbox binary) it publicly available before building and pushing a container image to dockerhub.
need to wait for the next release to truly test.

changed trigger to release to dockerhub to run on published releases

---

internal/devbox/devbox.go

Fixes issue introduced in https://github.com/jetify-com/devbox/pull/2277
This comment explains it pretty well: https://github.com/jetify-com/devbox/pull/2277/files#r1767085866
except:
> I think this doesn't matter in practice, because we always append @latest during devbox add <name>.
This is not 100% true. In the very small number of packages that are not in nixhub but are valid attribute paths, (e.g. `stdenv.cc.cc.lib`) we store the key in the lockfile without `@latest`  :(. The key missmatch caused lockfile.Tidy to remove entries.
My bad for making the suggestion that lead to this, this was really subtle difference.
Added `stdenv.cc.cc.lib` on devbox.json linux only, installed on linux and copied over lockfile to macos. Did `devbox install` and ensured lockfile was not modified.

[lockfile] Fix tidy for non-versioned packages

---

docs/app/docs/cli_reference/devbox_add.md
docs/app/docs/cli_reference/devbox_services_attach.md
docs/app/docs/cli_reference/devbox_services_up.md
docs/app/docs/configuration.md
docs/app/docs/devbox_examples/languages/go.md
docs/app/docs/env_variables.md
docs/app/docs/faq.md
docs/app/docs/guides/services.md
docs/app/docs/installing_devbox.mdx
docs/app/sidebars.js

* Update Services docs to include all new features (attach, port selection)
* Document `--patch` flag and json config
* Document installation via nix flake
* Document Devbox Environment Variables
localhost, `devbox run -- pnpm build`

Update docs for 0.13 series

---

internal/plugin/github.go

This adds new experimental env var `DEVBOX_X_GITHUB_PLUGIN_CACHE_TTL` that controls how long devbox caches github plugins. The default is 24h.
Ideally we store plugin versions in lockfile, but this can help improve UX in the meantime. 
Added print statement to monitor network requests
```bash
DEVBOX_X_GITHUB_PLUGIN_CACHE_TTL=0 devbox run echo hello
DEVBOX_X_GITHUB_PLUGIN_CACHE_TTL=1s devbox run echo hello
DEVBOX_X_GITHUB_PLUGIN_CACHE_TTL=1h devbox run echo hello
```

[plugins] Add env var to control github cache ttl

---

.github/workflows/vscode-ext-release.yaml

fixes publishing vscode extension to open vsx marketplace
ran the github action from a branch
https://github.com/jetify-com/devbox/actions/runs/11168838111

[github actions] fix publish ovsx

---

internal/boxcli/midcobra/telemetry.go
internal/boxcli/usererr/usererr.go
internal/telemetry/telemetry.go

Fixes bug introduced in https://github.com/jetify-com/devbox/pull/2305

[logging] Fix segment logging

---

devbox.json
internal/autodetect/autodetect.go
internal/autodetect/detector/detector.go
internal/autodetect/detector/poetry.go
internal/autodetect/detector/python.go
internal/boxcli/global.go
internal/boxcli/init.go
internal/devbox/devbox.go
internal/devbox/devbox_test.go
internal/devbox/util.go
internal/devconfig/config_test.go
internal/devconfig/init.go

Closes DEV-151
(re) implements something similar to our old "planner" framework but only for python/poetry. It's only opt-in.
Using the `--autodetect` with `init` flag generates a devbox.json with any detection results.
Currently the framework only only uses the most relevant detector, but could be modified to use multiple detectors.
`devbox init --autodetect --dry-run`

[zeroconfig] Implement --autodetect flag

---

internal/boxcli/init.go
internal/devbox/devbox.go
internal/devbox/devbox_test.go
internal/devconfig/config_test.go
internal/devconfig/init.go
pkg/autodetect/autodetect.go

closes DEV-152
instead of installing packages, this only generates the devbox.json making it easier to use and test and much faster.
`devbox init --auto --dry-run`

[zeroconfig] Change autodetect implementation so it generates devbox.json

---

internal/devbox/util.go

Bump process-compose to 1.34.0. This includes Greg's fix for the CultureAmp reported issue.

Bump process-compose to 1.34.0

---

docs/app/docs/devbox_global.md

Since Fleek is deprecated, removing it from Global docs

Remove Fleek from Docs

---

internal/build/build.go

`devbox auth login` with compiled devbox worked without ending up at error page

[auth | dev] use new dev auth url

---

internal/boxcli/auth.go
internal/devbox/providers/identity/identity.go

If refresh fails, we should tell user to log in again instead of showing weird invalid_grant error
* messed with refresh token to make it bad.
* Set expiration date in my session to date in past.
* Did `devbox auth whoami`

[auth] Fix failed session refresh

---

internal/devconfig/configfile/file.go
pkg/autodetect/autodetect.go

Previously config was not getting properly saved after packages were added. This fixes it.
`devbox init --auto`

[autodetect] Fix autodetect

---

internal/devbox/util.go

Process-compose 1.34 introduces a bug that causes postgresql and other daemon-based processes to hang indefinitely. 
See #2354 for more details.
Tested postgresql plugin using 1.34, 1.27 -- verified that the issue still existed
Tested postgresql plugin with 1.24.2 -- verified the issue was resolved

Revert process-compose to 1.24.2

---

flake.lock
flake.nix

Updating the version to fix a process-compose bug with postgresql
* Bump version to 0.13.5
* Upgrade the nixpkgs commit we use to build
nix build .
Tested `devbox init` on an existing project to validate warning
Tested `devbox services up` on postgres to validate process-compose change

bump version to 0.13.5

---

internal/devconfig/configfile/env.go

Fixes this bug:
https://github.com/jetify-com/devbox/pull/2174/files#r1659165116
- use compiled devbox
- put `export FOO = 'BBBAR'` in .env file
- put the following in a devbox.json file
```json
{
"packages": [],
"shell": {
"init_hook": [
"echo 'Welcome to devbox!' > /dev/null"
],
"scripts": {
"test": [
"echo $FOO"
]
}
},
"env_from": ".env"
}
```
- create a subdirectory besides devbox.json called `test`
- cd test && devbox run test

[env] Fixed env_from bug when it is called from a subdirectory

---

docs/app/docs/guides/creating_plugins.md

Fixes the syntax error in the plugin creation example docs.

fix: json syntax error in plugin example

---

docs/app/docusaurus.config.js

Search index should be back online now -- re-enable algolia
Localhost, Algolia Dashboard

Re-enable Algolia Search

---

docs/app/docs/quickstart.mdx

Found that we're using the older button on quickstart. Updated it here

fix wrong button on Quickstart

---

docs/app/docs/cli_reference/devbox_completion_zsh.md

The suggested docs don't work if Oh My Zsh Plugins are installed.
I updated the docs accordingly.

cli reference: update completion docs for zsh

---

internal/build/build.go
internal/shellgen/flake_plan.go
internal/shellgen/tmpl/glibc-patch.nix.tmpl

Update the patching flake to use the devbox flake (added in 37c36a1b) instead of copying the binary manually.
- It uses the flakeref `"github:jetify-com/devbox/" + build.Version` to get the same version of Devbox that's currently running.
- For dev builds, it attempts to find the devbox source and use the local flake instead.
When Devbox needs to patch a package, it generates a flake that calls `devbox patch` as its builder. Because flake builds are sandboxed, we need a way of getting devbox into the Nix store.
Previously, we were just copying the currently running devbox executable into the Nix store and using that. However, Devbox isn't actually a static binary (we don't build with CGO_ENABLED=0). This causes `devbox patch` to fail because the flake is isolated from the system's linker.

patchpkg: use devbox flake instead of local binary

---

pkg/autodetect/autodetect.go
pkg/autodetect/detector/go.go
pkg/autodetect/detector/go_test.go

[autodetect] Add go autodetection

---

docs/app/docs/configuration.md
docs/app/docs/guides/secrets.md
internal/devbox/devbox.go
internal/devconfig/configfile/env.go

[env] Fix env_from docs and improve error messaging

---

internal/shellgen/flake_plan.go
internal/shellgen/generate.go
internal/shellgen/generate_test.go

Fix a bug where `.devbox/gen/flake` gets locked on old versions of `.devbox/gen/flake/glibc-patch` by deleting the `flake.lock` file.
We only delete the lock file when the generated flake changes so that Nix isn't forced to re-evaluate it every time.
The repro steps are:
1. Add a package that gets auto-patched (`devbox add python@3.11.9`).
2. `.devbox/gen/flake` gets locked on the patch flake.
3. Change the patched package (`devbox add python@3.11.10`).
4. The new patch flake isn't used because of `.devbox/gen/flake/flake.lock`. Instead, the old version is used (from the Nix store).
Fixes #2316.
Fixes #2370.

shellgen: delete flake.lock if flake.nix changes

---

pkg/autodetect/autodetect.go
pkg/autodetect/detector/go.go
pkg/autodetect/detector/php.go
pkg/autodetect/detector/php_test.go

[auto] Add php detector

---

pkg/autodetect/autodetect.go
pkg/autodetect/detector/nodejs.go
pkg/autodetect/detector/nodejs_test.go
pkg/autodetect/detector/php_test.go

TSIA
Possible improvement: should we default `DEVBOX_COREPACK_ENABLED` to true? (cc: @LucilleH )

[zeroconfig] Implement nodejs detector

---

plugins/postgresql/process-compose.yaml

Hello,
Please view this PR as a bug report and proposal for a fix, and not a finished feature implementation. 
When we were working with devbox we realised we had errors on some of our machines. After some debugging we found that `devbox services start postgresql` did not work properly on machines, where the absolute path to the project contained a blank space. This change in the process-compose was what fixed the issue for us.
I did not perform any due dilligence in checking or testing if this proposed change does not introduce a breaking change for other consumers. I am merely proposing a change that has worked for us personally.
The postgresql process compose is faulty, as it does not properly escape the PGHOST variable. When a blank space is anywhere in the absolute path of the …

[PROPOSAL] postgresql process-compose is faulty when $PGHOST contains blank space

---

internal/devconfig/configfile/ast.go
internal/devconfig/configfile/ast_test.go
internal/devconfig/configfile/env.go
pkg/autodetect/autodetect.go
pkg/autodetect/detector/detector.go
pkg/autodetect/detector/go.go
pkg/autodetect/detector/nodejs.go
pkg/autodetect/detector/nodejs_test.go
pkg/autodetect/detector/php.go
pkg/autodetect/detector/poetry.go
pkg/autodetect/detector/python.go

* Adds `DEVBOX_COREPACK_ENABLED: "1"` to nodejs detector.
* Adds ability to set env programmatically on config. (This probably doesn't work with interspaced comments)
* Unit tests
* Manually created project with package.json and then did `devbox init --auto`

[zeroconfig] Default nodejs to corepack enabled

---

internal/boxcli/run.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/devbox/devbox.go
internal/devbox/devopt/devboxopts.go
internal/devbox/packages.go
internal/devbox/refresh.go

This PR continues the work from #2013 to also add the `--recompute` flag option for `devbox run` and `devbox shell`.
For some users on bad networks, this can save them annoyance and time for when they _know_ their devbox environment is up-to-date.
Fixes #2315
This PR affects 3 commands: `run`, `shell` and `shellenv`.
1. For `run`:
Added `"hello": "latest",` to devbox.json of this project.
```
devbox run --recompute=false -- echo "hello world"
Warning: Your devbox environment may be out of date. Run with --recompute=true to update it.
hello world
```
then
```
devbox run -- echo "hello world"
Info: Ensuring packages are installed.
✓ Computed the Devbox environment.
hello world
```
2. For `shell`. Ran similar commands as above.
3. For `shellenv`. Followed test plan of #1963.
Changed the …

Add --recompute flag for commands: shell and run

---

internal/devbox/devbox.go
internal/devconfig/config.go
internal/devconfig/config_test.go

When a plugin modifies PATH and also config in devbox.json modifies PATH via `env:{}`, the env overwrites the plugin and so PATH modification from the plugin is lost. This is because we do `maps.Copy()` to merge the env from plugin to the one from config. 
The copy is fine for all other env variables but for PATH we need to handle merging the two rather than overwriting.
Fixes #2138 
bug recreate:
- devbox init
- devbox add ruby (ruby plugin modifies PATH)
- devbox shell (see PATH is prepended with ruby plugin)
- modify devbox.json and add `"env": {"PATH": "/my/config/bin:$PATH"}`
- re-enter devbox shell and see PATH prepend from ruby plugin is lost, only `"/my/config/bin"` is prepended.
fix recreate:
- follow same steps, but in last step both PATH prepends from devbox.json and from …

[bug] plugin env PATH fix

---

examples/development/haskell/devbox.json

CICD jobs for [`cli-test`](https://github.com/jetify-com/devbox/actions/workflows/cli-tests.yaml?query=branch%3Amain) has been failing on Haskell example because the PATH (only) in test environment for macos doesn't have access to `/usr/bin/security` so it fails to verify TLS handshake on haskell package downloads. 
This small change ensures haskell has access to security binary. 
Broader fix would be to add `/usr/bin` to [`setupPATH`](https://github.com/jetify-com/devbox/blob/0fdfc6764a0a16fbbff504410053b13dee075e5f/testscripts/testrunner/setupenv.go#L39) function that sets up test environments before being run in CICD. But this PR keeps the scope to only the failing test.
related to https://github.com/commercialhaskell/stack/issues/4558
tested in this CI job: …

[cli-test] Added /usr/bin to PATH so that haskell can to verify pkg downloads

---

flake.nix

This stops including a potentially-colliding 'updater' binary in the derivation.
When I tried to install Zen browser on my NixOS system via a flake (`zen-browser.url = "github:MarceColl/zen-browser-flake";`), I got a build error saying that zen-browser included a file that collides with a devbox file:
```
error: builder for '/nix/store/8fy82p10qwd7z5aj4sraq9k88c62nz55-home-manager-path.drv' failed with exit code 25;
last 1 log lines:
> error: collision between `/nix/store/915ll44ksnhy369wyqlm8ys7ylxzmi89-devbox-0.13.6-0bc66cb/bin/updater' and `/nix/store/s2bz22csj1a8yjh3n3i1h67s5zhrh1g2-zen-browser-1.0.1-a.6/bin/updater'
```
My guess is that the zen-browser flake is also at fault (also errantly including a binary named `updater`) but this is where I looked (and figured out how to fix) …

Exclude testscripts from Flake build

---

devbox.go

Add a top-level package that makes a subset of the `internal/devbox` functionality (currently just install) public.
There are some places where we want to run devbox commands (such as in the prefetcher) which requires us to run the CLI externally. Exporting a package means we can run the command implementation directly and don't need to install the CLI (similar to what we're doing with autodetect).

devbox: export API for devbox install

---

flake.nix

Bump flake version to 0.13.7
nix build .

Bump version to 0.13.7

---

docs/app/docs/installing_devbox.mdx

Change the URL of Nix Installer, they have a proper documentation, now ; which is better than the announcement blog post
Just with markdown preview instead GitHub

Nix Installer have an official documentation, now

---

internal/boxcli/search.go

This is a cool package, i was looking for something like this and just found it. 
As we know when searching for a package the results will be like this
but the results will be a bit difficult to read when there are many versions are available like this.
I suggest it would be easier to read the available versions if it were like this
or if you have a more readable option I'm open to that. Thanks for making such a cool package.

feat(cli): improve search result view for large version lists

---

internal/boxcli/featureflag/detsys.go
internal/boxcli/setup.go
internal/nix/install.go
internal/nix/shim.go
nix/install.go

Remove the feature flag and make the DetSys installer the default.
- Download the installer directly in case the system doesn't have curl.
- Expose the auto-install functionality in the public nix package so we can reuse it elsewhere.
- Remove some checks that were only relevant to the old installer (WSL2 limitations and warnings about root).
The install logic is also now part of an `Installer` struct to provide some flexibility around what install program is run and when it's downloaded.
type Installer struct{ ... }
func (i *Installer) Download(ctx context.Context) error
func (i *Installer) Run(ctx context.Context) error

nix: make DetSys installer the default

---

examples/databases/postgres/devbox.json
plugins/mariadb.json
plugins/mysql.json
plugins/postgresql.json

Add `glibcLocales` to the Plugins for PostgreSQL, MySQL, and MariaDB so users don't have to add it on Linux
Run e2e tests, test in Devspaces

move glibcLocales to plugins

---

internal/devbox/nixprofile.go
testscripts/rm/multi.test.txt
testscripts/testrunner/testrunner.go

After syncing the flake packages to the profile, remove all old generations of the Nix profile. This allows the Nix garbage collector to eventually remove any old packages.
Opted for a Go implementation instead of calling `nix profile wipe-history` because deleting the history is pretty simple and this is faster.

devbox: clean up profile history after sync

---

nix/flake/flakeref.go
nix/flake/flakeref_test.go

Add support for the `narHash` and `lastModified` attributes of flakerefs. The new `Ref.Locked` method uses these attributes to report whether a flake is locked.

flake: add narHash and lastModified attributes

---

nix/flake/flakeref.go
nix/flake/flakeref_test.go

The string form of GitHub flakeref can only have a rev or a ref, not both. For example:
- Good: `github:NixOS/nixpkgs/b321c8e818546d5491ee5611476500557b880856`
- Good: `github:NixOS/nixpkgs/nixpkgs-unstable`
- Bad: `github:NixOS/nixpkgs/nixpkgs-unstable/b321c8e818546d5491ee5611476500557b880856`
If both the Rev and Ref fields are set, use Rev.

nix/flake: fix Ref.String() for github flakes w/ rev and ref

---

docs/app/docs/devbox_examples/languages/elixir.md
docs/app/docs/guides/plugins.md
examples/development/elixir/elixir_hello/devbox.json
examples/development/elixir/elixir_hello/devbox.lock
plugins/builtins.go
plugins/elixir.json

Adds a very basic elixir plugin to simplify installation to a simple `devbox add elixir`. Also now properly stores Mix/Hex artifacts in `.devbox/virtenv`.
- Tested it against the existing elixir example in the repo. Seems to work fine.
- Tested on my own projects as well, separately on Mac + Ubuntu.

Add simple elixir plugin

---

internal/devbox/devbox.go
internal/devbox/packages.go
internal/devbox/update.go
internal/devconfig/configfile/file.go
internal/devpkg/package.go
internal/devpkg/package_test.go
internal/lock/interfaces.go
internal/lock/lockfile.go
internal/lock/resolve.go
internal/nix/build.go
internal/nix/flake.go
internal/nix/nix.go
internal/nix/profiles.go
internal/nix/store.go
internal/shellgen/flake_input.go
internal/shellgen/flake_plan.go
internal/shellgen/generate_test.go
internal/shellgen/testdata/flake.nix.golden
internal/shellgen/tmpl/flake.nix.tmpl
internal/shellgen/tmpl/shell.nix.tmpl

Depends on #2464.
---
Make the `stdenv` (and other flakerefs) lockable and updateable. This makes it possible to update the stdenv with a regular `devbox update` and simplifies the logic for how the stdenv commit is chosen:
1. If there's no stdenv flakeref in devbox.lock, resolve github:NixOS/nixpkgs/nixpkgs-unstable to a locked ref and store it in the lockfile.
2. Otherwise, use the ref in the lockfile.

lock: add support for locking stdenv + flakerefs

---

internal/devbox/devbox.go

This allows to have a consistent output from `devbox run`.
Closes #1631 and #1991.
I tested running multiple times `devbox run` in different project where I use it.

fix: sort scripts list

---

docs/app/docs/guides/plugins.md

[docs] add note about github plugin cache env-var

---

internal/boxcli/search.go
internal/searcher/client.go

This allows to cancel the search request.
Mostly manual testing

fix: pass a ctx to client searcher `search`

---

internal/devbox/packages.go

Fixes #2510 
Previously, `devbox ls --outdated` would error on packages that it could not resolve, like `stdenv.cc.cc.lib` or `darwin.apple_sdk.frameworks.IOKit`. This prevented devbox from checking if the rest of the packages were outdated. 
This PR changes the error to a warning, so the rest of the version checks can proceed
1. Create a devbox.json
2. Add standard packages using `devbox add`
3. Add `stdenv.cc.cc.lib` or `darwin.apple_sdk.frameworks.IOKit` to the project
4. Verify that `devbox ls --outdated` shows a warning for the non-versioned packages instead of an error.

[ls] return unresolved packages as a warning instead of an error

---

internal/boxcli/update.go
internal/devbox/devopt/devboxopts.go
internal/devbox/packages.go
internal/devbox/update.go

As part of getting devbox working in renovate, we need to run devbox in renovate's base image (added here https://github.com/containerbase/base/pull/3191). The problem is the way nix is installed (already in that image) it cannot actually install anything. This is because it's a quirky variant of a single user install where all the `/nix/*` paths are set to custom values.
We can work around this by just having devbox update the lockfile but not actually install anything (which is also a speed win) - but this functionality doesn't seem to available in the devbox cli currently.
This is a potential implementation adding what we need for renovate to upgrade devbox projects. Happy for you to do it another way. The approach we've taken seems like it's misusing the `mode` variable a little bit. …

add --no-install flag to `devbox update`

---

plugins/python.json

Fixes #2411
The UV_PYTHON env variables sets which python executable uv will use. 
The current plugin sets the UV_PYTHON value  to `.devbox/nix/profile/default/bin/python` which means `uv pip install ` commands will try to install and save libraries under the  `.devbox/nix/profile/default/lib/python3.x/site-packages` directory. 
This will cause an error as the directory doesn't have write permissions because it exists under a folder that is a symlinked to a folder under the `/nix/store` path.
This change makes sure UV_PYTHON points to the python executable under .venv. 
This will make `uv pip install` commands install libraries to the site-packages directory  under .venv just like normal `pip install ` would.
1. devbox create uvtest --template python-pip
2. cd uvtest
3. devbox add uv
4. …

fix(python plugin): set UV_PYTHON to python in .venv

---

plugins/poetry/initHook.sh

When using poetry, with the suggested `init_hook` from the docs:
```
{
"packages": [
"python3",
"poetry@1.8" // notice I am using poetry 1.8, the poetry shell command is not part of poetry version 2.0
],
"shell": {
"init_hook": "poetry shell"
}
}
```
and running `devbox shell`, while the poetry env is being loaded, it generates this log: 
`Using virtualenv: /home/fotiadis/src/work/trumo/services/tc_gateway_consumer/.venv`
This can be problematic to users instant prompt like the very famous zsh theme [powerlevel10k](https://github.com/romkatv/powerlevel10k)
By adding the `--quiet` flag this solves the problem
poetry 2.0 has removed the `poetry shell` (the functionality still exists if you download a plugin). The new way to achieve the same behavior according to [the …

fix: disable poetry plugin output

---

devbox.lock
flake.lock
flake.nix

Bump to version 0.14.0
Confirmed via `nix build .` on localhost

Bump version to 0.14.0

---

internal/devbox/generate/tmpl/dev.Dockerfile.tmpl

This MR modifies the Dockerfile to reduce the final image size by optimizing the Nix store after installing packages. Added `nix-store --gc` and `nix-store --optimise` commands to clean up and optimize the Nix store after package installation.
Built the Docker image locally and verified the image size reduction. Confirmed that the application runs as expected after the changes.

Optimize Docker Image Size by Cleaning Nix Store

---

examples/development/elixir/elixir_hello/devbox.lock
internal/boxcli/run.go
internal/devbox/devbox.go

Allows running a script on all devbox projects nested in a directory. Useful for monorepos. Example:
`devbox run --all-projects lint`
Doing 
`devbox run --all-projects` without a script name shows all available scripts among all nested projects.
@savil I kinda regret changing `run` to remove the need for `--`. It means that this flag only works for defined scripts, not for arbitrary commands :( 
`devbox run --all-projects fmt`

[run] Add --all-projects flag

---

.github/workflows/cli-tests.yaml
flake.lock
testscripts/testrunner/testrunner.go
vendor-hash

[easy][cicd] Fix testscripts

---

internal/boxcli/update.go

https://github.com/renovatebot/renovate/issues/27543#issuecomment-2705204833
Running into issues running the no-install command in renovate because the Nix install is not mounted.
This PR makes it so the PreRunE check to check if Nix is installed correctly won't run if the --no-install flag is passed to the update command.
I built devbox with a println in the ensureNixInstalled function and validated that it does not run when the --no-install flag is passed …

Disable PreRunE check for Nix when passing no-install flag on update cmd

---

docs/app/docs/devbox_examples/databases/rabbitmq.md

Fix typo in rabbitmq docs

---

internal/plugin/github.go
internal/plugin/github_test.go

Currently when if `GITHUB_TOKEN` is set to an expired or invalid token requests to github will fail with a 404. There is not messaging to the user (even with `DEVBOX_DEBUG=1`) to indicate the cause. This took a while to debug, opening this PR to make it easier for the next person this happens to.
- make a temp devbox project and add a plugin like https://github.com/jetify-com/devbox-plugins/tree/main/mongodb
- set `GITHUB_TOKEN` to a random string
- see the following error that doesn't indicate the cause of the error at all (also try running with `DEVBOX_DEBUG=1` and see no extra helpful info
```
❯ devbox install
Error: failed to get plugin github:jetpack-io/devbox-plugins?dir=mongodb @ https://raw.githubusercontent.com/jetpack-io/devbox-plugins/master/mongodb/plugin.json (Status code …
```

Fix misleading error message when using an expired GITHUB_TOKEN 

---

devbox.lock
internal/devbox/update.go
internal/lock/lockfile.go
internal/lock/resolve.go
internal/nix/flake.go
internal/shellgen/flake_input.go
internal/shellgen/tmpl/flake.nix.tmpl
nix/flake/flakeref.go

This caches resolutions for unlocked nixpkgs (the default) for 90 days on the user's machine.  Otherwise, everytime devbox tries to resolve `github:NixOS/nixpkgs/nixpkgs-unstable` it will download a new version of nixpkgs. This is slow (40+ seconds) and usually nothing changes.
* `devbox update` without any arguments will update nixpkgs. This is existing functionality.
* `devbox update nixpkgs [...pkgs]` will also update nixpkgs.
I'm not convinced updating nixpkgs when using `update` without arguments is best, but I didn't want to break past functionality. It adds 40+ seconds to update operations when there is no package to update.
An alternative command syntax considered was `devbox update --nixpkgs`. The benefit of doing this would be to avoid conflicts in the future. 
I did not use …

[perf] Cache nixpkgs resolution

---

docs/app/docs/continuous_integration/github_action.md

I noticed the docs reference v0.11.0 instead of the latest version of v0.12.0, not sure if this was intended but I thought I'd update it for others to ensure new people install the latest version.
the

Update github_action.md to install latest devbox github action

---

internal/devbox/devbox.go
internal/devbox/shell.go
internal/devbox/shell_test.go

fixes: https://github.com/jetify-com/devbox/issues/2532
Possibly also fixes https://github.com/jetify-com/devbox/issues/2535 but need to test.
blame: https://github.com/jetify-com/devbox/pull/2465
cc: @Lagoja 
* unit test
* manual testing using --pure flag
the

[pure] Fix bad nixpkgs breaking pure mode

---

internal/boxcli/midcobra/telemetry.go
internal/boxcli/midcobra/telemetry_test.go
internal/shellgen/flake_plan.go
internal/shellgen/flake_plan_test.go
internal/shellgen/generate.go

`NixPkgsCommitHash` is no longer defaulted so it's best to use lockfile.Stdenv to get the nixpkgs for patching and telemetry. This ensures we use the correct resolved version at all times. (also I think, but have not confirmed that before this change, `newGlibcPatchFlake` will not work is nixpkgs hash is not specified in devbox.json)
unit tests 
the
[Community Contribution License](https://github.com/jetify-com/opensource/blob/main/CONTRIBUTING.md#community- …

[nixpkgs] Use lock.stdenv instead of NixPkgsCommitHash

---

flake.lock
flake.nix

Bump version to 0.14.2
nix build
./result/bin/devbox version
the

Bump version to 0.14.2

---

docs/app/cloud/cache/authenticating.md

Updated docs around devbox api tokens.
```
% DEVBOX_API_TOKEN=a-token devbox cache info
* s3://<a-valid-devbox-cloud-cache>?region=us-west-2&trusted=true 
* s3://<jetify-devbox-cache>?region=us-west-2&trusted=true (read-only)
```
```
% devbox cache info
No cache configured
```

docs: Fix docs around what environment variable and commands to generate token(s)

---

plugins/python.json

Fixes: #2575
The current python plugin sets `UV_PYTHON` to path of python executable under default `VENV_DIR` directory. However if someone sets a custom `VENV_DIR` in their `devbox.json` file, this will cause an error. Since `uv` will attempt and fail to find python in the default VENV_DIR path where the venv would no longer exist.
This change removes the `UV_PYTHON` environment variable from the plugin altogether. This can be done, since `uv` will use the python executable of the active virtual environment its running in (https://docs.astral.sh/uv/reference/cli/#uv-python), and the venv is automatically created and activated by the python plugin.
This change allows flexibility for users to set their own `VENV_DIR`. It also still works with pip (`uv pip install`) as expected. 
1. devbox …

fix(python plugin): remove UV_PYTHON  env variable

---

internal/boxcli/run.go

Narrow fix to completion when passing `-c`, `--config` flags.
Used tab completion when using `-c` flag and it worked.
the

[completion] Fix shell completion when specifying --config flag

---

internal/devpkg/pkgtype/runx.go

[runx] Use standard github token env name

---

internal/plugin/local.go

Fixes #2638
See issue for description of the problem. This PR is just a one-line change to evaluate current environment variables as devbox assembles the path for local plugins. This will allow things like a dynamic root directory for plugin source.
Built devbox locally with code change and copied it to /usr/local/bin/devbox. Refreshed global environment and plugins defined with an environment variable in the path now resolve properly.
the
[Community …

Evaluate environment variables in the local plugin path

---

internal/devbox/envvars.go
internal/devbox/testdata/shellrc/basic/env
internal/devbox/testdata/shellrc/basic/shellrc.golden

Fixes #995 - Error running `devbox shell` in environment with exported Bash function
Tested that when running the below commands:
- no errors are printed
- the `foo` function runs successfully and prints `foo`
Case 1 (simple):
```
foo() { echo foo; }
export -f foo
devbox shell
foo
```
Case 2 (function that contains special characters `"` and `$`):
```
foo() { echo "${bar}"; }
export -f foo
export bar=foo
devbox shell
foo
```
Case 3 (`shellenv`):
```
foo() { echo foo; }
export -f foo
devbox shellenv > shellrc
source shellrc
foo
```
Also added a Bash function to the test data used by `TestWriteDevboxShellrc`.
By …

[envvars] Fix error when env contains Bash function

---

internal/devbox/util.go

Bump the process compose version from 1.24.2 to the latest 1.64.1
Reran some services, will check tests in CI/CD
the

Update process-compose version

---

internal/services/manager.go

Currently the invocation of process-compose in devbox is smothering useful error messaging from the `is_strict` parsing provided by process-compose.
```shell
echo 'version: "0.5"
is_strict: true
processes:
foo:
commnad: echo "Hello, world!"
' > process-compose.yaml
devbox services up
```
#2579 
the

propagate output from process-compose invocation

---

internal/fileutil/fileutil.go
internal/fileutil/fileutil_test.go
internal/nix/install.go
internal/nix/install_test.go

Adds error return to `IsDirEmpty` and unit tests
CICD
the

[fileutil] Update IsDirEmpty, add unit tests

---

internal/devbox/generate/tmpl/DevboxImageDockerfile
internal/devbox/generate/tmpl/DevboxImageDockerfileRootUser

The docker-image is failing to build in GHA:
https://github.com/jetify-com/devbox/actions/runs/16204700194/job/47358742840
The error indicates that the seccomp (secure computing mode) BPF (Berkeley Packet Filter) program that Nix tries to load is incompatible with the Docker container environment on ARM64.
When filter-syscalls = true (the default), Nix uses seccomp BPF to filter system calls for security sandboxing. Setting filter-syscalls = false disables Nix's syscall filtering, which bypasses the seccomp BPF program entirely and prevents the error.
This PR uses the approach from #1811 to fix this for arm64 platforms.
`docker build --platform linux/arm64 -t devbox-image-arm64 -f /Users/savil/code/jetpack/devbox/internal/devbox/generate/tmpl/DevboxImageDockerfile .`
`docker build …

[docker image] set filter-syscalls = false in nix.conf to workaround missing `seccomp BPF program` in arm64 linux

---

.github/workflows/cache-upload.yml

Fixes https://github.com/jetify-com/devbox/actions/runs/16847493651/job/47729104601
This is a very specific fix to this job. I think a better solution is to pass `--extra-access-tokens` flag into nix commands that may interact with github.
Not sure how to test.
the

[cicd] Fix github rate limit issue

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json

[extension] updated readme to remove devbox.sh's open in Desktop

---

examples/databases/mariadb/devbox.json
examples/databases/mysql/devbox.d/mysql/my.cnf
examples/databases/mysql/devbox.d/mysql80/my.cnf
examples/databases/mysql/devbox.d/mysql84/my.cnf
examples/databases/mysql/devbox.json
examples/databases/mysql/devbox.lock
examples/databases/mysql/my.cnf
plugins/builtins.go
plugins/mariadb/process-compose.yaml
plugins/mysql/flake.nix
plugins/mysql/setup_db.sh

Fix some socket paths and settings that were causing issues
Use the MariaDB binaries to avoid a deprecation warning
Tested and added support for MySQL84
Localhost
the

Update MariaDB + MySQL Plugins

---

.github/workflows/cli-tests.yaml
examples/databases/postgres/devbox.lock
examples/stacks/django/devbox.lock
examples/stacks/lapp-stack/devbox.lock
examples/stacks/lepp-stack/devbox.lock
nix/install.go

Determinate Systems recently announced plans to drop upstream Nix support from their Installer. Since we would prefer to have our default installer stay on the main open-source Nix, we're switching the install script in `devbox setup nix` to use the official experimental installer.
the

change builtin installer to upstream nix experimental

---

internal/boxcli/integrate.go

Removing the HOME variable has adverse effects on many tools, most notable git. Without it, tools can't find the configurations.
- Overrode the derivation and applied the patch
- Restarted VSCode
- Triggered the "Reopen in devbox shell" action
- `echo $HOME` in the shell
- Make this commit with the opened VSCode
the

fix(vscode): Keep  HOME variable when starting VSCode

---

.github/workflows/cache-upload.yml
docs/app/docs/continuous_integration/github_action.md

bump devbox-install-action to v0.14.0
