boxcli/shell.go

Don't print an error message or the usage help when `devbox shell` exits with a non-zero code. We still want to propagate the shell's exit code in order to support scripts.
Before:
$ devbox shell
Installing nix packages. This may take a while...
$ exit 1
Usage:
devbox shell [<dir>] [flags]
Flags:
-h, --help   help for shell
After:
$ devbox shell
Installing nix packages. This may take a while...
$ exit 1
$ echo $?
1
- Running `devbox shell` and exiting 1 to check there's no error output.
- Removing nix from my PATH and running `devbox shell` to check I still see an error.

boxcli: don't print help w/ shell non-zero exit code

---

.goreleaser.yaml

Adds a Discord Announcement to Goreleaser, that will target our Releaser channel
Signed-off-by: John Lago <750845+Lagoja@users.noreply.github.com>

Add Discord Announce to Goreleaser

---

.github/workflows/release.yml
boxcli/add.go
boxcli/build.go
boxcli/init.go
boxcli/plan.go
boxcli/rm.go
boxcli/root.go
boxcli/shell.go
boxcli/version.go
config.go
devbox.go
generate.go
planner/empty_planner.go
planner/go_planner.go
planner/plan.go
planner/plan_test.go
planner/planner.go
planner/python_planner.go
tmpl/Dockerfile.tmpl

Allow for custom install/build/start commands by customizing them in `devbox.json`. This makes it possible for users to build docker images in the cases when they need to do some customization, or when we have not yet written a language planner for that language.
Built, and ran `devbox plan` and `devbox generate` against a few examples.

[devbox] Allow for custom install/build/start commands

---

tmpl/Dockerfile.tmpl

Check that each stage is set in the plan before attempting to use its command. This fixes a nil pointer error that occurs when using an empty devbox.json in an unsupported language.
Ran `devbox plan` in a Go project with an empty `devbox.json`.

tmpl: fix nil pointer error in Dockerfile.tmpl

---

go.mod
go.sum
planner/go_planner.go

Add version detection to the go planner based on the contents of `go.mod`. When we don't have a corresponding package in `nixpkgs` we default to `1.19`
Compiled and ran against local project.

[devbox] Add version detection to the go planner

---

.golangci.yml
nix/nix.go
shell/shell.go
tmpl/shell.nix.tmpl

This fixes an issue where the user's rc (~/.bashrc, ~/.zshrc, etc.) files were prepending to the devbox shell PATH. This can cause the shell to unexpectedly run the non-devbox version of programs. It's especially noticeable with some version managers that point the PATH at their shims so they can control which version of a program is run.
The basic steps that result in this issue are:
1. Devbox launches Nix, which sets the PATH to point to the Nix store.
2. From within Nix, we launch the user's default shell.
3. The shell runs the user's init files and stomps on the Nix PATH.
Fixing this is a little tricky because there's no straightforward way to run additional commands _after_ the shell runs the init files. Instead, we need to copy the user's init files and append to them. Doing this …

shell,nix: fix shell PATH to prefer nix packages

---

boxcli/build.go
docker/docker.go

As requested in https://github.com/jetpack-io/devbox/issues/18 this PR adds support for podman via a new `--engine` flag.

Add support for podman

---

devbox.go
generate.go

Do not generate dockerfile on shell command, as someone who is using the shell command may not need to use language detector, or need to fill in `install`, `build` and `start` command if the language planner is absent.
devbox shell
devbox generate
devbox build

Do not generate dockerfile on shell command

---

.github/workflows/release.yml

We updated the release process to automatically announce on Discord, but we forgot to pass those secrets as environment variables. As a result, the release process fails and I'm unable to release version `0.0.4`. This PR fixes that.
I'll test by trying to release again.

Add discord env variables to release job

---

README.md

The tests workflow only runs on PRs, so we were showing the status of whichever PR was built last. Use the release workflow instead, which only runs on main and includes the test workflow.
N/A

Fix README status badge

---

generate.go

Generate runtime.nix. After a bad merge, this file was no longer being generated, but it's required by my runtime dependencies change.
Built locally and ran devbox build against a clean example.

Generate runtime.nix

---

cuecfg/cuecfg.go
cuecfg/cuecfg_test.go
cuecfg/toml.go

We need this to parse Cargo.toml files.
I chose this  library: [github.com/pelletier/go-toml](https://github.com/pelletier/go-toml). 
- The alternative is https://github.com/BurntSushi/toml. This one has more github stars than `go-toml`.
- `go-toml`'s interface is more similar to `encoding/json`, and is also used by `viper`.
Also, changed `v` to `value` in `cuecfg.go` to address linter complaint.
`go test ./cuecfg/...`

[cuecfg] add toml support

---

.github/workflows/tests.yaml
.golangci.yml
boxcli/shell_test.go
shell/shell.go

Add tests that check that `devbox shell` launches successfully on the platforms (Linux and macOS) and shells (bash, dash, and zsh) that we support. Specifically, each test runs the equivalent of typing the following into your terminal:
cd `mktemp -d`
devbox init
devbox add hello
devbox shell
hello
exit
exit
The bulk of this change is the addition of some test helpers that handle launching shells and interacting with them. For now they live in the same file as the `boxcli` shell tests, but we can move them into their own `shelltest` package later on if necessary. With these test helpers in place, it should be a lot easier to add tests for more complicated scenarios.
In order to run these tests in CI, the GitHub test jobs now install Nix along with some additional shells. They also run on …

boxcli: add basic tests for devbox shell

---

planner/languages/javascript/nodejs_planner.go
testdata/nodejs/nodejs-npm/package.json
testdata/nodejs/nodejs-npm/plan.json

Quick fix nodejs npm build step, as the command is different between npm and yarn. This needs to go in before the next release.
go test ./...

[Bug] Fix nodejs npm build step

---

cuecfg/cuecfg.go
cuecfg/json.go
cuecfg/toml.go
cuecfg/yaml.go

These should be private for this package. External callers should invoke
`cuecfg.Marshal` and `cuecfg.Unmarshal`
compiles

[easy] make yaml, json, toml specific functions be private in cuecfg

---

boxcli/plan.go
devbox.go
devbox_test.go
planner/languages/golang/golang_planner.go
planner/languages/javascript/nodejs_planner.go
planner/languages/php/php_planner.go
planner/languages/python/python_poetry_planner.go
planner/plansdk/plansdk.go
planner/plansdk/plansdk_test.go
testdata/python/poetry-no-entrypoint/plan.json
testdata/python/poetry-no-lock-file/plan.json

We have decided on the following merging logic between `devbox.json` and `planners`:
- devbox.json `packages` field will merge with planners `devPackages` and `runtimePackages`. Merge will be `appendWithSlice`.
- devbox.json `start_stage`, `build_stage` and `install_stage` subfields (shared plan):
- if empty, will inherit the corresponding planners fields
- if set, will override corresponding planners fields
TODO (Will follow up with separate PRs)
- devbox.json schema would be a separate one from the planner
go build -o devbox cmd/devbox/main.go
devbox plan

Change the merging logic of devbox.json and planners

---

tmpl/Dockerfile.tmpl

The recommended base image in https://nixos.org/download.html#nix-install-docker
is `nixos/nix:2.11.0`. Can we bump to this? Are there any (hidden) dependencies
with some other pieces (like pinned nix packages version?)?
sanity test:
```
> cd testdata/go/go-1.19
> devbox build
> docker run devbox
```

bump the dockerfile base image to nixos/nix:2.11.0

---

.github/workflows/tests.yaml

I think this got removed by accident? We were only running boxcli tests instead of all tests.
btw, linting darwin is probably overkill (the tests themselves will confirm everything compiles, I guess we could do `go build -v ./...` but since it's pretty fast, it's not a big deal)
GHA

[CICD] Run tests in parallel, ensure we run all tests

---

.github/workflows/release.yml
.goreleaser.yaml

+ Disable automatic Discord announcement. It's not working great right now, and I'd rather turn it off until we improve it.
+ Clean up "prerelease" terminology in Github Action.
Via this PR

Tweaks to release process

---

devbox.go
devbox_test.go
examples/php/composer.json
examples/php/composer.lock
planner/languages/php/php_planner.go
planner/planner.go
planner/plansdk/plansdk.go
planner/plansdk/plansdk_test.go
testdata/php/php8.1/composer.json
testdata/php/php8.1/plan.json
tmpl/development.nix.tmpl
tmpl/runtime.nix.tmpl
tmpl/shell.nix.tmpl

Use composer.json to figure out if any extensions should be installed. Also, improved version detection (using `require` instead of `config`)
@loreto should we be using `systemPackages` instead of packages for languages?
```
devbox shell
php -m | grep mbstring 
```

[PHP] Add extension support and better version detection

---

config.go
devbox.go
planner/languages/golang/golang_planner.go
planner/languages/javascript/nodejs_planner.go
planner/plansdk/plansdk.go
planner/plansdk/plansdk_test.go

This is a continuation of https://github.com/jetpack-io/devbox/pull/103. It hides the `inputFiles` fields in each stage and only expose the `command` field.
This PR 
- Get rid of `SharedPlan`
- Separate stage struct for devbox.json config
- Only expose `command` field in each stage
It does not include:
- Getters and setters
- immutability
go test ./...

Separate devbox config struct from planner struct

---

go.mod
go.sum
nix/shell.go
nix/shell_test.go
nix/shellrc.tmpl
nix/testdata/shellrc/basic/env
nix/testdata/shellrc/basic/hook
nix/testdata/shellrc/basic/shellrc
nix/testdata/shellrc/basic/shellrc.golden
nix/testdata/shellrc/nohook/env
nix/testdata/shellrc/nohook/shellrc
nix/testdata/shellrc/nohook/shellrc.golden
nix/testdata/shellrc/noshellrc/env
nix/testdata/shellrc/noshellrc/hook
nix/testdata/shellrc/noshellrc/shellrc.golden

At the end of the devbox shellrc file, we're setting:
export PATH="$PURE_NIX_PATH:$ORIGINAL_PATH"
This will overwrite anything that the user's shellrc might've added to PATH. Change ORIGINAL_PATH to PATH to preserve those changes. There's also no need for ORIGINAL_PATH to be an environment variable, so set it directly in the template instead.
To prevent regressions, some tests that generate a devbox shellrc file and compare it to an expected golden file. This ensures we don't unknowingly change the way the shellrc is generated.
If we do intentionally change the devbox shellrc, the tests can automatically update the golden files with -update:
go test ./nix -update
It's up to the author of the change to verify that any new shellrc files still work in a real shell.
`go test` and `devbox …

nix: allow user's shellrc to update PATH; add tests for shellrc template

---

planner/languages/php/php_planner.go
testdata/php/php8.1/plan.json

The extensions array was not stably sorted so the testcase would be flaky when comparing the `devbox plan` output with `plan.json` 
`go test -v`

[php planner] sort extensions for test stability

---

config.go
config_test.go
devbox.go

Add a `ConfigShellCmds` type that supports marshalling/unmarshalling shell commands from devbox.json as either a string or an array of strings. This makes writing multi-line shell hooks a bit easier.
Example:
{
"packages": [
"go"
],
"shell": {
"init_hook": [
"echo 'line 1'",
"echo 'line 2'"
]
}
}
The original format is preserved so that if the hook is a string, it will marshal back to a string. Converting from a string to an array results in an array where the only element is the original string.
Unit tests and manually creating shell hooks in both formats.

devbox: allow shell.init_hook to be a JSON array

---

devbox_test.go
planner/languages/rust/rust_planner.go
testdata/rust/rust-1.62.0/devbox.json
testdata/rust/rust-1.62.0/plan.json
testdata/rust/rust-stable-hello-world/plan.json
testdata/rust/rust-stable/devbox.json
testdata/rust/rust-stable/plan.json

Reduce image size by
1. Replace `gcc` with `glibc` in the Runtime image. 
- `gcc` is needed in the DevPackages for the Build Stage. Replacing it with `glibc` doesn't work because `glibc` nix pkg is not available on mac OS (linux only). We want universal packages (defined as linux and mac, lol) since we share DevPackages with `devbox shell`.
2. Copy just the specific built binary to the Runtime image.
Using the basic `testdata/rust/rust-stable-hello-world` project:
- before, size of image = 320MB
- after, size of image = 64MB

[RFC][Rust Planner] Reduce image size by using glibc, and copying built binary

---

docker/docker.go

Not 100% why `BUILDKIT=1` worked locally, but not in CICD. 
Looking at all the documentations, it seems everywhere it uses `DOCKER_BUILDKIT`, hence the change.
Reference: https://docs.docker.com/develop/develop-images/build_enhancements/
devbox build

[bug] Change BUILDKIT to DOCKER_BUILDKIT

---

boxcli/add.go
boxcli/root.go
boxcli/shell.go

Change nix-shell requirements to only add and shell command. `devbox build` on CICD should not require Nix dependency
`devbox shell`
`devbox add`
`devbox build`

Change nix-shell requirements to only add and shell command

---

boxcli/build.go
devbox.go

Allow setting name and tag in devbox build
Example: 
```
devbox build --name devbox-test --tags latest
```
`devbox build`

Allow setting name and tag in devbox build

---

planner/languages/java/java_planner.go
planner/plansdk/plansdk.go
testdata/java/openjdk-11/plan.json
testdata/java/openjdk-17/plan.json
testdata/java/openjdk-8/plan.json
testdata/java/openjdk-default/plan.json

- Added custom JRE for runtime instead of installing JDK + maven
- Updated testdata plan
- Added build command to java planner
- devbox plan
- devbox build
- docker run devbox
- run `docker images | grep devbox` to check image size
see screenshot:

[Java planner] part3 reducing docker image size

---

planner/languages/rust/rust_planner.go
testdata/rust/rust-1.62.0/plan.json
testdata/rust/rust-stable-hello-world/plan.json
testdata/rust/rust-stable/plan.json

We can use the InstallStage as intended: leverage Docker layers to ensure incremental
builds are faster, when no crates (rust dependencies) change.
in `testdata/rust/rust-stable`:
```
> devbox build
> docker run devbox
```

[RustPlanner] use InstallStage

---

.github/workflows/tests.yaml
boxcli/shell_test.go

This is a workaround for some test runs that are failing due to how long it takes to install Nix packages. We need to figure out how to cache these instead.
CI

boxcli: increase shell test timeout to 3 mins

---

.github/workflows/debug.yaml

This workflow prints some diagnostic information and then starts a tmate session for debugging. It can only be triggered manually.
N/A

ci: add debug workflow

---

planner/languages/zig/zig_planner.go
planner/plansdk/analyzer.go
testdata/zig/README.md
testdata/zig/zig-hello-world/.gitignore
testdata/zig/zig-hello-world/build.zig
testdata/zig/zig-hello-world/devbox.json
testdata/zig/zig-hello-world/plan.json
testdata/zig/zig-hello-world/src/main.zig

Adds basic support for shell and build.
Build Size optimization:
- If I include the `zig` nix package in the runtimePackages, then the image size 
is really large (700MB)
- But I believe the zig executable is standalone https://github.com/ziglang/zig/issues/3660#issuecomment-552610783
- So, I get the zig-executable's name by:
- parsing the `build.zig` file (so unfortunate) to find the `addExecutable` line
- fallback: if I fail to find exactly one `addExecutable`, then I fallback to installing the `zig` nix package and invoking `zig build run`
- the image size is 22MB 
shell:
in the testcase folder:
```
> devbox shell
(devbox)> zig build run
info: All your codebase are belong to us.
```
Don't be alarmed! Just a printout.
build:
```
> devbox build
> docker run devbox
info: All your codebase …
```

[ZigPlanner] Add support for shell and build

---

.github/workflows/deployment.yaml
.github/workflows/previews.yaml
docs/.markdownlint.yaml
docs/README.md
docs/app/devbox.json
docs/app/docs/configuration.md
docs/app/docs/installing_devbox.md
docs/app/docs/language_support/nginx.md
docs/app/docs/language_support/nodejs.md
docs/app/docs/language_support/php.md
docs/app/docs/quickstart.md

Add docs markdown linter and readme
CICD + preview

Add docs markdown linter and readme

---

boxcli/shell.go
devbox.go
nix/nix.go

Simple implementation of `devbox shell -- <cmd>`. I struggled integrating this with all the other stuff that is happening with `devbox shell`. Would like thoughts on whether this is a good enough for an MVP of the feature, and later we improve it, or whether we think integrating with the other `devbox shell` logic is a must have.
Ran a few commands with `devbox shell --`

devbox shell -- cmd

---

devbox.go

Fix devbox exec. I think it is a merge failure
```
go build -o devbox cmd/devbox/main.go
devbox build
docker run -p 3000:3000 --expose 3000 -ti devbox
```

[bug] Fix devbox exec

---

boxcli/plan.go
testdata/python/poetry-with-custom-dir-structure/plan.json
testdata/python/poetry-with-main/plan.json
testdata/python/poetry-with-scripts/plan.json

In our `plan.json` that we generate the ampersand gets escaped. This happens
because golang does html escaping by default in its json/encoding. Hard for it to
escape its  web roots, I guess.
Anyway, there's no reason ampersands cannot exist in jsons, so we can turn off this escaping.
tests pass, so current testdata plan.json all work.
made this edit to a zig testdatum:
```➜ git diff
diff --git a/testdata/zig/zig-hello-world/devbox.json b/testdata/zig/zig-hello-world/devbox.json
index 3352a1b..498559e 100644
--- a/testdata/zig/zig-hello-world/devbox.json
+++ b/testdata/zig/zig-hello-world/devbox.json
@@ -2,5 +2,8 @@
"packages": [],
"shell": {
"init_hook": null
-  }
-}
\ No newline at end of file
+  },
+  "start_stage": {
+     "command": "./zig-hello-world && echo \"used ampersand\""
+   } …
```

[plan] do not html-escape json encoding

---

boxcli/shell.go

fixes parsing of the path/to/devbox/json and the command to be invoked
```
> cd testdata/zig/
> devbox shell zig-hello-world 
> devbox shell zig-hello-world -- zig help
> devbox shell -- zig help
```

[devbox shell] fix parsing of cmd and path

---

nix/shellrc.tmpl
nix/testdata/shellrc/basic/shellrc.golden
nix/testdata/shellrc/nohook/shellrc.golden
nix/testdata/shellrc/noshellrc/shellrc.golden

Fix the loop in `shellrc.tmpl` so that `devbox shell` doesn't end up with a broken `PATH` delimited by spaces instead of colons. This was due to a subtle bug related to how bash and zsh do word splitting differently. Read on for an in-depth explanation.
We fix up the `PATH` in `shellrc.tmpl` by looping over each `PATH` directory. To get each dir, we set `IFS=:` and rely on the shell's word splitting to loop over `PATH`. A caveat to this approach is that zsh doesn't follow the POSIX behavior for word splitting. Here's an example showing the difference:
bash:
bash$ export x=a:b:c
bash$ export IFS=:
bash$ echo $x
a b c
zsh:
zsh$ export x=a:b:c
zsh$ export IFS=:
zsh$ echo $x
a:b:c
To workaround this, we use command substitution to force zsh to word split:
zsh$ export x=a:b:c
zsh$ export IFS=: …

nix: fix shellrc PATH word splitting in bash

---

.github/workflows/debug.yaml
.github/workflows/tests.yaml
go.mod

Update the debug workflow to echo a message with some basic info on how to use tmate. Also rename the job to `debug`, put the timeout at the job level, and set a Homebrew GitHub token to help with rate limiting (as described below).
The changes in the second commit fix some of the rate limit issues in testa and clean up the job:
- Set HOMEBREW_GITHUB_API_TOKEN to tell Homebrew to use our CI token to authenticate with the GitHub API. This drastically increases the rate limit.
- Combine the two test jobs into a single matrix job. When installing additional shells, just look at the RUNNER_OS env var to decide whether to use apt or brew.
- Install Nix with a single build user to speed up the install time.
- Source Nix and set the relevant env vars in the install step so we don't forget to do …

ci: debug workflow, rate limit fixes, cleanup

---

planner/plansdk/plansdk.go
testdata/zig/zig-hello-world/plan.json

I'm adding omitempty to Plan.Definitions.
I'm not adding it to Plan.DevPackages and Plan.RuntimePackages. Because it explains to a reader that these are empty. These fields are so core and commonly used that I think we want to make an exception for them.
compiles

[plan] Plan.Definitions add omitempty

---

nix/shell.go
tmpl/shell.nix.tmpl

When `NIX_SSL_CERT_FILE` and `SSL_CERT_FILE` aren't explicitly set, `nix-shell --pure` sets them to invalid paths
(specifically "/no-cert-file.crt") to ensure that openssl doesn't use certificates that live outside of the current Nix environment. This causes HTTPS requests in most programs to fail. For example:
(devbox) $ curl https://google.com
curl: (77) error setting certificate verify locations:  CAfile: /no-cert-file.crt CApath: none
This is pretty inconvenient for development, so we want to undo those changes when launching a devbox shell. To do that, we:
1. Keep any `NIX_SSL_CERT_FILE` and `SSL_CERT_FILE` values that are set in the parent shell.
2. Unset `NIX_SSL_CERT_FILE` or `SSL_CERT_FILE` when they're set to the "/no-cert-file.crt" value set by `nix-shell`. This causes openssl …

nix: carry over (NIX_)SSL_CERT_FILE to devbox shells

---

devbox.go

The old message was not very nice.
```
> devbox shell empty-projects/no-devbox-json
Error: open /Users/savil/code/jetpack/devbox/testdata/empty-projects/no-devbox-json/devbox.json: no such file or directory
```
or
```
> devbox shell
Error: open devbox.json: no such file or directory
````
inside the project directory:
```
➜ devbox shell
Error: No devbox.json found in this directory. Did you run `devbox init` yet?
```
when using a path, print the relative dir:
```
➜ devbox shell empty-projects/no-devbox-json
Error: No devbox.json found in empty-projects/no-devbox-json. Did you run `devbox init` yet?
```

[polish] improve error message for missing devbox-json

---

docs/app/docs/language_support/csharp.md
docs/app/docs/language_support/go.md
docs/app/docs/language_support/haskell.md
docs/app/docs/language_support/java.md
docs/app/docs/language_support/nginx.md
docs/app/docs/language_support/nodejs.md
docs/app/docs/language_support/php.md
docs/app/docs/language_support/python.md
docs/app/docs/language_support/rust.md
docs/app/docs/language_support/zig.md
docs/app/sidebars.js

- Added Haskell and Zig planners.
- Added a period after "See the Configuration Guide for more details" in all the planner docs.
in `docs/app`:
```
yarn install
yarn start
```
inspected changes in `localhost:3000/devbox`

[Docs] Haskell and Zig Planners

---

docs/app/docs/language_support/ruby.md
docs/app/sidebars.js

Add docs for Ruby

---

devbox.go
planner/languages/golang/golang_planner.go
planner/plansdk/plansdk.go
planner/plansdk/plansdk_test.go
planner/plansdk/stage.go

Golang planner return error when main is not found. It looks for `main()` and if not found, print the following error as warnings:
```
Error: Cannot find main() file in the directory. If you wish to specify a different import path, add `build_stage` in your devbox.json
```
Warnings will only get printed out if the stage is not overridden by devbox.json.
related to https://github.com/jetpack-io/devbox/issues/137
devbox build

[planner] Golang planner return error when main.go is not found

---

boxcli/shell.go

Silence error on shell exit. This addresses https://github.com/jetpack-io/devbox/issues/159
devbox shell

[Bug] Do not propagate error on explicit shell exit

---

devbox.go
devbox_test.go

**Motivation**
Previously, a user would need to specify the directory of the devbox.json when
invoking `devbox shell` or `devbox build` and similar commands. In the absence,
of an explicit directory argument, we would assume the user is saying that
the devbox.json file is in the current directory.
This PR changes this to look for the devbox.json file in the specified-directory, or current directory if none specified,
AND any parent directory. 
This is desirable for a few reasons:
1. Convenience: it is nice especially for mono-repos to be located in a sub-directory
and be able to invoke `devbox shell` or `devbox build`, in a manner similar to
how `git` works.
2. Enable `devbox add` and `devbox rm` to run from any sub-directory. These commands
currently _require_ the user to be located in …

[config] look for the devbox.json file in parent directories as well

---

boxcli/add.go
boxcli/build.go
boxcli/generate.go
boxcli/plan.go
boxcli/rm.go
boxcli/shell.go
devbox.go
devbox_test.go
generate.go
nix/shell.go
nix/shell_test.go
nix/shellrc.tmpl
nix/testdata/shellrc/basic/shellrc.golden
nix/testdata/shellrc/nohook/shellrc.golden
nix/testdata/shellrc/noshellrc/shellrc.golden
testdata/rust/rust-stable/.gitignore
testdata/rust/rust-stable/devbox.json
tmpl/development.nix.tmpl
tmpl/shell.nix.tmpl

**Motivation:**
We can define a custom nix-profile, and install packages scoped to this profile.
The goal is to make it easier to add packages when within devbox shell. Currently,
users need to exit the shell and restart it for the nix package to be installed - clearly
not ideal. With a nix-profile, if we install the package using that profile, then the
package's binary should be downloaded and visible within the shell.
Within `devbox shell`:
- previously, we would manually add the path to each package to `PATH`.
- now, we can add the path to the nix-profile to `PATH` and skip manually adding each package.
**Limitations:**
1. For `devbox add` within a `devbox shell`, the user needs to manually execute `hash -r` to ensure the latest binaries are visible. 
2. ~For `devbox rm` within a …

[shell] add packages within shell, leveraging nix-profile

---

boxcli/shell_test.go

The shell tests are taking even longer now, presumably due to how long it takes to install the Nix packages. Skip them in CI until we can figure out a way to make them run faster and more reliably.
CI.

boxcli: skip shell tests due to timeout

---

devbox.go
nix/shell.go
nix/shellrc.tmpl

This PR aims to preserve shell command history across sessions, where sessions is defined as starting and exiting a `devbox shell`.
- started a `devbox shell`
- invoked `go version` and `which go` and `exit`
- restarted the `devbox shell`
- used up arrow key to get the previous commands used.

[shell] preserve history

---

devbox.go

Unblock shell when build fails. We are seeing
```
Error: Multiple buildable plans found: [{...}]
```
on `devbox shell`
devbox shell

[Bug] Unblock shell when build fails

---

testdata/python/pipenv/devbox.json
tmpl/shell.nix.tmpl

Fixes #216
Fixes issue where python can't find modules installed as nix packages. 
testdata/python/pipenv
`devbox shell`
`python -m pipenv`

[Fix] Ensure python sys path contains nix installed modules 

---

generate.go
tmpl/.gitignore.tmpl

With the recent use of nix-profile, the `profile` symlinks are showing up in git history.
This is regrettable.
This PR adds a `.gitignore` file to `.devbox` directory and ignoring the `gen/`, `profile*`
, `nix-profile` and `shell-history` symlinks.
Going forward, we should avoid editing this file. Each edit will need to be checked
in by our users. So, this PR is a breaking change, in a sense.
New features we add that generate files in `.devbox` should be added inside `gen/` 
if they want to be gitignored.
New features that we do want users to check in (like a lock file) can be placed
in `.devbox/` (and not `.devbox/gen`).
in a new devbox project, with `git init` and initial files already committed:
- did `devbox shell` to generate the gitignore and other files 
- did `git status` to …

[RFC] move gitignore file to .devbox directory and ignore gen/profile/shell_history

---

devbox.go

To avoid the nix-profile symlinks crowding the `.devbox/` directory, I push them
inside a `.devbox/nix/profile/` sub-directory. The symlink is renamed to `default` inside `.devbox/nix/profile` to be consistent with [nix naming](https://nixos.org/manual/nix/stable/package-management/profiles.html).
I also want to rename `profileDir` to `profilePath`. That is more accurate since 
it is not a directory but a symlink. However, will do in a separate PR since
it has some conflicts with concurrent work like #207.
```
> cd testdata/rust/rust-stable
> devbox shell
> which rustc
> devbox add openssl
> hash -r
> which openssl
> ls -al /Users/savil/code/jetpack/devbox/testdata/rust/rust-stable/.devbox/nix/profile/
total 0
drwxr-xr-x 5 savil staff 160 Oct  6 11:55 .
drwxr-xr-x 3 savil staff  96 Oct  6 …
```

[shell] move nix-profile into a specific directory inside .devbox directory

---

testdata/python/pipenv/plan.json

Fixes this test by making the python pip planner run for it.
did:
```
touch setup.py
touch requirements.txt
```
Needed this because `devbox_test` requires buildable plans.
NOTE: I had to manually edit the generated `plan.json` to get rid of the absolute paths.
Lets discuss if the planner needs to use these absolute paths, or if relative paths suffice.
`go test ./...`

fix pipenv test

---

nix/shell.go
nix/shell_test.go

When launching a devbox shell, we filter out any Nix user profiles from the PATH (i.e., ~/.nix-profile). This fixes a couple of bugs with how we determine if a PATH directory matches a Nix profile:
1. The `strings.HasPrefix("/Users", profileDir)` call is backwards.
2. Checking for `/Users` is macOS-specific and won't work on Linux. Instead, check if the directory starts with `/nix` to determine if it's the default system profile.
Added a test.

nix: fix removing user Nix profiles from PATH

---

boxcli/plan.go
devbox.go
devbox.json
devbox_test.go

Turn off auto-detection for language on devbox shell. This means:
1. `devbox plan` outputs plan for build only
2. `devbox shell` does not automatically add packages based on the project
3. `devbox shell` no longer automatically sets init hooks (python can potentially be the biggest one being affected by this change, but as far as I know, it wasn't being used before) 
I also added a `devbox.json` to the root of this project, because I need go 1.19 and I have go 1.18 on my personal machine.
devbox shell
devbox build
go test ./...

Turn off auto-detection for language on devbox shell

---

tmpl/development.nix.tmpl

Certain packages like mariaDB require access to the lib and share directories, so
we include those in `development.nix`. 
Recall that `development.nix` is used during `devbox shell` for:
`nix-env --profile .devbox/nix/profile/default --install -f path/to/development.nix`
```
> cd testdata/nodejs/nodejs-18
> rm -rf .devbox
> readlink -f .devbox/nix/profile/default/*
/nix/store/pnwba30msbx2dwld1ji3ak25f96pd9im-devbox-development/bin
/nix/store/pnwba30msbx2dwld1ji3ak25f96pd9im-devbox-development/lib
/nix/store/d1785s25kbb67l717srvnmf44a41dqk3-env-manifest.nix
/nix/store/pnwba30msbx2dwld1ji3ak25f96pd9im-devbox-development/share
```

[shell] add /share and /lib to development.nix

---

docs/app/docs/ide_configuration/direnv.md
docs/app/docs/ide_configuration/eclipse.md
docs/app/docs/ide_configuration/vscode.md
docs/app/sidebars.js

IDE Section of the docs were not visible because they were not added to sidebar.js. This should fix this on the next deploy
localhost

Make IDE docs visible via sidebar.js

---

devbox.go
go.mod
go.sum

Previously, devbox would indicate that an uninstall happened even if a package wasn't part of the `devbox.json` packages. This isn't great, especially if a user made an inadvertent typo.
This PR prints a warning for such a scenario.
It also changes logic to print the confirmation messages outside `devbox shell`.
```
> cd testdata/rust/rust-stable
> devbox shell
(devbox)> devbox add go_1_18 nodejs
(devbox)> devbox rm php
Warning: the following packages were not found in your devbox.json: php
Uninstalling nix packages. This may take a while...done.
No packages removed.
(devbox) > devbox rm php rummy nodejs
Warning: the following packages were not found in your devbox.json: php, rummy
Uninstalling nix packages. This may take a while...done.
nodejs is now removed. Run `hash -r` to ensure your …
```

[shell] warn when removing non-existent package

---

boxcli/add.go
boxcli/args.go
boxcli/build.go
boxcli/config.go
boxcli/generate.go
boxcli/init.go
boxcli/plan.go
boxcli/rm.go
boxcli/root.go
boxcli/shell.go
boxcli/version.go
config.go
config_test.go
devbox.go
testdata/nodejs/nodejs-18/devbox.json

**Motivation**
We want to introduce a `--config` flag and deprecate the use of config as an argument.
1. **ephemeral shells**. By enabling a way to (eventually) do `devbox shell --config path/to/devbox/json  nodejs-18_x`, or even more simply `devbox shell nodejs-18_x`.
2. **using devbox add/rm from shells started in parent directories**: today, if I have `my_sub_directory/devbox.json` and start `devbox shell my_sub_directory/devbox.json` from the root of the repository, then doing `devbox add` or `devbox rm` inside this shell will fail. 
- A first attempt at fixing this was in #206. This PR (#225) is a generalization of that idea. I'll be stacking #206 on top of this PR, and enabling the `--config` flag to override the env-var.
<insert motivation>
**preliminary steps**
- i added …

[CLI] add --config flag

---

planner/languages/rust/rust_planner.go
testdata/rust/rust-1.62.0/.gitignore
testdata/rust/rust-1.62.0/build_plan.json
testdata/rust/rust-1.62.0/devbox.json
testdata/rust/rust-1.62.0/init-shell.sh
testdata/rust/rust-1.62.0/shell_plan.json
testdata/rust/rust-stable-hello-world/.gitignore
testdata/rust/rust-stable-hello-world/build_plan.json
testdata/rust/rust-stable-hello-world/devbox.json
testdata/rust/rust-stable-hello-world/shell_plan.json
testdata/rust/rust-stable/.gitignore
testdata/rust/rust-stable/build_plan.json
testdata/rust/rust-stable/devbox.json
testdata/rust/rust-stable/init-shell.sh
testdata/rust/rust-stable/shell_plan.json

In furtherance of our efforts to remove "magic" and simplify the plans, this PR
removes the NixOverlay from the Rust Planner.
We replace it with the `rustup` toolchain. This should work, although the
performance for `devbox build` is bad, and the image is bloated now.
The `devbox shell` experience is good. I'll add an example in `devbox-example`
repo for others to reference to add the shell init hooks.
did `devbox shell` and `devbox build && docker run devbox` in the rust folders

[Rust Shell] change to use rustup nix package to avoid overlay

---

README.md

Updated the logo that's used in Readme from 📦 to devbox's logo.
The markdown source shows 2 logos one for light mode and one for dark mode. Github handles which one to show based on user's settings.
Change light mode & dark mode in macos settings > General > Appearance while having this branch open on your browser.

Readme logo update

---

nix/nix.go
nix/nix_test.go

nix-env returns an empty JSON object instead of an error for some missing packages. This leads to a panic because we check that unmarshalled nix-env JSON output only has 1 entry. Remove that check since it seems unnecessary.
Added a test that looks for the "rust" package, which triggers this panic for some reason.

nix: fix PkgExists panic for some missing packages

---

boxcli/featureflag/feature.go
boxcli/featureflag/feature_test.go
boxcli/featureflag/pkgconfig.go

Add very simple feature flag package that uses hard coded boolean to switch on and off. Can be overridden on by setting environment variable. 
unit tests

[feature-flag] Add simple feature flag package

---

boxcli/featureflag/nixpkgversion.go
config.go
devbox.go

We add `nixpkgs.version` to `devbox.json` if it is missing.
```
> cd testdata/rust/rust-stable
> DEVBOX_DEBUG=1 devbox shell
> git diff devbox.json
> DEVBOX_FEATURE_NIXPKG_VERSION=1 DEVBOX_DEBUG=1 devbox shell
> git diff devbox.json
diff --git a/testdata/rust/rust-stable/devbox.json b/testdata/rust/rust-stable/devbox.json
index 89b7c0d..028385d 100644
--- a/testdata/rust/rust-stable/devbox.json
+++ b/testdata/rust/rust-stable/devbox.json
@@ -7,5 +7,8 @@
"init_hook": [
"source init-shell.sh"
]
+  },
+  "nixpkgs": {
+    "version": "af9e00071d0971eb292fd5abef334e66eda3cb69"
}
-}
+}
\ No newline at end of file
```

[nipkgs version] add feature flag and write to devbox.json if missing

---

boxcli/featureflag/feature.go
devbox.go
generate.go
nix/shell.go
pkgcfg/pkgcfg.go

Creates a new package that allows loading of local configs. This will allow for rapid testing and iteration of package configuration before we read them remotely. 
Created dummy go config and ran:
```
DEVBOX_FEATURE_PKG_CONFIG=1 DEVBOX_LOCAL_PKG_CONFIG=~/dev/devbox ./dist/devbox shell
echo $FOO
./.devbox/test-file.sh
```

[pkgcfg] Create new pkgckg that can load local config

---

config.go
config_test.go

Changing the field name inside `Config.Nixpkgs` from `version` to `commit`.
The motivation stems from the realization that even `YY.MM` stable channels of
nixpkgs have periodic updates (mostly for security), which means the commit-hash
tracked by the `nixos-stable` branch changes.
To simplify the product design for now, and to avoid introducing a lockfile, 
we change `version` to be the unambiguous `commit`. For users who would like
to track the nixpkgs commit from `search.nixos.org` webpage, they can refer
to `status.nixos.org` and use the commit for the nixpkgs channel they want.
`go test ./...` b/c added a testcase for the validation function.
```
> cd testdata/nodejs/nodejs-18
> DEVBOX_FEATURE_NIXPKG_VERSION=1 DEVBOX_DEBUG=0 devbox shell -- node --version
Installing nix packages. This …
```

[nixpkgs version] change field from version to commit; add validation

---

boxcli/plan.go
devbox.go
devbox_test.go
planner/plansdk/plansdk.go
testdata/nodejs/nodejs-18/devbox.json
testdata/rust/rust-stable/devbox.json
tmpl/development.nix.tmpl
tmpl/runtime.nix.tmpl
tmpl/shell.nix.tmpl

This PR will parameterize the `shell.nix`, `development.nix` and `runtime.nix` files
to accept a `NixpkgsInfo` struct comprising of `url` and `sha256` fields.
To pass the `NixPkgsInfo` struct to these templates, we need to add them to the `ShellPlan`
and `BuildPlan` structs. I don't like this, but it seemed the most straightforward
approach. 
with the hardcoded commit hash
```
➜ DEVBOX_FEATURE_NIXPKG_VERSION=1 DEVBOX_DEBUG=0 devbox shell -- node --version
Installing nix packages. This may take a while...done.
v18.7.0
```
From https://status.nixos.org, I got the most recent commit for the `nixos-22.05` channel:
`b3a8f7ed267e0a7ed100eb7d716c9137ff120fe3`. I set this in the devbox.json file.
```
> DEVBOX_FEATURE_NIXPKG_VERSION=1 DEVBOX_DEBUG=0 devbox shell -- node …
```

[nixpkgs version] generate nix files containing the nixpkgs version from config

---

config.go
config_test.go
devbox.go
planner/plansdk/plansdk.go

This PR updates `devbox init` to insert the default nixpkgs commit.
feature flag OFF:
```
devbox/testdata/nodejs/nodejs-18/fake-dir on  savil/nixpkgs-version-init [!] at ☸️  jetpack-cloud (savil-srivastava-jetpack-io)
➜ devbox init
devbox/testdata/nodejs/nodejs-18/fake-dir on  savil/nixpkgs-version-init [!?] at ☸️  jetpack-cloud (savil-srivastava-jetpack-io)
➜ cat devbox.json
{
"packages": [],
"shell": {
"init_hook": null
},
"nixpkgs": {}
}%
```
feature flag ON
```
devbox/testdata/nodejs/nodejs-18/fake-dir on  savil/nixpkgs-version-init [!] at ☸️  jetpack-cloud (savil-srivastava-jetpack-io)
➜ DEVBOX_FEATURE_NIXPKG_VERSION=1 devbox init
devbox/testdata/nodejs/nodejs-18/fake-dir on  savil/nixpkgs-version-init [!?] at ☸️  jetpack-cloud (savil-srivastava-jetpack-io)
➜ cat devbox.json
{ …
```

[nixpkgs version] devbox init should add default nixpkgs commit

---

devbox.go
nix/shell.go
nix/shellrc.tmpl
pkgcfg/package-configuration/dummy-config/echo.sh
pkgcfg/package-configuration/dummy-config/go_1_19.json
pkgcfg/pkgcfg.go

This PR does two things:
* Adds `.devbox/conf/bin` to path
* Creates sym links for any files in `.devbox/conf/[pkg]/bin`
Using dummy package config

[pkg-config] Add bin sym links and add to path

---

boxcli/featureflag/feature.go
boxcli/featureflag/nixpkgversion.go

1. The Feature Flag library should respect the value of the env-var, whether ON or OFF.
2. Turn on the default value of the nixpkgs version FF.
For change #1: respecting the env-var:
```
> DEVBOX_FEATURE_NIXPKG_VERSION=0 DEVBOX_DEBUG=1 devbox shell
> git status
```
For change #2: enabling the nixpkgs version
```
> devbox shell
> git status
```

[feature flag] respect env-var of feature flag (even if turned off) and default enable Nixpkg Version FF

---

pkgcfg/pkgcfg.go

Stacked on https://github.com/jetpack-io/devbox/pull/263
This is a quick (and inefficient) implementation that fetches configuration from github. We can improve by caching and fetching multiple files at once.
DEVBOX_FEATURE_PKG_CONFIG=1  ./dist/devbox shell

[pkg-config] Read config from github

---

README.md

Using the `#gh-light/dark-mode-only` fragments is deprecated and doesn't render correctly on other sites (like pkgs.go.dev).

Use <picture> for logo light/dark mode

---

vscode-extension/package.json
vscode-extension/src/devcontainer.ts
vscode-extension/src/extension.ts

This doesn't fully implement the behaviour we discussed. But it does update the python interpreter and go path for the user.
The dev container setup is also possible via command palette (cmd + shift + P) in vscode.
- Added settings to the extension
- Added auto generating dev container config files
- cleaned up the code for more readability
- Added devbox commands (`devbox init | add | shell | install`) to the extension
- Open vscode-extensions/ in vscode
- press Run+debug
- check the prompt for update settings from devbox extension
- press cmd+shift+p and type devbox > choose "Devbox: Generate Dev Containers config files"
- check the generated files in .devcontainer/

vscode extension settings + devcontainer setup + devbox commands

---

.github/workflows/previews.yaml

They can't be longer than 63 characters.

ci: truncate long k8s namespace names

---

devbox.json

So that we can run the linter locally and not only when pushing to Github.
```
golangci-lint version
golangci-lint run
```

Add golangci-lint to devbox.json

---

.github/workflows/tests.yaml
devbox.go

Before:
It shows you the error but _not_ where it happens!
After: shows you both:
CICD on this very PR.

golangci-lint offending line is displayed in error logs

---

vscode-extension/src/extension.ts

fixed running devbox commands from vscode command palette not running when terminal is closed.
- make sure no terminal session in open in vscode
- cmd+shift+p
- devbox add python39
- verify terminal opens and runs the devbox add command

Fixed terminal commands not running when closed

---

vscode-extension/README.md
vscode-extension/src/devcontainer.ts
vscode-extension/src/extension.ts

Based on feedback from @Lagoja I added the following fixes:
- terminal only pops in and shows for devbox run and shell
- autoshell to a terminal doesn't happen when the opened terminal is from running devbox run/shell from extension's command palette (example: preventing duplicate devbox shell bug)
- updated readme to include features for version 0.0.2
- running the extension in vscode

vscode extension terminal behavior fixes + readme update

---

.github/workflows/release-extension.yaml

changed how we reference vscode marketplace token
will have to be tested in github actions

referencing vscode token from env variable

---

.github/workflows/previews.yaml
.github/workflows/tests.yaml

The PR at #288 has pending workflows. However, the workflows are not running because
they are triggered by the `push` event, which doesn't get triggered for public forks.
This PR adds `pull_request_target` event for them.
It also adds `workflow_dispatch` for manually triggering the workflow.
not tested.

[github actions] add workflow_dispatch and pull_request_target events to previews and tests Actions

---

.github/workflows/previews.yaml
.github/workflows/tests.yaml

Reading more about pull_request_target, it looks like it may not be what we want. 
> Due to the dangers inherent to automatic processing of PRs, GitHub’s standard pull_requestworkflow trigger by default prevents write permissions and secrets access to the target repository. However, in some scenarios such access is needed to properly process the PR. To this end the pull_request_target workflow trigger was introduced.
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
I think we want pull_request type:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
not tested

[github actions] s/pull_request_target/pull_request for previews and tests Actions

---

.github/workflows/previews.yaml

Following #290 and #291, I enabled the doc-preview action to run on `pull_request` event.
I then made a test PR with my own forked repo (#292). The CICD run for that succeeded
for the `tests` workflow, but failed for the `doc-preview` workflow.
The reason for the failure is that `doc-preview` relies on `launchpad up` which
relies on the `JETPACK_SECRET_KEY` github secret. But `pull_request` workflows from external forked
repos lack access to github secrets (see security blog at https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
and so this failed.
I think for now we can turn off doc-preview for PRs from forked repos, and can manually run it
if needed.
no test

[github workflows] remove pull_request event from doc-preview Action

---

docs/app/docs/configuration.md

Fix Example: A Rust Devbox. This Example had some syntax errors in it.

Fix Example: A Rust Devbox

---

pkgcfg/package-configuration/postgresql.json

* postgres is actually pretty simple, does not require shim.
* running initdb will actually tell you how to start it (but uses logfile in root)
* readme text is not currently used
```
devbox add postgresql
devbox shell
initdb
pg_ctl start
pg_ctl stop
```

[pkgcfg] Add postgresql config

---

.github/workflows/release-extension.yaml

Title says it.
The fix was to use `vsce publish -p <token>` rather than `echo <token> vsce login` then `vsce publish`.
For some reason github actions didn't like the 2 step method. 
Manually ran the github action workflow and it published the extension.

Fixed github action workflow publishing vscode extension

---

planner/languages/golang/golang_planner.go

TSIA
`devbox shell` after doing `touch go.mod`. Output:
```
> ../devbox shell
We detected extra packages you may need. To install them, run `devbox add go_1_19`
```

[bug] Fix nil pointer dereference in go planner

---

devbox.go
nix/shell.go
nix/shell_test.go
nix/shellrc.tmpl
nix/testdata/shellrc/basic/shellrc.golden
nix/testdata/shellrc/noshellrc/shellrc.golden
testdata/rust/rust-stable/devbox.json

This shell init-hooks and scripts should be run relative to the `--config` directory.
Previously, they assumed `--config` was always the current-working-directory. 
This PR fixes this by doing some manual change-directory calls. Is there a more elegant way?
Test cases:
1. using `--config` dir and `devbox run`
```
> cd testdata/rust
> devbox run --config rust-stable cargo-run
```
2. using `--config` dir and `devbox shell`
```
> cd testdata/rust
> devbox shell --config rust-stable
(devbox) > cd rust-stable && cargo run
```
3. NOTE: this does NOT work because the implementation of `devbox shell -- <cmd>` 
doesn't share the core `devbox shell` implementation.
```
> cd testdata/rust
> devbox shell --config rust-stable -- cargo run
```
Control cases:
1. `devbox run`
```
> cd …
```

[config-directory] run shell.initHooks and shell.scripts relative to --config dir

---

devbox.go
devbox_test.go

This is more technically accurate since we set the erstwhile `srcDir` from the `--config` flag.
Or if the `--config` is not set, then we search in parent-directories for the `devbox.json`
and set it to that directory.
compiles

rename srcDir to configDir for clarity

---

README.md
docs/app/docs/installing_devbox.md

I think clarifying that `nix` is required, while `docker` is optional would be good.
will view the preview docs from CICD.

improve installing devbox docs

---

boxcli/info.go
boxcli/root.go
devbox.go
devbox.json
generate.go
nix/nix.go
pkgcfg/package-configuration/mariadb.json
pkgcfg/package-configuration/nginx.json
pkgcfg/package-configuration/postgresql*.json
pkgcfg/pkgcfg.go

This shows notes whenever a package configuration has a non-empty "readme" field. It also adds a new (hidden) command `devbox info <pkg>` that displays said info.
I also updated a few readme fields to make them look better.
`devbox add mariadb`
`devbox add nginx`
`devbox info mariadb`

[pkgcfg] Show readme when adding packages. Add info command

---

docs/app/docs/guides/pinning_packages.md

Link to https://status.nixos.org/ is malformed.
Signed-off-by: Marvin Boothby <boothb@posti.io>
Explicitly set all URLs in the document pinning_packages.md
Markdown Preview

Fix broken link in pinning_packages.md

---

devbox.go
nix/nix.go
nix/nix_test.go

Devbox was not respecting the `nixpkgs.commit` from `devbox.json` for some operations
like `devbox info` and `devbox add`.
This PR fixes this by changing the `PkgInfo` function to rely on the `nix search` 
command, which lets us query for the exact package when given a nixpkgs commit.
For now, we strictly fail if the exact match was not found.  In the future, we could
improve the error message to suggest some of the specific alternatives that `nix search`
can provide.
Alternatives include:
1. `nix-env --json --file https://github.com/nixos/nixpkgs/archive/af9e00071d0971eb292fd5abef334e66eda3cb69.tar.gz  -qa pulumi`, but this takes 13 seconds.
2. Using `nix-instantiate`, but this doesn't let us later suggest specific alternatives like `nix search` does.
```
nix-instantiate --eval --strict …
```

Respect nixpkgs commit in devbox add by using nix search

---

README.md
boxcli/root.go
docs/app/docs/index.md

Update slogan and docs. Some of the wording we had made sense when `devbox build` was a primary feature. Now that we're deprecating it we need to update some of the positioning and docs.
N/A

Update slogan and docs consistent with removing build

---

vscode-extension/src/devcontainer.ts

2 small changes:
1. added devbox extension to the remote vscode environment so that it's installed when user runs vscode in a devcontainer
2. fixed `nix` not being in PATH when installed in WSL
ran on my windows machine with WSL2

Small fixes for devcontainers in WSL

---

testdata/rust/rust-1.62.0/init-shell.sh
testdata/rust/rust-stable/init-shell.sh

Updating the init-scripts here so that they can work, when invoked 
1. locally from a sub-directory using the --config flag
2. over an ssh connection
For scenario 1.
```
> cd testdata/rust
> devbox shell --config rust-stable
```
For scenario 2.
the set up is more complicated.
1. set up containers as per https://github.com/jetpack-io/axiom/pull/2877 (sorry, this is closed source, but happy to explain)
2. did ssh to the vm container and had the devbox shell start

[devbox testdata] improve rust testdata's init script to work over ssh

---

devbox.go
pkgcfg/pkgcfg.go
pkgcfg/rm.go

Removes config and broken symlinks when a package is removed. We could also clean up configs as part of `ensurePackagesAreInstalled` (which makes it more reliable) but this requires a bit of refactoring I didn't want to do as part of this PR.
Small unrelated change: made `installMode` type an int using iota (which is a bit more inline with golang quasi-enum pattern)
Manual testing:
* Added nginx and mariadb. 
* Inspected conf directory
* Removed one by one
* Inspected conf directory at each step.

[pkgcfg] Remove config if package is removed

---

cloud/cloud.go

Point the CLI to the production gateway (`gateway.devbox.sh`) by default.
Note that this means that if you're working on the gateway, you'll need to re-compile the devbox binary to test against your development version. Let me know if you prefer I add an (internal) flag to select which gateway to talk to.
Didn't.

Point the cli to the production gateway

---

.github/workflows/cli-release.yml
.github/workflows/cli-tests.yaml
.github/workflows/docs-deploy-preview.yaml
.github/workflows/docs-deploy-prod.yaml
.github/workflows/vscode-ext-release.yaml

Rename CICD workflows to be more descriptive. I was getting confused with the meaning of each workflow based on the filename. Adopting a naming convention of `<artifact>-<workflow>` so that all the worflows related to the same artifact are next to each other (i.e. `cli` worfklows are together, `doc` workflows are together and so on) 
Can't test until I merge this PR

Rename CICD workflows to be more descriptive

---

boxcli/cloud.go
cloud/cloud.go
cloud/sshclient/sshclient.go

This PR updates the cloud client to call `ssh -t <server> "bash -l -c \"start_devbox_server.sh <project-name>\""`.
This informs the server about which project to start the `devbox shell` for.
setup:
```
fly machines run --port 22:2222/tcp -e SSH_USER=savil --name=savil-test --region=sjc .
```
ran:
```
DEVBOX_DEBUG=1 DEVBOX_VM=savil@0e286003ad5486.vm.devbox-vms.internal devbox cloud shell
```
and got a `devbox shell` and could see the project's files and execute it.

[cloud] client directly calls start_devbox_server.sh <project dir>

---

pkgcfg/package-configuration/apache/httpd.conf
pkgcfg/package-configuration/apacheHttpd.json
pkgcfg/package-configuration/php.json
pkgcfg/package-configuration/php/php-fpm
pkgcfg/package-configuration/php/php-fpm.conf

This makes php-fpm work pretty much out of the box. It creates an php-fpm config (deamonized). Adds default ports and always includes `ProxyPassMatch` in the apache config (because it should not break anything if even if not used)
```
devbox add php apacheHttpd
devbox shell
php-from
apachectl start -f $HTTPD_CONFDIR/httpd.conf
```

[pkgcfg] Ensure php-fpm works out of the box

---

boxcli/args.go
boxcli/midcobra/telemetry.go
devbox.go

Add packages info in telemetry to get better understanding.
Note that different command behaves differently:
- for devbox shell, run, and add command, path can be set via --config
- for devbox init. path is set via args
go build
devbox shell

Add packages info in telemetry to get better understanding

---

boxcli/run.go
devbox.go
nix/shell.go

Added support for running devbox run when inside a devbox shell
- Compile devbox
- `./devbox shell`
- `./devbox run <script_name>`
example output:
devbox.json
```json
{
"packages": [
"python38"
],
"shell": {
"init_hook": null,
"scripts": {
"test": [
"echo helloworldtest",
"ls -l"
]
}
},
"nixpkgs": {
"commit": "af9e00071d0971eb292fd5abef334e66eda3cb69"
}
}
```
output:
```sh
(devbox) ➜  sample1 ./devbox run test
helloworldtest
total 23700
-rwxr-xr-x 1 mohsenansari 21500226 Nov 30 18:41 devbox
-rw-r--r-- 1 mohsenansari      250 Nov 30 22:26 devbox.json
-rw-r--r-- 1 mohsenansari        0 Oct  5 18:27 requirements.txt
-rw-r--r-- 1 mohsenansari        0 Oct  5 18:26 setup.py
```

devbox run inside shell

---

config.go
examples/default_nixpkgs/devbox.json
planner/plansdk/plansdk.go

This PR updates the default nixpkgs commit to the most recent commit of nixos-22.11,
as taken from https://status.nixos.org
Added an example project, and verified that `devbox shell` for it works

[config] update default nixpkgs commit to most recent nixos-22.11

---

boxcli/add.go
boxcli/featureflag/nixinstaller.go
boxcli/info.go
boxcli/midcobra/debug.go
boxcli/run.go
boxcli/shell.go
boxcli/usererr/usererr.go
nix/install.go

This change makes devbox attempt to install nix if it is missing and the command the user ran requires it. It shows yellow text alerting the user before it starts (otherwise it is really jarring). One improvement could be to combine the sudo warning into the yellow text.
If the installation fails we show the error that caused it. If the installation succeeds we show a user warning which is yellow text. This warning is an error which causes the CLI execution to end. We need this because nix requires restarting the terminal. This is another area where having a pkg installer may be an improvement. 
cc: @Lagoja 
Ran `devbox add mariadb` without having nix installed. Got:
Pressing enter started the installation.
After installation we show:

[nix-installer] auto-install nix if we detect it's missing

---

cloud/openssh/sshconfig.tmpl
cloud/openssh/testdata/already-setup/in/.config/devbox/ssh/config
cloud/openssh/testdata/already-setup/out/.config/devbox/ssh/config
cloud/openssh/testdata/existing-config/out/.config/devbox/ssh/config
cloud/openssh/testdata/no-config/out/.config/devbox/ssh/config

The ssh session to my vm would auto-close with this output:
```
❯ time ssh savil@91859edc4e2783.vm.devbox-vms.internal
Welcome to Devbox Cloud!
(devbox) savil in 🌐 91859edc4e2783 in ~
❯ Connection to proxy.devbox.sh closed by remote host.
Connection to 91859edc4e2783.vm.devbox-vms.internal closed by remote host.
Connection to 91859edc4e2783.vm.devbox-vms.internal closed.
ssh savil@91859edc4e2783.vm.devbox-vms.internal  0.08s user 0.01s system 0% cpu 1:01.30 total
```
Setting this value in the config would result in the ssh connection staying active
for longer than a minute.
1. Set the config value, and could keep the connection alive.
2. As a sanity test, I removed the value and tried again: connection terminated at one minute again.

[cloud] set KeepAlive setting for ssh to vm

---

nix/install.go

A few small changes:
* No more sudo up-front. This breaks situations where user is already root but sudo is not available
* Default to `--daemon` (multi-user) install. This makes the macOS and linux installs the same
* pipe error to stdout. Helps debug issues
* Ran `devbox setup nix` on mac and ubuntu (via docker)

[nix] Improve nix installer

---

boxcli/root.go
boxcli/services.go
boxcli/shell.go
devbox.go
devbox.json
pkgcfg/info.go
pkgcfg/package-configuration/apacheHttpd.json
pkgcfg/package-configuration/nginx.json
pkgcfg/package-configuration/nginx/nginx
pkgcfg/package-configuration/php.json
pkgcfg/package-configuration/php/php-fpm
pkgcfg/pkgcfg.go
pkgcfg/services.go

This adds new `services` command (behind flag). It allows:
`devbox services ls`
`devbox services start|stop [service]`
Services are configured using package configuration (plugins)
Also modified `info` command to include services instructions.
```
devbox services ls
devbox services start nginx
devbox services start apache
devbox services start php-fpm
...
devbox services stop nginx
devbox services stop apache
devbox services stop php-fpm
```

[services] Add services to package configs (plugins)

---

boxcli/root.go
cloud/mutagen/install.go
cloud/mutagen/wrapper.go
cloud/openssh/sshshim/generate.go
cloud/openssh/sshshim/invoke.go
cloud/openssh/sshshim/logger.go
debug/debug.go

This PR hooks up the ssh command invocation.
Two design choices:
1. Choose to have the `ssh` symlink in `~/.config/devbox/ssh/shims` point to `devbox` binary, and have devbox first check if the `args[0]` is `ssh` before starting the cobra logic for regular commands. This ensures that all flags are handled directly by ssh, instead of cobra. The alternate design would be implementing `devbox cloud ssh` command which relies on cobra parsing flags, and any global devbox flags would interfere.
2. Choose syscall.Exec instead of exec.Cmd so that we preserve the exit code and environment, and the current process is replaced by ssh. Without this, we'd see errors during mutagen sync: the mutagen binary would fail to be copied to Beta, the remote machine. 
Also make a small fix to ensure we always …

[cloud] ssh shim part 2: invoke ssh

---

boxcli/root.go
cloud/openssh/sshshim/generate.go
cloud/openssh/sshshim/invoke.go

This PR generalizes part 2 to also shim scp
1. started a vm
2. `DEVBOX_FEATURE_SSH_SHIM=1 DEVBOX_DEBUG=1 DEVBOX_VM=savil@24d89664a95187.vm.devbox-vms.internal devbox cloud shell`
gave a devbox shell in the vm

[cloud] ssh shim part 3: invoke scp

---

boxcli/services.go
boxcli/shell.go
devbox.go
nix/nix.go

This change allows starting and stopping services out of shell.
This PR exposed a few bugs in package configuration. Specifically we were not setting up the bin path and environment variables for package configuration when running scripts and when doing nix.Exec.
We have 3 different functions that need very similar setup:
* shell
* RunScript
* Exec
They all need path and environment variables to be setup in the same way. Currently we have a lot of copy paste between shell and RunScript, and Exec is done in a different way. Maybe we can unify all of these?
Tested out of shell
```
devbox add nginx
devbox services start nginx
```
To test RunScript added new script:
```json
"scripts": {
"foo": "echo NGINX_CONFDIR=$NGINX_CONFDIR"
}
```
and ran
```
devbox run foo
```

[services] Allow running services out of shell

---

boxcli/root.go
cloud/cloud.go
cloud/mutagen/wrapper.go
cloud/mutagenbox/doc.go
cloud/mutagenbox/mutagenbox.go
cloud/openssh/sshshim/logger.go
cloud/openssh/sshshim/mutagen.go

This PR adds logic for the `sshshim` to check for a live VM. If the VM is not reachable,
then it should terminate the sync session. We label each sync with the machineID
so that cloud-shells to the same vm get the same label for their mutagen sync.
To test for liveness, I currently execute a `echo "alive"` command in the VM. There
are likely better ways to do this. Suggestions welcome!
NOTE:
For now, I pass-thru the ssh/scp command if the arguments indicate that the server
is not a devbox-vm. In the next PR, I'll see if we can have a dedicated mutagen daemon
via setting MUTAGEN_DATA_DIRECTORY, in which case we can more strongly impose
that the ssh/scp command can be executed only with a liveVM. UPDATE: this works!
NOTE:
I also discovered that I need to manually empty-out the …

[cloud] ssh shim part 4: detect stopped vm, and terminate mutagen sessions

---

cloud/cloud.go
cloud/mutagen/wrapper.go
cloud/mutagenbox/mutagenbox.go
cloud/mutagenbox/shim.go
cloud/openssh/sshshim/generate.go
cloud/openssh/sshshim/logger.go

This PR enables running devbox's own mutagen daemon by setting MUTAGEN_DATA_DIRECTORY.
Refactored code so that more of the devbox-specific logic is centralized in `mutagenbox`
package, which then calls the generic `mutagen` package.
```
> brew install mutagen
> which mutagen 
/usr/local/bin/mutagen
> mutagen daemon start
> ps aux | grep mutagen
```
Then:
1. manually start a vm (command omitted due to closed source, but happy to share)
2. `DEVBOX_FEATURE_SSH_SHIM=1 DEVBOX_VM=username@vmaddress devbox cloud shell`
3. `cd ~/.config/devbox/ssh/shims` and `tail -f logs.txt` to monitor the shim.
4. exit the cloud shell 
5. `fly m stop <id>` to stop the vm
6. `touch foo.txt` in the devbox project folder to trigger a sync action
7. wait for the `logs.txt` to show the `mutagen sync terminate` …

[cloud] ssh shim part 5: run own mutagen daemon

---

boxcli/midcobra/debug.go
boxcli/midcobra/midcobra.go
boxcli/midcobra/sentry.go
boxcli/midcobra/telemetry.go

**Motivation**
The sshshim command path bypasses the existing cobra stack. We need to add some basic telemetry around error tracking so we have visibility into errors users may run into (due to our programming mistakes).
We would like to reuse the existing `midcobra` abstraction which has a `telemetry` middleware that does both sentry and segment tracking. However, for sshshim we desire just sentry, not segment. So we want to:
1. split telemetry middleware into sentry and segment middlewares
2. set a common sentryID for both sentry and segment to correlate the corresponding events/data.
**Implemention**
This PR adds an executionID to `midCobra.Middleware`.
We use this executionID in two ways:
1. We set executionID in both sentry.EventID and segment's sentry_event_id
2. For an error and …

[midcobra] add executionID

---

internal/nix/install.go

Previously we were using `--daemon` to force multi-user on all platforms. This doesn't work on WSL, so omit the flag. This means on macOS it will use multi-user and on linux it will install as single user.
Untested, but this is what it used to be and was tested previously.

[nix] nix install without using daemon flag DEV-1266

---

internal/boxcli/add.go
internal/impl/devbox.go

Minor UX improvements:
* Using devbox add without specifying a package shows a helpful message.
* After installing a package we show the exact version that was installed.
```sh
➜ devbox add
Usage: devbox add <pkg>... [flags]
To search for packages use https://search.nixos.org/packages
```
```sh
➜  devbox add curl
curl (curl-7.86.0) is now installed.
```

[add] Show better message if package is missing. Specify exact version after installing

---

internal/boxcli/midcobra/midcobra.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/root.go
internal/cloud/openssh/sshshim/command.go
internal/telemetry/sentry.go
internal/telemetry/telemetry.go

This PR is an alternative to both #361 and #363.
This PR's approach is lighterweight:
1. refactor sentry code into its new `telemetry` package.
2. directly call that in the sshshim command execution function.
The advantages it has are:
1. Major: The implementation in #363 is rather gross because we need to introduce an interface equivalent of cobra.Command. This is really ugly, and not very maintainable. If new middleware uses other functions of cobra commands, then we'll have to add those to the interface and also handle them in the sshshim-command version.
2. Minor: We keep the `midcobra.telemetry` middleware for the regular devbox command.
Disadvantages are:
1. We may in the future need to incorporate new middleware into the sshshim command in a non-middleware manner.
compiles.
Tested …

[sshshim] add sentry without using middleware

---

internal/impl/devbox.go
internal/impl/generate.go
internal/pkgcfg/manager.go
internal/pkgcfg/pkgcfg.go

This changes plugins so that `devbox.d` files are only created on `add` and not on other commands.
Following discussion with @loreto I was going to return error if any of the files are missing, but I'm afraid this will backfire. Specifically there are plugin files that are non-essential to plugin. Two immediate examples:
* nginx plugin creates a `web/index.html` example page.
* php plugin creates a php-fpm config  which is not needed if you don't want to use php-fpm.
Currently this PR simply takes no action if a given file is missing. I think that's probably Ok for now.
Some possible solutions:
* We could mark certain files as "optional" but this would complicate the plugin json.
* We could save some data in `devbox.d/devbox.lock` to keep track of plugins we've already generated files for …

[plugins] Only create devbox.d files on add

---

internal/cloud/cloud.go
internal/cloud/mutagen/types.go

This minimal fix creates a mutagen session for each code project that a user
starts a `devbox cloud shell` for.
In a future PR, we can refactor SessionSpec so that sanitize name is always applied
by adding `WithName` options to a constructor function.
started cloud shells for rust and golang example projects. Synced files in each.
`MUTAGEN_DATA_DIRECTORY=~/.config/devbox/mutagen mutagen sync list` -> reports 2 active sessions.
Closed shells. Stopped VM. 
`MUTAGEN_DATA_DIRECTORY=~/.config/devbox/mutagen mutagen sync list` -> reports no active sessions.

[cloud] enable multiple projects opening shells in same VM

---

internal/boxcli/featureflag/sshshim.go

Turns on this feature for all `devbox cloud shell` users.
- started a fly VM
- started a `devbox cloud shell` to that VM
- inspected ~/.config/devbox/ssh/shims` to see files created and `logs.txt` to see operations running well
- `MUTAGEN_DATA_DIRECTORY=~/.config/devbox/mutagen sync list` to inspect active sync sessions.
- stop VM
- `MUTAGEN_DATA_DIRECTORY=~/.config/devbox/mutagen sync list` to confirm no more active sync sessions.

[sshshim] turn on gate

---

internal/boxcli/add.go
internal/impl/devbox.go
internal/nix/nix.go
internal/pkgcfg/files.go
internal/pkgcfg/info.go
internal/pkgcfg/pkgcfg.go
internal/pkgcfg/services.go

UX improvements:
* If user adds a package without a readme, don't show any readme. (previously we would show: "To show this information, run `devbox info %s")
* If user tries to add non-existent package show better message.
```sh
devbox add curl
curl (curl-7.86.0) is now installed.
```
```sh
devbox add foobar
Error: foobar: package not found
To search for packages use https://search.nixos.org/packages
```

[UX] Improve post-install readme, improve message if package not found

---

internal/cloud/cloud.go
internal/cloud/openssh/client.go

Consistently return a more informative error message when an SSH command fails. The errors now contain the pid, the quoted command, and exit code.
When debug logging is enabled, also write the full command when the process starts and when it exits. If the command fails, indent and log its stdout and stderr buffers. If it succeeds, only log stderr to avoid logging private VM keys. Instead, the caller will redact, format, and log a successful JSON response.

openssh: improve command errors and debug logging

---

internal/boxcli/services.go
internal/plugin/pkgcfg.go
plugins/apache/httpd.conf
plugins/apacheHttpd.json
plugins/nginx/nginx.conf
plugins/php.json
plugins/php/php-fpm.conf

@Lagoja called out that we were using absolute paths in conf files. Since the conf files are checked-in, they need to be env variables or relative paths if the file doesn't support env variables.
I also added `services restart` which really helped me test this out.
```
devbox add nginx apacheHttpd php
devbox services start
curl localhost
curl localhost:8080
curl localhost:8080/index.php
```

[plugins] Use relative paths or env variables in configs DEV-1272

---

internal/cloud/cloud.go
internal/cloud/mutagen/types.go
internal/cloud/mutagen/wrapper.go

I discovered that the rust-stable project was not syncing, because it stores compiled
artifacts in a child-directory: `.rustup`. This directory is in the `.gitignore` file
but mutagen was syncing it.
In the long run, we should not sync any files that are gitignored (agree?).
However, code for that is a bit more involved, so as a first pass I implement
looking for a .gitignore file in the `configDir` and passing its rules to mutagen
as `--ignore` flags. Thankfully, mutagen's ignore rules match gitignore format.
was able to start `devbox cloud shell` in the `rust-stable` example project

[cloud shell] respect gitignore file in --config directory to limit large data syncs

---

internal/cloud/cloud.go

We should always ignore the `.devbox` directory, even if the user has not explicitly
added a `.gitignore` in their devbox-project.
1. did cloud shell.
in local directory:
```
❯ readlink -f .devbox/nix/profile/default
/nix/store/aszi29qz92wlsllyh0hzcf6qxvs71hzf-user-environment
```
in remote cloud shell:
```
(devbox) savil in 🌐 239080d49b6875 in ~
❯ readlink -f code/go-1.19/.devbox/nix/profile/default
/nix/store/5l1i25kli85b0870bbcab90haclmam4z-user-environment
```
note that these are different

[cloud shell] always ignore .devbox directory

---

internal/cloud/cloud.go
internal/cloud/user.go
internal/cloud/user_test.go

This PR makes an `ssh -T git@github.com` query that is rejected with a friendly error
message of the form:
```
Hi savil! You've successfully authenticated, but GitHub does not provide shell access.
```
We can parse the username (`savil`, for me) from this response.
In a future PR, we can cache this value in `~/.cache/devbox/user.yaml` to reduce
the number of network calls
Not the most extensive testing. In my case, `savil` is used on both my local
laptop and github, so the usernames match. 
1. Github auth is set up
`DEVBOX_DEBUG=1 devbox cloud shell` and saw the printed output matches the code paths
for successfully parsing the github username.
2. Github auth is not set up
(see comment below)
Used Stepper UI:
When we cannot resolve the username, we'll ask as before:
and when we can …

[cloud shell polish] query Github to get username

---

README.md

Updates the `README.md` to reflect the new installation instructions based on v0.2.0.
Removed Nix locally, ran the `curl` command in the `README.md` and started Devbox.

[docs] Update "Installing Devbox" instructions.

---

internal/cloud/cloud.go
internal/cloud/openssh/sshconfig.tmpl
internal/cloud/openssh/testdata/devbox-ssh-config.golden
internal/cloud/openssh/testdata/devbox-ssh-debug-config.golden

We would like `devbox cloud shell` sessions in multiple terminal tabs to connect
to the same VM Host. Reason:
1. Speed: that VM host already has the correct packages installed
2. User may want to monitor some existing process from the other tab
Unfortunately, fly.io isn't reliably connecting to the gateway of the same region,
so we need to implement a manual solution.
Solution:
1. Use a single ssh connection using `ControlMaster` and `ControlPath` in ssh config.
Set its timeout to be 300 seconds, which matches the scale-to-zero timeout in the VM's
docker image for when it shuts down.
2. Inspect the `~/.config/devbox/ssh` directory for a ControlPath socket, and derive
the existing VM hostname from the socket name.
started devbox cloud shells in two tabs and ensured it reuses the VM …

[cloud] set ssh ControlPath and use it to detect existing VM Host

---

plugins/caddy.json
plugins/caddy/Caddyfile

Adds a plugin for the Caddy Server: 
* caddy
Use `devbox services start|stop [service]` to interact with services
* devbox.d/caddy/Caddyfile
* devbox.d/web/index.html
* CADDY_ROOT_DIR=devbox.d/web
* CADDYFILE=devbox.d/caddy/Caddyfile
* CADDY_CONFIG_DIR=devbox.d/caddy
* CADDY_LOG_DIR=.devbox/virtenv/caddy/log
To show this information, run `devbox info caddy`
Localhost, following Caddy file serve tutorial

Add basic Caddy plugin

---

plugins/redis.json
plugins/redis/redis.conf

Adds a plugin for Redis, including environment variables, default conf file, and a service
Built locally, then ran `devbox services start redis` to validate configuration

Add Redis Plugin

---

internal/cloud/cloud.go

A small polish PR. 
IMO the previous transition message was kinda wordy. It also becomes confusing
if a user opens another cloud-shell in another terminal tab: this results in 
the starship prompt showing the transition message in both cloud-shells.
So, to simplify, we can dispense this transition message and have smaller messages.
opened devbox cloud shell in two tabs and saw the starship prompt update

[polish] simplify the starship prompt for mutagen status

---

internal/boxcli/init.go
internal/boxcli/root.go
internal/boxcli/run.go
internal/boxcli/shell.go
internal/boxcli/writer/writer.go
internal/impl/devbox.go
internal/impl/tmpl/shell.nix.tmpl

- Wrote a custom IOWriter
- Added `--quiet`/`-q` flag to run, init, and shell commands
- Devbox init doesn't produce any output right now, but it will start suggesting packages after #385 is merged
- Addresses #406 
1. Compile
2. `devbox init -q`
3. Add scripts to devbox.json
4. `devbox run <script> -q`
5. `devbox shell -q`
6. Assert in all cases devbox logs aren't printed

[CLI] Added quiet mode to devbox run, init, and shell

---

internal/impl/tmpl/shell.nix.tmpl
internal/nix/shell.go

This change is a no-op, and is just in preparation for a larger change that will stop using `nix-shell` as the implementation for `devbox shell`. Separating these changes in their own PR allow the other change to be a bit more self-contained.
Building and running `devbox` locally.

Refactor var filtering; check var in posix way

---

internal/cloud/cloud.go
internal/cloud/openssh/client.go
internal/cloud/openssh/config.go
internal/cloud/openssh/config_test.go
internal/cloud/openssh/sshconfig.tmpl
internal/cloud/openssh/testdata/devbox-ssh-config.golden
internal/cloud/openssh/testdata/devbox-ssh-debug-config.golden

Setting ControlMaster to auto prevents a warning from being shown when there's already a ControlMaster process running. Put the control sockets in a separate directory in case we later support multiple VMs per user.
Also move the socket-specific code to the openssh package so that hostname parsing lives with sshconfig.tmpl.
Unit tests and connecting to a VM multiple times.

cloud: change ControlMaster to auto and add sockets dir

---

internal/cloud/cloud.go
internal/cloud/fly/region.go

Two changes:
1. Update the introductory text
2. Update the stepper-success message to include the region the VM was created in.
For the second change, there are two scenarios:
1. New VM -> `Created a virtual machine in <location>`
2. Existing VM -> `Detected an existing virtual machine`. We don't include location information because we don't have it. This scenario occurs either when opening another cloud-shell in another terminal tab OR when starting a new cloud-shell within 300 seconds (`ControlPersist` time in sshconfig).
I copied the region names table from https://fly.io/docs/reference/regions/. I did not editorialize the names, but of course we can: for example, someone connecting to a region near them called `Sunnyvale, California` likely doesn't need the `(US)` part since they …

[cloud | polish] update intro text, and display VM region

---

internal/boxcli/featureflag/flakes.go
internal/impl/devbox.go
internal/impl/flake.go
internal/impl/generate.go
internal/impl/tmpl/flake.nix.tmpl
internal/nix/shell.go
internal/nix/shellrc.tmpl
internal/nix/testdata/shellrc/basic/shellrc.golden
internal/nix/testdata/shellrc/nohook/shellrc.golden
internal/nix/testdata/shellrc/noshellrc/shellrc.golden

re-submit of https://github.com/jetpack-io/devbox/pull/247
with an additional commit to gate the code in `generate.go`
Did `devbox shell` in a project
Previously, it would print info about initializing the inner git repo.
Now, it does not do that. 
Also inspected `.devbox/gen` to verify no flakes are generated.

flakes etude (with gating fix)

---

devbox.go
internal/boxcli/generate.go
internal/boxcli/generate/devcontainer_util.go
internal/impl/devbox.go
internal/impl/tmpl/envrc.tmpl

title says it:
this is step 1 of 4 to make integration with direnv more convenient
- compile
- run `devbox generate direnv`
- confirm `.envrc` file is generated and works with direnv

[Generate] Added devbox generate direnv command

---

examples/testdata/unfree-packages/devbox.json
internal/impl/devbox.go
internal/nix/nix.go
internal/nix/shell.go

We want to enable all users to install unfree packages. In this PR, we do so by
setting the env-var NIXPKGS_ALLOW_UNFREE=1. The wiki mentions also being
able to use config options, but I was unable to use that on a per-command basis.
Implementation note:
1. I define a `nix.DefaultEnv()` function that is used in most commands.
2. For `nix-shell`, because we use the `--pure` function, we need to explicitly
`--keep` this env-var. We also cannot use the `nix.DefaultEnv()` in some places
which already manipulate the environment, and so we manually add the NIXPKGS_ALLOW_UNFREE there.
Start a new project:
```
❯ devbox init
examples/testdata/unfree-packages on  savil/allow-unfree [$!+?] on ☁️  (us-east-2) on ☁️  savil.srivastava@jetpack.io 💫 initial project sync
```
Ensure we can add an unfree …

Enable all users to install unfree packages

---

devbox.go
internal/boxcli/cloud.go
internal/cloud/cloud.go
internal/impl/config.go
internal/impl/config_test.go
internal/impl/devbox.go
internal/impl/devbox_test.go
internal/impl/flake.go

`configDir` is used to mean the directory-path corresponding to the `--config`
flag in the `devbox` commands. Unfortunately, this can be conflated with the 
directory at `~/.config/devbox`, and so we can choose to rename it to `projectDir`.
Future PRs will address:
1. changes in `cloud.go` and other `devbox cloud` code.
2. changes in plugin framework, where this is referred to `rootDir`.
tests pass
could open `devbox shell` in a golang example project.

[cleanup] rename configDir to projectDir

---

internal/cloud/cloud.go
internal/cloud/cloud_test.go

This PR renames configDir to projectDir for `devbox cloud` code.
After this PR, the following is what is left which correspond to `~/.config/devbox`
```
❯ git grep -in configDir | grep cloud
internal/cloud/mutagen/xdg.go:19:func ConfigDir() string {
internal/cloud/mutagen/xdg.go:24:	return filepath.Join(ConfigDir(), subpath)
internal/cloud/openssh/config.go:90:		ConfigDir     string
internal/cloud/openssh/config.go:97:		ConfigDir:     devboxSSHDir,
internal/cloud/openssh/config.go:240:	devboxConfigDir := filepath.Join(dotConfig, "devbox")
internal/cloud/openssh/config.go:241:	if err := EnsureDirExists(devboxConfigDir, 0755, true); err != nil {
internal/cloud/openssh/config.go:246:	devboxSSHDir := filepath.Join(devboxConfigDir, "ssh")
internal/cloud/openssh/sshconfig.tmpl:6: …
```

[cleanup] devbox cloud: rename configDir to projectDir

---

go.mod
go.sum
internal/nix/shell.go

While this seems like a no-op, please note that I removed the quotes around the formatted string in each of the cases. I was finding that the rc files weren't being executed when using the quotes (and while using nixless shell).
Add a var into `shellrc.tmpl`, build devbox, run `./devbox shell`, and check if the var is defined. Do this for bash, zsh, ksh.

Extract shell-specific init file injection into own func

---

internal/impl/devbox.go
internal/nix/shell.go
internal/nix/shell_test.go
internal/nix/shellrc.tmpl
internal/nix/testdata/shellrc/basic/shellrc.golden
internal/nix/testdata/shellrc/noshellrc/shellrc.golden

Doing the rename for `nix/shell.go` code.
After this PR, the remaining references are to
(1) pkgConfigDir which is unrelated 
(2) DevboxConfigDir in pkgconfig code, which I'm addressing in its own PR.
```
❯ git grep -in configDir | grep -v cloud
internal/impl/devbox.go:244:			nix.WithPKGConfigDir(filepath.Join(d.projectDir, plugin.VirtenvBinPath)),
internal/impl/devbox.go:323:			nix.WithPKGConfigDir(filepath.Join(d.projectDir, plugin.VirtenvBinPath)),
internal/nix/shell.go:42:	pkgConfigDir    string
internal/nix/shell.go:141:func WithPKGConfigDir(pkgConfigDir string) ShellOption {
internal/nix/shell.go:143:		s.pkgConfigDir = pkgConfigDir
internal/nix/shell.go:371:	if s.pkgConfigDir != "" {
internal/nix/shell.go:372:		pathPrepend = s.pkgConfigDir + ":" + pathPrepend …
```

[cleanup] nix/shell: rename configDir to projectDir

---

internal/boxcli/midcobra/midcobra.go
internal/boxcli/run.go
internal/boxcli/shell.go

Currently, there is no way to figuring out if the shell / run command succeeded or not in the CI-like environment.
This commit fixes this issue by returning exit code of the exec call if errored.
- Running `shell` with the failing command
```sh
❯ ./devbox shell -- exit 1
Error: exit status 1
❯ echo $?
1
```
- Running `script` with the failing command
```json
{
"shell": {
"scripts": {
"failing_script": "exit 1"
}
}
}
```
```sh
❯ ./devbox run failing_script
Error: exit status 1
❯ echo $?
1
```

Return exit code of the exec call

---

internal/cloud/cloud.go
internal/cloud/cloud_test.go
internal/cloud/openssh/client.go

**Problem**
A scenario we want to protect against is two distinct projects sharing the same directory name. For example, consider projects located at `~/customer1/my_project` and `~/customer2/my_project`. Prior to this PR, we would attempt to sync both projects to the same folder in the VM: `~/code/my_project`.
**Approach**
This PR attempts to solve this conflict by seeking to emulate the user's directory structure in the VM. So, for the aforementioned example projects, they will sync to `~/customer1/my_project` and `~/customer2/my_project` in the VM as well. This has the additional benefit that if a user has relative paths between two projects they are actively developing (for example, a golang library and golang application that uses that library), then these relative paths will …

[cloud] emulate user's local directory structure in VM

---

internal/plugin/files.go
internal/plugin/hooks.go
internal/plugin/info.go
internal/plugin/pkgcfg.go
internal/plugin/rm.go
internal/plugin/services.go
plugins/apacheHttpd.json

For the plugin framework, this renames rootDir to projectDir. This change
makes it consistent with the rest of the devbox codebase.
did not change this one, because it may break users. Or are we early enough that 
we can change it?
```
docs/app/docs/devbox_examples/servers/apache.md:HTTPD_DEVBOX_CONFIG_DIR={PROJECT_DIR}
```
automated tests

[cleanup] plugin framework: rename rootDir to projectDir

---

internal/boxcli/midcobra/midcobra.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/usererr/execerr.go
internal/nix/nix.go
internal/nix/shell.go

Update sentry to avoid logging errors from os exec commands. After https://github.com/jetpack-io/devbox/pull/441 goes in, sentry starts to log user script errors which are not devbox errors. This is to exclude those errors. cc @devholic 
./dist/devbox shell -- exit 1
./dist/devbox run nonexistentcmd

Update sentry to avoid logging errors from os exec commands

---

internal/cloud/mutagen/type_test.go
internal/cloud/mutagen/types.go

Sanitizes the mutagen session name to match the validation done in mutagen's code.
Specifically:
1. ensure the first char is a letter
2. ensure only numbers, letters and dash characters are used
1. added test
2. copied `rust-stable` example project into folder: `/var/folders/79/1yc1ywp10w9f2xnr_rpp_ff00000gn/T/tmp.XshVTWYu`.Then started `devbox cloud shell` and saw it sync files successfully.

[cloud] improve mutagen session name sanitization

---

internal/impl/devbox.go
internal/plugin/info.go
internal/plugin/pkgcfg.go

This improves the message we show when a package that has env vars is installed. It shows it in yellow at the very end always. It also joins the `hash -r` command so that it's a single command.
This is a stopgap until we have a better way to use update env variables while in shell. Once that is done, some of this change can be reverted. (we might also be able to remove the need for `hash -r` command by running it directly from devbox and/or only showing it when it actually needs to be run)
I also considered creating a global env file that sources all the env files but this would cause potential overwriting I didn't want.

[plugins] Join hash -r and source message and show in yellow

---

internal/boxcli/featureflag/pkgconfig.go
internal/boxcli/info.go
internal/boxcli/services.go
internal/impl/devbox.go
internal/impl/generate.go
internal/nix/shell.go
internal/plugin/pkgcfg.go
internal/plugin/services.go

Ensures services have correct environment when called in shell. This fixes a particular case where a plugin is installed and then a service is started without restarting the shell.
Cleanup:
* Removed feature flag
* Simplified code by having plugin.Env return a slice instead of a map
* Factored out service start/stop to make linter happy
* `devbox shell`
* `devbox add apacheHttpd && devbox service start apache`

[services] Ensure services have env vars + cleanup

---

.github/workflows/cli-release.yml

Update latest version in s3 after each devbox release. This is related to the github api rate limit issue we've been seeing in devbox installation.
CICD

[CICD] Update latest version in s3

---

devbox.go
internal/boxcli/shell.go
internal/impl/devbox.go
internal/impl/tmpl/envrc.tmpl

Transformed `devbox shell --print-env` command to add env variables from plugins when cd-ing into a direnv directory.
- compile
- run `./devbox init` (requires direnv)
- respond yes to prompt for direnv integration
- Using nginx as an example for a package with plugin, run `./devbox add nginx`
- confirm nginx plugin's env vars are set 
- `echo $NGINX_CONFDIR `, `echo $NGINX_PATH_PREFIX`, and `echo $NGINX_TMPDIR`

[direnv] Added env variables from plugins to direnv

---

internal/nix/nix.go

This simply adds the ability to call `nix print-dev-env -f <file>`, parses the result and returns it. The idea is to then use the output of this to implement a better (read faster and more isolated) version of `devbox run` and eventually `devbox shell`. The output can also be used for a more correct implementation of `devbox shell --print-env` (albeit slower).
Used it for experimental implementation of `devbox shell` that relies on it. Will send that on a separate PR.

Adds code to call nix print-dev-env

---

internal/nix/shell.go

TSIA
Fixes #402 
```
SHELL=bash ./devbox run <script>
```

Put call to run_script at the end, to unbreak bash

---

internal/impl/tmpl/envrc.tmpl

With recent changes to direnv integration. cd-ing into a direnv integration devbox project would prevent the user to run `devbox shell`. That is because the env variable `DEVBOX_SHELL_ENABLED` gets set alongside others with direnv integration even though the user may not be inside a devbox shell. 
This change keeps a back up of the value of `DEVBOX_SHELL_ENABLED` before letting direnv make any changes to env variables. Then puts the backed up value back for `DEVBOX_SHELL_ENABLED`.
- cd into a direnv directory
- confirm direnv has set devbox's env variables
- run `./devbox shell`
- confirm it goes into the shell successfully
- while in shell run `cd ..` and then `cd` back into the directory
- confirm `DEVBOX_SHELL_ENABLED` is still set to 1
- exit from devbox shell
- confirm …

[direnv] Fix a bug with devbox shell enabled & direnv

---

internal/boxcli/cloud.go
internal/cloud/cloud.go
internal/cloud/mutagen/forward.go
internal/cloud/mutagen/wrapper.go
internal/cloud/mutagenbox/forward.go

Implement port forwarding using mutagen. 
This implements the following:
* `devbox cloud port-forward <port> | :<port> | <port1>:<port2>`
* `devbox cloud port-forward list`
* `devbox cloud port-forward terminate` 
Improvements:
* port forward fails if port is in use
* Automatically find a port if user uses ":<port>" argument
* Better output after forwarding
* Started cloud vm, installed and started apache
* Started a few port forwards
* Went to browser and confirmed it was working.
* Tested `list` command, `terminate` command and `list` again.

[cloud] Implement port forwarding using mutagen

---

internal/nix/shell.go

For shells that aren't fully detected and for which we don't have custom logic (like fish), we fallback to just running the shell. `devbox run` was failing to attempt to run any command in this case. This PR makes it so that we at least attempt to run the command. It may or may not work, depending on the shell, but it does work with fish.
This is a bit of a hacky fix to get fish to work. Longer-term I want to re-implement devbox run so it doesn't depend on specific shells and rcfiles, so we can avoid these compatibility problems altogether.
```
SHELL=fish ./devbox run <script>
```

Fix devbox run for fish and possibly other shells

---

.github/workflows/cli-release.yml

Fix cicd release version to read directly from github context.
I'm pretty confident this will work, but it is hard to test. Will wait till the next release cycle.

Fix cicd release version to read directly from github context

---

internal/boxcli/setup.go
internal/nix/source.go

Fixes bug in ensure nix installed.
@gcurtis was right. source does not work in sh. Changed with a `.`. My best guess is that I did not test the end-to-end installation when I switched this code from `bash` to `sh` in this [commit](https://github.com/jetpack-io/devbox/pull/426/commits/dd7287936f37b7ccc5ea7170e9b70a2896efaed3#diff-5012a4a5b4cd2f8957a7f9aebcb2cca11654b6f85d72800aa8be9c482a644535R30)
Also made a small fix to re-source after installation. This should prevent the user from having to re-run the command after nix is installed. (I thought this was working previously, but I'm not sure how)
Edit: This can be improved by properly handling stderr. But I want to get this out fast so we can patch it.
* Fresh ubuntu container, created user for single user install
* `devbox init` and …

[nix] Fix ensure nix installed

---

internal/boxcli/shell.go

cmd.print() was not printing in stdout. Therefore the output was not being picked up by `eval` in `.envrc`
- `devbox init`
- `devbox add nginx`
- `echo $NGINX_CONFDIR`

Fixed plugin env not setting in direnv

---

internal/boxcli/cloud.go
internal/boxcli/shell.go

We want to prevent shell inception in both `devbox shell` and `devbox cloud shell`.
Specifically, within regular shell and cloud shell we want to prevent another
regular shell or cloud shell from starting.
- refactor into a common utility function, and parameterize by the attempted 
- change from vanilla golang error to `usererr`
tested in `devbox shell`:
```
(devbox)
❯ devbox shell
Error: You are already in an active devbox shell.
Run `exit` before calling `devbox shell` again. Shell inception is not supported.
(devbox)
❯ devbox cloud shell
Error: You are already in an active devbox shell.
Run `exit` before calling `devbox cloud shell` again. Shell inception is not supported.
```
I didn't test within a `devbox cloud shell`, but conceptually it should work the
same because in the VM the …

Prevent shell inception in cloud shell

---

internal/nix/install.go

Wait for copying from the stdout/stderr pipe to finish in Install before calling cmd.Wait. This fixes a race where the goroutine may try to read after the defer closes the pipe.
Ran `devbox add go` in a container without Nix installed.

nix: wait for pipe read to finish before cmd.Wait

---

go.mod
internal/boxcli/featureflag/nixless_shell.go
internal/nix/shell.go
internal/nix/shell_test.go
internal/nix/shellrc.tmpl

This is a simplistic implementation of `devbox shell` that launches a shell directly, instead of calling `nix-shell`. Instead it uses `nix print-dev-env` to construct the environment needed to replicate a nix shell, and launches the shell directly. As with `devbox shell`, it lets some parts of the user's environment "leak" into the shell, in the same ways that the current implementation of `devbox shell` does. The behavior is behind a feature flag, so this PR should be a no-op for any user that doesn't explicitly enable the feature.
The current implementation relies on exporting the variables in the shellrc file, which I'd like to change in the future (will probably just change it on this PR itself).
Tried it with a few shells and verified that the PATH and other vars looked reasonable, …

Experimental impl of nixless shell

---

internal/boxcli/info.go
internal/boxcli/root.go
internal/boxcli/shell.go
internal/boxcli/version.go

To follow convention of (a) help for commands is capitalized, (b) help for flags isn't.
I also removed "quiet mode" and "verbose", because when you print the help, "quiet" and "verbose" is printed directly next to it, so it's kind of redundant.
Ran `./devbox` and `./devbox help <cmd>` for every command

[polish] Minor polish on help text

---

internal/boxcli/midcobra/telemetry.go
internal/nix/shell.go

This PR adds two properties to each segment event from midcobra:
1. `cloud: bool`
2. if cloud is true, then `cloud.region: string`

[cloud telemetry] part 2: add 'cloud_region' property to segment

---

devbox.json
internal/cuecfg/cuecfg.go
internal/cuecfg/json.go
internal/impl/generate.go
internal/impl/shellcmd/command.go
internal/impl/shellcmd/command_test.go
internal/planner/plansdk/plansdk.go
internal/plugin/pkgcfg.go

This fixes issue reported by @Lagoja where we are HTML encoding the config.
Not sure if it makes sense to only expose `cuecfgMarshalJSON` but this was easiest/quickest fix.
* Added a script with "&&" and ">>" 
* Added a pkg to force a config write
* Inspected config.

[cuecfg] Don't HTML escape json

---

examples/testdata/go/go-1.19/devbox.json
internal/boxcli/log.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/root.go
internal/boxcli/shell.go
internal/cloud/cloud.go
internal/cloud/openssh/client.go
internal/impl/devbox.go
internal/nix/shell.go
internal/nix/shellrc.tmpl
internal/telemetry/segment.go
internal/telemetry/telemetry.go

This PR logs a `shell-time-to-interactive` segment event.
`devbox shell` approach:
1. Upon starting a command, we capture the `telemetry.CommandStartTime()`.
2. When `devbox shell` runs, in the custom shellrc we have a "Devbox Post Init Hooks" section. Here, we call `devbox log shell-tti <command-start-time>`.
3. `devbox log shell-tti <command-start-time>` logs to segment TrackEvent with the elapsed time.
`devbox cloud shell` approach:
1. invoke `ssh <username>@<vm-address> start_devbox_shell.sh project-path <command-start-time>`.
2. (TODO in a separate axiom PR): we will invoke `DEVBOX_SHELL_START_TIME=<command-start-time> devbox shell`
3. `devbox shell` will use the `DEVBOX_SHELL_START_TIME` instead of the `telemetry.CommandStartTime()` in step (2) in the previous `devbox shell` …

[cloud] add shell time-to-interactive segment event

---

internal/impl/devbox_test.go

Small update to `testShell` since we aren't using shellPlan.json anymore (other than phpv2 planner) to remove the check for "shell plan should have devPackages"
This is small PR part of a bigger cleanup task for shell planner left overs and revamping our tests.
Unit test (test_devbox) passes

[cleanup] Removed test for shell plan should have devPackages

---

plugins/nginx/nginx.conf

Port 80 requires root. Use 8081 instead. (Avoided 8080 because apache plugin has that as default)
```bash
devbox add nginx
devbox services start
curl localhost:8081
```

[plugins] Change default nginx port to a non-privileged port

---

internal/boxcli/featureflag/nix_dev_env_run.go
internal/impl/devbox.go
internal/nix/run.go

This is part of unifying everything (devbox run/shell) to use nix print-dev-env.
This implementation of `devbox run` is pretty simple:
* Write all the init hooks into a file named `.devbox/gen/scripts/.hooks.sh`. This includes plugin hooks.
* Write all the scripts into files named `.devbox/gen/scripts/<name>.sh.` The scripts have a call to source the hooks in the beginning.
* When calling `devbox run`: (1) compute the environment with `nix print-dev-env`, (2) merge any plugin environment vars, and (3) call `sh -c <script>` with the computed environment.
Tested by running all the scripts in this `devbox.json` and confirming their results as expected:
```
{
"packages": [
"go_1_19",
"golangci-lint",
"hello",
"ps",
"redis",
"ruby"
],
"shell": {
"init_hook": [
"export \"GOROOT=$(go env …
```

Implement stricter "devbox run" using "nix print-dev-env"

---

internal/nix/shell.go

For `devbox shell`, we do NOT return an exit error if a user's shell command had 
returned a non-zero exit code. `devbox cloud shell` inherits this behavior.
For `devbox run`, we do return an error for the above scenario (as before).
scenarios:
- verified local `devbox shell`
- cloud: custom built a binary and deployed a machine. Observed that we no longer
return an error if the user's last command was errant:
cloud shell output:
```
(cloud) ❯ which foobar
(cloud) ❯ exit
exit
Shared connection to 9080557a662987.vm.devbox-vms.internal closed.
❯ echo "$?"
0
```

[shell] do not return error if it was a user shell command or script

---

internal/cloud/openssh/sshshim/mutagen.go

This PR should stop port-forward sessions once the user's VM is found to be inactive
and we are terminating the sync sessions as well.
- `devbox cloud shell`
- `devbox add apacheHttpd` (Make sure to run the source line after installing)
- `devbox services start apache`
- locally port forward: `devbox cloud port-forward :8080` (test localhost on printed url)
- Test port forward is active: devbox cloud port-forward ls
- Stop cloud shell, and wait (30 seconds) for the scale-to-zero logic to stop the VM.
- edit some file in the directory (triggers a mutagen sync ssh operation)
- Test port forward is no longer exists: devbox cloud port-forward ls

[port forward] terminate port-fwd sessions if VM is not active

---

internal/boxcli/run.go
internal/impl/devbox.go
internal/nix/run.go

TSIA
```
devbox run echo "hi"
devbox run hello
devbox run cowsay -d hello      # fails because -d is interpreted as devbox flag
devbox run -- cowsay -d hello   # works!
```

devbox run can run arbitrary commands

---

devbox.json
internal/boxcli/cloud.go
internal/cloud/mutagenbox/forward.go

Renames:
* `port-forward` -> `forward`
* `terminate` -> `stop`
Simplifies:
* Removes single port option
* accepts 0 (zero) as a local port. If this is passed in, we determine the port.
```bash
devbox cloud forward :8080
devbox cloud forward list
devbox cloud forward stop
```

[forward] Rename port-forward to forward and simplify API

---

internal/impl/devbox.go

This is more a of a nice-to-have. It cleans up any files in the script directory that are old or not part of the existing set of scripts.
Added files to `.devbox/gen/scripts` and then saw them be deleted after running `devbox run` again

Clean up old script files

---

internal/impl/tmpl/development.nix.tmpl
internal/impl/tmpl/runtime.nix.tmpl
internal/impl/tmpl/shell.nix.tmpl

If the DEVBOX_NIXPKGS_URL environment variable is set, use it for the nixpkgs URL instead of the one baked into the nix file.
Ran `devbox shell` with it set and unset.

impl: allow nixpkgs URL to be set with DEVBOX_NIXPKGS_URL

---

internal/impl/config.go

We shouldn't have allowed this in the first place, but if we allow it, then it's impossible to support arbitrary commands, as well as passing args to a script.
Improves error messages a bit by including the script name.
Added spaces to some scripts in `devbox.json` and called `devbox run`

Disallow script names with whitespace in them

---

internal/nix/run.go

TSIA
Study on how these vars were chosen:
https://www.notion.so/jetpackio/Env-audit-nix-shell-vs-print-dev-env-bebe176d2a2b4796967df92f58201fef
```
DEVBOX_FEATURE_NIX_DEV_ENV_RUN=1 ./devbox run -- echo '$HOME' # my home, instead of /homeless-shelter
DEVBOX_FEATURE_NIX_DEV_ENV_RUN=1 ./devbox run -- echo '$TMP' # not set in host, not set here
DEVBOX_FEATURE_NIX_DEV_ENV_RUN=1 ./devbox run -- echo '$TMPDIR' # set in host, set here
DEVBOX_FEATURE_NIX_DEV_ENV_RUN=1 ./devbox run lint # works without complaining about lockfile
DEVBOX_FEATURE_NIX_DEV_ENV_RUN=1 ./devbox run build # works as well
DEVBOX_FEATURE_NIX_DEV_ENV_RUN=1 ./devbox run curl https://www.google.com # works without ssl failure
```

Allow limited set of vars to leak into devbox run env

---

internal/impl/devbox.go

I made a mistake merging all the recent small PRs recently and this slipped through.
`./devbox run a_script`

bugfix: use correct script filename

---

internal/boxcli/featureflag/strict_run.go
internal/impl/devbox.go

Enable print-dev-env based devbox run by default. A user can always disable it by passing `DEVBOX_FEATURE_STRICT_RUN=0`. Note that I renamed the feature because the other name was a mouthful.
````
./devbox run test_single
./devbox run hello # success. would've failed otherwise
DEVBOX_FEATURE_STRICT_RUN=0 ./devbox run hello # fails

Flip swich on strict devbox run feature flag

---

internal/boxcli/shell.go

TSIA
To be merged after #503.
```
> ./devbox shell -- hello
[Warning] "devbox shell -- <cmd>" is deprecated and will disappear in a future version. Use "devbox run -- <cmd>" instead
Hello, world!
```
```
> ./devbox shell -q -- hello
Hello, world!
```
```
> ./devbox shell --help
Start a new shell with access to your packages.
The shell will be started using the devbox.json found in the --config flag directory. If --config isn't set, then devbox recursively searches the current directory and its parents.
[Deprecated] If invoked as devbox shell -- <cmd>, devbox will run the command in a shell and then exit. This behavior is deprecated and will be removed. Please use devbox run -- <cmd> instead.
Usage:
devbox shell -- [<cmd>] [flags] …
```

Add deprecation warning on shell -- cmd

---

examples/testdata/go/go-1.19/devbox.json
internal/impl/devbox.go

I was playing around with making the install step show more incremental progress.
This PR explores it by doing `nix-env --install` for just the nixpkgs and then
each package individually. This lets us print installation output as we go along.
The implementation is rather hacky. I override `devbox.cfg.Packages` to re-generate
the `development.nix`. There's more likely a more direct `nix-env --install` 
command invocation we can use but I was failing to figure it out this evening. I don't think 
we should commit this code as-is, but sharing for product oriented feedback and suggestions
on the right `nix-env --install` command to use so we can improve the hacky code.
deployed a custom binary to a custom VM:
```
Devbox Cloud
Remote development environments powered by Nix
✓ File syncing …
```

[install UX] show incremental progress

---

devbox.go
internal/boxcli/run.go

The new devbox run implementation lets us reuse the exact same implementation, whether we're in or outside a devbox shell. I also behaves exactly the same way, yay!
```
./devbox shell
./devbox run hello
./devbox run echo '$HOME'
```

Use same impl for devbox run in shell or out

---

internal/impl/devbox.go
internal/ux/stepper/stepper.go

Thanks to @mikeland86's suggestion we can have snappy incremental in-line updates
of what the `nix-env --install` is doing.
added `buf` to a devbox.json and did `devbox shell`

[install UX] incrementally show the output in-line

---

internal/cloud/cloud.go
internal/impl/devbox.go
internal/ux/stepper/stepper.go

I noticed the stepper wasn't respecting the `io.Writer` used in the `impl/devbox.go`
and `cloud/cloud.go` apis.
Hooked it up.
Ran `devbox shell` and `devbox cloud shell` and got expected output.

[stepper] respect the io.Writer used in impl/devbox.go

---

internal/impl/devbox.go
internal/ux/filterwriter.go

Filters out
```bash
replacing old 'devbox-development'
installing 'devbox-development'
```
from every command that runs `ensurePackagesAreInstalled`
```bash
> devbox run echo hello
Installing nix packages. This may take a while...
Done.
hello
```

[nix] Filter out 'devbox-development' messages

---

internal/cloud/cloud.go
internal/impl/config.go

Problem:
When running `devbox cloud shell` (and other commands) if we don't find 
a `devbox.json` in the current directory and no `--config` flag is specified,
then we walk up the directory tree to find a `devbox.json` file. If we do find one,
we use that directory as the `projectDir`.
This has the danger that we may sync a sensitive directory like a user's homedir
or the filesystem-root dir (i.e. `/`). The syncing may inadvertently delete something in the directories
under this sensitive dir. 
@Lagoja ran into this since he has a devbox.json in his homedir.
Solution:
This PR protects against this by requiring a `.git` repository to be present in 
the same dir. We presume this would protect against data loss. Without a `.git`
we display a user error.
```
❯ devbox cloud shell
Devbox Cloud …
```

[devbox cloud] require git in home and fs-root dirs to use as devbox project dir

---

internal/boxcli/shell.go

This reverts commit e9a9a4f7afcff48e5a6c14a605f2812193fbcbdc.
Reverts #502 because `run <cmd>` is not released yet.

Revert "Add deprecation warning on shell -- cmd (#502)"

---

internal/boxcli/featureflag/strict_run.go

Turning the feature off after finding some issues when running against `devbox-examples`.

Unflip strict run feature flag

---

internal/boxcli/featureflag/sshshim.go
internal/cloud/mutagenbox/mutagenbox.go
internal/cloud/openssh/sshshim/generate.go

This code has been active for quite a while now. So we can remove the gate.

[devbox cloud] remove sshshim gate

---

devbox.json
internal/impl/tmpl/development.nix.tmpl
internal/impl/tmpl/runtime.nix.tmpl
internal/impl/tmpl/shell.nix.tmpl
internal/planner/plansdk/plansdk.go

This change is a bit hacky. I'd like to eventually clean this up to work better with the various nix commands. It also reverts the previous env var change since it's no longer needed.
When generating the various *.nix files, check to see if the cloud mirror is reachable. If it is, download nixpkgs archives from there instead of GitHub.
Also update the default commit hash to be the current nixpkgs unstable, which is also in the cache. This guarantees that any new devbox projects created after this release will hit the cache in the cloud.

plansdk: use nixpkgs mirror when in cloud VM 

---

internal/impl/devbox.go

If we get any error while trying to add packages we revert devbox.json and show error.
Tried to add a broken package and made sure it did not get added to devbox.json
```bash
devbox add php81Extensions.blackfire
Installing nix packages.
error: attribute 'extensionName' missing
at /nix/store/j5a7i3dvxslg2ychfy53wdhg1m3xfrwm-source/pkgs/development/interpreters/php/generic.nix:94:29:
93|
94|           getExtName = ext: ext.extensionName;
|                             ^
95|
(use '--show-trace' to show detailed location information)
There was an error installing nix packages: php81Extensions.blackfire. Packages were not added to devbox.json
Error: apply Nix derivation: running command /nix/var/nix/profiles/default/bin/nix-env --profile /Users/mike/dev/scratch/php/.devbox/nix/profile/default …
```

[nix] Don't add bad package to devbox.json

---

internal/impl/tmpl/development.nix.tmpl
internal/impl/tmpl/shell.nix.tmpl

This was just bugging me a bit.
They used to look like this:
```
let
mirrorURL = builtins.getEnv "DEVBOX_NIXPKGS_URL";
pkgs = import (fetchTarball {
url = if mirrorURL == "" then "https://github.com/nixos/nixpkgs/archive/52e3e80afff4b16ccb7c52e9f0f5220552f03d04.tar.gz" else mirrorURL;
}) {
};in with pkgs;
mkShell {
shellHook =
''
export IN_NIX_SHELL=0
export DEVBOX_SHELL_ENABLED=1
if [ "$NIX_SSL_CERT_FILE" = "/no-cert-file.crt" ]; then
unset NIX_SSL_CERT_FILE
fi
if [ "$SSL_CERT_FILE" = "/no-cert-file.crt" ]; then
unset SSL_CERT_FILE
fi
export "PATH=$PATH:$PARENT_PATH"
'';
packages = [
mariadb
git
php81
php81Packages.composer
nginx
];
}
```
Now they look like this:
```
let
mirrorURL = builtins.getEnv "DEVBOX_NIXPKGS_URL";
pkgs = import (fetchTarball {
url = if mirrorURL == "" then …
```

[tiny] Improve format of generated nix files

---

internal/boxcli/cloud.go
internal/boxcli/shell.go

Allow `devbox shell` calling `devbox cloud shell`
Prevent:
1. `devbox shell` calling `devbox shell`
2. `devbox shell` in a cloud VM calling `devbox cloud shell`.
called `devbox cloud shell` from a `devbox shell`.
These operations were stopped
```
(devbox)
❯ DEVBOX_REGION=savil devbox cloud shell
Error: You are already in an active devbox cloud shell.
Run `exit` before calling `devbox cloud shell` again. Shell inception is not supported.
(devbox)
❯ devbox shell
Error: You are already in an active devbox shell.
Run `exit` before calling `devbox shell` again. Shell inception is not supported.
```

[cloud shell] prevent cloud-shell-inception

---

internal/nix/run.go

This was causing problems with variable substitution. For example, `clang` would try to compile `'`
`devbox run clang` returns "no files" instead of `clang-11: error: no such file or directory: '''`

Do not shell quote environment variables

---

internal/impl/tmpl/flake.nix.tmpl
internal/impl/tmpl/shell.nix.tmpl

The `nixpkgs` URL in the flakes template was using the latest nixpkgs
and not respecting the version in `devbox.json`
ran `DEVBOX_FEATURE_FLAKES=1 devbox shell` in go1.19 example project.
inspected `devbox.lock` and verified that the nixpkgs version matches that
of `devbox.json` (and confirmed that with `main` branch's devbox binary these would not match)

[flakes] respect nixpkgs commit hash

---

devbox.json
internal/boxcli/cloud.go
internal/cloud/cloud.go

Adds preview wording to cloud commands and to text that shows up when doing `devbox cloud shell`

[cloud] Add preview wording

---

internal/cloud/mutagen/wrapper.go
internal/xdg/xdg.go

So that I can re-use it in other parts of the code not related to mutagen.
`go test -v ./...`

Move xdg functions into its own package

---

internal/planner/plansdk/plansdk.go

The previous commit broke poetry.
```
devbox init
devbox add python310 poetry
```

plansdk: default nixpkgs -> f80ac84

---

internal/impl/devbox.go

It is common convention to capitalize the default answer in linux CLI prompts.
the default behavior appears to be No

[polish] capitalize the default answer in direnv integration question

---

.github/workflows/cli-tests.yaml

We're going way above our GHA cache limits because every branch creates new cache keys for golangci-lint and our go builds. This means we rarely get cache hits.
This bumps GHA versions and changes golangci-lint to use daily cache (instead of creating a new unique cache key on every branch)
This also fixes a an issue where we're doing tests twice (once on push and once on pull request)
CICD

[GHA] Bump versions, create daily golangci-lint cache

---

.github/workflows/cli-tests.yaml

Currently tests are only run on pull requests (and prior to https://github.com/jetpack-io/devbox/pull/556 on non-main branches).
We do want to run them on main pushes for 2 reasons:
1. Ensure main is not broken (e.g. in case of a bad merge)
2. Create GHA caches that can be used by all branches (GHA cache looks for cache keys in own branch and also in main)
Untested

[gha] Run tests on main

---

.github/workflows/cli-tests.yaml
docs/app/docs/quickstart.mdx

Fixes URLs for badges in Quickstart
Launchpad + Localhost

Fix URLs for badges in Quickstart

---

internal/cloud/cloud.go
internal/cloud/openssh/cmd.go

Use the `openssh` package where possible when executing the SSH commands for setting the mutagen sync status. This provides better logging when commands fail.
Also rename `openssh.Client` to `Cmd` to better reflect that we're calling an external process.

cloud: clean up mutagen sync ssh commands

---

.github/workflows/cli-tests.yaml
docs/app/docs/devbox_examples/languages/csharp.md
docs/app/docs/devbox_examples/languages/fsharp.md
docs/app/docs/quickstart.mdx
docs/app/sidebars.js

Add an F# Example
Localhost + Launchpad

Add Fsharp to the docs

---

.github/workflows/cli-release.yml
.github/workflows/cli-tests.yaml

mac tests are really slow (failing because they hit timeout). This increases the timeout to 20 minutes but only runs it on main.
CICD

[CICD] Only run mac tests on main

---

internal/cloud/cloud.go

The stepper is stepping over the password prompt. Remove it for now.
Using a password protected key, I stopped ssh-agent, deleted the devbox vm socket, and deleted github_username
`devbox cloud shell`

[cloud] Fix password ssh key

---

internal/nix/shell.go
internal/telemetry/segment.go

Updating:
1. Event name to be of the form: `[devbox] Shell event: interactive` which is consistent with the command event names.
2. Changing is_cloud to shell_access with values `local | ssh | browser`
1. apply development keys for segment and sentry
2. `local`: run local `devbox shell` and verify event logged in segment dashboard.
3. `ssh`: deploy custom VM with custom devbox binary. verify event logged in segment dashboard.
4. `browser`: Follow devbox-cloud README for http-gateway, but how do I test the custom devbox binary?

[telemetry] update event name and change is_cloud to shell_access kind

---

README.md

This changes the button to use the quickstart example in devbox examples.
Signed-off-by: John Lago <750845+Lagoja@users.noreply.github.com>

Change README badge to use the Quickstart Example

---

examples/testdata/go/go-1.17/main.go
examples/testdata/go/go-1.18/main.go
examples/testdata/go/go-1.19/main.go

These gave errors like:
```
expected version: go1.17, got: go1.17.13
```
when doing `go run main.go` in their respective `devbox shell`
opened a `devbox shell` and did `go run main.go` and got the version printed out without any panic

fix golang testdata

---

internal/boxcli/run.go
internal/impl/devbox.go

So that they're not reported to Sentry.
```
DO_NOT_TRACK=0 devbox run invalid-script
```

Mark some more errors as user errors

---

internal/cloud/cloud.go
internal/cloud/openssh/cmd.go

`copyConfigFileToVM` is the first command we run on the VM. Sometimes is takes fly.io a few seconds to propagate DNS, especially if the VM is located in a different region than the proxy (this can happen if the gateway is in a different region to proxy) We retry a few times to avoid failing the command.
`DEVBOX_DEBUG=1 devbox cloud shell`
many times

[cloud] Add retry when trying to connect to cloud vm for first time

---

internal/boxcli/midcobra/telemetry.go

Problem:
UserID field was missing for logs for Command events
Cause:
1. The `event` struct in `midcobra/telemetry` embeds the `telemetry.Event`.
2. Both structs had a `UserID` field
3. We were writing to the `telemetry.Event.UserID` field
4. But when reading the outer struct's `UserID` field would be read, masking the value in the embedded field.
Fix:
Remove the outer field definition
1. Added print statements prior to logging the Command and Shell events, and confirmed that UserID was present.
2. Verified in segment's development project Debugger events that UserID is present for both Command and Shell events.

[telemetry] fix missing UserID for command events

---

internal/telemetry/segment.go

**Motivation**:
From inspecting the segment logs, I am reminded that the userID is logged as a 64 char.
Segment says that ideally this userID is something we track in our main database. Longer term, I'm not sure we'd want our primary userIDs to be TEXT kind in Postgres data type terms, compared to smaller uuid or int variations.
**Approach**:
This PR amends the `UserIDFromGithubUsername` function to __deterministically__
return a UUID string (or empty string if not authenticated or error occurs).
It is important that the same UUID is returned for the same github username.
**RFC: Breaking Change**
Tradeoff: in Segment we'll not be able to track the same users' activity prior to this PR.
copied this function into a devbox-project for golang and executed it multiple times
with different …

[RFC] make Telemetry UserID be a uuid string

---

internal/boxcli/midcobra/telemetry.go

We do not want to log hidden commands (like `devbox log`) to segment Command Events.
We continue logging them to sentry to track any errors therein.
Ran `devbox shell` whose shellrc will invoke `devbox log shell-interactive`.
Opened Segment Dashboard > Source > Development Project > Debugger, and:
1. saw Command Events for "devbox shell" and Shell Events for interactive and ready durations.
2. did not see any Command Events for "devbox log" (which did show up previously)

[telemetry] do not log hidden commands to segment Command Events

---

internal/impl/devbox.go

spotted this when testing
before:
after:

[polish] add newline to end of multi-add/rm packages

---

internal/impl/devbox.go

Before this fix, if your had `export FOO=bar` in your init hook, and you had a script `"foo": "echo $FOO"`, then these two commands would have different results:
```
> devbox run foo
bar
> devbox run -- echo '$FOO'
```
The second invocation should _also_ return `bar`. This change makes it so.
Note that the implementation is a bit odd. I left a comment explaining why it's so.
Ran the commands in the description above and they both returned the same.

[bugfix] Arbitrary commands should also run init and plugin hooks

---

plugins/pip.json
plugins/pip/venvShellHook.sh

This plugin automatically sets up a virtual environment for python packages whenever a python3 version of `pip` is added.
- Sets a `VENV_DIR` environment variable that determines where the virtualenv is
- A `venvShellHook.sh` file is added in `devbox.d` which creates the venv directory at $VENV_DIR if it doesn't already exist
- The plugin's init hook runs the `venvShellHook.sh` script
I've left it so the user still needs to source the virtualenv manually, so they can choose whether or not to activate on starting devbox shell
Tested in devbox-examples, create a simple requirements.txt and ran it with the plugin

[Plugin] Add a plugin for `python3xxPackage.pip`

---

internal/nix/shellrc.tmpl
internal/nix/testdata/shellrc/basic/shellrc.golden
internal/nix/testdata/shellrc/nohook/shellrc.golden
internal/nix/testdata/shellrc/noshellrc/shellrc.golden

Change the order of init hooks to ensure user hooks are run last. Also ensure plugin hooks are run from the same directory as user hooks (the project dir)
```
devbox add ruby
devbox shell
```

[easy][plugins] User init hooks should run after plugins

---

docs/app/yarn.lock

https://github.com/jetpack-io/devbox/security/dependabot/12
https://github.com/jetpack-io/devbox/security/dependabot/13
CICD

[docusaurus] Bump docusaurus version to remove vulnerable dependencies

---

internal/impl/devbox.go
internal/impl/tmpl/flake.nix.tmpl
internal/nix/nix.go
internal/nix/run.go
internal/nix/shell.go
internal/nix/shellrc.tmpl

This PR is a step towards enabling `devbox shell` to work with both Flakes and NixlessShell featureflags enabled.
Future PR TODOs: refer to notion doc on Post Devbox Cloud Clean up Tasks.
in `examples/testdata/go/go-1.19`:
```
> DEVBOX_FEATURE_FLAKES=1 DEVBOX_FEATURE_NIXLESS_SHELL=1 DEVBOX_DEBUG=1 devbox shell
(devbox) > go run main.go
Go version: go1.19.3
```
Also started shells with the following control cases:
1. `DEVBOX_FEATURE_FLAKES=0 DEVBOX_FEATURE_NIXLESS_SHELL=0 DEVBOX_DEBUG=1 devbox shell`
2. `DEVBOX_FEATURE_FLAKES=0 DEVBOX_FEATURE_NIXLESS_SHELL=1 DEVBOX_DEBUG=1 devbox shell`
For the control cases, did:
```
> devbox add vim
> which vim
> devbox rm vim
```
to verify that the package was added and removed

[flakes | print-dev-env] enable flakes to work with print-dev-env

---

internal/impl/devbox.go
internal/nix/shell.go
internal/nix/shell_test.go
internal/nix/shellrc.tmpl

This makes devbox shell (with "nixless shell" feature enabled) reuse the `computeNixEnv` function that devbox run uses (with strict run feature enabled).
Next I will rename and unify the feature flags so we just have 1 to control both behaviors, and also better separate the implementation of `shell`, which is a bit complex atm. But this should help unblock @mohsenari in his work to add env vars.
Ran `devbox shell` with/without "nixless shell" enabled and check environment vars looked as expected.

devbox shell uses computeNixEnv

---

.github/workflows/cli-tests.yaml
.github/workflows/docs-deploy-prod.yaml

Github Workflows for the merge-queue need to be explicitly opted-in.
I inspected the existing workflows which were opted in for `push` events on `main` branch,
and enabled those for `merge_queue` events as well.
Relevant help article:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
haven't tested

[github merge queue] enable Github Workflows for merge-queue

---

.github/workflows/stale-issue-cleanup.yml

Adds a stale issue workflow that will close issues and PRs after 30 days of inactivity. 
This will exempt issues and prs with certain labels, so long drafts or issues that are marked for the future can be preserved
Untested, but marking this `debug-only` so we can try it as a dry run

Add a default stale issue workflow

---

internal/nix/shell.go
internal/nix/shellrc.tmpl
internal/nix/testdata/shellrc/basic/shellrc.golden
internal/nix/testdata/shellrc/nohook/shellrc.golden
internal/nix/testdata/shellrc/noshellrc/shellrc.golden

This is being included by print-dev-env work, so no need to special case now.
```
> DEVBOX_FEATURE_FLAKES=1 devbox shell
(devbox)> env | grep TERM
TERM=xterm-256color
```

[flakes] remove special-case env-var TERM

---

internal/impl/devbox.go
internal/impl/packages.go
internal/nix/nix.go

If a nix-profile-directory was created for an old `nix-env` profile, then when
trying to use the new flake-y `nix profile` with the same directory, an error is 
reported.
This PR enables us to toggle `DEVBOX_FEATURE_FLAKES=` on and off for the same
devbox-projects by inspecting the contents of the profile:
1. a `manifest.nix` means that its an old style profile
2. a `manifest.json` means that its a new style profile (i.e. to be used with flakes feature)
The code will "reset" i.e. delete the directory and re-create it.
inserted a print statement prior to `os.Remove(dir)` in the reset function
```
> DEVBOX_FEATURE_FLAKES=0 devbox shell
> DEVBOX_FEATURE_FLAKES=1 devbox shell
reset = true
> DEVBOX_FEATURE_FLAKES=0 devbox shell
reset = true
```
Observe:
1. no error, we can toggle seamlessly
2. …

[flakes] reset nix profile directory when Flakes feature is toggled

---

internal/impl/tmpl/flake.nix.tmpl

Now that we are installing packages individually in `nix profile`, we no longer
need the `buildEnv` that is specified in the `flake.nix`.
Using `DEVBOX_FEATURE_FLAKES=1 DEVBOX_FEATURE_NIXLESS_SHELL=1`:
```
> devbox shell
(devbox) > devbox add vim emacs
(devbox) > which vim
(devbox) > devbox rm vim
(devbox) > which vim
```

[flake] remove buildEnv from flake.nix

---

internal/impl/devbox.go
internal/impl/packages.go
internal/nix/shell.go
internal/nix/shellrc.tmpl

This brings the `computeNixEnv` PATH handling to (almost) parity with `devbox shell`. I might remove the virtenv path after confirming we don't need it.
Compared `devbox shell` PATH with the PATH I get in `devbox shell` or `devbox run` when I have `NIXLESS_SHELL` or `STRICT_RUN` enabled, respectively.

Add virtenv path and nix profile path to computed nix path

---

internal/boxcli/featureflag/nixless_shell.go
internal/boxcli/featureflag/strict_run.go
internal/boxcli/featureflag/unified_env.go
internal/boxcli/run.go
internal/boxcli/run_test.go
internal/impl/devbox.go
internal/nix/shell.go
testscripts/testrunner/setupenv.go

TSIA. Lmk if you have a better name suggestion. I can't seem to be satisfied with any name I pick.
```
DEVBOX_FEATURE_UNIFIED_ENV=1 ./devbox run -- echo '$PATH'
```

Unify print-dev-env feature flags

---

internal/nix/shell.go
internal/nix/shell_test.go

Removes obsolete setting of `NIX_PROFILES` var, which allows us to move the splitting of nix profiles paths inside the `cleanEnvPath` function (which I then plan to reuse elsewhere).
This change is a no-op.
Verified that `NIX_PROFILES` wasn't even making it through to `devbox shell`

Remove obsolete var and simplify cleanEnvPath()

---

docs/app/docusaurus.config.js
docs/app/src/css/custom.css

Add Algolia Docsearch to our documentation
https://devbox-web-john-lago-jetpack-io.cloud.jetpack.dev/devbox/docs/
(note, the Logo uses the moon color in the actual preview).

Add Docsearch

---

internal/impl/devbox.go
internal/nix/shell.go
internal/nix/shell_test.go

TSIA
Verified that the following did _NOT_ include the nix profile path to `/Users/<user>/.nix-profile/bin`
```
DEVBOX_FEATURE_STRICT_RUN=1 ./devbox run -- echo '$PATH'
```

Clean PATH of nix profile paths in print-dev-env shell/run

---

internal/boxcli/featureflag/home.go
internal/impl/config.go
internal/impl/global.go

Turns feature on. Adds warning if profile/bin path is not in $PATH
`devbox global add hello`

[global] Turn on feature, keep command hidden

---

internal/impl/devbox.go
internal/nix/nix.go
internal/nix/run.go
internal/nix/shell.go
internal/plugin/pkgcfg.go
internal/services/services.go

This makes it easier to manipulate vars in functions (like `computeNixEnv`). On the flip side, it does mean we need to convert them to `[]string` in order to pass them to a `Command`, which is a bit annoying, but I think it's reasonable. We can introduce a helper function `asPairs(map[string]string)` or something like that later on if we feel the need to clean up.
CICD

Refactor env vars as map[string]string instead of []string

---

internal/impl/packages.go

`nix flakes prefetch` has a native progress indicator in its output. However,
it seems that using the `nixPackagesInstallWriter` would result in it not displaying.
Perhaps because of the tab indentation? Not entirely sure.
This PR uses the regular `io.writer` instead of the custom `nixPackagesInstallWriter`
for the nixpkgs prefetch
- set a new commit hash in devbox.json
- ran `devbox shell`
observed the progess indicator

[flakes] enable native nixpkgs download progress output

---

internal/impl/devbox.go
internal/plugin/pkgcfg.go

I think this callsite was missed in #621
```
> cd devbox/examples/php
> devbox shell
```
previously this would fail with `runtime error: index out of range [1] with length 1`

[bug fix] update Env caller to use map instead of key=val array

---

devbox.go
internal/boxcli/featureflag/env_config.go
internal/boxcli/generate.go
internal/boxcli/init.go
internal/impl/config.go
internal/impl/devbox.go

Added ability to add env variables in devbox.json
Current implementation only supports literal string values as well as `$PATH` and `$PWD` variables.
1. Create a devbox.json similar to below:
```json
"shell": {
"env": {
"my_wd": "$PWD/test",
"my_path": "$PATH:my_stuff/bin",
"my_key": "string value"
},
```
2. Run `DEVBOX_FEATURE_NIXLESS_SHELL=1 DEVBOX_FEATURE_ENV_CONFIG=1 ./devbox shell`
3. Inside devbox shell `echo $my_wd`, `echo $my_path` and `echo $my_key` and confirm values are correctly setup.

[devbox.json] Added env in config

---

internal/boxcli/generate/devcontainer_util.go
internal/impl/tmpl/envrc.tmpl

When print-dev-env and env variables in config features get out of feature flag, `devbox generate direnv` no longer needs to rely on `use nix` function of direnv to calculate the environment variables.
This PR puts the use nix line in generated `.envrc` template file, behind the same feature flag.
Compile.
Run `./devbox generate direnv && cat .envrc`
remove or rename `.envrc`
Run `DEVBOX_FEATURE_ENV_CONFIG=1 ./devbox generate direnv && cat .envrc` 
compare the content of 2 `.envrc` files

[direnv] Added featureflag for devbox generate direnv

---

internal/impl/tmpl/development.nix.tmpl
internal/impl/tmpl/flake.nix.tmpl
internal/impl/tmpl/shell.nix.tmpl

Run `nixpkgs-fmt *.nix.tmpl` to make everything follow common formatting/style conventions.

tmpl: run nixpkgs-fmt on nix files

---

devbox.go
internal/boxcli/global.go
internal/boxcli/midcobra/debug.go
internal/impl/config.go
internal/impl/global.go
internal/ux/messages.go

This is stacked on https://github.com/jetpack-io/devbox/pull/630
This moves global data to XDG_DATA_HOME or `~/.local/share`
* The devbox.json is stored in `~/.local/share/devbox/global/default/devbox.json`
* The nix profile is in `~/.local/share/devbox/global/default/nix-profile`
* the bin path is `~/.local/share/devbox/global/current/nix-profile/bin`
`devbox global add hello`

[global] Move global to XDG_DATA_HOME

---

internal/impl/devbox.go
internal/impl/generate.go
internal/impl/tmpl/shell.nix.tmpl
internal/nix/shell.go
testscripts/run/env.test.txt

Add some more variables that are required for shell: DEVBOX_ vars, a couple hard-coded nix vars, and a few more vars to leak.
Also removes the `shell.nix` hook, which we no longer need if we're using unified env.
go tests

Include some more shell-specific vars, remove nix shell hook

---

internal/impl/devbox.go
testscripts/run/shellception.test.txt

I inadvertently removed this when cleaning up `shell.nix.tmpl` for unified env. I prefer to set this var in Go-code, as opposed to a nix shell hook.
```
> devbox shell
(devbox) > devbox shell
Error: You are already in an active devbox shell.
Run `exit` before calling `devbox shell` again. Shell inception is not supported.
```
```
devbox run devbox shell
Error: You are already in an active devbox shell.
Run `exit` before calling `devbox shell` again. Shell inception is not supported.
```

Prevent shell inception when using print-dev-env

---

internal/boxcli/shell.go
internal/impl/devbox.go
testscripts/run/command.test.txt

Makes `devbox shell -- <cmd>` print a Warning and recommend using `devbox run <cmd>` instead. This behavior is protected behind the UNIFIED_ENV feature flag.
Note that `devbox services` internally uses `devbox shell -- <cmd>`, so when UNIFIED_ENV is enabled, it'll use `devbox run` instead. But it's a bit circular... when outside of a shell, running `devbox services start` is exactly equivalent to running `devbox run devbox services start`.
```
DEVBOX_FEATURE_UNIFIED_ENV=0 ./devbox shell --help
DEVBOX_FEATURE_UNIFIED_ENV=1 ./devbox shell --help
DEVBOX_FEATURE_UNIFIED_ENV=0 ./devbox shell -- echo "foo" # no warning
DEVBOX_FEATURE_UNIFIED_ENV=1 ./devbox shell -- echo "foo" # see warning
DEVBOX_FEATURE_UNIFIED_ENV=1 ./devbox shell -- echo '$PATH' 
DEVBOX_FEATURE_UNIFIED_ENV=1 ./devbox run …
```

Deprecate shell -- <cmd> in favor of run <cmd>

---

examples/testdata/php/php-extensions/devbox.d/php81/php-fpm.conf
examples/testdata/php/php-extensions/devbox.json
examples/testdata/php/php-extensions/index.php

Added an example devbox-project that has a php extension package. This has been useful for doing adhoc testing when developing the feature of "flakes with php extensions". In a future PR, I'll add a testscript (and possibly remove this one).
```
> devbox shell
> php index.php
Original vector elements
idx: 0 and elem: hello
idx: 1 and elem: world
done
> php index.php
ds extension is not enabled
```

[flake] php extensions example project

---

internal/boxcli/run.go

Update help text when unified env feature is on. This feature also enables `run` to accept arbitrary commands, and to pass arguments to scripts.
```
> DEVBOX_FEATURE_UNIFIED_ENV=1 ./devbox run --help
Starts a new shell and runs your script or command in it, exiting when done.
The script must be defined in `devbox.json`, or else it will be interpreted as an arbitrary command. You can pass arguments to your script or command. Everything after `--` will be passed verbatim into your command (see examples).
Usage:
devbox run [<script> | <cmd>] [flags]
Examples:
Run a command directly:
devbox add cowsay
devbox run cowsay hello
devbox run -- cowsay -d hello
Run a script (defined as `"moo": "cowsay moo"`) in your devbox.json:
devbox run moo
Flags:
-c, --config string   path to directory …
```

Update devbox run help text

---

internal/boxcli/root.go

Since no other flag help text uses punctuation

Remove dot from flag help text

---

README.md

It's currently pointing to `release.yml`, which doesn't exist (but `cli-release.yml`) does.

Fix cli-release badge

---

testscripts/assert/assert.test.txt
testscripts/run/path.test.txt
testscripts/testrunner/assert.go
testscripts/testrunner/testrunner.go

Tests that the PATH is built in the desired order. Had to add a `print` function and `path.order` assertion function. Let me know if you have any other ideas!
```
go test ./testscripts/testscripts_test.go
```

Add testscript tests for PATH setting

---

internal/impl/tmpl/devcontainerDockerfile.tmpl

- Fixed permission issue with generated dockerfile for `devebox generate devcontainer` and `devbox generate dockerfile` addressing issue #627 
- Fixed issue with entrypoint command for generated dockerfile. The old format was causing the built image to have `devbox /bin/sh -c ["shell"]` as entrypoint instead of the intended `devbox shell`. So running `docker run image_name` would result in `Error: unknown command "/bin/sh" for "devbox"`
compile
run `devbox generate dockerfile`
run `docker built devboximage .`
run `docker run -it devboximage`
confirm docker image is built successfully
confirm docker image runs successfully

[generate] Fixed permission issue for generated dockerfile

---

internal/nix/shell_test.go
internal/nix/testdata/shellrc_unifiedenv/basic/hook
internal/nix/testdata/shellrc_unifiedenv/basic/shellrc
internal/nix/testdata/shellrc_unifiedenv/basic/shellrc.golden
internal/nix/testdata/shellrc_unifiedenv/nohook/env
internal/nix/testdata/shellrc_unifiedenv/nohook/shellrc
internal/nix/testdata/shellrc_unifiedenv/nohook/shellrc.golden
internal/nix/testdata/shellrc_unifiedenv/noshellrc/env
internal/nix/testdata/shellrc_unifiedenv/noshellrc/hook
internal/nix/testdata/shellrc_unifiedenv/noshellrc/shellrc.golden

Add shellrc tests for unified env

---

internal/nix/shell.go

Before this change, we would panic (in unified env) when using `fish`, because we didn't have the user's init file to write into devbox shellrc. Now we write the shellrc regardless of whether the user's init file is available or not.
```
SHELL=fish DEVBOX_FEATURE_UNIFIED_ENV=1 devbox shell
```
(Also tested that non-unified-env doesn't break.

Write shellrc file on fish (unified env)

---

internal/impl/devbox.go
internal/impl/util.go
plugins/apache/httpd.conf
plugins/apache/process-compose.yaml
plugins/apacheHttpd.json
plugins/php.json
plugins/php/process-compose.yaml

This adds process compose for apache and php. It also fixes a hash to ensure we download a version of process compose that allows multiple config files to be merged.
```bash
devbox add php apacheHttpd
devbox services manager
```

[service-manager] Add more process compose yamls

---

internal/boxcli/featureflag/unified_env.go
internal/nix/shell_test.go
internal/nix/testdata/shellrc_unifiedenv/basic/hook
internal/nix/testdata/shellrc_unifiedenv/basic/shellrc
internal/nix/testdata/shellrc_unifiedenv/basic/shellrc.golden
internal/nix/testdata/shellrc_unifiedenv/nohook/env
internal/nix/testdata/shellrc_unifiedenv/nohook/shellrc
internal/nix/testdata/shellrc_unifiedenv/nohook/shellrc.golden
internal/nix/testdata/shellrc_unifiedenv/noshellrc/env
internal/nix/testdata/shellrc_unifiedenv/noshellrc/hook
internal/nix/testdata/shellrc_unifiedenv/noshellrc/shellrc.golden

I guess it _actually_ was ready right on time on 2/16 :). (but not for a 2/16 release)
testscript tests and using it while developing

Enable unified env by default

---

internal/impl/config.go

TSIA
Added go_1_19 as global and local package.
`devbox run echo 5`

[easy][global] Fix duplicate packages DEV-1281

---

internal/impl/tmpl/flake.nix.tmpl

https://github.com/jetpack-io/devbox/pull/635 hid the shell hook from `shell.nix` behind the unified-env flag (where shell hook is active when flag is OFF).
So, this PR removes it from `flake.nix`, since flakes depend on unified-env being turned on.
opened `devbox shell` in `examples/testdata/go/go-1.19` project

[flakes] remove shell hook

---

examples/testdata/go/go-1.18/devbox.json
examples/testdata/go/go-1.18/shell_plan.json
examples/testdata/unfree-packages/devbox.json
internal/impl/devbox.go
internal/impl/packages.go
internal/nix/nix.go
testscripts/run/env.test.txt

To enable unfree packages with flakes, we need to do both of:
1. set `NIXPKGS_ALLOW_UNFREE=1`
2. use `--impure` flag
There is also an option to do:
```
nixpkgs {
config {
allowUnfree = true;
} 
}
```
However, I have not done this because:
1. we'd still need `--impure` for `nix profile install` that doesn't use `flake.nix`.
2. I couldn't actually figure out how to set `config.allowUnfree` in our flake.nix since we are using the num-tides flakes-utils to enable the flake to work for all `system` values.
in `examples/testdata/unfree-packages`, I can now do:
```
DEVBOX_FEATURE_FLAKES=1 DEVBOX_FEATURE_UNIFIED_ENV=1 DEVBOX_DEBUG=1 devbox shell
```
I was a little concerned that `--impure` would introduce a lot of other environment variables 
into the shell, but I think it is safe for the …

[flakes] enable unfree packages

---

internal/nix/shell.go
internal/nix/shellrc_fish.tmpl

Adds support for `fish` shell.
When running `devbox shell`:
We write the post-initialization steps into a "shellrc" file (see `shellrc_fish.tmpl`). I attempted to reuse the existing `shellrc.tmpl`, but the differences in syntax between fish and other shells were large enough that I had to separate them. Next, we invoke `fish -C <shellrc>`. This will make `fish` use the user's existing config first, and _then_ run whatever is in `<shellrc>`, which is similar to what we do for non-fish shells.
When running `devbox run`:
- If unified env is ON, then we invoke `sh -c <script>` just like we do for every other shell.
- If unified env is OFF, then we'll invoke `fish -C <shellrc> -c <script>`. However, note that #650 already enables unified env by default, so this branch is mainly here just in …

Add support for fish

---

internal/boxcli/add.go
internal/boxcli/global.go
internal/boxcli/midcobra/debug.go
testscripts/run/shellception.test.txt

This changes output for
* add
* global add
* global pull
(since these are not expected to print anything except diagnostic output)
It also fixes the debug middleware which prints all errors.
`devbox run test`

[stderr] Fix a few prints that were going to out instead of err DEV-1282

---

internal/impl/packages.go
internal/nix/nix.go
internal/nix/profile.go

I noticed that print-dev-env and nix profile commands were using a different set
of nix experimental features.
I think we should unify these so that they're writing to the store in a common fashion.
**Implementation Note**
It appears that: `"--extra-experimental-features", "nix-command flakes"`, is different from `"--option", "experimental-features", "nix-command flakes"` for our `nix print-dev-env` testscripts.
We must have the latter. The former is insufficient and not needed.
This confuses me because the docs suggest that `--extra-experimental-features` should append these experimental features, whereas `--option` replaces the experimental features:
>  --option name value
Set the Nix configuration setting name to value (overriding nix.conf).
and
>  --extra-experimental-features value …

[nix] create common ExperimentalFlags function

---

internal/boxcli/global.go

This PR unhides the global feature. I'm leaving ENV hidden for another release, so we can do some more validation of the feature. 
Tested locally, verified help text appeared when running devbox

Unhide Global 

---

internal/nix/shellrc_fish.tmpl

Otherwise we get a line like:
```
```
which is obviously not what we want.
```
SHELL=fish ./devbox shell
> echo $PATH
```

Fix whitespace in fish shellrc template

---

internal/impl/devbox.go

Nix sets TMPDIR to its own path when building an environment and then prints it with `print-dev-env`. Devbox "leaks" TMPDIR, meaning it takes the TMPDIR from the parent shell and overwrites the Nix TMPDIR. However, this doesn't work when TMPDIR isn't set in the parent shell, which is the case in WSL and Docker.
This is a quick fix for just TMPDIR. We should double check the other variables that `nix develop` unsets when there's more time to test.
```
$ unset TMPDIR
$ devbox shell
$ echo $TMPDIR
<nothing set>
```

devbox: unset TMPDIR in shell/run environment

---

internal/boxcli/midcobra/debug.go

Fixes minor double error issue. (This was pulled out of https://github.com/jetpack-io/devbox/pull/695)
```bash
devbox global add hello
hello is now installed
Warning: the devbox global profile is not in your $PATH.
Add the following line to your shell's rcfile (e.g., ~/.bashrc or ~/.zshrc)
and restart your shell to fix this:
eval "$(devbox global shellenv)"
```

[easy][errors] Fix double error

---

.github/workflows/cli-tests.yaml

For some reason Nix stopped being able to find nixpkgs by default after a fresh install. Explicitly setting `NIX_PATH` seems to fix it.
CI

ci: set NIX_PATH after installing Nix

---

internal/nix/source.go

This should not be needed, but nice to have until nix fixes bad nix link.
Tested in devbox cloud, but it didn't completely work because `.nix-profile` sym link was broken.

[nix] Add additional source path

---

.github/workflows/cli-tests.yaml
internal/boxcli/shell_test.go

This fixes mac os tests by setting `NIX_PATH` on the test itself. This should not be needed so it makes me a bit nervous we are covering up another issue.
Added auto-install test for mac
CICD

[CICD] Fix mac tests

---

internal/boxcli/shell_test.go
internal/impl/devbox.go
internal/nix/shell.go
internal/nix/shell_test.go

Previously, if `SHELL` env-var was not set, we'd return an error from `nix.DetectShell`
and initialize an empty struct `nix.Shell{}`. Then, in `Shell.Run` we'd see that `Shell.binPath` is empty
and call `nix-shell`.
This has the following problems:
1. Initializing an empty `nix.Shell{}` means that we drop all the other `ShellOptions`
in the constructor.
2. In `Shell.Run`, we'd use `nix-shell` but fail if the flakes feature was not enabled. This `nix-shell` also loses all the print-dev-env work that we have done for Unified-Env.
To solve and/or mitigate these issues, I propose the following changes:
- Rename `nix.Shell` to `nix.DevboxShell` to make it clear that its not a raw nix shell. TODO for future to move this out of `nix` package.
- Rename `nix.DetectShell` to `nix.NewDevboxShell` to …

Improve handling when no SHELL env-var is defined

---

.golangci.yml
internal/boxcli/midcobra/debug.go
internal/boxcli/midcobra/midcobra.go
internal/cloud/mutagen/sync.go
internal/cloud/user.go
internal/impl/devbox.go
internal/initrec/recommenders/golang/golang.go
internal/initrec/recommenders/java/java.go

1. Add `revive` linter to `.golangci.yml`
2. Enable `indent-error-flow` rule only for `revive`
3. Address related issues.
Linter.

Add revive linter and enable indent-error-flow rule

---

internal/boxcli/generate/devcontainer_util.go

The generated dockerfile puts the devbox packages and files in `/code/.devbox/` in the container. But in devcontainer.json the path is set to `/devbox/.devbox/`. This makes this small fix.
- `devbox generate devcontainer`
- run `code .`
- reopen and rebuild in container
- confirm python interpreter path is set correctly in vscode

[Devcontainer] Fixed path for python interpreter in devcontainer.json

---

internal/boxcli/generate/devcontainer_util.go

Fixed a bug where devbox generate devcontainer would list multiple `ms-python.python` extensions in `devcontainer.json`.
The issue was due to the check inside a for loop. Updated the check to use regex and it resolves the issue.
- `devbox add python39Packages.sip`
- `devbox add python39`
- `devbox generate devcontainer`
- confirm the list of extensions (`"customizations"."vscode"."extensions"`) in `devcontainer/devcontainer.json` file specifies only one `ms-python.python` entry.

[devcontainer] Fixed bug on multiple python extensions listed in devcontainer

---

internal/impl/devbox.go
internal/nix/shell.go
internal/nix/shellrc.tmpl
internal/nix/shellrc_fish.tmpl

* Applies the same changes from #706 to the fish shellrc.
* Ignores the `_` variable. It's read-only and `fish` complains if we try to write it.
* Added a note in `shellrc` so we remember do edit `shellrc_fish` too. If we had tests for fish we could remove this silly note.
* Alphabetized vars so the generated shellrc is a bit cleaner (imo).
Fixes #719 
```
SHELL=fish ./devbox shell
```
I'll add some shellrc_fish tests in a future PR

Fix fish shell after #706

---

.golangci.yml
internal/nix/shell_test.go

It is recommended to use `t.Setenv` instead of `os.Setenv` in tests, so I replaced them.
test and linter

Replace os.Setenv with t.Setenv in tests

---

internal/impl/devbox.go
internal/impl/packages.go

Doing some pending refactoring to de-clutter `impl/devbox.go` by moving functions
responsible for package management to `impl/packages.go`
No other change in logic to make this easy to review.
buildkite tests

[easy][code cleanup] move packages specific functions to impl/packages.go

---

.github/workflows/cli-tests.yaml

I've been seeing this `auto-nix-install` test falsely fail on multiple PRs. For example:
https://github.com/jetpack-io/devbox/actions/runs/4356921852/jobs/7615570020
title says it for the two changes
buildkite run

[CICD] auto-nix-install: export env-var and add DEVBOX_DEBUG=1

---

internal/impl/devbox.go

Fixes #687 
```
echo $PATH
devbox shell
hello # fails
devbox add hello
eval $(devbox shellenv)
hello # ok!
devbox rm hello
eval $(devbox shellenv)
hello # fails
```

Shellenv prepends to original path, not current path

---

internal/planner/plansdk/plansdk.go

Remove the hardcoded IP and instead get the base URL from the `DEVBOX_CACHE` environment variable.

plansdk: get cloud cache from environment

---

plugins/plugins.go

TSIA. See #742 for context.
Ran `devbox shell`

Fix build: only go:embed .json files in plugins dir

---

docs/app/docs/quickstart.mdx

Quickstart Devbox.sh button now points to the tutorial
localhost

Fix quickstart button to link to tutorial

---

internal/impl/config.go

From inspecting the code, I think this should early return. The following statement
about `readConfig(filepath.Join(dataPath, "devbox.json"))` doesn't make sense
to execute if there's been an error in retrieving the `dataPath`.
buildkite testscripts

[config] early return if cannot find GlobalDataPath

---

.github/workflows/stale-issue-cleanup.yml

Updates the stale-issue-cleanup action with the following changes
1. Turns off `debug-only` mode so it can run on live issues
2. Increases operations, so that we can process the full list of issues
3. Increases stale timer to 45 days, giving us ~2 cycles to act on an issue/PR before it gets marked stale
This action has been running daily in debug mode for over a week. See logs and actions here: 
https://github.com/jetpack-io/devbox/actions/workflows/stale-issue-cleanup.yml

Update and activate stale-issue-cleanup

---

internal/impl/generate.go
internal/impl/generate_test.go
internal/impl/packages.go
internal/impl/testdata/flake-empty.nix.golden
internal/impl/testdata/flake.nix.golden
internal/nix/nix.go
internal/nix/nixpkgs.go
internal/nix/profile.go

The previous devbox shell/run startup time was taking about 3.5x longer than `nix develop` for "warm" runs where the flake had already been evaluated once:
$ time nix develop .devbox/gen/flake -c echo hi
hi
0.12s user 0.04s system 45% cpu 0.356 total
$ time devbox run -- echo hi
hi
0.66s user 0.17s system 62% cpu 1.330 total
This was due to two reasons:
1. Devbox was passing `--impure` so that `NIXPKGS_ALLOW_UNFREE` could be used. This prevents Nix from using its eval cache. Fix it by setting the `allowUnfree` attribute directly in the flake.
2. Under certain circumstances, Nix uses the flake file's modified time stamp to determine if it can use its eval cache. Devbox unconditionally writes generated files on every run, which was changing the modified timestamp of the flake. Update the …

nix,impl: avoid modifying flake.nix; don't use --impure

---

testscripts/testrunner/setupenv.go

The testscript tests clear out the environment, so we need to re-enable DEVBOX_DEBUG in order to get more info when a command fails.

testscripts: enable DEVBOX_DEBUG

---

internal/boxcli/midcobra/midcobra.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/midcobra/trace.go
internal/boxcli/root.go
internal/impl/devbox.go
internal/impl/packages.go
internal/nix/nix.go
internal/planner/planner.go

Add a hidden `--trace` flag that turns on tracing to measure execution time. When set, a trace file is written (by default to trace.out) which can be inspected with `go tool trace trace.out`.
This is an example of the trace output after running `devbox --trace run -- echo hello` and then `go tool trace trace.out`:

all: add tracing

---

docs/app/docs/devbox_examples/languages/java.md

This includes an update in odcs for a potential issue where jdk versions other 17 are not chosen by gradle if users don't explicitly specify them in `gradle.properties` file.
- devbox init
- devbox add jdk11 gradle binutils
- devbox shell
- gradle -v
- confirm gradle is using JVM version 17

[Docs] Updated docs for java to include fix for gradle

---

.github/workflows/cli-tests.yaml

We don't have any tests that would make -race useful and we're not looking at code coverage. These flags (especially when combined) can slow down tests by a lot.

ci: remove go test -race and -cover

---

internal/impl/generate_test.go

When the tests run too fast, the mod time doesn't change between writes and the tests become flaky. Remove that check since we verify the file contents anyway.

impl: remove mod time check from template tests

---

internal/services/services.go

Print message telling user how they can access their services on devbox cloud. We could improve this in the future by trying to figure out what port the user is using for this particular service. (we can reuse port field that was already added for auto-port forwarding)
Ideally this is not part of the CLI since it's only important for cloud, but this was quickest implementation.
```bash
(devbox) ➜  devbox git:(main) ✗ DEVBOX_REGION=lax devbox services restart
Service "nginx" stopped
Service "nginx" started
To access services on this vm use: Mike.local-<port>.svc.devbox.sh
```

[cloud] Print message telling users how they can access their services

---

docs/app/docs/devbox_examples/languages/java.md
plugins/gradle.json
plugins/gradle/gradle.properties

Added plugin for gradle to force it to use the installed jdk version instead of default (17).
Also fixed a small error in documentation for gradle setup
- compile
- in empty directory run `./devbox init`
- `./devbox add gradle jdk11`
- `./devbox shell`
- confirm a gradle.properties file is created with content similar to below:
```gradle.properties
org.gradle.java.home=/nix/store/3y1sh00km4c616prn19brd3vj9ikc2h2-zulu11.48.21-ca-jdk-11.0.11
```

[plugin] Added gradle plugin and fixed typo in docs

---

internal/impl/tmpl/devcontainerDockerfile.tmpl

Fixed devcontainer fail due to `devbox shell -- ` being deprecated.
devbox generate devcontainer
open in vscode
cmd + shift + p -> devcontainer: rebuild and reopen in container

[devcontainer] Updated dockerfile to use devbox run dash dash

---

internal/impl/config.go
internal/impl/devbox.go
internal/impl/packages.go
internal/nix/profile.go
internal/nix/writer.go

I was implementing a progress indicator for global install, and the profile install retry logic was making it a bit complicated. I then realized that the order we were assigning to priorities (latter package takes precedence) is actually inverse to what flake `buildInputs` does (it uses earlier precedence). In practice, this means the profile generated by devbox and the flake generated by devbox would have different behaviors. This is not terrible but also not ideal. So I removed the sorting and added some documentation to ensure we always keep the same (local, global) order.
Finally, I tried out a slightly different approach which doesn't require a profile install with retries. By reading the profile manifest file we're able to see what the highest number existing priority (lowest …

[nix] Simplify profile priority, make it match flake file

---

internal/impl/global.go
internal/impl/packages.go
internal/nix/profile.go
internal/plugin/info.go
testscripts/packages/unfree.test.txt

This shows inline progress when installing new packages (both global and local). `nix profile install` does this automatically but only in tty mode. @gcurtis curious if we can somehow make nix believe we're in tty mode without having to specify stdin and stdout?
Removed 2 blockers that are no longer needed:
* `PackageInstallWriter` is no longer needed I don't think. It could not see the lines it was meant to supress.
* Returning package not found is a bit redundant because all callsites of `ProfileInstall` already defensivelly check if package exists. If the user somehow does end up trying to install a package that doesn't exist, we still show a decent error  
Fixed 2 semi-related errors:
* global add  would print success message even if nothing was installed because of errors
* Removing …

[nix] Show nix profile install progress

---

internal/boxcli/featureflag/feature.go
internal/boxcli/featureflag/flakes.go
internal/impl/generate.go
internal/impl/global.go
internal/impl/packages.go
internal/impl/shell.go
internal/nix/nix.go
internal/nix/profile.go

Removes non-flakes code and tries to clean up some branching that is no longer needed.
@savil I removed `featureflag.disabled()` because it makes reasoning about these refactorings quite a bit more difficult and error prone. The words are really similar and some callsites use `!enabled()` which means now I have to think about 4 different combinations. Is this something you feel strongly about? I'm a bit more of the pythonic "only one correct way to do something" than the ruby-like "many ways to write this to make the code sound like english" thoughts?
```
devbox add hello
devbox run hello
```

[flakes] Remove non-flakes code

---

CONTRIBUTING.md
internal/impl/config.go
internal/impl/generate.go

Update the output path of `go build` to be compatible with the following run and test in `CONTRIBUTING.md`.

Fix building target path

---

internal/boxcli/cloud.go
internal/boxcli/generate.go
internal/cloud/cloud.go

Added a `devbox cloud init` command similar to devbox cloud shell but it can be called in to create a cloud vm (if it's not created already) and sets up ssh configs without dropping user in an interactive cloud shell.
This will be used in the extension so that the extension can ensure:
1. the remote vm exists
2. get its ssh address (vm ID)
3. the client (vscode) can connect to it via ssh
Also, added `devbox generate ssh-config` command that only sets ssh-config without creating cloud VMs.
`devbox cloud init`
and 
`devbox generate ssh-config`

[Cloud] Added cloud init command for open in vscode

---

internal/boxcli/cloud.go
internal/boxcli/midcobra/telemetry.go
internal/cloud/envir/envir.go
internal/services/services.go
internal/services/status.go
internal/telemetry/segment.go

This improves:
* port auto-forwarding only happens on CLI shells
* Print port on service proxy if available.
* Refactor common cloud env variables into a single package
builds

[services] Improve auto-port forward and proxy

---

internal/boxcli/root.go
internal/boxcli/run.go

Added devbox install command. Re-used the same functions as devbox run since it's just an alias for calling `devbox run -- :` ( `:` is noop in shell).
`./devbox install`

[CLI] Added install command

---

internal/impl/devbox.go

Adds `LD_LIBRARY_PATH` and `LIBRARY_PATH` env vars to shellenv (pointing to profile lib directory). 
This is a bit of a blunt approach, so not sure if it's best. This would fix https://github.com/jetpack-io/devbox/issues/760 and also lets us simplify the [rust plugin](https://github.com/jetpack-io/devbox/blob/main/plugins/rustup.json#L7-L7)
Two questions/considerations:
* I considered adding to the flake.nix file instead, but wasn't example sure how to point to the right directory (without hard coding). It might look something like `LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath...` 
* I also read the following:
> Not setting LD_LIBRARY_PATH is usually the right choice because usually the native binaries find their libraries using RUNPATH which is specific to the binary. Setting …

[lib-path] Add a few common env variables

---

devbox.go
internal/boxcli/services.go
internal/impl/devbox.go
internal/services/manager.go

Adds new `--process-compose-file` flag that allows user to specify additional process compose services (in addition to ones already specified by plugins). We also auto-detect `process-compose.yaml` or `process-compose.yml` in the root directory.
This allows users to flexibly add new services to process compose without having to write plugins. 
Created `process-compose.yml` in root and added simple hello world printing service. Also added nginx. Ran `devbox process manager` with and without new flag.

[services] Allow custom process compose

---

docs/app/docs/devbox_cloud/browser_getting_started.md
docs/app/docs/devbox_examples/databases/mariadb.md
docs/app/docs/devbox_examples/databases/postgres.md
docs/app/docs/devbox_examples/databases/redis.md
docs/app/docs/devbox_examples/index.md
docs/app/docs/devbox_examples/languages/csharp.md
docs/app/docs/devbox_examples/languages/elixir.md
docs/app/docs/devbox_examples/languages/fsharp.md
docs/app/docs/devbox_examples/languages/go.md
docs/app/docs/devbox_examples/languages/haskell.md
docs/app/docs/devbox_examples/languages/java.md
docs/app/docs/devbox_examples/languages/nim.md
docs/app/docs/devbox_examples/languages/nodejs.md
docs/app/docs/devbox_examples/languages/php.md
docs/app/docs/devbox_examples/languages/python.md
docs/app/docs/devbox_examples/languages/ruby.md
docs/app/docs/devbox_examples/languages/rust.md
docs/app/docs/devbox_examples/languages/zig.md
docs/app/docs/devbox_examples/servers/apache.md
docs/app/docs/devbox_examples/servers/caddy.md
docs/app/docs/devbox_examples/servers/nginx.md
docs/app/docs/devbox_examples/stacks/django.md
docs/app/docs/devbox_examples/stacks/drupal.md
docs/app/docs/devbox_examples/stacks/jekyll.md
docs/app/docs/devbox_examples/stacks/lapp.md
docs/app/docs/devbox_examples/stacks/lepp.md
docs/app/docs/devbox_examples/stacks/rails.md
docs/app/docs/guides/scripts.md
docs/app/docs/quickstart.mdx

Replaced all links that pointed to Devbox Examples to point to the examples folder in the devbox repo
Manual verification

migrate links: devbox-examples -> devbox/examples

---

testscripts/testrunner/testrunner.go

The `testscripts` can be run 2x faster. Specifically, time reduces from 30 seconds to 16 seconds.
the problem is:
- in `RunTestscripts` function of `testrunner.go`, we call `t.Run()` which calls `testscript.Run`
- inside `testscript.Run`, the framework calls `t.Run()` with `t.Parallel()`.
The old way would run testscripts within the same sub-directory in parallel, but now we run all the testscripts in parallel.
The reason for this is:
When the golang test framework is executing a sub-test via `t.Run`, it will start executing it until it hits a `t.Parallel()`. It will then pause this sub-test. It then starts the next sub-test. And so on. Finally, it will resume all paused sub-tests which had `t.Parallel()` and run them concurrently.
By injecting the extra `t.Run` for each sub-directory we …

[testscripts] run in parallel

---

internal/impl/devbox.go
internal/planner/languages/haskell/haskell_v1_planner.go
internal/planner/planner.go

This PR addresses #29, using a similar framework as our PHP planner. It makes it possible to use Haskell packages installed via `haskellPackages` alongside GHC.
This PR is incomplete - right now it only works for the default `ghc` in Nixpkg. We should make sure that we can detect when users request a different compiler version (like `haskell.compiler.ghc810`)
**Default GHC:** Use the following devbox.json:
```json
{
"packages": [
"haskellPackages.aeson",
"ghc",
"stack"
],
"shell": {
"init_hook": null
},
"nixpkgs": {
"commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
}
}
```
Run `devbox shell`, then run `ghc-pkg list | grep aeson` to make sure that it installed correctly
**Versioned GHC:** Use the following devbox.json
```json
{
"packages": [
"haskell.compiler.ghc92", …
```

First Pass at a Haskell Package Planner

---

testscripts/testrunner/examplesrunner.go
testscripts/testrunner/run_test.test.txt
testscripts/testrunner/setupenv.go
testscripts/testrunner/testrunner.go
testscripts/testscripts_test.go

**Why**
Our goal is to make each Devbox release higher-quality by ensuring that all the devbox-projects in `examples/` are able to run.
**What**
We aim to do so by adding a `run_test` devbox script to each project in `examples/`, and ensuring that it can run. This has the additional benefit of making the `devbox.json` self-documenting for any user who is reading the code in the `examples/` directory: they can refer to the `run_test` to understand how to execute that example project.
**How**
To do so in our automated tests:
1. We will generate a simple testscript for each of these devbox-projects that calls
`devbox run run_test`.
2. We copy the devbox project's files and directories into the testscript's workdir.
As a proof of concept, this PR runs a testscript for the …

[Lagobot 2.0] part 1: generate testscript for a single devbox example project

---

testscripts/testrunner/examplesrunner.go

This PR enables the generated testscript to run over more projects in the `examples/` directory.
- This PR enables those projects that happen to work without any further fixes.
- It maintains a skipList of disabled projects.
- We remove the `t.Run` so that the testscripts can run in parallel. This improved execution
time from 150 seconds to 60 seconds locally.
- Internally, the `testscript` framework already does a `t.Run` with a `t.Parallel()`. 
By having the outer `t.Run()`, these tests were not being run in parallel.
- This required a bit of refactoring to rename the `run_test.test.txt` file to
`<project_path>_run_test.test.txt`. We do this because the framework names
the golang testcase after this `txt tar` file, and I wanted a nicer name.
```
DEVBOX_DEBUG=0 go test -v -run …
```

[Lagobot 2.0] part 2: run Examples whose run_test script passes

---

testscripts/testrunner/examplesrunner.go
testscripts/testrunner/setupenv.go

Many language toolchains rely on $HOME being set. For example:
1. csharp and fsharp were failing due to `~/.dotnet` not being writable.
2. golang was failing due to `GOCACHE=$HOME/Library/Caches/go-build`
In this PR, I set HOME to a temp-dir. This continues to ensure isolation.
I also only do this for examplesrunner, and not for the testrunner so that 
we continue to ensure devbox unit tests do not rely on this.
This enables quite a few projects: csharp, fsharp, haskell, poetry, ... and golang (removed the specific GOCACHE code for golang)
I also wrote comments for why the remaining ones are failing and will address
them in followups.
```
DEVBOX_DEBUG=0 go test -v -run TestExamples/development_go -count 1 ./testscripts
...
--- PASS: TestExamples (2.09s)
--- PASS: …
```

[Lagobot 2.0] part 3: set HOME to temp-dir to enable a few example projects

---

testscripts/testrunner/examplesrunner.go

failing in buildkite
buildkite run should be green
local:
```
DEVBOX_DEBUG=0 go test -v -run TestExamples/ -count 1 ./testscripts
--- PASS: TestExamples (0.39s)
--- PASS: TestExamples/development_go_hello-world_run_test.test (5.82s)
--- PASS: TestExamples/development_ruby_run_test.test (5.93s)
--- PASS: TestExamples/development_java_gradle_hello-world_run_test.test (12.75s)
--- PASS: TestExamples/stacks_lepp-stack_run_test.test (22.42s)
--- PASS: TestExamples/development_java_maven_hello-world_run_test.test (16.85s)
--- PASS: TestExamples/development_csharp_hello-world_run_test.test (23.49s)
--- PASS: TestExamples/development_fsharp_hello-world_run_test.test (23.50s)
--- PASS: TestExamples/development_zig_zig-hello-world_run_test.test (21.52s)
--- PASS: …
```

[Lagobot 2.0] disable haskell

---

internal/impl/devbox.go

plugin hooks should run first, user hooks last
```bash
➜  devbox git:(main) ✗ cd examples/development/python/pip
➜  pip git:(main) ✗ devbox run run_test
```

[hooks] Fix hook order

---

examples/development/haskell/devbox.json
testscripts/testrunner/examplesrunner.go

Failure message was:
> [2 of 2] Compiling StackSetupShim   ( /tmp/TestExamples4181845809/020/.stack/setup-exe-src/setup-shim-Z6RU0evB.hs, /tmp/TestExamples4181845809/020/.stack/setup-exe-src/setup-shim-Z6RU0evB.o )
[198](https://github.com/jetpack-io/devbox/actions/runs/4504377069/jobs/7928774568#step:7:199)
Linking /tmp/TestExamples4181845809/020/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_Z6RU0evB_3.6.3.0_ghc-9.2.5 ...
[199](https://github.com/jetpack-io/devbox/actions/runs/4504377069/jobs/7928774568#step:7:200)
/nix/store/178vvank67pg2ckr5ic5gmdkm3ri72f3-binutils-2.39/bin/ld: cannot find -lgmp: No such file or directory
[200](https://github.com/jetpack-io/devbox/actions/runs/4504377069/jobs/7928774568#step:7:201)
collect2: error: ld returned 1 exit status …

[Lagobot] enable haskell

---

examples/development/elixir/elixir_hello/devbox.json
testscripts/testrunner/examplesrunner.go

Add $PWD to the environment variables to fix the elixir example
This is probably worth noting — The env variables are passed as-is to the `sh` binary in the nix store, so without the $PWD, `sh` and `mix` are looking for the elixir deps in /nix/store/<hash>-sh/.nix-mix/ instead of in the project directory. Adding $PWD seems to fix this
`devbox run run_test` in the elixir dir

Fix Elixir Example

---

devbox.json

Move `$(pwd)/dist` to the end of `PATH` as the last choice of `devbox` binary.

Adjust paths order

---

examples/development/python/pip/devbox.json
examples/stacks/django/devbox.json
testscripts/testrunner/examplesrunner.go

We use period `.` instead of `source`, and can now enable pip and django.
Not entirely sure why but I think the testscripts run in `sh` and not `bash`. `source` is a bash-ism.
buildkite run needs to be green

[lagobot] enable pip and django

---

testscripts/testrunner/examplesrunner.go
testscripts/testscripts_test.go

I'm in the middle of adding this but sending this pre-emptively so that Lagobot tests
can stop running in CICD.
The integration tests will only run via `go test -tags=integration`
References:
1. https://www.reddit.com/r/golang/comments/a1iuhg/comment/eat8uyn/?utm_source=reddit&utm_medium=web2x&context=3
2. https://mickey.dev/posts/go-build-tags-testing/
ran locally but rm_test testscript is failing (unrelated to this?)

[lagobot] add integration tag to separate the tests

---

testscripts/testrunner/examplesrunner.go

The pipenv stuff is slow, because it seems to not respect the nix packages cache? Not fully sure. We should debug it.
But we can land it for now, since we are no longer running examples tests on PRs. They will be run on `main` soon.

[lagobot] enable pipenv

---

.github/workflows/cli-tests.yaml

The example-tests take too long to run, so they only run if DEVBOX_EXAMPLE_TESTS are enabled.
In CICD, we do not run them on regular PRs.
We want to run the example-tests on `main` or if the workflow_dispatch has `input.run-example-tests` set to `true` (for debugging)
Github Action run for this PR:
1. Cli tests ran in 1 min 23 sec https://github.com/jetpack-io/devbox/actions/runs/4515550386/jobs/7952967257
2. I manually did a workflow dispatch with `run-example-tests` enabled. Cli tests ran in 7 min https://github.com/jetpack-io/devbox/actions/runs/4515569436/jobs/7953008609

[lagobot] run cli-tests with DEVBOX_EXAMPLE_TESTS on main or input.run-example-tests

---

.github/workflows/cli-tests.yaml

this needs to be longer for lagobot tests
will test on landing

[lagobot] extend macos test timeout to 15 mins

---

internal/impl/devbox.go
internal/impl/generate.go

Fixes https://github.com/jetpack-io/devbox/issues/829
`run` and `shell` always call generate but using `shell --print-env` and `shellenv` don't. This means that sometimes the `.devbox` directory might be out of date (e.g. when we turned on flakes, not everyone has `flake.nix` file). Since not all workflows involve `shell` and `run`, some users never update it. For performance reasons, we only update if the devbox version doesn't match whatever version created the `.devbox` dir.
This change may not be sufficient to fix all cases, but it fixes the attached issue.
```bash
rm .devbox/gen/flake/flake.nix
devbox shellenv > /dev/null
rm .devbox/gen/flake/flake.nix
devbox shell --print-env > /dev/nul
``
no error (previously this gave me same error as issue)

[shellenv] PrintEnv should generate just in case

---

.github/workflows/cli-tests.yaml
internal/impl/generate.go

This fixed a bad path (was missing root dir) when writing `.devbox/version` file.
I also changed out cli-tests so that it runs example tests in PRs (but we should not require them)
Untested

[direnv] Fix version path, run example tests on PRs

---

testscripts/testrunner/examplesrunner.go

**Problem:**
If we have a `.devbox` directory in an example project, then running the testscript
seems to fail. Something about copying that `.devbox` directory is breaking some logic.
We should clear the `.devbox` directory before we execute the testscript.
**Approach:**
In this PR, I clear the `.devbox` directory in the example project __before__ 
copying the contents over into the testscript's workdir.
This has the downside that if we have a `devbox shell` active for that project,
then its `.devbox` directory will get cleared out under it. This is sub-optimal
but also not a common scenario.
I tried deleting the `.devbox` directory __after__ copying it into the testscript's workdir,
but that failed. I think but couldn't confirm that it was due to some permissions issue.
for …

[lagobot] clear .devbox dirs

---

internal/impl/shell_test.go

Looks like this writeShellrc functionality is still valid?
anyway, we can remove this env-var call
test passed locally

[UnifiedEnv] remove env-var from shell_test

---

.github/workflows/cli-tests.yaml
devbox.json
testscripts/testrunner/examplesrunner.go

My previous PR was done in a rush and I didn't properly verify that it worked (newsflash: it did not).
Changes:
- undo mistaken timeout change of golangci-lint: back from 15 min to 10 min
- add `actionlint` to devbox.json. Useful for spotting errors in github actions, although the lint seems a bit overeager, so we shouldn't enforce it is clean (yet).
- ~add `-v` to `go test` so we get incremental output~
- extend the `-timeout` on `go test`. The default is 10 minutes, but macos tests need longer.
- turn off `pipenv` example project from running on `darwin` in CICD, since it took over 1100 seconds. Will revisit why this is so slow, but aiming to get CICD in a stable place first.

[lagobot] properly extend timeout for macos tests

---

docs/app/docs/cli_reference/devbox_run.md
docs/app/docs/cli_reference/devbox_shell.md
docs/app/docs/guides/scripts.md
internal/boxcli/shell.go

Our docs and inline help for `devbox shell` are not updated to show that `devbox shell -- cmd` is deprecated, potentially leading to a lot of user errors. This PR update the docs and inline help.
We should also try to detect when `--` is passed to `devbox shell`, and direct users to `devbox run` instead
localhost,

Fix incorrect docs on `shell -- cmd`

---

internal/boxcli/root.go

There should only by `devbox version update`
Fixes https://github.com/jetpack-io/devbox/issues/838
`devbox update --help`
`devbox version update --help`

[update] Remove devbox update

---

vscode-extension/package.json
vscode-extension/src/openinvscode.ts
vscode-extension/yarn.lock

- Added handling for open in vscode on windows (show as unsupported will implement handling WSL in future).
- Added handling for devbox not installed for open in vscode by downloading and using launcher script.
See steps in #804

[vscode-extension] Handling for window os and devbox not installed

---

.goreleaser.yaml

Add the `-trimpath` flag to release builds so that log lines and stack traces don't contain absolute paths to source files.
Before:
/Users/gcurtis/src/devbox/internal/impl/devbox.go in Open at line 92
After:
go.jetpack.io/devbox/internal/impl/devbox.go in Open at line 92
Also remove the duplicated `-s -w` flags in `ldflags`.

.goreleaser.yaml: add -trimpath; fix ldflags

---

.golangci.yml
internal/debug/debug.go
internal/redact/redact.go
internal/redact/redact_test.go

Package redact implements functions to redact sensitive information from errors. A basic example is:
name := "Alex"
id := 5
err := redact.Errorf("error getting user %s with ID %d",
name, Safe(id))
fmt.Println(err)
// error getting user Alex with ID 5
fmt.Println(redact.Error(err))
// error getting user <redacted string> with ID 5
See the package docs and tests for more examples.
This will allow us to get more information in Sentry without sending any identifying information.

redact: package for redacting error messages

---

internal/impl/devbox.go
internal/plugin/plugin.go
internal/plugin/rm.go
internal/services/services.go
internal/wrapnix/wrapper.go

This creates symlinks for all dirs in profile dir except `bin` (because that has wrappers). Also moved bin dir from
`.devbox/virtenv/bin` to `.devbox/virtenv/.wrappers/bin`
and all support symlinks are in `.devbox/virtenv/.wrappers`. This ensures we can't have collisions with plugin data which is stored in `.devbox/virtenv/[plugin-name]`
This fixes https://github.com/jetpack-io/devbox/issues/851
```
devbox shell 
ls -al .devbox/virtenv
ls -al .devbox/virtenv/.wrappers
which go
```
Also tested mariadb example

[virtenv] Create symlinks for support dirs, move wrappers to a subdir.

---

.golangci.yml
internal/boxcli/featureflag/feature.go
internal/boxcli/midcobra/debug.go
internal/boxcli/midcobra/midcobra.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/midcobra/trace.go
internal/boxcli/root.go
internal/build/build.go
internal/cloud/openssh/sshshim/command.go
internal/debug/debug.go
internal/nix/install.go
internal/redact/redact.go
internal/redact/redact_test.go
internal/telemetry/segment.go
internal/telemetry/sentry.go
internal/telemetry/telemetry.go

Clean up and fix telemetry so that it can be actually useful. This commit is rather large because telemetry happens to touch a lot of different things.
Example of what it looks like in Sentry: https://jetpack-io.sentry.io/issues/4047374127
Depends on #841.
Client
------
- Remove unnecessary telemetry configuration, such as `InitOpts`. Make the `build` package the source of truth for version information and link-time variables. Generate a global execution ID once at startup.
- Standardize the contexts to use names and values recognized by Sentry.
- Remove arbitrary CLI args and DEVBOX_ environment variables from the context, as these were leaking information.
Errors
------
- In combination with the `redact` package, errors can now include data that has been marked as safe for telemetry.
- …

telemetry: improve stack traces, error names, contexts

---

internal/impl/shellrc_fish.tmpl

In [fish 3.4.0](https://fishshell.com/docs/current/relnotes.html#id16), command substitution was added to enable bash-style: `$(var)`. The reported bug is from a user who is using an older version 3.3.
In this PR, I drop the `$(var)` in favor of the older command substitution of `(var)`.
One interesting point to note is that (from the above announcement post) one can use `(expr | string collect)` to prevent line splitting of the `expr` results. I use this in the evaluation of `devbox shellenv`. I _think_ this makes sense, but not totally sure. [Docs for string collect are here](https://fishshell.com/docs/current/cmds/string-collect.html).
For `(pwd)` I do not use `string collect` since I expect it to be just one line.
Fixes #850 
1. used https://lazamar.co.uk/nix-versions/ to find the …

[fish] fix command substitution to support older fish shells

---

internal/plugin/plugin.go

We were not creating the plugin dir if there were no files in it but the redis plugin depends on the directory existing. Solution is to always create directory.
Fixes https://github.com/jetpack-io/devbox/issues/856
```
devbox add redis
devbox services start redis
```

[plugins] Always create plugin dir

---

.github/workflows/cli-tests.yaml

The macos tests seem to timeout fairly regularly (though not always).
I'm bumping the non-macos tests timeout in anticipation of us hitting this limit
once we add more tests for redis, and other databases.
In a separate line of work, we should find a way to have these tests run faster.
buildkite run should be green

bump the timeouts for example tests

---

internal/boxcli/midcobra/telemetry.go
internal/boxcli/root.go
internal/telemetry/sentry.go
internal/telemetry/telemetry.go

Instead of immediately sending errors to Sentry, write them to an XDG state directory as JSON and then upload them in a separate process. This allows devbox to exit faster (Segment still uploads synchronously).
Error reporting works by executing another devbox process with a single "bug" argument (i.e., `devbox bug`). This argument causes the child devbox process to immediately upload any Sentry events and then exit. It skips all other initialization. Because the parent devbox process exits without waiting for the child, the child process may become orphaned. There's a 3 second timeout for uploading events to help ensure that the process always exits.

telemetry: report errors in separate process

---

.github/workflows/cli-release.yml

Use the Sentry GitHub action to create releases for dev and prod. This should enable better tracking of issues + versions.

ci: create Sentry release

---

internal/boxcli/add.go
internal/boxcli/cloud.go
internal/boxcli/gen-docs.go
internal/boxcli/generate.go
internal/boxcli/global.go
internal/boxcli/info.go
internal/boxcli/init.go
internal/boxcli/install.go
internal/boxcli/log.go
internal/boxcli/plan.go
internal/boxcli/rm.go
internal/boxcli/root.go
internal/boxcli/run.go
internal/boxcli/services.go
internal/boxcli/setup.go
internal/boxcli/shell.go
internal/boxcli/version.go

1. Use imperative sentences for command descriptions
2. Use exported functions for commands added to the root

chore: update descriptions for commands

---

docs/app/docs/installing_devbox.mdx

Fix typo in command for installing on non-NixOS
By running the corrected command

Fix typo in installing_devbox.mdx

---

internal/impl/devbox.go

Skip interactive survey if devbox is not executed in a terminal. When `devbox init` or `devbox generate direnv` is called in a dockerfile for example, we do not want to prompt for user input.
I tried `echo 'y' | devbox generate direnv` or `yes | devbox generate direnv` or `devbox generate direnv <<< "y"`. None of them worked.
Bug in the survey package: https://github.com/go-survey/survey/issues/394
./dist/devbox init (interactive mode)
docker build -t devbox-cli .
docker run --entrypoint=/bin/sh -ti devbox-cli (non interactive mode)

Skip interactive survey if devbox is not executed in a terminal

---

internal/impl/devbox.go
internal/impl/generate.go

This PR generates devbox-script files in `generateShellFiles`.
1. This means that script files are now generated via `devbox generate debug` as well.
2. I changed the function generateShellFiles to be a method on the Devbox struct, so that
we can call the writeScriptsToFiles method.
did `devbox generate debug` and observed that `.devbox/gen/scripts` folder was filled

[devbox] generate script files when we generate shell files

---

devbox.go
internal/boxcli/services.go
internal/impl/devbox.go
internal/services/client.go
plugins/postgresql/process-compose.yaml

`devbox services ls` can now show the services available in your project, as well as the ones running in process-compose with their status: 
Still needs some tweaking to only show services, and not all processes
Localhost on examples. Should not affect backwards compatibility

List Services and Status via Process Compose

---

internal/boxcli/shellenv.go

Add init hook flag to shellenv command. This prints out the env variables and the init hooks to stdout, and should replicate the behavior of a `devbox shell` within the context of the current shell.
```
devbox shellenv --init-hook
```
And changing the shell by
```
eval "$(devbox shellenv --init-hook)"
```

Add init hook flag to shellenv command

---

internal/impl/devbox.go
internal/nix/nix.go

Re-add profile to path to ensure we expose binaries exposed by `propagated-build-inputs`
Some packages like `curl` expose binaries using `propagated-build-inputs`. We need to make sure these are in path.
A better solution is to just revert to using profile to create all the wrappers. This requires some work to avoid breaking php and Haskell because they do some pre-processing in the top level flake that would not be in the files installed in the profile. 
```
devbox shell
which curl # shows system curl
devbox add curl
hash -r
which curl # shows profile curl
```

[nix] Re-add profile to path

---

testscripts/run/env.test.txt
testscripts/testrunner/examplesrunner.go
testscripts/testrunner/setupenv.go
testscripts/testrunner/testrunner.go

We set `HOME` for testscripts. 
Previously, we discussed in #744 wanting to enable HOME env-var, so I do it now.
Will follow up with the other recommendation for explicitly setting up the env in testscripts.
Motivation:
In the next PR, the xdg.RuntimeDirSubpath change creates a HOME/.local/run/ directory and sets 0700 permissions.
We need `HOME` to be valid to exercise this code.
`go test -v -run TestScripts ./testscripts/...`

set HOME for testscripts

---

internal/nix/nixstore/indexpkgs.nix

This expression generates a JSON blob containing the metadata for every derivation in nixpkgs, similar to that of hydra's `packages.json`. It differs in that it also includes the store path for each package and contains the system that generated the index. The system field lets us know which packages can actually be evaluated for a given system, which tends to differ from the systems that claim to be supported in the metadata.
This isn't used anywhere yet, but it can be manually called as a script to generate the JSON for prototyping or debugging.

nixstore: Nix expression for generating a nixpkgs index

---

internal/boxcli/args.go
internal/boxcli/generate.go
internal/boxcli/plan.go
internal/boxcli/run.go
internal/boxcli/shell.go

Getting config path from arguments is deprecated, so I remove related code and let config path be fetched from --config flag only.

chore: get config path from --config only

---

examples/development/rust/rust-stable-hello-world/devbox.json
examples/stacks/django/devbox.json
examples/stacks/lapp-stack/devbox.json
examples/stacks/lepp-stack/devbox.json
internal/boxcli/featureflag/script_exit_on_error.go
internal/impl/devbox.go
testscripts/testrunner/run_test.test.txt

RFC: we should have failures in the devbox-scripts reflect in a non-zero exit status
from `devbox run <script>`.
There is some risk that customers whose code was previously running will now fail. However, their scripts were indeed failing and its just that this failure will now be exposed. 
Update: Based on John's feedback in a comment below I am adding a featuregate that is activated in examples tests. We'll make a plan for rolling this out to users, in a way that is not a big surprise for them.
TODO:
Removed `curl` from `lepp-stack` packages, and ran:
```
DEVBOX_EXAMPLE_TESTS=1 DEVBOX_DEBUG=0 go test -count 1 -v -run TestExamples/stacks_lepp ./testscripts/...
```
This failed, demonstrating that the `set -e` was working as intended.
I then added the `curl` back and the above command …

[example tests] generate "set -e" to exit scripts upon failure

---

devbox.go
internal/boxcli/services.go
internal/impl/devbox.go
internal/services/client.go
internal/services/manager.go
internal/services/services.go

This PR allows users to run process-compose for multiple devbox projects at the same time, without any collisions or undesirable behavior. This does _not_ provide any isolation between services in different projects, but it does let a user effectively manage them on a per project basis
When starting process-compose in a devbox project, we create a UUID for the project, and then store the port + PID of the process-compose instance in a global `process-compose.json` file, with the UUID as the key. 
When making client requests to process-compose, a devbox project looks up the UUID for the project in the .devbox directory, gets the right port, and then makes the request. This ensures each project is communicating with the correct process-compose instance to start and stop services. 
Devbox …

Multi-instance Process Compose

---

.envrc

- enable us to use direnv in the repo
enabled direnv as per: https://direnv.net/docs/hook.html
verified via:
```
~/code/jetpack on ☁️  (us-east-2) on ☁️  savil.srivastava@jetpack.io
❯ cd devbox
direnv: loading ~/code/jetpack/devbox/.envrc
direnv: using devbox
direnv: using nix .devbox/gen/shell.nix
direnv: ([/usr/local/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
this path will be fetched (1.05 MiB download, 6.52 MiB unpacked):
/nix/store/vsm70r60gfg7bkzcyybm932qfc3cirl9-bash-interactive-5.2-p15
copying path '/nix/store/vsm70r60gfg7bkzcyybm932qfc3cirl9-bash-interactive-5.2-p15' from 'https://cache.nixos.org'...
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +DEVBOX_OG_PATH +DEVBOX_SHELL_ENABLED +GETTEXTDATADIRS +HOST_PATH +IN_NIX_SHELL +LD +LD_DYLD_PATH …
```

[devbox] add .envrc file to repo

---

vscode-extension/CHANGELOG.md
vscode-extension/README.md
vscode-extension/package.json

[vscode-extension] Prep for version 0.0.6 release of vscode extension

---

examples/stacks/lapp-stack/devbox.json
examples/stacks/lepp-stack/devbox.json

The lepp-stack test was sporadically failing with unable to find the working postgres socket.
I think but not 100% this could be because the `devbox services start` completes but postgres
may take a short while to fully initialize before it is ready. So, here I inject
a one second sleep to hopefully let postgres be ready.
`DEVBOX_EXAMPLE_TESTS=1 DEVBOX_DEBUG=0 go test -v -count 1 -run TestExamples/stacks_l ./testscripts/...`

[examples tests] insert one second sleep for services to initialize

---

.github/workflows/cli-tests.yaml

The test-step `cli-test` timeout needs to be bigger than the `go test --timeout` value
since we run other steps prior to it.
Also bumped the go test timeout, just to be safe.
Obviously, this is not a long term solution. We need a way of caching the nix packages,
but in the meantime prefer to have the Github Actions be Green.
buildkite run should be green

[cicd] bump timeouts for cli-tests

---

.github/workflows/cli-tests.yaml

The current test output when the macos tests timeout is not helpful. We don't know
if any of the specific example tests is taking longer:
https://github.com/jetpack-io/devbox/actions/runs/4685049031/jobs/8301872973
In this PR:
1. set `go test -v`. This should stream the output as the tests run. It also has 
the benefit of printing a summary of which testscripts passed versus failed (tho 
not useful for timeouts). I use this always locally when running these example testscripts.
2. turn off DEVBOX_DEBUG for example testscripts. The devbox-internal logging is
less useful for examples testscripts, and makes it hard to follow where in the examples's `run_test` the script
is failing or getting stuck on. 
DEVBOX_DEBUG _is_ useful for other unit tests so left it on for those.
buildkite run, will …

[CICD] stream go test output, and turn off DEVBOX_DEBUG for example tests

---

.github/workflows/cli-tests.yaml

Until we figure out a caching strategy we should disable example tests on macs.
CICD

[CICD] Don't run example tests on mac

---

.envrc
internal/boxcli/generate.go
internal/boxcli/init.go
internal/boxcli/setup.go
internal/impl/devbox.go
internal/impl/tmpl/envrc.tmpl
internal/nix/install.go

Two changes:
1. Run `shellenv --init-hook` to ensure correctness. There will be a small perf hit if the init-hooks are very slow, but we are biasing towards correctness over perf.
- To improve the perf, we can distinguish a generic init hook versus shell-specific init hook, later on.
2. Ensure packages are installed and shell files are generated. This is important because we check for existence of `.devbox/gen/flake/flake.nix` prior to running `devbox shellenv --init-hook`.
- since this requires `nix`, we add `ensureNixInstalled` to `devbox init` and `devbox generate direnv` commands.
- I refactored to call `ensureNixInstalled` from within `GenerateEnvrc` so that we don't block `devbox init` if envrc is not required.
```
> rm -rf .devbox
> devbox generate direnv --force
> cd ..
> which go …
```

[direnv] run init-hooks in envrc, and generate shell files prior to gen envrc

---

internal/boxcli/root.go

This provides a "single view" listing of all available commands.
Sometimes I find myself wanting a global view to quickly find something.
credit to chatgpt for writing some of this.
Its a hidden command, since the printed view is not polished.
```
❯ devbox all
devbox              Instant, easy, predictable development environments
add <pkg>...        Add a new package to your devbox
all                 List all commands, including hidden ones
cloud               [Preview] Remote development environments on the cloud
forward <local-port>:<remote-port> | :<remote-port> | stop | list[Preview] Port forward a local port to a remote devbox cloud port
list                List all port forwards managed by devbox
stop                Stop all port forwards managed by devbox
init …
```

[devbox] add hidden all command to list all sub-commands (including hidden)

---

devbox.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/impl/devbox.go

We want the `--init-hooks` flag to run both shell init hooks and plugin hooks
of packages
Need to check with @lagoja for a good repro case.
Did a sanity test that the local `devbox` repo works fine.
re-generated the `examples/cloud_development/temporal` .envrc. Upon entering the directory it sourced the python virtualenv without errors.

[direnv] ensure shellenv --init-hooks also runs plugin hooks

---

.envrc
examples/cloud_development/temporal/.envrc
examples/data_science/jupyter/.envrc
examples/development/ruby/.envrc
examples/servers/nginx/.envrc
examples/stacks/jekyll/.envrc

Ran `devbox generate direnv --force` in these directories.
Note, now that we ensure packages are installed during this step for one or two of these it took a short while, but better than
a long pause when `cd`-ing into the directory.
didn't test

[direnv] update envrcs in projects

---

docs/app/docs/guides/using_flakes.md

Update Flakes.md Typos

---

.golangci.yml
internal/boxcli/featureflag/feature.go
internal/boxcli/generate/devcontainer_util.go
internal/fileutil/fileutil.go
internal/impl/devbox.go
internal/impl/shell.go
internal/services/config.go
internal/services/status.go

1. Reduce cognitive complexity to 30
2. remove unnecessary nolint comments
3. Correct some comments
4. Remove unused `IsSymlink()`
Build and test.

Reduce cognitive complexity

---

internal/boxcli/shell.go

title says it
- `devbox shell --print-env`
- confirm output does not contain `. /path/to/.hooks.sh`

[direnv] change default hooks for shell --print-env

---

internal/impl/generate.go
internal/impl/tmpl/shell.nix.tmpl

We can bring back the `shell.nix` file to ensure older .envrc files work.
did `devbox shell` and saw that `.devbox/gen/shell.nix` exists.
```
❯ cat .devbox/gen/shell.nix
let
pkgs = import
(fetchTarball {
url = "https://github.com/nixos/nixpkgs/archive/3364b5b117f65fe1ce65a3cdd5612a078a3b31e3.tar.gz";
})
{ };
in
with pkgs;
mkShell {
packages = [
go_1_20
golangci-lint
actionlint
];
}
```

bring back shell.nix

---

internal/impl/packages.go
internal/searcher/client.go
internal/searcher/model.go
internal/searcher/searcher.go

Stacked on https://github.com/jetpack-io/devbox/pull/916
This implements `devbox add pkg@version`. It stores the nix flake reference in the devbox.json but this is temporary. In a follow up we will implement a lock file that will store the reference instead.
```bash
devbox add php@8.1 # success
devbox add python39@3.9.167 
Error: No results found for "python39@3.9.167". Available versions 3.9.16, 3.9.1
devbox add python39@3.9.16 # success
devbox shell
(devbox) ➜  devbox git:(landau/version-add) ✗ python --version
Python 3.9.16
(devbox) ➜  devbox git:(landau/version-add) ✗ php --version
PHP 8.1.17 (cli) (built: Mar 22 2023 21:22:45) (NTS)
```
```bash
cat devbox.json
```
```json
{
"packages": [
"go_1_20",
"golangci-lint",
"actionlint", …
```

[add] Implemented devbox add granular package selection

---

internal/impl/devbox.go
internal/impl/envvars.go
internal/impl/testdata/shellrc/basic/shellrc.golden

This hardens the `devbox shellenv --init-hook` command so that it works without quotes.
Did the following for `zsh`, `bash`, and `fish`:
- `eval "$(direnv hook ...)"`
- `cd devbox`
- edit .envrc to not quote the eval
- `cd ..; cd devbox`

impl: semicolon at the end of env string commands

---

internal/boxcli/generate.go

`ssh-config` is quite different from other sub-commands, so I move its part out of `runGenerateCmd`. I also wrap its error with `errors.WithStack`.

chore: move ssh-config generation out of general generating process and wrap its error

---

internal/conf/doc.go
internal/conf/env.go
internal/impl/devbox.go
internal/plugin/plugin.go

1. correct package comment
2. adjust `OSExpandEnvMap`'s parameters order
3. use `nil` check for `existingEnv` to replace `if v, ok := existingEnv[value]; ok { ... }` because non-existing key's value are `""`

chore: correct package comment and tweak OSExpandEnvMap

---

internal/boxcli/global.go
internal/boxcli/install.go

Pretty much title says it.
This is using the same concept as `devbox global shellenv` except it doesn't output the computed environment.
Since we check and install packages in shellenv, we can reuse the same logic for devbox install.
- Also updated `devbox install` implementation to be the same as `devbox global install`
- compile
- edit the global devbox.json (`~/.local/share/devbox/global/default/devbox.json`) and add packages to it
- ./devbox global install

[devbox global] Added devbox global install command

---

internal/wrapnix/wrapper.sh.tmpl

Without exec, the wrapper script spawns a new process and the new process might not receive a signal sent to the wrapper script's pid. With exec, the wrapper process is replaced by the new process and the pid stays the same.
Example (without exec):
1. Supervisord starts process X which has been wrapped.
2. X wrapper script's pid is 10
3. X's wrapper script starts actual X with pid 11
4. Supervisord attempts to stop X on pid 10 by sending SIGTERM
5. X's wrapper script is terminated
6. Actual X is still running because it never received the signal
By editing the files locally.

Replace current process instead of spawning a new one.

---

vscode-extension/src/openinvscode.ts

This fix ensures the ssh keys directory exists. Previously, the call to
`const fileHandler = await open(prkeyPath, 'w');`
would fail if the prKeyPath's directory did not exist.
Followed the Test Plan from https://github.com/jetpack-io/devbox/pull/804.
First: `rm -rf ~/.devbox/config/ssh/keys` to remove the "keys" folder.
- Open `vscode-extension` folder via `code vscode-extension`. 
- In vscode terminal: `yarn run pretest` to compile and lint the extension.
- For the debugger, we need a file to be open. I suggest `openinvscode.ts`. 
- Then click the icon on the left bar for "Run and Debug" and press the "Run and Debug" button in the left pane that opens. A new vscode window pops up. Ensure you have focus on it as "the last vscode window".
- Go to `devbox.sh` and open some repo in it. …

[vscode extension] ensure directory exists for ssh keys

---

internal/cloud/cloud.go
internal/cloud/openssh/config.go
internal/cloud/openssh/sshshim/generate.go
internal/cuecfg/cuecfg.go
internal/cuecfg/hash.go
internal/fileutil/fileutil.go
internal/fileutil/untar.go
internal/impl/devbox.go
internal/impl/generate.go
internal/impl/global.go
internal/impl/packages.go
internal/impl/shell.go
internal/impl/shell_test.go
internal/impl/util.go
internal/lockfile/local.go
internal/nix/nix.go
internal/nix/nixpkgs.go
internal/nix/profile.go
internal/plugin/plugin.go
internal/plugin/rm.go
internal/plugin/symlink.go
internal/services/status.go
internal/telemetry/sentry.go
internal/wrapnix/wrapper.go
testscripts/testrunner/examplesrunner.go

`os.Isxxx` predates errors.Is. It only supports errors returned by the os package. New code should use `errors.Is`.
1. replace `os.IsNotExist(err)` with `errors.Is(err, fs.ErrNotExist)`
2. replace `os.IsExist(err)` with `errors.Is(err, fs.ErrExist)`

[cleanup] update checks for exist errors and not exist errors

---

vscode-extension/CHANGELOG.md
vscode-extension/package.json

Inspired by #903
Not tested.
Will release via manually running https://github.com/jetpack-io/devbox/actions/workflows/vscode-ext-release.yaml

[vscode extension] bump version and add to CHANGELOG

---

internal/boxcli/global.go
internal/impl/global.go
testscripts/add/add.test.txt
testscripts/add/global_add.test.txt

Makes a couple of fixes:
1. `devbox global add` should avoid returning an error status code if devbox-global-bin-path is not in PATH. We should instead print a warning, and return a 0 code.
2. `devbox global shellenv` should call `ensureNixInstalled` to find `nix` if not in `PATH`.
Adds basic test cases for multiple packages for `devbox add` and `devbox global add`
`go test -v -run TestScripts/add\.test ./testscripts/...`
`go test -v -run TestScripts/global_add\.test ./testscripts/...`

[tests] global-add should not fail if global-bins-not-in-path and add testscript unit tests for add and global-add

---

internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

We're relying on binaries getting called within the same directory hierarchy where the original devbox.json lives but this can break down in the following cases:
* global
* Multiple devbox.json within the hirarchy
* if you navigate outisde the directory with the devbox.json
```bash
devbox shell
devbox add hello # to change the env hash
cd ~/
go version
```
Also tested global:
```
eval "$(devbox global shellenv)"
devbox global add hello  # to change the env hash
go version
```

[easy][wrappers] Ensure wrappers use correct project dir

---

internal/impl/devbox.go
internal/impl/global.go

Two fixes:
* We were computing the wrong hash for projectDir. (using config contents instead). We want it to be stable even when adding packages so dir is the correct one.
* In devbox global we were showing the shellenv warning even when user had already shellenved.
`devbox global add hello`

[easy][global] Don't show eval message if already shellenved

---

.github/workflows/cli-post-release.yml

We want to introduce a "stable" channel, as part of turning off auto-update.
As a first step, we'll begin publishing to the `stable` bucket in S3, in addition to the existing `latest`.
Once we deploy the new launcher and binary that turns off auto-updating, we'll drop `latest` from this github action.
have not tested. Do I need to pre-create the S3 bucket?

[release] also release to stable-channel's S3 bucket

---

internal/boxcli/root.go
internal/vercheck/vercheck.go
internal/vercheck/vercheck_test.go

This PR updates the `vercheck.CheckVersion` to check launcher and devbox CLI binary versions,
and print a notice if either is out-of-date.
I print the message in all yellow similar to flyctl. But open to other renderings.
`go test -run TestCheckVersion ./internal/vercheck/...`

[version] part 2: print notice if devbox CLI binary or launcher version is outdated

---

internal/boxcli/root.go
internal/boxcli/version.go
internal/vercheck/vercheck.go
internal/vercheck/vercheck_test.go

**Motivation:**
We want to disable auto-update for devbox CLIs. This will minimize unexpected interruptions for our users.
To do so, we are going to do the following:
1. Update `launch.sh` file in `axiom` repo to write new versions to `{XDG_CACHE_HOME}/devbox/available-version`. https://github.com/jetpack-io/axiom/pull/3150
2. Change `devbox version update` to update the launcher (if needed) and else, update the CLI binary. (this PR).
3. Change the `vercheck.CheckVersion` that runs in `boxcli/root.go` on every command to check if the launcher or CLI binary versions are out-of-date, and to print a notice if so. (reviewed in #966, but merged into this PR)
We will cherry-pick ~these two PRs~ this PR for the next release so auto-update stops for users.
**Implementation:**
This PR enables …

[version] part 1: update command for devbox and launcher updates

---

docs/app/docs/devbox_examples/languages/zig.md

There were copy paste leftovers from go.md.

doc: Fix typo in zig.md

---

devbox.go
devbox.json
devbox.lock
internal/boxcli/root.go
internal/boxcli/update.go
internal/impl/devbox.go
internal/impl/update.go
internal/lock/lockfile.go
internal/lock/resolvers.go
internal/nix/input.go
internal/nix/input_test.go
internal/nix/profile.go
internal/planner/plansdk/flake.go
internal/searcher/client.go

Implements `devbox update [pkg]...`
It basically just re-resolves version. If there's a new version that satisfies constraints, it installs it and removes the previous one.
Other improvements:
* implemented `findPackageByName` which allows us to use `devbox update go` instead of `devbox update go@1.20`. In follow up we can also use this for `devbox rm` 
* flake.nix optimization: If there are no dev packages (this is a legacy planner concept that is almost never used) and we add at least one nixpkgs flake input, we use that input for mkShell. This avoids having to download an additional nixpkgs.
* Manually modified lockfile to point to older versions and ran `devbox update` and `devbox update go`
* Inspected flake.nix 
* Inspected nix profile

[update] Implement devbox update

---

internal/boxcli/version.go
internal/envir/env.go
internal/envir/util.go
internal/vercheck/vercheck.go
internal/vercheck/vercheck_test.go

1. replace constants with existing envir constants
2. add new envir constants

chore: use constants defined in envir in version check

---

.github/workflows/cli-post-release.yml

This is so that users who are on the old launcher (pre version `0.2.0`) do not get auto-updated.
Stop updating latest channel, only stable gets updated.

cli-post-release.yml: freeze latest channel

---

internal/nix/input.go
internal/nix/input_test.go

Fixes 2 bugs:
* Avoid triple slashes that can make comparing urls break when adding flakes (this was affecting correct removal of profile packages and also detecting that they were already installed)
* Fix package validation for non-versioned packages (They should use nix search instead of new search service)
* `devbox add sqlite3`  showed error and was not added to devbox.json
* In examples/flake/php added and removed packages and confirmed profile remained in sync.

[easy][bugs] Fix 2 package input bugs

---

internal/boxcli/root.go

For `devbox global shellenv` which may be used in the user's shellrc file, its
not ideal to show the update notice everytime the user opens their shell (likely
for a non-devbox purpose).
For devbox engineers, we need not see the notice everytime we execute a devbox command
during development.
Added `fmt.Fprintf(os.Stderr, "version was checked")` in `boxcli/root.go` just prior
to calling `vercheck.BuildVersion`. Then did `devbox global shellenv 1> /dev/null`,
and saw that "version was checked" was not printed. As a sanity test, verified
that it was printed for `devbox shellenv 1> /dev/null`.
Also ran `devbox run build` and saw that the notice was not printed since I'd built
the `devbox` originally with the code of this PR.

[update] Silence update notice for devbox-global-shellenv and development-devbox

---

.github/workflows/cli-release.yml
.goreleaser.yaml

This needed some changes for it to work again. Changes:
* Renamed to alpha
* Create a new tag of the form `ALPHA_TAG=0.0.0-alpha.$(date +%Y-%m-%d)` This tag is semver.
* Run goreleaser --snapshot with this tag as version.
* Create/update github release with same name as tag.
This almost works with new CLI launcher. It has a regex that is not completely accurate so it complains that a version ending in `.2023-01-1` is not valid.
Github actions

[CICD] Fix pre-release job and create new edge release process.

---

internal/impl/devbox.go
internal/impl/flakes.go
internal/impl/packages.go
internal/lock/lockfile.go
internal/nix/input.go
internal/nix/nix.go
internal/nix/search.go

Fixes a few bugs:
* Remove panic
* If package can't be found for current system, search on all systems so we can return better error message.
* Don't automatically write to disk when resolving lockfile packages. That way if there's an error we don't leave the lockfile in a bad state.
```bash
➜  devbox git:(landau/fix-panic) ✗ devbox add ripgrep@12
There was an error installing nix packages: ripgrep@12. Packages were not added to devbox.json
Error: Package "ripgrep@12" was found, but we're unable to build it for your system. You may need to choose another version or write a custom flake.
```
```bash
➜  devbox git:(landau/fix-panic) ✗ devbox add foobar1@8
Error: foobar1@8: package not found
To search for packages use https://search.nixos.org/packages
```
```bash
devbox add php@8
```
```bash …
```

[versioned] Deal with packages that don't build on system

---

internal/impl/global.go
internal/impl/tmpl/shell.nix.tmpl
internal/planner/plansdk/plansdk.go

Fixes 2 unrelated bugs:
* Create current symlink if needed. This has no user impact, but is causing devbox cloud to break. It is also needed for future multi-profile support.
* Ensure shell.nix works by including correct URL in fetchTarball. This affects direnv users that have a legacy .envrc file. New/updated users are unaffected. Fixes https://github.com/jetpack-io/devbox/issues/1010
cc: @Lagoja 
* Deleted current symlink, and saw it being recreated.
* `nix-shell .devbox/gen/shell.nix`

[bugs] Fix shell.nix bug and ensure current symlink

---

internal/boxcli/root.go
internal/vercheck/vercheck.go
internal/vercheck/vercheck_test.go

Some devbox commands like `devbox shell` may invoke other devbox commands. For example,
`devbox shell` generates a shellrc file that calls `devbox log`. This results in 
multiple "update version" notices being printed for the same devbox command invocation.
To avoid this, we set an env-var after printing the notice, and unset that env-var
when this devbox command will exit. Note, I keep this env-var inside vercheck
to maintain encapsulation, instead of putting it in envir package.
I also pushed some of the skipping checks from `root.go` inside `vercheck` for
(1) better encapsulation (2) adding test cases for them.
`go test ./internal/vercheck/...`
For manual testing:
1. `set -gx DEVBOX_LATEST_VERSION 0.5.0`
2. modify binary to `vercheck` to have `currentDevboxVersion = 0.4.8` and …

[version check] Avoid re-printing update notice in child devbox commands

---

testscripts/languages/php.test.txt

When reviewing #1000, I found myself wanting to ensure the test plan of #648 was used.
So, I added it to testscripts. It works :)
`go test -run TestScripts/php ./testscripts/...`

[testscripts] augment php testscrpt to remove and re-add a php-extension

---

.github/workflows/cli-release.yml
.github/workflows/cli-tests.yaml

We were double caching in some places. 
I remove `cache: true` because this is default in v4 go action.
@loreto any reason cache was disabled for release?
CICD

[cicd] Simplify go CICD cache

---

internal/fileutil/fileutil.go
internal/impl/devbox.go

Checks for old .envrc file if all following is true:
- usePrintDevEnvCache is false
- .envrc file exists
- DEVBOX_NO_ENVRC_UPDATE env variable is not set to 1
Then checks if the .envrc file contains the 1 line that we have in new .envrc file:
```eval "$(devbox generate direnv --print-envrc)"```
if the file doesn't contain this line it prints out a warning.
- compile
- prepend path to compiled binary to PATH
- create an empty dir
- `devbox init`
- `touch .envrc` (don't run `devbox generate direnv`)
- copy the following to .envrc
```
eval "$(../devbox/dist/devbox generate direnv --print-envrc)"
```
replace `../devbox/dist/devbox` with a relative path to the compiled devbox binary
- then run `direnv allow` or run `devbox shell`
- it should show the warning about the content of your envrc …

[direnv] Added warning for old envrc content

---

devbox.go
internal/boxcli/global.go
internal/boxcli/install.go
internal/boxcli/shellenv.go
internal/impl/envvars.go
internal/impl/global.go

This PR is in preparation for adding more global commands (update, etc) and to allow `global pull` to download additional data.
It simplifies how global works by removing global only code-paths and reusing projects code-paths where possible. (it removes 3 lines for every line it adds :) )
It turns the global parent command into an alias for `--config [global-path]` which let's us make any command global fairly easily.
One semi-significant change this makes is that the global nix profile is changing. It was previously stored in `~/.local/share/devbox/global/default/profile`  (which is at the same level as the devbox.json). It is now stored in the more familiar `~/.local/share/devbox/global/default/.devbox/nix/profile/default` which is the same as regular projects. This should not affect …

[global] Remove global only functions, make global reuse local code

---

internal/impl/packages.go

Problem:
The local.lock file has an empty field for `lock_file_hash` on the first run.
This probably results in print-dev-env cache misses, and may cause some perf regressions.
Cause:
We were doing `localLock.Update()` first, which writes a hash of the `devbox.lock` file (which is currently empty).
Instead, we should first write the `devbox.lock` file and then the `.devbox/local.lock` file.
```
> cat devbox.json
{
"packages": [
"go@1.20",
"actionlint@1.6.23"
],
"shell": {
"init_hook": null
},
"nixpkgs": {
"commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
}
}⏎
> devbox shellenv
```
BEFORE:
```
> cat .devbox/local.lock
{
"config_hash": "d85415929c9f724a7e0aa2acdf2ecf3de219cc9562462fa94ce161f917112b0f",
"devbox_version": "0.0.0-dev",
"lock_file_hash": "",
"nix_profile_manifest_hash": …
```

[bug fix] write devbox.lock file first, and then write local.lock

---

internal/boxcli/generate/devcontainer_util.go
internal/impl/devbox.go
internal/impl/tmpl/devcontainerDockerfile.tmpl

title says it.
fixes #1028 
- devbox init
- devbox add terraform
- devbox generate devcontainer
- add a file in `.vscode/tasks.json` and put the following json in it:
```
{
"version": "2.0.0",
"tasks": [
{
"label": "terraform version",
"type": "shell",
"command": "terraform version"
}
]
}
```
- `cmd + shift + p` and select "Rebuild and Reopen in Container"
- `cmd + shift + p` and select "Run Task" 
- Choose terraform task to run
- Assert that the output shows terraform version is printed in output

[devcontainer] Added shellenv to dockerfile template

---

docs/app/docs/ide_configuration/direnv.md

Docs update. Docs refer to `devbox generate envrc` when it should be `devbox generate direnv`
Visually? 🤷

[docs] Correct direnv.md reference to `devbox generate direnv`

---

internal/impl/devbox.go

This PR ensures we preserve the XDG_DATA_DIRS env-var by appending the original
value to the end of the new shellenv XDG_DATA_DIRS paths:
`XDG_DATA_DIR={shellenv-XDG_DATA_DIR}:{original-XDG_DATA_DIR}`
I have direnv enabled in my devbox repo
```
> cd ~/code/jetpack
> echo $XDG_DATA_DIRS
some /nix/store/.... path is printed
> cd devbox
> echo $XDG_DATA_DIRS
the original XDG_DATA_DIRS is preserved
BEFORE: this would be empty
```

[shellenv] prepend to XDG_DATA_DIRS, instead of overwriting

---

internal/boxcli/run.go

If merged this change will print available scripts if no arguments are given on the `devbox run` command.
Trivial change, tested with CLI.

feat: add list to devbox run if no args are given

---

internal/impl/flakes.go
internal/nix/input.go
internal/plugin/plugin.go
plugins/haskell/flake.nix
plugins/mariadb/flake.nix
plugins/php/flake.nix

This improves plugins by using attribute path instead of canonical name.
for example, in `php@8.2` the attribute path is `php82` and not `php`. Previously we were using canonical name which may not be the correct version. (and may not even exist).
Since existing PHP example had canonical name that matches attribute name, I changed the php version to `PHP@8.2` and the inspected generated `php/flake.nix`. Also did `devbox run "php -b | grep imagick" to verify plugin worked.

[plugins] Improve how we determine package name in plugins

---

internal/impl/packages.go

The if-condition was ignoring genuine errors
```
> rm -rf <project>/.devbox
> cd <project>
```

[packages] fix error check in pendingPackagesForInstallation

---

internal/templates/template.go

For users and Dockerfile that has no ssh key setup, we need to clone by https
devbox create --template apache

Fix template create when ssh key is not setup

---

internal/boxcli/global.go
internal/boxcli/path.go

Inspired by https://github.com/jetpack-io/devbox/pull/1058
```bash
➜  devbox git:(landau/global-path) devbox global path
/Users/mike/.local/share/devbox/global/default
```

[path] Add global path command

---

devbox.go
internal/boxcli/install.go
internal/impl/devbox.go

Fixes https://github.com/jetpack-io/devbox/issues/1073
The underlying cause of https://github.com/jetpack-io/devbox/issues/1073 is that we were creating bin wrappers in shellenv which can get called a lot (and in parallel) this was leading to race conditions.
We should still try to limit shellenv calls (because they slow things down), but this fixes the race condition.
cc: @bketelsen 
Since I could not repro race condition, I created a setup that simulated it:
* Wrote some testing code that would save a file to /tmp every time create wrappers is called.
* Setup the environment to call a bin wrapper for every command
* Before change, saw new /tmp file being created on every command.
* After change, no new /tmp file was getting created.
* Tested `devbox install` for sanity.

[wrappers] shellenv should not create bin wrappers

---

internal/wrapnix/wrapper.sh.tmpl

Fixes https://github.com/jetpack-io/devbox/issues/1049
In certain cases, shellenv might call a wrapped binary causing an infinite loop. This prevents it. 
Called a test script and confirmed env var was set.

[shellenv] Fix infinite loop

---

docs/app/docs/ide_configuration/direnv.md

Title + added link to direnv extension for vscode
Addresses: #1078 
N/A

[docs] Updated direnv docs to reflect update after v0.5.0

---

.github/workflows/docs-deploy-preview.yaml
README.md
docs/app/docs/devbox_cloud/index.mdx
docs/app/docs/devbox_examples/databases/mariadb.md
docs/app/docs/devbox_examples/databases/postgres.md
docs/app/docs/devbox_examples/databases/redis.md
docs/app/docs/devbox_examples/languages/csharp.md
docs/app/docs/devbox_examples/languages/elixir.md
docs/app/docs/devbox_examples/languages/fsharp.md
docs/app/docs/devbox_examples/languages/go.md
docs/app/docs/devbox_examples/languages/haskell.md
docs/app/docs/devbox_examples/languages/java.md
docs/app/docs/devbox_examples/languages/nim.md
docs/app/docs/devbox_examples/languages/nodejs.md
docs/app/docs/devbox_examples/languages/php.md
docs/app/docs/devbox_examples/languages/python.md
docs/app/docs/devbox_examples/languages/ruby.md
docs/app/docs/devbox_examples/languages/rust.md
docs/app/docs/devbox_examples/languages/zig.md
docs/app/docs/devbox_examples/servers/apache.md
docs/app/docs/devbox_examples/servers/caddy.md
docs/app/docs/devbox_examples/servers/nginx.md
docs/app/docs/devbox_examples/stacks/django.md
docs/app/docs/devbox_examples/stacks/drupal.md
docs/app/docs/devbox_examples/stacks/jekyll.md
docs/app/docs/devbox_examples/stacks/lapp.md
docs/app/docs/devbox_examples/stacks/lepp.md
docs/app/docs/devbox_examples/stacks/rails.md

Update readme `open in devbox.sh` button link, and fix badge images
Markdown preview

Update open in devbox.sh links

---

internal/boxcli/add.go
internal/searcher/client.go

Change error message for devbox add when a package is not found. To repro:
`devbox add hellow@latest`
Original output:
```
Error: No results found for "hellow@latest".
```
New output:
```
Error: No results found for "hellow@latest".
To search for packages, use the `devbox search` command
```
```
devbox add hellow@latest
```

Change error message for devbox add when a package is not found

---

internal/boxcli/gen-docs.go
internal/fileutil/dir.go
internal/pullbox/pullbox.go

1. Get the filemode of the directory before everything inside is deleted and use that mode for re-creation
2. Reuse the `ClearDir` in gen-docs

Keep file mode the same as it is cleared

---

internal/boxcli/cloud.go

Hide devbox cloud cli command for now as we decided that devbox.sh will be the primary way to create a vm, and a user can ssh into that vm directly with local credentials
devbox help

Hide devbox cloud cli command for now in favor of devbox.sh

---

examples/servers/caddy/README.md
examples/servers/caddy/devbox.d/caddy/Caddyfile
examples/servers/caddy/devbox.json
examples/servers/caddy/devbox.lock
plugins/caddy.json
plugins/caddy/Caddyfile
plugins/caddy/process-compose.yaml

Change caddy to run on non privileged ports. I added the following script to the caddy example:
- devbox run start
Since I have a global caddy running on port `2019` for the admin endpoint already, I need to run this caddy under a separate admin port.
Running `devbox services up` has the following error
```
[caddy_1	] Error: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use
```
Where as `devbox run start` is successful 🤷‍♀️ Are we doing something special with process compose? Seems like for some reason, it is loading some initial config, then reload it with the new config. And because the initial config has a port conflict, everything fails.
To reproduce, go to …

Change caddy to run on non privileged ports

---

internal/boxcli/push.go
internal/fileutil/dir.go
internal/pullbox/config.go
internal/pullbox/git/git.go
internal/pullbox/git/push.go

1. clone `.git` only for push (See https://stackoverflow.com/questions/38999901/clone-only-the-git-directory-of-a-git-repo for more information)
2. add `CreateDevboxTempDIr` to `fileutil` and reuse it in more cases

[push] Simplify git clone for push

---

internal/impl/update.go

`devbox update` should ensure the wrappers point to the latest binaries of any updated packages.
- take a devbox.json having go@1.20 package  (such as the devbox-repo!)
- do `devbox shell` 
- confirm go version 1.20 via `go version`
- manually set a package to go@1.19
- do `devbox update`
- run `go version` and see the updated version
BEFORE: would continue to show `go 1.20` version
AFTER: shows `go 1.19` version

[update] call createWrappers

---

internal/impl/tmpl/envrcContent.tmpl

Our `.envrc` today calls `shellenv` but that doesn't run `createWrappers`.
If the package's binary may change, then the .envrc environment will not get updated.
in `examples/flakes/php`, I did:
1. `devbox generate direnv`
2. `php -m | grep ds` which prints `ds`.
3. edit `examples/flakes/php/my-php-flake/flake.nix` to remove `ds` extension
4. re-run `php -m | grep ds`. This still prints `ds`.
Now, for the test steps:
- cd out of the direnv 
- re-enter the direnv-enabled directory (`examples/flakes/php`)
- re-run `php -m | grep ds`. 
BEFORE: This still prints `ds`.
AFTER: no `ds` is printed.
Note, in Step 4, ideally we would not print `ds` but for that to happen the direnv would need
to check local flake files for changes. Today, it just checks devbox.json for changes.
Not addressing in …

[envrc] run devbox install to ensure createWrappers is called

---

internal/impl/update.go

Calling `removePackagesFromProfile` after forcing a resolve was causing an error because package doesn't exist in profile. Also, make update a little more forgiving, don't break if you can't remove pkg from profile.
* Hand changed devbox.lock to older version of go and older hash.
* deleted .devbox dir
* Ran `devbox install`
* Ran `devbox update`
* Observed new version of go installed, old one removed. No error.

[update] Fix update bug

---

devbox.go
internal/boxcli/run.go
internal/impl/devbox.go

Now that the implementation of `RunScript` is using `context.Background()`, I think it's better to pass the context.Context from `cmd.Context()`.
None

[RunScript] Add ctx parameter

---

internal/boxcli/midcobra/midcobra.go
internal/boxcli/root.go
internal/cloud/openssh/sshshim/command.go
internal/cloud/openssh/sshshim/mutagen.go

Title says it.
Now that `context.Context` is used, I think it's better to pass this parameter from the top instead of creating it when necessary.
None.

[sshshim] Add and pass ctx parameter for sshshim execution

---

internal/boxcli/update.go
internal/impl/update.go

1. update description for `update` command
2. add copyright automatically
devbox update --help
devbox global update --help

[update] update description for update command

---

internal/fileutil/dir.go

Use 0755 as default filemode to create dir. If dir exists, use its own filemode to recreate.

[fileutil] use 0755 as default filemode to create dir

---

internal/impl/tmpl/devcontainerDockerfile.tmpl

This change installs GPG (via the `gnupg2` package) in the dev container for the purposes of GPG commit-signing.
Fixes #1110
- [Install GPG locally](https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials#_sharing-gpg-keys)
- [Set up GPG commit-signing](https://docs.github.com/en/authentication/managing-commit-signature-verification) (i.e. generate a key and tell Git about it)
- devbox init
- devbox generate devcontainer
- cmd + shift + p and select "Rebuild and Reopen in Container"
- [Make a signed commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)
- Enter the password for your GPG key
- Assert that the commit is created successfully

[devcontainer] Add GPG to dockerfile template

---

devbox.go
internal/boxcli/featureflag/autolatest.go
internal/boxcli/generate.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/run.go
internal/boxcli/shellenv.go
internal/boxcli/update.go
internal/impl/devbox.go
internal/impl/devbox_test.go
internal/impl/tmpl/envrcContent.tmpl
internal/impl/update.go
internal/lock/lockfile.go
internal/nix/input.go

Add warning if devbox.json contains legacy packages. Fix them with update command. Update will turn legacy packages to `<pkg>@latest` and resolve them to current hash. This guarantees version will not change. If they run update again, it will update to newest version.
```bash
devbox update
```
Inspected devbox.json and devbox.lock and verified it was now `curl@latest`

[update] Show warning for legacy packages and fix with update

---

docs/app/docs/devbox_global.md

Adds details about how to use a Fleek config with Devbox Global, and how to sync the config with Git push/pull
Localhost

Add Fleek + Git push/pull to devbox global docs

---

internal/impl/devbox.go
internal/impl/devbox_test.go
internal/impl/shell.go
testscripts/run/path.test.txt

**problem**
Doing `devbox rm <package>` within a devbox shell will usually still have the package's binary accessible in PATH. This is confusing and unexpected.
**cause**
In shellenv's `PATH`, we now have 3 sources of paths:
1. `.devbox/virtenv/.wrappers/bin`
2. `.devbox/nix/profile/default/bin`
3. `/nix/store/<hash>-<package>-<version>/bin`
When we do `devbox rm <package>`, the first two (wrappers and profile bins) are removed, but the `/nix/store` remains in PATH. 
The user would have to do `eval $(devbox shellenv)` to remove it. But that is not a good UX.
**background context**
Heres’ why we need/don’t need each one:
1. bin-wrapper dir: is our path for binaries. Binaries here are wrapped to ensure the correct environment is sourced. “Support files” are also sym linked here to ensure …

[shellenv] filter out buildInput paths from PATH

---

devbox.go
internal/boxcli/midcobra/telemetry.go
internal/boxcli/run.go
internal/impl/devbox.go
internal/impl/devbox_test.go
internal/impl/devopt/devboxopts.go
internal/impl/update.go

Fixes/refactors:
* If legacy package is global, show correct update message
* If a legacy package is updated, don't try to update it again (which will show warning because it is not versioned)
* Made `ShowWarnings` -> `IgnoreWarnings` because we ignore in the vast majority of cases. Fixed a few cases that were accidentally ignored.
* Modified global config to have "curl" pacakge.
* Saw `devbox global update` and ran it.
* Inspected config.
Repeated process for non-global as well.

[update] UX fixes to update path

---

internal/impl/devbox.go
testscripts/run/quote_escaping.test.txt

Implementing a narrow fix for #1137
We wrap each command arg in double-quotes and escape any double-quotes within.
Fixes #1137
Added testscript unit test
from issue:
```
> devbox run -- jq -r '.shell.scripts | keys | join(" ")' devbox.json
build build-linux build-linux-amd64 code lint test
```
Also, this now matches:
```
> echo 'hello "world"'
hello "world"
> devbox run -- echo 'hello "world"'
hello "world"
```
previously:
```
> devbox run -- echo 'hello "world"'
hello world
```

[run] escape quotes in arguments

---

internal/impl/devbox.go
internal/impl/shell.go
testscripts/run/pure.test.txt

This is a follow up PR from as a result of [this discussion](https://github.com/jetpack-io/devbox/pull/1084#discussion_r1224750558). 
Note, xdg dirs don't keep any nix executables as far as I know. Single user and multi user nix installation put the nix executable in `~/.nix-profile/bin/` and `/nix/var/nix/profiles/default/bin` respectively.
Also added tests for devbox run pure mode. For `devbox shellenv`, pure mode doesn't really make sense to write tests for, and for `devbox shell` it's not possible to write testscript tests.
- in a single user nix installed env, run `./devbox shell --pure` 
- `devbox add which`
- `which nix` should point to `~/.nix-profile/bin/nix`
- in a multi-user nix, same test should point to `/nix/var/nix/profiles/default/bin/nix`

[pure-shell] making sure nix is in path in pure mode

---

devbox.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

**Motivation**
In elixir projects, `iex -S mix <script>` has the `iex` interpreter invoking the
`mix` build tool. However, the `mix` build tool has been wrapped by devbox in a bash script.
And this leads to a failure as `iex` is unable to interpret a bash script.
**Fix**
Binaries should be able to directly invoke other installed binaries.
We implemented the binary-wrappers so that the shell-environment is correctly 
configured prior to the installed binary being invoked. In this case, the `iex`
binary wrapper will run thereby correctly configuring the environment. Any subsequent
binary invoked in the same sub-shell will inherit this up-to-date environment. So, 
the other binaries can be directly invoked (instead of the binary-wrapper scripts).
**Implementation**
In this PR, we change the …

[bin wrappers] add --omit-wrappers-from-path to shellenv to prevent a binary from invoking a wrapped-binary.

---

devbox.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

Reverting due to regression:
Within a devbox script if any environment variable has been exported, and
if a devbox-plugin also sets that env-var, then the devbox-plugin env-var
will be set for the wrapped-binary.
Specifically, in the `lapp-stack/devbox.json`, we have:
```
"run_test": [
"mkdir -p /tmp/devbox/lapp",
"export PGHOST=/tmp/devbox/lapp",
"initdb",
```
but the PGHOST that `initdb` sees is a different value i.e. the one set by the devbox plugin.
In the code being reverted, the wrapped-bin's bash script would always invoke
`eval $(devbox shellenv --omit-wrappers-from-path=true)` in order to omit wrappers
from PATH. A side-effect is that the PGHOST would also get overridden.
no testing done.
straight revert, tests should pass.

Revert "[bin wrappers] add --omit-wrappers-from-path to shellenv to prevent a binary from invoking a wrapped-binary. (#1151)"

---

devbox.go
examples/stacks/lapp-stack/devbox.json
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/wrapnix/wrapper.sh.tmpl

This is an alternate to #1151 (see explanation in #1159)
In this approach, the wrapped-binary always calls:
`eval $(devbox shellenv only-path-without-wrappers)` 
to ensure that the PATH is set without the `wrappers/bin` directory.
In contrast to #1151, we do not always set any other environment variables
Fixes #1142
issue from #1142 is fixed:
```
> devbox run -- iex -S mix
* creating .nix-mix/archives/hex-2.0.6
* creating .nix-mix/elixir/1-14/rebar3
Resolving Hex dependencies...
Resolution completed in 0.016s
Unchanged:
cowboy 2.9.0
cowlib 2.11.0
ranch 1.8.0
All dependencies are up to date
Erlang/OTP 25 [erts-13.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Hello World!
Interactive Elixir (1.14.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Goodbye World …
```

wrappers] ensure bin-wrappers invoke other binaries and not bin-wrappers

---

internal/boxcli/generate/devcontainer_util.go
internal/impl/devbox.go
internal/impl/flakes.go
internal/impl/tmpl/devcontainerDockerfile.tmpl

This PR addresses the issue in generated dockerfiles by `devbox generate dockerfile` and `devbox generate devcontainer` in which packages mentioned as local flakes are not copied over in dockerfile and user has to manually do that.
Addresses: #1051 
- compile
- add a local flake (example: https://github.com/NixOS/templates/blob/master/go-hello/) 
- add local flake to devbox
- ./devbox generate dockerfile
- check the contents of generated dockerfile and confirm there is a Step 6 comment and COPY commands for each local flake.

[dockerfile] Copying local flakes in dockerfile

---

devbox.go
internal/boxcli/shell.go
internal/boxcli/shellenv.go
internal/impl/devbox.go
internal/impl/devopt/devboxopts.go
internal/wrapnix/wrapper.go
internal/wrapnix/wrapper.sh.tmpl

follow up to #1160 
correctness:
- consolidate some code into calling `wrapnix.GetWrapperBinPath`
- the earlier code had a bug where I forgot to call `-c <project dir>`, but that is moot now (see below change)
perf:
- call DO_NOT_TRACK=1  to minimize segment perf impact
- simplify OnlyPathWithoutWrappers to directly call `os.Getenv("PATH")`, remove WrapperBins, and exportify it. This function is used in a very specific context, so we can _know_ we can  skip the nix.ComputeEnv calculation.
- Doing `time devbox shellenv only-path-without-wrappers` is now consistently ~ 18-25 milliseconds. 
I have a slight preference for this over writing PATH to a file and sourcing it, since we may run into correctness issues with that file getting outdated, and it'll introduce perf regression on every …

[bin wrappers] fixes for only-path-without-wrappers call

---

internal/boxcli/shellenv.go

This flag used to be used by bin-wrappers, but has been removed as of 0.4.8
cc @mikeland86
compiles

[cleanup] remove --use-cached-print-dev-env from shellenv

---

docs/app/docs/devbox_examples/languages/php.md
internal/impl/devbox.go
internal/plugin/files.go
internal/plugin/info.go
internal/plugin/plugin.go
internal/plugin/services.go
internal/services/config.go
internal/services/manager.go
internal/services/services.go
internal/wrapnix/wrapper.go
plugins/README.md
plugins/apacheHttpd.json
plugins/caddy.json
plugins/mariadb.json
plugins/nginx.json
plugins/php.json
plugins/postgresql.json
plugins/redis.json
plugins/ruby.json

Removes `services` stanza from the plugin's json definition, in favor of using `process-compose.yaml`.
* Fixes bug where, in doing `devbox services ls`, we would only return the _first_ service defined in a plugin, and would call it the name of the plugin (instead of the name of the service). This had some downstream effects as well.
* Removes creation of wrappers of the form `<svc>-start|stop-service`. They were using the json-based definitions of the services, but `devbox service start <svc>` was using the process-compose definition, so they could diverge. Some wrappers were not being generated either, due to the bug above.
* Deletes obsolete code.
* Updates plugins that define services and bump their versions. Since plugins are packaged in the CLI, and the process-compose yamls were …

[bugfix, cleanup] Finish moving plugin services to process compose

---

devbox.go
internal/boxcli/add.go
internal/boxcli/create.go
internal/boxcli/generate.go
internal/boxcli/generate/devcontainer_util.go
internal/boxcli/info.go
internal/boxcli/init.go
internal/boxcli/install.go
internal/boxcli/plan.go
internal/boxcli/pull.go
internal/boxcli/push.go
internal/boxcli/search.go
internal/boxcli/setup.go
internal/cloud/mutagen/install.go
internal/impl/devbox.go
internal/impl/flakes.go
internal/impl/generate.go
internal/impl/packages.go
internal/impl/pushpull.go
internal/plugin/info.go
internal/pullbox/git/push.go
internal/pullbox/pullbox.go
internal/templates/template.go

1. Add `ctx` parameter for most Devbox methods
2. Add trace tasks for Devbox methods
3. Add regions for sub-methods

[trace] Add trace for Devbox methods

---

internal/impl/devbox.go
internal/impl/shell.go
internal/wrapnix/wrapper.go

Fixed an issue which caused devbox to disappear from PATH in pure shell mode.
NOTE: Moved the location of the symlink from `.devbox/virtenv/bin` to `.devbox/bin`. I'm open to changing the location but since it's only in pure mode and the location doesn't really affect the user (they can just use `$(which devbox)` inside the shell to get the location dynamically) I'm eager to not have the location of devbox symlink be a blocking issue.
- compile
- ./devbox shell --pure
- which devbox
- which nix

[pure shell] Fixed devbox not being in path

---

internal/boxcli/search.go
internal/searcher/client.go
internal/searcher/searcher.go

1. Merge `Search` and `SearchVersion` into `Search` (if version is not provided, do not use `v=<version>` in search
2. Remove unused `Exists` function
devbox search python

[searcher] Merge Search and SearchVersion

---

internal/telemetry/sentry.go

"github.com/pkg/errors" wraps some functions of `errors` (like `Is` and `Unwrap`), so it's okay to use those functions provided by the former.

[errors] use pkg errors instead of std errors

---

internal/impl/update.go

We can't update flakes yet, so show error,  but continue.
fixes bug introduced in https://github.com/jetpack-io/devbox/pull/1129

[update][easy] Fix update

---

examples/flakes/php/my-php-flake/flake.nix
internal/impl/update.go
internal/nix/upgrade.go

Update flakes via `nix profile upgrade`.
Purposefully forgiving.
Note: local flakes don't need updating because they automatically use latest version of file.
fixes https://github.com/jetpack-io/devbox/issues/1094
```bash
devbox add github:F1bonacc1/process-compose 
devbox update github:F1bonacc1/process-compose
```
This works, but but need to test something that will actually update.

[update] Update flakes

---

internal/boxcli/pull.go
internal/pullbox/s3/pull.go

If path doesn't exist, S3 returns access denied. Show a better error message. This can be improved by checking if object exists (But that would slow things down, so maybe only check if the initial pull failed so we can show a better error message).
* deleted my profile manually
* Ran `devbox global pull`

[global] Better error message when profile doesn't exist

---

internal/filegen/devcontainer_util.go
internal/filegen/generate.go
internal/impl/devbox.go

This moves the `devcontainer_util.go` file into `filegen`. I didn't like `impl` code calling into `boxcli/generate`. The direction should be `boxcli` -> `impl` -> `{helper packages}`. Also, would be nice to keep `boxcli` for `cobra.Command` logic.
We can now also make `filegen.TmplFS` internal i.e. `filegen.tmplFS`
Needed to create `filegen.EnvrcContent` since it was inlined in `impl/devbox.go`.
**RFC**: Arguably, this is unrelated to the rest of `filegen` which has to do with generating `flake.nix` and `scripts` files in aid of `PrintEnv`. So, we can also move into its own self-contained package. Let me know if that's preferable (and suggest a package name!)
compiles

[filegen] move devcontainer_util.go into package filegen; make tmplFS internal

---

internal/devconfig/config.go
internal/filegen/flake_input.go
internal/filegen/flake_plan.go
internal/filegen/generate.go
internal/filegen/nixpkgs.go

1. Move `NixpkgsInfo` into package `filegen`. 
2. Make its functions internal, since it is only used within filegen.
3. Move DefaultNixpkgsCommit to devconfig package, since it is only used there.
compiles

[filegen] move NixpkgsInfo into filegen (no more plansdk)

---

docs/app/docs/devbox_examples/stacks/laravel.md

Change link to an example link, until we publish the template
localhost

[Docs] Fix link for Laravel "Open in Devbox.sh"

---

internal/nix/input.go
internal/nix/input_test.go
internal/nix/profile.go
internal/nix/search.go
internal/plugin/manager.go
internal/plugin/plugin.go
internal/shellgen/flake_input.go

I find `nix.Input` fairly hard to understand. I make a first pass at adding
comments and renaming functions and variables for clarity. Made it about
halfway through the `nix/input.go` file.
**nomenclature**: I have tried to ensure consistency around:
1.  `inputs` referring to `nix.Input`
2. `flakeInputs` referring to `shellgen.flakeInput`
3. `packages` referring to raw strings that are in the packages list in `devbox.json`.
cc @mikeland73 
Have not tested. Please review carefully.
relying on testscripts passing.

[nix input] Add comments, and renames for clarity

---

internal/impl/update.go
internal/nix/upgrade.go
internal/shellgen/generate.go
internal/shellgen/path.go

Ensure we update flake when updating devbox packages. This helps in some edge cases where the user adds an unlocked flake.
`devbox update`

[update][easy] Run nix flake update
